### ISSUE TITLE
How to provide an API key to the documentation?

### ISSUE THREAD

**Issue by ernsheong** [mrin9/RapiDoc#1]
Hey, this looks great and promising. How can I give the docs an API key?

**Comment by mrin9** [comment]
@ernsheong have added features to add `api-key` or `http` authentication give it a spin let me know if that works for your use-case

**Comment by ernsheong** [comment]
I went with plain Swagger UI for now. I will definitely revisit this sometime! Thank you for the efforts

**Comment by FlaxHaxx** [comment]
Is oauth2 authentication being implemented?
