### ISSUE TITLE
Example only displayed for JSON Array

### ISSUE THREAD

**Issue by GitGraf** [mrin9/RapiDoc#100]
```yml
openapi: 3.0.0
info:
  title: Example-Rendering Problem Demonstration
  description: Example is only getting displayed for JSON-Arrays
  version: 1.0.0
paths:
  /test/examples:
    get:
      summary: Get a TestSchema object and a TestSchema array!
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  objectProperty: 
                    type: object
                    $ref: "#/components/schemas/TestSchema"
                    example: 
                      testProp: 'TestPropFromObject'
                  arrayProperty:
                    type: array
                    items:
                      $ref: "#/components/schemas/TestSchema"
                    example: 
                      - testProp: 'TestPropFromArray'
components:
  schemas:
    TestSchema:
      type: object
      properties:
        testProp:
          type: string
```

I would expect that the examples of `objectProperty` and `arrayProperty` are displayed as defined in the spec, but this is the result:

![example](https://user-images.githubusercontent.com/19150483/70325241-e0129600-1831-11ea-87a7-d4676df3a4b7.PNG)

**Comment by mrin9** [comment]
I dont think thats correct spec. When you use `$ref` for the object schema then you must put the `example` too in the reference same goes with `type`, you can not have `type` alongside `ref`

In case of `array` it is working because you put example is a level above the `$ref` not along-side `$ref`,
you can as well put the entire example for the whole object one more level up, instead of putting it field by field

I think below spec should get you the result you are looking for
```yml
openapi: 3.0.0
info:
  title: Example-Rendering Problem Demonstration
  description: Example is only getting displayed for JSON-Arrays
  version: 1.0.0
paths:
  /test/examples:
    get:
      summary: Get a TestSchema object and a TestSchema array!
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  objectProperty: 
                    $ref: "#/components/schemas/TestSchema"
                  arrayProperty:
                    type: array
                    items:
                      $ref: "#/components/schemas/TestSchema"
                    example: 
                      - testProp: 'TestPropFromArray'
components:
  schemas:
    TestSchema:
      type: object
      properties:
        testProp:
          type: string
          example: 'TestPropFromObject' 
```

**Comment by GitGraf** [comment]
I'm sorry, I forgot to validate the spec before submitting this issue. So you are saying that `$ref` and `example` should not be on the same level, ok. Something like this should be working then, right?
```yml
openapi: 3.0.0
info:
  title: Example-Rendering Problem Demonstration
  description: Example is only getting displayed for JSON-Arrays
  version: 1.0.0
paths:
  /test/examples:
    get:
      summary: Get a TestSchema object and a TestSchema array!
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  objectProperty: 
                    allOf:
                      - $ref: "#/components/schemas/TestSchema"
                    example: 
                      testProp: 'TestPropFromObject'
                  arrayProperty:
                    type: array
                    items:
                      $ref: "#/components/schemas/TestSchema"
                    example: 
                      - testProp: 'TestPropFromArray'
components:
  schemas:
    TestSchema:
      type: object
      properties:
        testProp:
          type: string
```

The reason I am not using the method you showed above is because it is not really feasible for my use case. Let's say in addition to having `GET /test/examples`, my spec also features `POST`, `PUT` and `DELETE` for that endpoint. Now, the **schema** for the response is always the same, but the response itself differs depending on which HTTP method was used. 

Example:
 `GET /test/examples` ---> `{ testProp: "Hello from GET"}` 
`POST /test/examples` ---> `{ testProp: "Hello from POST"}`

If my response contains a Json Object, do I really have to create a seperate schema for it if I want to display some different examples?

Thanks,

**Comment by mrin9** [comment]
my quick analysis says the revised spec you provided is correct, but RapiDoc interprets `allOf` little differently so you may still end-up with the previous result. (_not sure, but test it once_)

What you are trying is, to associate an example with the end-point, so try to put the example at the operation level, not per field in the schema

for some examples and history behind how RapiDoc handles examples, refer the below issues
#60 
#68
