### ISSUE TITLE
Page not loading when 'render-style' is set to 'view'

### ISSUE THREAD

**Issue by vasnav** [mrin9/RapiDoc#104]
I have set attribute 'render-style' to 'view'.
But the page does not load and keeps trying to load.

`<rapi-doc
               spec-url="../../LoginRapidoc.yaml"
 		show-header='false'
		show-info='false'
		allow-authentication='false'
		layout="column"
		allow-search = 'false'
		allow-spec-url-load = 'false'
		allow-spec-file-load = 'false'
		render-style = 'read'
		id = 'rapidoc'>
	</rapi-doc>`

**Comment by mrin9** [comment]
its a non issue. you must be providing incorrect file path
the below path works with the same set of attributes

```html
<rapi-doc 
  spec-url = "https://petstore.swagger.io/v2/swagger.json" 
  show-header = 'false' 
  show-info = 'false' 
  allow-authentication = 'false' 
  layout = "column" 
  allow-search = 'false' 
  allow-spec-url-load = 'false' 
  allow-spec-file-load = 'false'
  render-style = 'read' 
  id = 'rapidoc'
> </rapi-doc>
```
