### ISSUE TITLE
Can't set api keys using SetAttribute (Example #8 Broken) 

### ISSUE THREAD

**Issue by wbrian-onlineed** [mrin9/RapiDoc#105]
Example 8 appears not to be working:
https://mrin9.github.io/RapiDoc/examples/example8.html

**Expected:**
API key should be set in the javascript and should send this data on "TRY IT" requests.

**Observed Result:**
Adding the recommended api-key string into the box and clicking submit does not actually set the api key. It *does* set the attribute on the element, but it does *not* actually send any Authorization header. Additionally, the screen continues to say "Authentication: No API key applied".

**Tested On:**
FF 71, Chromium 78 on Ubuntu 19.04

Thank you for providing this software. This is a great project!

**Comment by mrin9** [comment]
Thanks for pointing it out, will work on it soon.

**Comment by roderik** [comment]
Did anyone find a workaround for this?

**Comment by mrin9** [comment]
not yet released, to test if it works for you use case, either use `rapidoc-min.js` from `dist` folder. or build it yourself using `yarn build`

> do not rely on `rapidoc-min.js` in `dist` folder for production. we do not actively maintain it

**Comment by mrin9** [comment]
this is now fixed in release `7.1.0`
