### ISSUE TITLE
Broken external x-badge reference

### ISSUE THREAD

**Issue by LazyRichard** [mrin9/RapiDoc#1056]
Until 9.3.4 the badges from external file is fine.

but since 9.3.5 it does not render at all and after 9.3.7 it completely broken. (failed to load)

Here is the spec I test

- badges.yml

    ```
    Test:
      color: red
      label: external-badge
    ```

- openapi.yml

    ```
    openapi: 3.1.0
    info:
      version: 0.1.0
      title: Rapidoc Badge Test
    
    paths:
      /badge-test:
        post:
          tags:
            - Test
          summary: Test Badge Ref
          operationId: testBadgeRef
          x-badges:
            - $ref: ./badges.yml#/Test
          requestBody:
            content:
              application/json:
                schema:
                  type: object
          responses:
            '202':
              description: Accepted
              content:
                application/json:
                  schema:
                    type: object
    ```

Currently, I use [redocly/cli](https://github.com/Redocly/redoc) for merge openapi spec fragments.

and this tools does not properly merge all the `x-` prefixed component.

So, I can't bundle the seperated `x-` prefixed file to `openapi.yml` file directly.

Here is rendered result

- 9.8.4

    ![스크린샷 2024-11-14 오후 2 02 16](https://github.com/user-attachments/assets/297b0b46-7f5a-4410-841e-385bdabf7c5f)

- 9.8.5

    ![스크린샷 2024-11-14 오후 2 02 48](https://github.com/user-attachments/assets/e450c43e-2348-4f70-8198-1b358a9f89e9)

**Comment by mrin9** [comment]
Since `9.3.5` we are using a more strict OpenAPI parser. When using `refs` in spec ensure that they are conforming to the rules of OpenAPI standard. First try without using `refs`  . Refer to #1027 for more details

if it is still not working then re-open a new issue.
As a test case [this example](https://rapidocweb.com/examples/badges.html#get-/no-badges-path) uses barges and works
