### ISSUE TITLE
Degradation in enum rendering in 9.3.7

### ISSUE THREAD

**Issue by YousefHaggy** [mrin9/RapiDoc#1058]
In version 9.3.6 my enum path parameter renders perfectly fine.

But in 9.3.7, it renders as follows with no enum values
<img width="1351" alt="image" src="https://github.com/user-attachments/assets/5a1eb3d0-43ac-43ee-a6bc-050e73b83724">

I can't share my exact spec, if you can not reproduce it let me know and I can try to generate a sample spec

**Comment by mrin9** [comment]
can you confirm if thats the case in `9.3.8`

I am unable to produce it in our test cases https://rapidocweb.com/examples/parameters.html

**Comment by YousefHaggy** [comment]
@mrin9 Still happens in 9.3.8, I'll try to get a reproducible spec for you

**Comment by mrin9** [comment]
closing as it cannot be reproduced. please open a new issue if you were able to recreate it

**Comment by YousefHaggy** [comment]
@mrin9 Created a new issue with a spec to recreate: https://github.com/rapi-doc/RapiDoc/issues/1062
