### ISSUE TITLE
Does RapiDoc support multipart/mixed content-Type?

### ISSUE THREAD

**Issue by vasnav** [mrin9/RapiDoc#107]
Hi,
   We are using RapiDoc and like it very much.

   Does RapiDoc support multipart/mixed content-Type?
   If so any examples that can be used?
Thanks

**Comment by mrin9** [comment]
Its little generic question for me to answer, can you provide me a sample spec and tell me what you are expecting ?

**Comment by vasnav** [comment]
We were able to get it working with RapiDoc.
We needed a requestBody which can be **json** or **xml** and Content-Type as **multipart/mixed** with boundary informataion.

### Our sample content-type: 
   multipart/mixed; boundary=----WebKitFormBoundaryLyRAYGiE5mFu3Ucv

### Our sample example requestbody (requestBody can be either json or xml):
   ------WebKitFormBoundaryLyRAYGiE5mFu3Ucv
Content-Disposition: form-data; name="data"
Content-Type: application/json

{"name": "sample.apk"}
------WebKitFormBoundaryLyRAYGiE5mFu3Ucv
Content-Disposition: form-data; name="sample_details"; filename="sample.apk"
Content-Type: text/plain

This is a sample
------WebKitFormBoundaryLyRAYGiE5mFu3Ucv--

### our .yaml file:
paths:
    /ws/path/example:
        post:
            summary: Multipart mixed content type.
            operationId: multipartMixedContentType
            description: | 
            tags:
                -     
            parameters:
                - $ref: './../../HeaderParamsRapidoc.json#/components/parameters/accept'
                - $ref: './../../HeaderParamsRapidoc.json#/components/parameters/acceptLanguage' 
                - name: Content-Type
                  in: header
                  description: Media type sent by the client. 
                  required: true
                  schema:
                    type: string 
                    enum: [multipart/mixed]
            requestBody:
                description: Request body
                required: true
                content:
                    application/json:
                        schema:
                    application/xml:
                        schema:
