### ISSUE TITLE
Can I display external docs with RapiDoc?

### ISSUE THREAD

**Issue by GitGraf** [mrin9/RapiDoc#108]
I am trying to provide additional documentation for some of my Schemas and Endpoints by using the "externalDocs" property. In my snippet, I placed this property in all four of the valid positions (according to https://swagger.io/specification/):
```yaml
openapi: 3.0.0
info:
  title: ExternalDocs
  description: I am not able to display external documentation
  version: 1.0.0
externalDocs:
  url: http://example.com
  description: Get help here
paths:
  /test/example:
    get:
      tags:
        - test_tag
      externalDocs:
        url: http://example.com
        description: Get help here
      summary: Get a TestSchema object and a TestSchema array!
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/TestSchema"
components:
  schemas:
    TestSchema:
      type: object
      properties:
        testProp:
          type: string
          description: This is a description
          example: Hello
          externalDocs:
            url: http://example.com
            description: Get help here
tags:
 - name: test_tag
   description: Description for the test tag
   externalDocs:
     url: http://example.com
     description: Get help here
```

Sadly, the "example.com" Link is not showing up anywhere on the page. Is this a bug, oversight by me, or is the feature currently not supported?

Thanks

**Comment by mrin9** [comment]
at present external content is not supported in RapiDoc, but will soon be getting this feature in. For now as an work around you can use markdown to provide external links

**Comment by GitGraf** [comment]
Thank you, the workaround is a good alternative. Looking forward to seeing this feature implemented.

**Comment by winonecheng** [comment]
Hi @mrin9 
Is this feature supported?
