### ISSUE TITLE
Use "example" field of schemas

### ISSUE THREAD

**Issue by birdayz** [mrin9/RapiDoc#11]
Each schema (e.g. for a response or request) can have a field "example".
This field is currently not used to display the example.

You can see this with our API doc: https://infinimesh.github.io/infinimesh/swagger-ui/openapi.yaml

POST to /namespaces/{namespace}/objects/{parent}/children has an example, it's shown in swagger-ui but not in rapidoc.

**Comment by mrin9** [comment]
I am sorry, I could not find the endpoint you mentioned in the spec. Not even in swagger-ui.

can you try this spec from Microsoft Azzure
https://api.apis.guru/v2/specs/azure.com/workloadmonitor-Microsoft.WorkloadMonitor/2018-08-31-preview/swagger.json

This has a lots of examples in the response schema, and RapiDoc is showing the examples

**Comment by birdayz** [comment]
Yeah bad timing, i removed the examples just right now in a refactoring :(

here from history:
https://raw.githubusercontent.com/infinimesh/infinimesh/d0c5127a908b6471e44da1a233d93d418dceb904/docs/swagger-ui/openapi.yaml

    infinimeshapiCreateObjectRequest:
      example:
        name: name of child

That example is not shown in rapidoc if im not wrong

**Comment by mrin9** [comment]
ok, I see the difference.
RapiDoc, uses example from each field (if provided) to generate the JSON structure that matches the model.
But ignores the example provided for the entire response.
Let me think over it over a little on this

Thanks for reporting

**Comment by mrin9** [comment]
this should be fixed in release 4.2.4
