### ISSUE TITLE
serve-rapidoc

### ISSUE THREAD

**Issue by BigBlueHat** [mrin9/RapiDoc#112]
First, a huge thank you for building this project! This is easily one of the best OpenAPI documentation generator/viewers out there!

Second, I've written a small express.js app for quickly running RapiDoc from any directory to help with local previewing of OpenAPI docs:
https://github.com/WileyLabs/serve-rapidoc

Long term I'd like to make more of the options configurable from the command line (or via a config file), but for now, this allows for quick local API spec viewing (i.e. `http://localhost:3000/#spec-url=spec.yaml`).

I hope you and the community here find it useful!

Cheers,
🎩

**Comment by mrin9** [comment]
awesome,
really handy to serve RapiDoc with ease
