### ISSUE TITLE
Linking to specific endpoint

### ISSUE THREAD

**Issue by adamdecaf** [mrin9/RapiDoc#113]
👋 Thanks for making this project. It's really useful for showing an OpenAPI Spec.

I was wondering with `7.0.1+` how linking to specific endpoints was supposed to work. I've tried the following URL fragments, but neither works as expected (scroll and expand to that endpoint).

- https://api.moov.io/apps/paygate/#post-/depositories
- https://api.moov.io/apps/paygate/#post-%2Fdepositories

**Comment by mrin9** [comment]
checkout the issue #80 and follow the example provided ther, if it helps

you should be able to scroll to the end-point, but wont expand, for expanded endpoints you need to change your render style

let me know,

**Comment by adamdecaf** [comment]
I see that example, but it doesn't scroll to that endpoint. Is the only way to scroll to a shadow-dom element with javascript? Read the URL fragment and scroll to it?

I was trying https://mrin9.github.io/RapiDoc/examples/read-mode.html#post-/pet and it doesn't scroll.

Using `render-style=read` is nice. I'll probably switch to that!

**Comment by mrin9** [comment]
I see, you are trying to use the URL hash to navigate to certain section. 

Well, as you know, RapiDoc is a custom-element and it is very much possible that you can put this multiple times in the html. 
just for the sake of understanding, lets say you added 3 RapiDoc element displaying the same spec in the html, now if you provide an` location-hash(#)` on the locattion bar, how will it decide to which element's section it should go (there would be 3 such sections )

So yes, you have write a bit of java script to read the location hash, and use RapiDocs elements method to navigate to that section (checkout RapiDocs API to see what methods you can use to scroll to certain section)

> I hope it should resolve your issue, feel free to open it up, if you still find difficulties

**Comment by adamdecaf** [comment]
Thanks! I got it working pretty well.

For anyone who runs into this here's my solution: https://github.com/moov-io/api/pull/126

**Comment by mrin9** [comment]
awesome, 
does  [onhashchange](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange) event makes more sense than `onload` ?

**Comment by adamdecaf** [comment]
Good call! There's nothing on the page that changes the fragment, but if that fires on page load it would be a more accurate event listener.
