### ISSUE TITLE
Is there a way to load settings from object?

### ISSUE THREAD

**Issue by hh-h** [mrin9/RapiDoc#114]
Hi, thank you for the nice library!
I want to use it in my project, but for a convenient way to use it I need to load settings via js object, something like this

```html
<!doctype html>
  <head>
    <script type="text/javascript" src="../rapidoc-min.js"></script>
    <script>
      document.getElementById("thedoc").loadSettings({
          specUrl: "https://...",
          sortTags: true,
          layout: "dark",
          ...
      });
    </script>
  </head>
  <body>
    <rapi-doc id="thedoc"> </rapi-doc>
  </body>
</html>
```
Is there a way to do that?

Best regards

**Comment by mrin9** [comment]
No, there isnt any method like that. 
In general, HTML Elements or various custom elements wont expose a methods that takes object and assign it to various attributes. and we would would like be in line with this approach.

having said that, you can always build a function at your end that takes an object assign the attributes.

**Comment by hh-h** [comment]
Gotcha. I'll come up with something. Thanks!
