### ISSUE TITLE
display maps in model/examples

### ISSUE THREAD

**Issue by joy4eg** [mrin9/RapiDoc#115]
Hey,

Thanks for the great app! :)

I tried to use it in my project, but found that maps are not rendered at all.
[Spec example](https://github.com/mrin9/RapiDoc/blob/master/docs/specs/xxx-of-with-primitives-and-recursive-model.yaml#L380:L398)
How it looks: 
![Screenshot_20200120_130821](https://user-images.githubusercontent.com/878385/72722040-127c1680-3b86-11ea-82ec-f35db84b0d28.png)

Expected example/model (as redoc/swagger-ui do):
```
{
   "additionalProp1": { ... model data ... },
   "additionalProp2": { ... model data ... },
}
```
They just add some dummy keys to show the whole model behind map.
It is a bit confusing, because in my project I have a `map[string]SomeLargeObject` and it doesn't appear in model/examples.

**Comment by mrin9** [comment]
yep, maps are not supported just yet.  Let me add this in our task list.
will try to address this soon

**Comment by mrin9** [comment]
to test it out checkout this example 
https://mrin9.github.io/RapiDoc/examples/additional-props.html

We decided to include `additional-properties` in model only.  not in example as it makes less sense putting it there

**Comment by joy4eg** [comment]
@mrin9 I found that maps now rendered fine, but if that map has `example` - it is still empty.
Anyway, this [code](https://github.com/joy4eg/RapiDoc/commit/3bdad3e6a010f6a50f9e6e2f75810753c172c9c7) works for me:
```diff
diff --git a/src/utils/common-utils.js b/src/utils/common-utils.js
index d697d9c..2a5d5a0 100644
--- a/src/utils/common-utils.js
+++ b/src/utils/common-utils.js
@@ -247,6 +247,11 @@ export function schemaToSampleObj(schema, config = { }) {
         obj[key] = schemaToSampleObj(schema.properties[key], config);
       }
     }
+    // If current object doesn't have any properties but have the `example` field,
+    // let's return it as is
+    if (!schema.properties && schema.example) {
+     obj = schema.example;
+    }
   } else if (schema.type === 'array' || schema.items) {
     if (schema.example) {
       obj = schema.example;
```
Feel free to use/cherry-pick.

Thanks!
