### ISSUE TITLE
How to change default font path?

### ISSUE THREAD

**Issue by hh-h** [mrin9/RapiDoc#116]
Hello,
It seems that fonts always loading from the path where index.html is held.
I have a situation where my index.html file is in `/docs/` path, but fonts are in `/docs/static/` path (and I cannot put them inside `/docs/`), so I modified the `rapidoc-min.js` file and it works fine.
Is it possible to handle it somehow without modifying the js file?

**Comment by mrin9** [comment]
define `@font-face` in your html 
provide them in `<rapi-doc>` element's `regular-font` and `mono-font` attributes

```
<rapi-doc 
   spec-url     = "swagger.json" 
   regular-font = "my-font1"
   mono-font    = "my-font2"
> 
</rapi-doc>
```
