### ISSUE TITLE
Response body formatting

### ISSUE THREAD

**Issue by birdayz** [mrin9/RapiDoc#12]
I guess it would make sense if it's formatted like the example! Especially with larger responses it's not so well readable

https://abload.de/img/deepinscreenshot_seleh4jxh.png

**Comment by mrin9** [comment]
that must be fixed, thanks for reporting

**Comment by birdayz** [comment]
Yeah it seems to be set:
https://abload.de/img/deepinscreenshot_seleabkjk.png

**Comment by mrin9** [comment]
hmm, seems like this is happening in firefox, chrome looks fine, let me see what I can do

**Comment by mrin9** [comment]
this should now be fixed in `4.1.0` release. 
Please reopen, if you are still facing issues
