### ISSUE TITLE
Option to make "includes" change to "Dropdowns"

### ISSUE THREAD

**Issue by Gildo-Sargi-Neto** [mrin9/RapiDoc#120]
is there any way to make my includes become Dropdowns, there is no sense in making the user write what he wants to include, this can cause unnecessary support calls.
![image](https://user-images.githubusercontent.com/49002665/72999550-45b8e280-3dde-11ea-90bf-b770f9ef24ac.png)

**Comment by mrin9** [comment]
this is something thats quite often requested, especially people coming from swagger-ui. 

Well, there are certain differences in RapiDoc's approach to API documentation. 
It's goal is not to become a perfect client tool, rather serve more as a testing tool for developers. 

Now, if we change that textfield to a dropdown, there will be no way for you to test the API and its response when you submit a wrong value.

I hope that should answer why we dont validate inputs

**Comment by Gildo-Sargi-Neto** [comment]
i understand your point but isn't possible to set a dropdown = true/false in the project?
