### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by robsontenorio** [mrin9/RapiDoc#121]
Is there a way to override RapiDoc default css?

Just tried declare <style> on html <header> but no lucky.

**Comment by mrin9** [comment]
If you can provide me little more details on what styles are you trying to customize, I will be in a better position to provide you with a suggestion.

RapiDoc exposes many properties out of the box that can help you customize various styling. if none of them helps you, then, there may be some css vars that you may tweak to change things

**Comment by robsontenorio** [comment]
@mrin9 Thanks for answering! I mean fine tunning. I am inspecting html elements and trying to override default rapidoc css.

```html
<!doctype html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, minimum-scale=1, initial-scale=1, user-scalable=yes">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,700i,800,800i,900,900i&display=swap"
        rel="stylesheet">
    <script type="text/javascript" src="./rapidoc-min.js"></script>
    <style>
        rapi-doc {
            width: 100%;
        }

       /* Here */
        h2 {
            font-weight: bold !important;
            color: red !important;
        }

        /* Here */
        .sub-title {
            font-weight: bold !important;
        }
    </style>
</head>

<body>
    <rapi-doc spec-url="./api.v1.yaml" allow-spec-file-load="false" allow-spec-url-load="false" layout="row"
        schema-style="table" schema-description-expanded="true" heading-text="API" schema-expand-level="1"
        regular-font="'Montserrat', sans-serif">
    </rapi-doc>
</body>

</html>
```

**Comment by mrin9** [comment]
I am afraid you cannot do that, `<rapi-doc>` is a custom element (not a website/webapp) it does not come with any stylesheet.
Custom element has style encapsulation, which would prohibit you from changing its style from outside of the element.

however, we expose some css vars that you may alter to achieve your desired output. but you are limited to only the vars that the author of the element have decided to expose.

for instance, let say you are not satisfied with the blue color thats associated with `get` method, instead you want to change it to pink you may try the below style override

```
<style>
rapi-doc {
  --blue: #ff6781;
}
</style>
```
you may check all the css vars that we expose using browser's devtool and change them.

**Comment by robsontenorio** [comment]
@mrin9 web components can import external stylesheets. It could be a option o RapiDoc API. Would you accept a PR?

**Comment by mrin9** [comment]
we are always open to PRs, 

in this regard if you are referring to `@import <somestyle.css>` then we wanna avoid it, it is considered  anti-pattern for web-components, it has performance issues and it will have a flash of un-styled component.

our roadmap on styles is to move towards `::parts()` https://developer.mozilla.org/en-US/docs/Web/CSS/::part

when we started this project, `::parts()` was not supported in majority of the browser so we used `css-vars`. 
the other thing that we care about is to keep things simple at 
- code level (simpler code allows us to get in more PRs)
- element usage (many of our users are tech-writers having basic knowledge of html/js, we shouldnt be making things complex for them to adopt)
- not breaking backward compatibility but exceptions are allowed

if you can help us achieve this and keep the [existing theming support](https://mrin9.github.io/RapiDoc/examples/themes.html)  , will be a great help for the project.

>PS: reopening to discuss it further, we dont get notifications on closed issues

**Comment by robsontenorio** [comment]
So in this case are you open to new themes PR? 

Do you see any issue on exposing new vars? Another PR.

**Comment by mrin9** [comment]
I am open to PRs.

I dont see much of an issue to add new css-vars, 
as long as it is applied in a way that dont change the existing styles
