### ISSUE TITLE
Support for OpenApi 3 $ref multiple files

### ISSUE THREAD

**Issue by Gildo-Sargi-Neto** [mrin9/RapiDoc#122]
Open API 3 $ref support multiple file referencing, but when i use it, rapidoc don't renders the endpoints, what is happening?

here is an example
![image](https://user-images.githubusercontent.com/49002665/73190097-35697600-4104-11ea-8704-947a7133c66e.png)
![image](https://user-images.githubusercontent.com/49002665/73190160-4e722700-4104-11ea-8979-eb8796c743bc.png)
![image](https://user-images.githubusercontent.com/49002665/73190235-75305d80-4104-11ea-9e3c-f3051f913fc0.png)

**Comment by mrin9** [comment]
thanks for bringing it up.
we are in the process of changing some internals of rapidoc, which will take care of this issue too.

You will be getting this fixed in our next patch

**Comment by Gildo-Sargi-Neto** [comment]
ok, thanks for the amazing service and support :)

**Comment by mrin9** [comment]
this issue is fixed in release `7.2.0`
refer to this example https://mrin9.github.io/RapiDoc/examples/external-refs.html
> PS: `$ref` paths must be relative to the html file where rapidoc element is defined
