### ISSUE TITLE
API SERVER: http://localhost:8080//localhost:8080/

### ISSUE THREAD

**Issue by dagnelies** [mrin9/RapiDoc#125]
Hi,

my swagger 2 specs deliver: `"host": "localhost:8080",`

and rapi docs makes out of it API SERVER:  `http://localhost:8080//localhost:8080/`

which is a bit silly. But I guess it comes from the swagger -> OpenAPI converter, right?

**Comment by dagnelies** [comment]
Apparently, this behavior was introduced quite some time ago, from 7.0.1 to 7.0.2

**Comment by mrin9** [comment]
Thanks for the PR, will merge it soon.
