### ISSUE TITLE
Empty query parameters are sent

### ISSUE THREAD

**Issue by birdayz** [mrin9/RapiDoc#13]
Rapidoc sends empty query params. so if i don't fill it out, i'll get an error..

Example:
It calls:
https://api.infinimesh.io/namespaces/joe/objects?recurse=

it should omit this param completely..in my case my backend will reject it because the value is not a legit boolean. if it's omitted, it's fine.

Swagger-ui omits this param completely, if nothing is entered into the textbox

**Comment by mrin9** [comment]
Thanks for reporting this issue. Let me think it over a little. 

However, there is difference in the approaches of swagger-ui and RapiDoc's API console

Swagger-UI puts many validations for its console,  RapiDoc avoids putting any validation, the goal is not to make a perfect client for the API, but to allow users/developers to checkout the api with various values (including the negative ones)

The case you presented above is actually a good test case on how the api behaves when provided with an empty value, With swagger-ui you can never test this case.

Having said that we are having a little discussion on our end on what to do with empty params.
I will update this issue once we come to a conclusion.

I hope you understand our philosophy of not doing any validation

**Comment by mrin9** [comment]
Like you suggested , we decided to not submit empty values. Just  published a new release `4.1.0`, can you confirm, if it takes care of your issue ?

**Comment by birdayz** [comment]
i can confirm, it now works as i expected. when empty, it's omitted.
perfect, thanks so much for acting so quickly! :+1:
