### ISSUE TITLE
Is there any way to pass url variables to schema?

### ISSUE THREAD

**Issue by Gildo-Sargi-Neto** [mrin9/RapiDoc#132]
I'm trying to pass URL to my schemas thru a variable like in the image below, isn't there any way to do this? If some day we change the base url we would have to change all the project this would be very inconvenient, i hope there is a solution for this problem :) 

![image](https://user-images.githubusercontent.com/49002665/74846573-702f8a00-530f-11ea-8fbf-9d87836518c7.png)
![image](https://user-images.githubusercontent.com/49002665/74846623-89383b00-530f-11ea-9d60-3d08b42c833e.png)

**Comment by mrin9** [comment]
I am not sure if I get your question correctly, 
but Open-API spec dont allow having variables in `schema`

However for `servers` the spec do allow having variables. Some call them as [Server Templating](https://swagger.io/docs/specification/api-host-and-base-path/)

RapiDoc supports server-templating 
check out this example which demonstrate this https://mrin9.github.io/RapiDoc/examples/server-vars.html

the open-api spec for the above example is here https://github.com/mrin9/RapiDoc/blob/master/docs/specs/server.yaml
