### ISSUE TITLE
Feature - API additions

### ISSUE THREAD

**Issue by Mhirji** [mrin9/RapiDoc#133]
I am wondering if it would be possible to add to the api a hide-loading attribute with a default value of false.  This would allow for those who have their own loaders to use them.  

Thanks!!

**Comment by mrin9** [comment]
too bad, you dont like our spinner :)

kidding,
you always have the option of hiding the `<rapi-doc>` element itself,  use your own spinner, and show rapidoc after `spec-loaded` event.

We dont want to make our API surface too granular. Let me know if that helps

**Comment by Mhirji** [comment]
That could definitely work, had not thought of using the spec-loaded in that way.  Thanks for the help, and all the work on this project.

**Comment by baboonmaj** [comment]
Can the loader be a `.svg` file that can be overwritten easily ? 
I believe this is how Redoc does as mentioned in this issue https://github.com/Redocly/redoc/issues/1187

Not, suggesting that RapiDoc should follow what Redoc is doing, It just a reference point on how others are dealing in this space. Hiding the entire element seems like an overkill
