### ISSUE TITLE
css question

### ISSUE THREAD

**Issue by Mhirji** [mrin9/RapiDoc#134]
Hi,

Looking at the css used on the <rapi-doc> tag, I see that there is a min-width of 360px being set.  Would it not be better to set it to 100%?  It would allow rapidoc to be placed in the context of other UI libraries and inherit parent containers, specifically on when being viewed on a mobile device.

Thanks!!

**Comment by mrin9** [comment]
RapiDoc is Responsive and mobile frendly `min-width` of `360px` is smallest screen that we support other wise it takes the entire width of the view-port or any custom width, just like you specify for any other element.

check out this example on how you can embed RapiDoc in an HTML
https://mrin9.github.io/RapiDoc/examples/example4.html 

if you are dealing with micro-services and you have multiple open api docs to show in a single page  you can do that too,
Checkout how Northbricks uses RapiDoc to document their micro-services. View the HTML source and checkout that the page contain multiple RapiDoc element each showing a separate OpenAPI spec
https://www.northbricks.io/apis/

Hope that helps

**Comment by Mhirji** [comment]
It does help, thanks.
