### ISSUE TITLE
Question: text selection color

### ISSUE THREAD

**Issue by croudet** [mrin9/RapiDoc#135]
Is it possible to change the text selection color. I find it difficult to see selection with DARK theme.

Thanks.

**Comment by mrin9** [comment]
can you point few places where you find it difficult 
- for instance text-input have darker background than the regular body, so same selection color may not be appropriate in both case
- some colors are calculated on the fly to support custom theming, for instance users may provide a background color of their choice, but may not provide any other color in that case we generate rest of the color combination on the fly.

I might be taking some middle ground for selection colors to support various color-combinations, I will revisit it to see if I can better align with the default/custom theme

**Comment by croudet** [comment]
I'd like to have more contrast when selecting some text in the response or in parameter input field.
