### ISSUE TITLE
Question: logo-url

### ISSUE THREAD

**Issue by croudet** [mrin9/RapiDoc#136]
I the code I see a `logo-url` param:
https://github.com/mrin9/RapiDoc/blob/69a4441aa9c59c46202f217514fed0eb77420f07/src/rapidoc.js#L35

It looks it is not used anywhere. To change the logo, is the right way to use a slot or this parameter?

Thanks

**Comment by mrin9** [comment]
that is correct, we deprecated it in very initial stage and moved to usage of slots. Seems like its not been cleaned up entirely, I will take this out from the code. Our [API Documentation](https://mrin9.github.io/RapiDoc/api.html)  dont mention about it

The correct way to change the logo is to use slots. And there are 2 slots for it 
- `logo` :  use this slot to replace the logo on top header
- `nav-logo` :  use this slot to replace the logo left navigation bar (available in `read-mode` only)
```
<rapi-doc spec-url="http://petstore.swagger.io/v2/swagger.json">
  <img slot="logo"  src="https://img.icons8.com/color/48/000000/youtube-play.png"/> 
</rapi-doc>
```
thanks for pointing

**Comment by davinchia** [comment]
Hi,

I've been trying to modify my logo unsuccessfully. 

```<!doctype html> <!-- Important: must specify -->
<html>
<head>
         <meta charset="utf-8"> <!-- Important: rapi-doc uses utf8 charecters -->
         <script type="module" src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>
</head>
<body>
	<rapi-doc spec-url="https://raw.githubusercontent.com/airbytehq/airbyte/master/airbyte-api/src/main/openapi/config.yaml"
	  primary-color = "#625fff"
	  <img id="logo" slot="logo"  src="https://img.icons8.com/color/48/000000/youtube-play.png"/> 
	</rapi-doc>
</body> 
</html>```

This displays the right docs and header color, however leaves the logo untouched. Am I missing something?
