### ISSUE TITLE
Markdown not processed for summary field inside operation box

### ISSUE THREAD

**Issue by shaigluskin** [mrin9/RapiDoc#138]
The summary field (or description if no summary is provided) displays in small print to the right of the operation header. RapiDoc handles markdown there with no problem.

However, Rapidoc displays the summary information again when the operation header is clicked and opens up the detail. There the summary is displayed again this time in a bigger font. And there, any markdown is NOT converted to html.

The description field immediately following the summary _does_ process the markdown.

![markdown_rapidoc_screenshot](https://user-images.githubusercontent.com/611571/74981985-42c30900-5401-11ea-9403-eca20ecbdb50.png)

**Comment by mrin9** [comment]
per the spec,
- Path summary cannot have markdown
- Path description can have markdown

https://swagger.io/specification/#pathsObject

the right side section of the path is common for summary description therefore the markdown there works even for summary 

Hope that helps
