### ISSUE TITLE
Stuck when trying to view the stripe openApi definitions

### ISSUE THREAD

**Issue by LevinGuy** [mrin9/RapiDoc#14]
When trying to load the following openAPI definitions the RapiDoc is stuck (page not responding):
https://api.apis.guru/v2/specs/stripe.com/2019-02-19/swagger.json

I have tried to load this in the following:
https://mrin9.github.io/RapiDoc/example2.html

Thanks,
Guy

**Comment by mrin9** [comment]
I am getting some issue with circular refs in the spec,  will work on a fix soon

**Comment by mrin9** [comment]
this should be fixed with the latest commit. You may give it a try by pulling latest code 

to build and test
```
yarn install
yarn serve
```
then navigate to `http://localhost:8080`

**Comment by mrin9** [comment]
Reopening the issue, The fix broke some other functionalities

**Comment by mrin9** [comment]
The spec seems to have circular references, The latest commit ensures that it does not get into an un-ending loop. 
But it may ignore certain parts of the spec. 
Can you verify again if it shows like you expect it to be?

**Comment by mrin9** [comment]
caused due to a bug in json-schema-ref-parser  https://github.com/APIDevTools/json-schema-ref-parser/issues/56

**Comment by mrin9** [comment]
have introduced another attribute `resolve-circular-refs` which defaults to true.  If you are facing any performance issue you might turn off resolving circular refs.

stripe open-api spec can now be loaded by setting this attribute to 'false'

I am closing this issue as the actual reason is at https://github.com/APIDevTools/json-schema-ref-parser/issues/56

but now you have a workaround

Reopen it if you still face problem

>  you still cant use https://mrin9.github.io/RapiDoc/example2.html to open stripe open-api spec as this example attempts to resolve all the circular refs in the spec

**Comment by LevinGuy** [comment]
Thanks for the quick fix. Really love the RapiDoc.

**Comment by mrin9** [comment]
@LevinGuy released version `4.2.1` this version replaces `json-schema-ref-parser` with `json-refs`
In our testing we have found `json-refs` to be performing better than `json-schema-ref-parser`  when handling large files. 
It did not had an issue in resolving https://api.apis.guru/v2/specs/stripe.com/2019-02-19/swagger.json

the drawback is its size.

**Comment by LevinGuy** [comment]
@mrin9 Thanks, looks good 👍
