### ISSUE TITLE
Script import of RapidDoc in angular project breaking ngx-chips functionality

### ISSUE THREAD

**Issue by ranjitkumarsingh** [mrin9/RapiDoc#140]
As there is no angular module available for RapidDoc,  I am using the script import, it does the work of it's own but breaking some other functionalities related to ngx-chip. 

Here is what ngx-chip initially looks on page 
   
![image](https://user-images.githubusercontent.com/6113404/75091213-fe537c80-556a-11ea-8821-3a8f294946b1.png)

when I integrated RapidDoc it started to look like below as it lost all it's visual style:
 
![image](https://user-images.githubusercontent.com/6113404/75091231-4bcfe980-556b-11ea-84f9-ec3dfa51f91f.png)

**Version details**
RapidDoc CDN: https://unpkg.com/rapidoc/dist/rapidoc-min.js
Angular: 8.2.14
ngx-chips: 2.1.0

Please help by fixing this issue or let me know how can I prevent it.

**Comment by mrin9** [comment]
I would have no clue why the styles of `ngx-chips` are getting overwritten. RapiDoc is a web-component and styles are encapsulated, so it shouldn't be overriding anything else. If you believe RapiDoc is overriding `ngx-chips` styles then inspect the element and let me know which `css class` in RapiDoc is responsible in doing so ?

Second, RapiDoc being a WebComponent can be imported as a module in most frameworks. Angular too supports importing WebComponent/Custom Element. A quick search lead me to this
https://medium.com/@jorgecasar/how-to-use-web-components-with-angular-41412f0bced8

Hope it helps.
