### ISSUE TITLE
does Rapidoc really support Oauth2?

### ISSUE THREAD

**Issue by Gildo-Sargi-Neto** [mrin9/RapiDoc#142]
i'm trying to implement Oauth2 to my documentation but in rapidoc it does not requests any key, just shows the link that i set in authorization Url, am i doing something wrong?

code example =
![image](https://user-images.githubusercontent.com/49002665/75448108-5f06fe80-5949-11ea-9822-3f97bac4c2b2.png)

how it looks like : 
![image](https://user-images.githubusercontent.com/49002665/75448192-7f36bd80-5949-11ea-8ba3-3b96881ca4e7.png)

how it should looks like : 
![image](https://user-images.githubusercontent.com/49002665/75448222-8f4e9d00-5949-11ea-8bd5-4db2828c8b1f.png)

**Comment by mrin9** [comment]
To allow oAuth functionality, you need to implement the authorization flow on your own end, and once you receive the token transfer it to RapiDoc element using `setAttribute()` method

check #54 for more info on this.
