### ISSUE TITLE
Formatting text

### ISSUE THREAD

**Issue by marta-lioness** [mrin9/RapiDoc#143]
Hello,

RapiDoc is a great tool, thanks for creating it! 

I'm going to use it in my project, and I noticed a couple of formatting issues:
1. No support for Markdown formatting in the field descriptions. Would you add it, please? It will improve the look of the docs significantly.
2. Alignment of the field names, types, and descriptions. 
It would be easier to read if they were aligned.

![image](https://user-images.githubusercontent.com/58218415/75537996-8ed50580-5a20-11ea-8870-c26e0ae50b32.png)

I'd be very grateful if you implement these fixes to RapiDoc.

Regards,
Marta

**Comment by Gildo-Sargi-Neto** [comment]
maybe you did something wrong, i'm using it here and they are all aligned make sure your rapidoc is up to date and there is nothing that you can change using the api commands described here = https://mrin9.github.io/RapiDoc/api.html

![image](https://user-images.githubusercontent.com/49002665/75557995-d5763000-5a1f-11ea-9134-433153cf3e0b.png)

**Comment by mrin9** [comment]
@marta-lioness , the screenshot that you attached did not came out properly.
But to answer your queries,
- RapiDoc do support markdown on field descriptions
- Field descriptions are aligned 

checkout this example https://mrin9.github.io/RapiDoc/examples/data-types.html that should confirm to  the functionality of markdown and alignment

![image](https://user-images.githubusercontent.com/5056899/75646555-de712800-5bfe-11ea-9610-79c10e9f4da6.png)

In case you are not satisfied with the way things are laid out then change the `schema-style` attribute to `table` 

checkout this example for that http://localhost:8080/examples/schema-table.html#get-/nested-object

![image](https://user-images.githubusercontent.com/5056899/75646882-fd23ee80-5bff-11ea-8b65-3b6d1e1c9429.png)

And if things are not working the same way as shown above on your end please provide an reproducible test case on stalkblitz

**Comment by croudet** [comment]
```yaml
      requestBody:
        description: The commands to register.
        content:
          application/json:
            schema:
              type: array
              description: A list of *CommandBatchs*
              items:
                $ref: '#/components/schemas/CommandBatch'
        required: true
```
The description in array schema (`A list of *CommandBatchs*`) is not formatted with markdown.

**Comment by mrin9** [comment]
we removed markdown support on description for Objects and Arrays some time back as it was interfering with the overall format, since then we have improved the rendering process, but have missed   to apply the markdown back for object/array descriptions

Thanks for pointing it out, will get this into our next patch
