### ISSUE TITLE
No markdown in response description

### ISSUE THREAD

**Issue by abeckers** [mrin9/RapiDoc#144]
I want to add some more information to a response, but the only place I found to put a description, is not formatted.

    get:
      responses:
        "400":
          description: |
            Test1

            | Tables        | Are           | Cool  |
            | ------------- |:-------------:| -----:|
            | col 3 is      | right-aligned | $1600 |
            | col 2 is      | centered      |   $12 |
            | zebra stripes | are neat      |    $1 |

![Bildschirmfoto 2020-03-05 um 13 02 18](https://user-images.githubusercontent.com/10499170/75979856-aeb56f00-5ee1-11ea-9964-9cf9a430266a.png)

Is there a way to do it? Thanks, Andreas

**Comment by mrin9** [comment]
thanks for bringing it up, will add the support in our next patch
