### ISSUE TITLE
multiple request/response examples not working

### ISSUE THREAD

**Issue by humar82** [mrin9/RapiDoc#145]
HI,
with the following yaml, only the first example is shown with rapidoc,
Is there a option to display all the examples? Thanks.

      examples: 
        foo:
          summary: A foo example
          value: {"foo": "bar"}
        bar:
          summary: A bar example
          value: {"bar": "baz"}

**Comment by abeckers** [comment]
Saw this too. I would like to see all examples too.

**Comment by mrin9** [comment]
there is certain complexities in dealing with examples, 

If you want to get a bit of historical info, check out these below issues
#101 ,  #115,  #100 

I am sorry about this, but at present we want to keep this piece simple and will stick with single example

Having said that issue #101 is tagged with `Help Wanted`, I am open for PR's that can take care of it in a clean way and may include the support for multiple examples.

**Comment by mrin9** [comment]
I am opening this issue, as It specifically talks about the support of multiple example. The way we are trying to go forward is to address certain common and easy scenarios.
