### ISSUE TITLE
Print/Download PDF using RapiPDF?

### ISSUE THREAD

**Issue by jcayzac** [mrin9/RapiDoc#150]
I love both projects. If would be so nice if we could:

- Have a PDF download button in RapiDoc
- Have the page layout done with RapiPDF when we want to print.

**Comment by mrin9** [comment]
Adding that button wont be difficult on your end. You can add any html content such as buttons/divs/ custom-elements inside rapi-doc.

Below I am inserting a `<rapi-pdf>` custom element inside `<rapi-doc>`
read about [slots](https://mrin9.github.io/RapiDoc/api.html#slots) to place html contents at specified locations


```html
<!--  untested code, just to give you an idea -->
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <script type="module" src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>
  <script type="module" src="https://unpkg.com/rapipdf/dist/rapipdf-min.js"></script>
</head>
<body>
  <rapi-doc spec-url = "https://petstore.swagger.io/v2/swagger.json" > 
    <!-- put a rapi-pdf button inside rapi-doc slot will decide the placement of button -->
    <rapi-pdf
      slot = 'header' 
      spec-url = "https://petstore.swagger.io/v2/swagger.json" 
      hide-input = "true"
    > </rapi-pdf>
  </rapi-doc>
</body> 
</html>

```
