### ISSUE TITLE
What is happened with body text-area?

### ISSUE THREAD

**Issue by fasikchan** [mrin9/RapiDoc#152]
https://mrin9.github.io/RapiDoc/examples/themes.html#post-/pet

Looks like text area for json body is broken.
Is this latest release?

**Comment by mrin9** [comment]
omg, it seems like this was an issue from past few releases, our test cases (which is pretty much manual at this point) have missed it.
Will look into it soon,  

Looks like release `7.1.1` seems to be working fine, 
But, from `7.2.0` onward after we replace our spec parser `json-refs` with `swagger-client` and this issue started coming up

if you have some time to spare, can you confirm if you can get it working in any release after `7.1.1` ?  Will help me to focus on correct place

**Comment by mrin9** [comment]
On looking little deeper, this issue is limited to swagger 2 specs and occurs during conversion of swagger 2 spec to OpenAPI 3. The `$refs` were not getting resolved. It is addressed in release `7.4.2`

**Comment by fasikchan** [comment]
Thanks for the reply, I'll try 7.1.1.

**Comment by mrin9** [comment]
this is fixed in the latest release `7.4.3`
