### ISSUE TITLE
NODE_ENV error and Modules Missing

### ISSUE THREAD

**Issue by ethanabowen** [mrin9/RapiDoc#153]
Steps to reproduce;
npm
![image](https://user-images.githubusercontent.com/1947151/76910079-0907e580-687b-11ea-88c9-7bce381a9e46.png)

I've read a fair bit about this potentially being a Windows issue (I'm on Windows) though I was previously able to use RapiDoc with no issues.  I've installed/uninstalled/reinstalled nodejs, npm, yarn, and the repo a few times to make sure I'm starting from scratch.  I've cleared out my AppData cache as apart of that process as well.

Also, node_modules seems to be missing the webpack associated folders, it might be missing more as well.
![image](https://user-images.githubusercontent.com/1947151/76910242-7ddb1f80-687b-11ea-8e34-5f05c6a6c28c.png)

Thoughts?

**Comment by mrin9** [comment]
I added a new script command for windows build, I haven't tested it as I work out of mac, but you can pull the latest changes and try building using `yarn run build_windows`
This should work when you  use Powershell to build, if still there is an issue, try to tweak https://github.com/mrin9/RapiDoc/blob/master/package.json#L42

let me know if it worked ?

**Comment by ethanabowen** [comment]
Hmm, I modifiedthe script to 
![image](https://user-images.githubusercontent.com/1947151/76964026-03001c00-68f0-11ea-8d0c-b128351a376e.png)
but still got
![image](https://user-images.githubusercontent.com/1947151/76963989-ec59c500-68ef-11ea-8890-dfae00a2e4c9.png)

A lot of packages are still missing and the install doesn't look super clean.  I was concerned about modifying the package.json versions without knowing reasons behind the versions:
![image](https://user-images.githubusercontent.com/1947151/76964194-570b0080-68f0-11ea-9c66-466ecd4826aa.png)

**Comment by ethanabowen** [comment]
I'm able to resolve all but the fsevents error (which is an optional dpendency, so that's ok.

Build still chokes on webpack error even after manually installing them.  Running the install command wipes out the webpack modules.  Should I consider installing webpack globally?

**Comment by ethanabowen** [comment]
Ok I got it. It was a webpack issue.  I needed to globally install webpack and webpack-cli.

I'm going to go ahead commit that change and close it.

**Comment by mrin9** [comment]
Thanks for testing it out, I have made the changes you suggested. Can you conform me, if you are using `cmd` or `powershell` for building and version of your windows? may be handy if someone else visits this issue

**Comment by ethanabowen** [comment]
powershell

**Comment by tsoestini** [comment]
@ethanabowen were you able to resolve this warning?
`warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.4.1".`

if so, any tips?

**Comment by ethanabowen** [comment]
@tsoestini Sorry for the late reply, I believe I followed mrin9's suggestions on this one.    Using build_windows worked.
