### ISSUE TITLE
Anchor Links in Introduction Do Not Work

### ISSUE THREAD

**Issue by BinaryWizard904** [mrin9/RapiDoc#155]
While markdown anchor links work within most of the document, ones placed in the info/description value do not.  As the OpenAPI 3.0.3 specification [explicitly states](http://spec.openapis.org/oas/v3.0.3#info-object) CommonMark syntax may be used inside of this field and neither #80 nor the [provided an way to interlink document sections using markdown ](https://github.com/mrin9/RapiDoc/commit/4c6d8c833a905dc623a753a39e826dfab286d595) commit mentioned any limits to placement of anchor links, I feel this is a bug.

**Comment by mrin9** [comment]
hmm, just added some markdown at `info > description` It is coming out fine on my end

check this below example, let me know if it is working for you
https://mrin9.github.io/RapiDoc/examples/markdown.html#markdown

**Comment by BinaryWizard904** [comment]
Forgive me, but I don't see any anchor links in that example. Just a few weblinks to other websites.  This issue is with anchor links in the format (to use your example): `[Markdown Content](#post-/markdown)`.  Regular weblinks work fine; there's no problem with those.

Oddly though I can't seem to reproduce the issue from my home computer when I created an [example](https://github.com/BinaryWizard904/RapiDoc/blob/c86b5c6e44690c7f957677e9a6275dc32f66c264/docs/specs/data-types.yaml#L3).  I'll have to dig further into this when I get a chance tomorrow.  Myself and three others were able to reproduce it at work on different devices, so I know it exists.

**Comment by mrin9** [comment]
interesting, there shouldn't be any difference whether you create an internal link or an external link. both are resolved to an `anchor <a>` tag. RapiDoc too, do not treat them as separate cases

In your original issue, did you mean the external link worked but not the internal link?

Will wait for your findings,
thanks for testing it out

**Comment by BinaryWizard904** [comment]
Yes, my original issue was that while external links in the introduction worked, internal links did not.  I tried to make that clearer by linking to issues and commits about internal linking.

Anyways, RE: Testing, I think I found the issue.  It looks like the version of rapidoc-min.js deployed to [UNPKG](https://unpkg.com/rapidoc/dist/rapidoc-min.js) differs from both the [one](https://mrin9.github.io/RapiDoc/rapidoc-min.js) you use in your demos and the dist/rapidoc-min.js version.  As the UNPKG version is the one specified in your [quickstart](https://mrin9.github.io/RapiDoc/index.html#qstart), it's the one I downloaded and used.

You can clearly see the issue by creating an HTML file containing the following code. The in-document links in the introduction do not work, but the ones in the method descriptions do.
```html
<!doctype html> <!-- Important: must specify -->
<html>
<head>
  <meta charset="utf-8"> <!-- Important: rapi-doc uses utf8 charecters -->
  <script type="module" src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>
</head>
<body>
  <rapi-doc
    spec-url="https://raw.githubusercontent.com/BinaryWizard904/RapiDoc/master/docs/specs/data-types.yaml"
  > </rapi-doc>
</body>
</html>
```

**Comment by mrin9** [comment]
Thanks for spending your time and digging it. From your findings, It should work fine in the next release.

**Comment by mrin9** [comment]
`7.5.0` has been released there should not be difference in the behavior for this functionality between [dist/rapidoc-min.js](https://github.com/mrin9/RapiDoc/blob/master/dist/rapidoc-min.js) and the one hosted in [UNPKG](https://unpkg.com/rapidoc/dist/rapidoc-min.js) 

> Do not use `dist/rapidoc-min.js` from github in production, they are canary releases and may contain bugs.
