### ISSUE TITLE
Support of multiple examples.

### ISSUE THREAD

**Issue by pme123** [mrin9/RapiDoc#157]
We use more than one example in a request body, like:

```
      requestBody:
        description: Message Body
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/MessageBody'
            examples:
              Ex without Result:
                value: {
                  "messageName": "startProcessMessage",
                  "businessKey": "myBK",
                  "resultEnabled": false,
                  ...
                }
              Ex with Variables:
                value: {
                  "messageName": "startProcessMessage",
                  "businessKey": "myBK",
                  "resultEnabled": true,
                  ...
                }
```

With editor.swagger.io I can select the example:
![image](https://user-images.githubusercontent.com/3437927/77147987-e3532a00-6a8e-11ea-9f1d-3031f419e6af.png)

With RapiDoc it shows only the first one:
![image](https://user-images.githubusercontent.com/3437927/77148102-244b3e80-6a8f-11ea-9fa0-fa4871c8bf1e.png)

Is there a way I can achieve this?
Thanks

**Comment by croudet** [comment]
See https://github.com/mrin9/RapiDoc/issues/145

**Comment by mrin9** [comment]
thanks I will close this issues and reopen #145 as it has some historical info associated with it.
