### ISSUE TITLE
docker tags

### ISSUE THREAD

**Issue by fbacker** [mrin9/RapiDoc#158]
Is it possible for you to push docker releases with same release tags?

That would make it possible to allow more stable deployments using for example a specific release tag

```docker pull mrin9/rapidoc:7.4.2```

**Comment by mrin9** [comment]
Yes, I need to streamline the docker build pipeline, as on today, it triggers a build whenever something is pushed to github.

**Comment by fbacker** [comment]
Gr8. Nerver trind it bit this might help.

https://github.com/marketplace/actions/build-tag-publish-docker

**Comment by mrin9** [comment]
From release 8.0.0 docker images can be pulled using tags 
https://hub.docker.com/r/mrin9/rapidoc/tags
