### ISSUE TITLE
Problem with API Server with query string

### ISSUE THREAD

**Issue by alitalaghat** [mrin9/RapiDoc#160]
If the API Server has a query string, appending query string goes wrong.

For example, let the following:
API server: http://example.com/index.php?r=
API route: /posts
Query string parameters: page = 1 & limit = 10

Expected call URL:
http://example.com/index.php?r=/blog&page=1&limit=10

Current behavior call URL:
http://example.com/index.php?r=/blog?page=1&limit=10

As you can see, we have two "?" in the current behavior call URL.

Tested via rapidoc v7.4.3.

**Comment by mrin9** [comment]
Per the specs
>  Server URL must not include query string parameters

https://swagger.io/docs/specification/api-host-and-base-path/
