### ISSUE TITLE
Missing font support on Linux

### ISSUE THREAD

**Issue by louwers** [mrin9/RapiDoc#164]
A lot of the used fonts seem to be missing on Linux. E.g. the endpoints are serif fonts instead of monospace. Maybe add `monospace` and `sans-serif` as a fallback where appropiate?

![image](https://user-images.githubusercontent.com/649392/77432619-9a78d980-6dde-11ea-9a64-f888e6f8cb14.png)

**Comment by mrin9** [comment]
Not many, Just 2 fonts are used in the whole app.
And they can overridden by the user to match their style/brand/environment

checkout [API](https://mrin9.github.io/RapiDoc/api.html) on how to provide your own fonts. `regula-font` and `mono-font` attribute can help you with that

The screenshot you provided
- Regular Font is not a part of Linux but getting downloaded from CDN therefore it works
- Mono font is expected to be a part of system installed font therefore dosen't work in case of linux, you may however get it too from a CDN or provide a font thats available on your system.

Nevertheless the suggestion you made is good one and I will add them as fallback fonts

**Comment by louwers** [comment]
Excellent. And I will check out the API. :+1:
