### ISSUE TITLE
Oauth2 clientCredentials: client-id/client-secret rendering

### ISSUE THREAD

**Issue by pavlovmike** [mrin9/RapiDoc#165]
Some days ago I discovered Oauth2 PR from @fbacker 
(this fork https://github.com/fbacker/RapiDoc/tree/feature/oauth2)

This feature does the useful render and processing of client-id/secret in Authentication block 
![image](https://user-images.githubusercontent.com/1196542/77845565-8e16c700-71b8-11ea-8085-25d36859ef78.png)

Today PR is gone :) and in the current release no essential clientCredential flow support added - any plans to do that?

P.S. Thanks for the great project, BTW!

**Comment by mrin9** [comment]
Yes there are plans to support other OAuth flows.

In `7.5.0` release  we provided `Authorization Code` flow. 
currently we are receiving feedbacks on UI/UX, how easy /terrible it is to set it up. will add little bit of documentation on how to set it up

If things go fine
`password` and `client-credential` flow will follow soon

> Feel free to provide your feedback on `Authorization Code` flow if you are using it

**Comment by fbacker** [comment]
I've tried to adjust my PR a third time to more match mrin9 requests. The latest PR allows for a lot of different types, not all tested but client credentials and authorization code is tested. Sorry to see that this PR is closed as well leaving 7.5.0 with limited oauth support. I need these features myself and are forced to turn back to the swagger ui project.

If you have the time @pavlovmike please try the PR out. Might help you with what you need. https://github.com/mrin9/RapiDoc/pull/163

**Comment by pavlovmike** [comment]
@fbacker - I'm already in use with your code, client cred flow works fine.
For now, I have only one comment - maybe it's better to move Auth procedure block to the left - because of asymmetric view, but it's very IMHO
![image](https://user-images.githubusercontent.com/1196542/77999927-1e314980-733c-11ea-9c5a-b63e21fb09f4.png)

**Comment by fbacker** [comment]
Also missing some kind of errors.
I've made an update that shows errors e.g. 'invalid_client' that is returned from the oauth server. Also changes the button text when making the request so we know that something is happening.

**Comment by pavlovmike** [comment]
So - we will wait for @mrin9 to make a decision about supporting all the flows in the master branch.

Maybe it's a good idea to make this partially-tested code merged into master under some feature-toggling/optional flag mechanism? Just thoughts about.

**Comment by fbacker** [comment]
Maybe in gui when using not tried oauth flows show a messy/ugly description to provide feedback if it worked or what happend. Then for each type that gets tested / fixed a new release can remove the description for the type.

best would of course someone that could create all different types in an oauth provider and test/develop them.

so a approaches maybe :)

1. release them all and wait for the community to give feedback
2. hide the non tested auth flow types and wait until a developer can help out because they need it
3. release them all with a api toggle to enable untested types

**Comment by mrin9** [comment]
Release `7.5.1` adds `client credentials` and `implicit` OAuth flow support
checkout the instructions and example on how to set it up
 - [Instructions](https://mrin9.github.io/RapiDoc/oauth_instructions.html) 
 - [Demo](https://mrin9.github.io/RapiDoc/examples/oauth.html#authentication) 

password flow will follow soon
