### ISSUE TITLE
Multiple response body mime-type issue with non identical mappings.

### ISSUE THREAD

**Issue by jwag956** [mrin9/RapiDoc#166]
Thank you for 7.5 support for multiple body types. I have found a small bug - that I think might be pretty common. Say you support form based and json based API. Very often, the form-based responses are always 200 (with errors returned in the form). While the json API would return both 200 and 400.
If you have an endpoint which has 200 (text/html, and application/json), and for 400 just has
application/json. If you select 200 and 'text/html' - then click on 400 - you get 'schema not found'.

Attached is the yaml and screen shot of the error.
![Screen Shot 2020-03-30 at 1 29 51 `PM](https://user-images.githubusercontent.com/1002831/77958892-9b03eb00-728a-11ea-9299-e8e4199c092b.png)

[openapi-bug.txt](https://github.com/mrin9/RapiDoc/files/4405304/openapi-bug.txt)

**Comment by mrin9** [comment]
thanks, will work on it soon

**Comment by mrin9** [comment]
I have updated the test case you mentioned in this example https://mrin9.github.io/RapiDoc/examples/request-body-multiple.html#post-/item-price

will be great if you can confirm from your end

**Comment by jwag956** [comment]
LGTM - thanks!
