### ISSUE TITLE
Support for discriminator objects inside schemas

### ISSUE THREAD

**Issue by sm-Fifteen** [mrin9/RapiDoc#170]
https://github.com/mrin9/RapiDoc/blob/9c5401f06f3f1fe162b1a80a540b45da26ae74db/docs/specs/petstore_extended.yaml#L781-L786

In the extended petstore OpenAPI example, the `Pet` schema has a `petType` tag that is used as a discriminator to determine which of the 3 variants of pet is actually used. [Redoc][redoc-demo] supports it (see the `POST /pet` route) and adjusts the properties presented in the UI based on the value of the discriminator property. RapiDoc does not currently appear to support this, at least not in the way the above example does it. For the record, Swagger UI doesn't support it either, despite this being [a standard OpenAPI property][spec]).

There was recently a discussion from the OpenAPI team to deprecate `discriminator` (see OAI/OpenAPI-Specification#2143), but the consensus now seems to be that it does have a clear purpose (namely: identify tagged unions) and should be kept.

[spec]:https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#discriminator-object
[redoc-api]:https://redocly.github.io/redoc/openapi.yaml
[redoc-demo]:https://redocly.github.io/redoc/#operation/addPet

**Comment by mrin9** [comment]
Well, at RapiDoc, we wont be supporting discriminator at least for the foreseeable future. 
It is an extremely complex feature to implement in the context of RapiDoc with a very little return.

We did try to implement it in the past, but were not able to cleanly address certain complex cases involving other schema composition rules such as `all-off`, `any-of`, `one-of`

Redoc do supports discriminator but their implementation is buggy too.

**Comment by sm-Fifteen** [comment]
Do you happen to have any examples regarding those complex composition use cases, or in what ways Redoc's implementation turns out to be buggy? I understand your point on how this is a somewhat niche feature (as far as OpenAPI goes, anyway) and that the returns on user experience wouldn't be all that significant, but I'm curious to know about the implementation issues and pitfalls.

**Comment by mrin9** [comment]
a quick search of `discriminatior` issues in redoc's source has  given me some

https://github.com/Redocly/redoc/issues/1088
https://github.com/Redocly/redoc/issues/1076
https://github.com/Redocly/redoc/issues/1031
https://github.com/Redocly/redoc/issues/862

there are more, I am just listed few of them

**Comment by pschichtel** [comment]
Would a pull request be welcome for this?
