### ISSUE TITLE
incorrect boundary used for multipart-form requests

### ISSUE THREAD

**Issue by skwakman** [mrin9/RapiDoc#174]
Since RapiDoc 7.5.0, requests generated using `Content-Type: multipart/form-data` contain an incorrect `boundary` header. Because of this incorrect header value, all multipart/form-data requests will fail on probably any backend.

**Steps to reproduce this issue:**
1. have a swagger YML file containing a multipart/form-data element (see https://github.com/skwakman/rapidoc-multipart-issue/blob/master/test.yml )
2. have a html file loading rapidoc version 7.5.0 or higher (see https://github.com/skwakman/rapidoc-multipart-issue/blob/master/api-test.html )
3. load up a local webserver, for example using python's `python http.server`
4. open up your browser's dev tools and open the 'network' tab
5. open up the api-test.html, fill the fields and click 'try'

Find the sent request in the network tab. The request's `content-type` header will be `multipart/form-data; charset=utf-8; boundary=RAPIDOC`. However, looking at the request's body, the actual boundary looks like a randomly generated string created by the browser, such as `-----------------------------3779300221716527953402675240`. 

The request generated by rapidoc sets the boundary value to `RAPIDOC`, but does not actually use this boundary for its request body. This behaviour was introduced since 7.5.0, version 7.4.3 does not seem to have this issue.

**Comment by mrin9** [comment]
thanks for reporting, 
we were testing to support some pipeline integrations where we needed some predictable form boundaries, seems like it somehow mistakenly got merged. will remove it in our next patch, which will be coming soon
