### ISSUE TITLE
Scrolling keeps resetting

### ISSUE THREAD

**Issue by eladchen** [mrin9/RapiDoc#175]
Hi, 

First of all, thank you for sharing this project, it seems promising.

While trying to integrate this library I came across an issue during scrolling.
I have a feeling the CSS used here is the main culprit (I noticed a mix of position: sticky + overflow: hidden, which is tricky)

Anyway since I can't describe it, I thought it will be more helpful to share it using a sandbox.

Here is the source to reproduce the issue I'm trying to describe:
https://codesandbox.io/s/rapidoc-nav-bug-h8t8o

Below is a link to the rendered example, while scrolling down the page, I'm experiencing a reset; I'm taken back to the top of the page.

https://h8t8o.csb.app

Let me know if there is any other information I can provide you with.

**Comment by mrin9** [comment]
I think it is to do the interference from other elements on the page and their css styling.
can you attach some `overflow` style property to rapidoc element so that it is not inherited from parent
```
    <>
      <CssBaseline />
      <div className={classes.root}>
        <Container>
          <Paper className={classes.content}>
            <h1>Edit me...</h1>
            <rapi-doc {...rapidocAttrs} style={{ "height":"600px", "overflow":"scroll" }}/>
          </Paper>
        </Container>
      </div>
    </>
```

**Comment by eladchen** [comment]
Looks like this does solve the issue, however, isn't this something the library should abstract?

Also, this limitation kinda forces the navigation to always have a limit in height?

**Comment by mrin9** [comment]
this is more of a feature than an issue. RapiDoc is allowed to be embedded in html just like any other html element. and it gives the control of its styling to its user and among other things it includes sizing/padding/margin etc.

Users can place it the way they like it, but that comes with a responsibility of styling it correctly. 

embedding it in `read-mode` is tricky as it highlights the nav bar as you scroll, and for that it needs a defined height.
I just gave an example of a fixed size, but you are allowed to size it as you like, it can be dictated by the parent components height, relative sizing such as `height:80vh` use css `vars` and `calc` if you want to, 

there are also cases mostly with micro services where people put many RapiDoc elements into the same page rendering multiple open-api specs. here is an similar implementation https://www.northbricks.io/apis/ (view-source of the page will give you an idea)
