### ISSUE TITLE
Examples are broken

### ISSUE THREAD

**Issue by mayaswrath** [mrin9/RapiDoc#176]
Looks like all of the examples are broken. 
https://mrin9.github.io/RapiDoc/rapidoc-min.js returns a 404.

It looks like commit 852321679d2231f63dae8a847d51146b992e8f93 removed the files from the docs directory.

**Comment by mrin9** [comment]
oops... thanks much for reporting, I have put back the file

Let me know if it works at your end

**Comment by mayaswrath** [comment]
Looks good.
