### ISSUE TITLE
markdown support

### ISSUE THREAD

**Issue by bharath144** [mrin9/RapiDoc#177]
Hello,

As per the Openapi 3.x specification, markdown syntax is allowed for the `description` fields through out the spec (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#richtet). I tried a bunch of options using the markdown syntax as per (https://spec.commonmark.org/0.27/) but nothing seemed to get rendered.

Does rapidoc support any kind of markdown?

**Comment by mrin9** [comment]
Do you have a spec that can reproduce what you are saying ?
When I test these below examples it works fine on my end
- https://mrin9.github.io/RapiDoc/examples/markdown.html
- https://mrin9.github.io/RapiDoc/examples/code-highlight.html

**Comment by bharath144** [comment]
Thanks for the response. The examples helped. I was using it incorrectly.

Appreciate your help!
