### ISSUE TITLE
Oauth2 Proof Key for Code Exchange(PKCE) support

### ISSUE THREAD

**Issue by Gildo-Sargi-Neto** [mrin9/RapiDoc#178]
I saw that recently you added Oauth2 Support but i'm trying to use this key(PKCE) and i'm not obtaining success, is there any way to use it?

**Comment by mrin9** [comment]
PKCE and Password flows are still under some reviews. 

If your API supports other OAuth flows, did it worked with them ? do you know what issues are you facing with PKCE flow ?

**Comment by mrin9** [comment]
You should be able to use Authorization Code flow, if your provider is supporting PKCE. 
The work that we are doing for PKCE is for our exclusive clients and wont be released publicly coz AFASIK OpenAPI spec do not have an option yet to specify PKCE support in the spec.
