### ISSUE TITLE
Path parameters are not automatically URL encoded

### ISSUE THREAD

**Issue by mjbrisebois** [mrin9/RapiDoc#18]
When trying a request using the documentation interface, path parameters must by manually URL encoded (eg. "/some/path" > "%2Fsome%2Fpath" or "Creme Brulee" > "Creme%20Brulee").

Is there a reason it is not automatically encoded?

**Comment by mrin9** [comment]
there shouldnt be any reason, must be an oversight/bug. 
Thanks for reporting will take care of this soon

**Comment by mjbrisebois** [comment]
Thanks!  I added a pull request in case that helps #19

**Comment by mrin9** [comment]
thanks for the PR, have merged it now, feel free to test the latest from master and if it works as expected, you may close this issue

**Comment by mjbrisebois** [comment]
What file am I supposed to use?

I tried using `/dist/rapidoc-min.js` from master but it looks like it hasn't been rebuilt.  I got the same behavior as before.

**Comment by mrin9** [comment]
you need to run 
```
yarn install
yarn build
``` 
to generate `/dist/rapidoc-min.js`

**Comment by mjbrisebois** [comment]
Thanks!  I was able to test it and it worked as expected.

I don't use the yarn development environment so I ran the build using a docker.  Here is the makefile if your interested [GNUmakefile](https://github.com/webheroesinc/RapiDoc/blob/master/GNUmakefile).  Then anyone who has docker can easily rebuild the dist.

Run:
`make build`

For now, I'm going to keep using my built file.  Can you let me know when you update https://unpkg.com/rapidoc/dist/rapidoc-min.js so can I can switch back?

**Comment by mrin9** [comment]
I am planing for the next release either this weekend or next. You can use [GitHub's Release Notification](https://help.github.com/en/articles/watching-and-unwatching-releases-for-a-repository) to be on top of the releases

I will be very interested on a Docker build. 
you are welcome to create PR, containing a dockerfile and some instructions in readme
