### ISSUE TITLE
Issues with Clients Cred flow: No errors notification + Empty "Auth procedure" column

### ISSUE THREAD

**Issue by pavlovmike** [mrin9/RapiDoc#180]
@mrin9, hi
Just re-tested OAuth feature and got some little issues:
1. No error is shown in case of wrong credentials (for Client Cred flow)
2. If no API keys or basic auth set => "Authentication procedure" header and empty space under it looks a little bit messy
![image](https://user-images.githubusercontent.com/1196542/78601919-39c9b200-785e-11ea-8302-e744c4ab27f5.png)

_Originally posted by @pavlovmike in https://github.com/mrin9/RapiDoc/issues/165#issuecomment-610019960_

**Comment by mrin9** [comment]
this should have been fixed by 9dad355
not yet released , but you can build it yourself or take in from `src/dist`

feel free to open, if you still face an issue, with a minimal spec to reproduce
