### ISSUE TITLE
Oauth Client cred flow: the token request not using Basic auth auth by default

### ISSUE THREAD

**Issue by pavlovmike** [mrin9/RapiDoc#182]
Hi! 
Most of Oauth servers supports Basic auth for token request with x-www-form-urlencoded body => like it's described in RFC : [Client Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.4) 
Sample:
```javascript
var data = "grant_type=client_credentials";
var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.addEventListener("readystatechange", function() {
  if(this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("POST", "https://demo.identityserver.io//oauth2/token");
xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
xhr.setRequestHeader("Authorization", "Basic S0000bla-bla-bla");
xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
xhr.send(data);
```

But after testing I found out that RapiDoc uses form-data encoded body token request that optionally may be supported by some Oauth servers - but not always.

Maybe it can be an option? But I guess the "Oauth RFC" way need to be default one

**Comment by pavlovmike** [comment]
I have dug a little deeper into that: 
Linked with base Oauth RFC [Dynamic Client Registration](https://tools.ietf.org/html/rfc7591#section-2.3.1) describes that client_secret_basic (client_id/secret in Auth Basic header) and client_secret_post (creds in POST body) - is a setting used in Client registration and saved in metadata on Auth server.

Every Oauth service prefer some default behaviour - for example, https://auth0.com use client_secret_post, popular opensource server ORY Hydra - client_secret_basic

So I guess - client-side should support both of them and let this option to be chosen - cause we are not always can manage the server-side

**Comment by mrin9** [comment]
that is true, I will make the needed modifications to follow the RFC
thanks for digging.

**Comment by pavlovmike** [comment]
@mrin9, Hi!
Which server do you use to test your Auth code? [Current code](https://github.com/mrin9/RapiDoc/commit/2d5491e0ed5fc1c4e8d8964c5bfdc860d724b095) use client_id and secret in the POST body - it's the _alternative_ way, not required.

As I mentioned before base RFC requires in Client cred flow to set up client_id/secret with Authorization basic scheme: this is correct sample from here  https://tools.ietf.org/html/rfc6749#section-4.4.2
```
POST /token HTTP/1.1
Host: server.example.com
Authorization: Basic czZCaGRSa3F0MzpnWDFmQmF0M2JW
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
```

**Comment by mrin9** [comment]
no it is not using `POST Body`
the commit i mentioned above has changed it to use `application/x-www-form-urlencoded`
https://github.com/mrin9/RapiDoc/commit/2d5491e0ed5fc1c4e8d8964c5bfdc860d724b095#diff-f78d18f808358d306c1cd1b99fbd4b30R50

this is not yet released, so if you want to test using the latest code then you need to build it yourself or pickup the file from `dist/rapidoc.min.js` 

we tested it against multiple clients who sponsor our work. but if you need create generate your own oAuth provider then use  [keycloak](https://www.keycloak.org/getting-started/getting-started-docker)

if you have dockers on your end, then the below command should get you up with your own personal oAuth provider
```
docker run -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin quay.io/keycloak/keycloak:9.0.2
```

**Comment by pavlovmike** [comment]
I have already update RapiDoc (from master) and tested - with network logging => client id and secret still NOT in Authorization: Basic header

I guess, we misunderstood each other a little: RapiDoc now use credentials inside application/x-www-form-urlencoded **body** 
Created PR #184 for a better explanation and correction => code from PR already tested with public Oauth service https://demo.identityserver.io/

**Comment by mrin9** [comment]
Got it, by `POST body` I meant it is sending over URL. 

But from your PR #184, I see what you mean. and you are correct in saying
- Authorization Server **MUST** accept client-id and secret in `Authorization` header if possible
- Alternatively Auth Servers who are unable to use `Authorization` take client-id and secret in the POST url

However, some of our test failed when I applied your PR. I will accept your PR and also attach `client_id` and `client secret` in the Post url.

will be great if you can tell me if it worked on your end.

> below is the extract from the RFC https://tools.ietf.org/html/rfc6749#section-2.3.1 for reference purpose
```
   the client
   password is encoded using the same algorithm and used as the
   password.  The authorization server MUST support the HTTP Basic
   authentication scheme for authenticating clients that were issued a
   client password.

   For example (with extra line breaks for display purposes only):

     Authorization: Basic czZCaGRSa3F0Mzo3RmpmcDBaQnIxS3REUmJuZlZkbUl3

   Alternatively, the authorization server MAY support including the
   client credentials in the request-body using the following
   parameters:

  client_id
         REQUIRED.  The client identifier issued to the client during
         the registration process described by Section 2.2.

   client_secret
         REQUIRED.  The client secret.  The client MAY omit the
         parameter if the client secret is an empty string.

 ```

But this broke some of our test cases.

**Comment by pavlovmike** [comment]
Unfortunately, our OAuth server ( https://github.com/ory/hydra ) setups only one token_endpoint_auth_method for each client - client_secret_basic OR client_secret_post => not both. 

In case than client_secret_basic set - service automatically detects client_id and secret in request Body and throws a validation error about that => even if Authorization header is correct. 
Don't know why - but server forces me to use only one of auth style methods for a client, not both at the same time, I guess it may be incorrect behaviour of auth service :-/

At least - I`ll prefer to add for RapiDoc some checkbox "Use basic auth". If I will have time - I will try to make a PR for that, but UI tasks are not my "power skill"

**Comment by mrin9** [comment]
thanks for helping us on this, I will provide an option in the UI to allow user to select how they like to submit client-id and secret.

**Comment by pavlovmike** [comment]
Yeee, "It's alive, it's alive!" ))
Thanks!
