### ISSUE TITLE
Request: one page per endpoint

### ISSUE THREAD

**Issue by dcarr178** [mrin9/RapiDoc#185]
One of the cons of making a large html page with every endpoint on it is when users click on a specific endpoint from the left navigation bar it's not immediately clear where that endpoint documentation starts and ends. The start usually bleeds into the previous endpoint documentation and the end bleeds into the next endpoint documentation. Rapidoc uses HR breaks but for some users it's just not enough to create clear separation.

Other renderers present users with only one endpoint at a time (example https://dcarr178-4.docs.stoplight.io/api-reference/crunch-api/log-in/get-public-login) for greater clarity and I think Rapidoc would be stronger if it had a configuration option to do that as well.

Is this a good idea? If yes then I'm more than willing to work on this code contribution.

**Comment by mrin9** [comment]
I can see how showing single endpoint view can improve usability experience. Currently RapiDoc offers two rendering styles `view`, `read` and like you suggested another can be added  `focused` or `single-endpoint` (_welcome to provide for a better name_)

but before, there are few important aspect I would like you to consider

- The following functionality that is supported by RapiDoc must not break
  - Navigating to any endpoint using the URL. that is, you can have links to any endpoint and share via email, messenger etc.
  - Creating links to other endpoints using the markdown
  - `scrollTo(endpoint)` method that takes you to a given end-point

   this [example](https://mrin9.github.io/RapiDoc/examples/collapsable.html) shows some of the above mentioned functionality

- Provide a brief insight on how the search gonna work in this view

can you do a little assessment on your end if this can be achieved ?

**Comment by mrin9** [comment]
the following commits adds a new rendering style `focused`

709b5c72c2cff3b25aafe3923befea73c0a195be
438b7ca8060f1bcc9033b8bb97195a49bf5b0cc3
684fed3bb71bbcfdffc5f154c1a07246508ee02b

you can check it out in action here https://mrin9.github.io/RapiDoc/examples/focused-mode.html
