### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by stevenj** [mrin9/RapiDoc#193]
I find the font size selections to be rather small.  What is the recommended way to change the size of the fonts?

**Comment by mrin9** [comment]
There isnt any official recommendation on that. We did build our internals to allow users to change font-sizes using API / attribute. 

But in case you need to change it now in a `non-recomended` manner 

try changing the below [css variables](https://developer.mozilla.org/en-US/docs/Web/CSS/var) to your desired sizes

```yaml
  --font-size-mono: 13px;
  --font-size-regular: 14px;
  --font-size-small: 12px;
```
