### ISSUE TITLE
v8.0.0 dist build is still 7.5.1

### ISSUE THREAD

**Issue by Uzlopak** [mrin9/RapiDoc#194]
Hi,

nice project you have :). Why is your 8.0.0 still identifiying itself as 7.5.1?

**Comment by mrin9** [comment]
thats a bummer, our build pipe-line got messed-up. The code is `8.0.0` but the version banner is `7.5.1`
I guess I will have to release a new build, will do it soonish...

**Comment by mrin9** [comment]
this is now fixed in release `8.1.0`
