### ISSUE TITLE
Accept or Content-Type in header to select json or xml

### ISSUE THREAD

**Issue by joelweeks** [mrin9/RapiDoc#195]
Hi,

I have an API that can take either JSON or XML. Swagger uses a pulldown to control the response or request schema type.  It seems that RapiDoc combines them. But I only want one.

Swagger curl:

-H  "accept: application/xml"
OR
-H  "accept: application/json

RapiDoc:

 -H "Accept: application/json, application/xml" 

Thanks for any suggestions.

**Comment by mrin9** [comment]
is it creating an issue on your end ?

the `curl` syntax is only for viewing/copying, it is not the actual call RapiDoc is making to the server when you click **TRY**

**Comment by joelweeks** [comment]
My API throws a 

"Response Status: Bad Request. Invalid content type specified in request:400"

I guess for GET, for example, it doesn't know which type to return.

**Comment by mrin9** [comment]
So as I understand it is not the problem with `curl` syntax that is shown in RapiDoc.
instead it is the Actual call that RapiDoc is making to your API Server when you click **TRY** button

can you confirm if thats the correct understanding ?

**Comment by joelweeks** [comment]
I applied the content-type fix already. You're correct, problem is not with curl. I was just comparing curl with curl from Swagger to see any differences. Swagger doesn't use curl either, but it's the best debugging info for me.  But same .yaml file works in Swagger. I can play with some more tests in Postman on Wednesday. They all have Content-type in them but not Accept. Our docs say Accept is required but it's not in my test library and it works fine.

**Comment by joelweeks** [comment]
I created a test case where I removed the XML response for a GET. This worked.

```
  /departments:
    get:
      summary: Retrieve a list of departments
      description: Retrieve a list of departments.
      operationId: getDepartments
      tags:
        - Department
      parameters:
        - $ref: '#/components/parameters/maxPage'
        - $ref: '#/components/parameters/pageNumber'
      responses:
        '200':
          description: A list of departments
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepartmentListResponse'

vs

  /departments:
    get:
      summary: Retrieve a list of departments
      description: Retrieve a list of departments.
      operationId: getDepartments
      tags:
        - Department
      parameters:
        - $ref: '#/components/parameters/maxPage'
        - $ref: '#/components/parameters/pageNumber'
      responses:
        '200':
          description: A list of departments
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DepartmentListResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/DepartmentListResponse' `

```

**Comment by mrin9** [comment]
I think this isnt any issue anymore on your end. There is no change needed on RapiDoc's end
- If you specify in the spec that it accept multiple `content-type` responses then rapidoc will form the `Accept` header accordingly
- `content-type` header will be formed based upon what data are you sending `json, xml, txt`

**Comment by joelweeks** [comment]
Thanks for looking at this issue.

I pulled the latest changes from master, include #213. But it still fails if there are multiple response types. I'm not sure what I can change on my end to fix the problem - it needs both types of responses.

**Comment by tnotheis** [comment]
I have a related/more specific issue: if I select a content type for the Accept header of a GET request, everything works as expected: only the selected content type will be sent to the server. 

BUT: if I want to set the header for a POST, all available content types are concatenated, as described by the author of this issue.
