### ISSUE TITLE
json ref tags not expanded when using embedded json

### ISSUE THREAD

**Issue by mattcobb** [mrin9/RapiDoc#197]
Trying a technique like in example9 to have the json in the html page, but the ref tags are not followed (7.5.1).  I see in 8.0 there is an attempt at a fix, if you also rewrite your JSON with /JSON in place of the paths.  This has the problem that all the paths become /JSON

GET /JSON

should be 

GET /pets

in example9 (8.0.0).

Refs are followed in a spec from URL ok.  It is not clear why loading all the json from a string is different.  The refs are all local in the json in both cases.

**Comment by mattcobb** [comment]
I was thinking that the /JSON string was some kind of keyword.  You can correct this path to whatever you need, /pets for example, or longer paths.  So 8.0.0 fixes this problem of refs for me without issues

**Comment by mrin9** [comment]
sure, will take your suggestion and make it less confusing for others.

Thanks for the feedback
