### ISSUE TITLE
Response example rendered incorrectly

### ISSUE THREAD

**Issue by jakul** [mrin9/RapiDoc#2]
Hi,

Firstly, thanks for making this repo! It does everything I want from a Swagger viewer, all in a lightweight package ❤️ 

That said, I've found a small bug in the example response section, where the content from one example flows on top of the next one.

![captura de tela 2019-02-15 as 09 21 55](https://user-images.githubusercontent.com/862794/52847166-5dceaf00-3103-11e9-99d0-9d96e1e7037d.png)

# Possible solution
There is a `flex: 1` applied to the element. If I remove that, then the example renders much better:

![captura de tela 2019-02-15 as 09 22 20](https://user-images.githubusercontent.com/862794/52847304-b69e4780-3103-11e9-9516-748da2e88b54.png)

**Comment by mrin9** [comment]
I am unable to recreate this issue on my end, (tested on chrome, firefox and safari)
Can you share the following info

* RapiDoc Version you are using
* Browser and its Version
* OS and Screen Resolution

If you know a possible solution then I will be more than happy to take a PR

**Comment by jakul** [comment]
The cause of this is the same as in my [other issue](https://github.com/mrin9/RapiDoc/issues/3#issuecomment-464651452). If I change the opening tag from `<html>` to `<!doctype html>` then the examples render correctly.
