### ISSUE TITLE
server-url attribute defaults to spec-url domain root

### ISSUE THREAD

**Issue by jonvictory** [mrin9/RapiDoc#203]
Hello,

This is my first issue, so I apologize if I'm breaking any rules or missing any information, feel free to advise and I'll fix any errors.

According to this documentation:

> **allow-server-selection** | If set to 'false', user will not be able to see or select API server (Server List will be hidden, however users will be able to see the server url near the 'TRY' button, to know in advance where the TRY will send the request). **The URL specified in the server-url attribute** will be used if set, else the first server in the API specification file will be used.
>

However, when I set the attribute allow-server-selection to false and set my server-url attribute to any value, the rapidoc will always default to sending my requests to the root domain of the spec-url attribute:

![image](https://user-images.githubusercontent.com/19315203/81013804-035d6380-8e19-11ea-9a80-06d3f2323df5.png)

If I set the attribute allow-server-selection to true, then I'm able to select the server that is specified in the server-url attribute from the radial button list:

![image](https://user-images.githubusercontent.com/19315203/81013036-c04ec080-8e17-11ea-8e04-87b9a21b3029.png)

The root domain of my spec does not exist anywhere except for in the spec-url attribute of the rapidoc element, so it seems like the spec-url is overriding my server-url attribute regardless of whether server-url is set on window load, or afterwards through a button click. 

The api-key-value attribute works as expected, and will update in the UI regardless of whether I set it on window load, or later through a button click.

I love your product, have been working on a test project site for my company and rapi-doc has been a huge part of my ongoing success. Thanks for all you do.

**Comment by mrin9** [comment]
can you confirm my understanding, 

the expectation here is, if `server-url` is provided and `allow-server-selection = false` then it must redirect all the API calls to `server-url` and not to the url where the spec file is hosted

**Comment by jonvictory** [comment]
Yeah, that sums up my expectation. Perhaps I read the documentation
incorrectly, but that's what I thought the description (included in the
issue request) was implying.

Let me know if I can provide you with anything else.

**Comment by mrin9** [comment]
Well in that case I am unable to recreate this issue on my end. Above I provided a minimal `yaml spec` and the corresponding `html` to show it through `<rapi-doc>` and it is correctly sending the API requests to `server-url`

Can you try the above spec and html on your end ? else provide me with a minimal spec that highlights this issue ?

**Comment by jonvictory** [comment]
Will do my best.

**Comment by jonvictory** [comment]
"Can you confirm is this is what you are trying to achieve
if server-url is provided and allow-server-selection = false then it must redirect all the API calls to server-url and not to the spec-url

I tried with the following setup
my-spec.yaml (no API servers in the spec)"

So, the issue was that I still had a 'servers' section in the spec, even though there was no specified URL for the server.

`"servers": [
    {
      "url": "",
      "description": ""
    }
  ],`

After reading your quote above, I checked my schema again, saw the empty server specification and removed it. This eliminated the error I was experiencing where rapidoc would default the server-url to the root directory where my spec documented was being hosted from.

**Comment by jonvictory** [comment]
Thanks for looking into this--love rapidoc!
