### ISSUE TITLE
Bug: Slugger hash error in description headers

### ISSUE THREAD

**Issue by winonecheng** [mrin9/RapiDoc#204]
There is one header text `Beginner's Guide` and the slugger would hash this string to `beginner39s-guide`. But, its corresponding navbar is not the same id (`link-beginners-guide`).

Reference code:
- https://github.com/mrin9/RapiDoc/blob/master/src/rapidoc.js#L161
- https://github.com/mrin9/RapiDoc/blob/master/src/templates/navbar-template.js#L41

**Comment by mrin9** [comment]
Thanks for reporting and pointing to the code !!!
this is now been fixed (not yet released)

to test it, you can pick `rapidoc.min.js` from `dist` folder or generate yourself from the source

**Comment by winonecheng** [comment]
Hi @mrin9 ,
would u plan to publish the latest release?

**Comment by mrin9** [comment]
It is planned in the first week of june
