### ISSUE TITLE
REST methods not in navigation

### ISSUE THREAD

**Issue by ethanabowen** [mrin9/RapiDoc#212]
The REST methods (GET/POST/etc) are not displaying in the Read style navigation.

![image](https://user-images.githubusercontent.com/1947151/81819812-6cb63400-94f5-11ea-81ef-3af0fa818ed6.png) (This picture was taken from the RapiDoc website)

The RapiDoc webpage pictures display these values, but no example has a working version of this feature and I was unable to get it working locally.

**Comment by mrin9** [comment]
Duplicate of #210
