### ISSUE TITLE
Release doesn't have fixed Content-Type

### ISSUE THREAD

**Issue by mjbrisebois** [mrin9/RapiDoc#213]
The dist build code doesn't have the "Content-Type" fix in commit 6337f0c2457b1615fde4597f37a0e79f8c9fe0ff.

This defect took me a while to discover because standard body parser's just return null with no errors.  Could you release a hotfix patch for this?

**Comment by mrin9** [comment]
I am sorry that it took away some of your time, I need to put it somewhere thats easy to discover that build in `dist` folder isnt official build, its  a `canary` build that we keep there.

`npm` is where  we publish our releases so `https://unpkg.com/rapidoc/dist/rapidoc-min.js` is the place to get the released versions

I have updated the `dist` with the latest build, you should be able to get that fix now
