### ISSUE TITLE
Feature Request - Show cUrl example for each path

### ISSUE THREAD

**Issue by LevinGuy** [mrin9/RapiDoc#214]
Hi,

I think that auto-generating a curl / languages commands should be a great addon for the paths:

For example:
![image](https://user-images.githubusercontent.com/8510784/82117775-3984d680-977b-11ea-8d91-88c3bcc2d02e.png)

Thanks,
Guy

**Comment by LevinGuy** [comment]
Hi @mrin9 ,

Perhaps adding something like this:
https://apiembed.com/

I think it can be very useful.

Thanks,
Guy

**Comment by mrin9** [comment]
auto code generation is not the primary focus of this library.
However, I have added this feature in our internal roadmap
