### ISSUE TITLE
Issue with curl - does not show the authorization header unless it is set

### ISSUE THREAD

**Issue by LevinGuy** [mrin9/RapiDoc#215]
There is a small issue in the curl command generated.
At the moment the curl command does not include the authorization header (or any other authorization) unless it is set which leads to unclear curl examples.

![image](https://user-images.githubusercontent.com/8510784/82117739-faef1c00-977a-11ea-8244-cff11d519562.png)

Thanks,
Guy

**Comment by mrin9** [comment]
I am not sure whats the ask here ?

It wont be possible to provide authorization token unless it is set by the user.  
also, the generated curl request is valid without the authorization token is a valid one

**Comment by LevinGuy** [comment]
Hi @mrin9 ,
I think that the cURL command should include the authorization - if it is not specified. Perhaps it should write 'undefined' or something. 

It seems that many people want to have an example cURL command (example URL) that they can run to see for themselves - not always to run from the docs since there could be possibly CORS issues and etc...

Thanks,
Guy

**Comment by mrin9** [comment]
> if it is not specified. Perhaps it should write 'undefined' or something.

This will almost make every `curl` command invalid. It is not only true about the authentication, a request may include form/query parameters and generating a curl will only be possible when these parameters are provided and the user hits `TRY` button.
