### ISSUE TITLE
Sorting of Response -> Model -> Object

### ISSUE THREAD

**Issue by ralpha** [mrin9/RapiDoc#217]
It seem that by default the response schema under Response -> Model -> Object is sorted alphabetically. 
This might be desired in some cases. But could you allow an option to use the order of the schema itself?
If there is already an option, I could not find it here: https://mrin9.github.io/RapiDoc/api.html

This is handy because my `id` is now somewhere in the middle and when you have responses with a lot of optional fields this is very confusing. And it does not line up with how the actual response comes back.

This is also the same for Response -> Model -> Example.

( maybe because of some kind of tree/map structure the order is not preserved but, lets hope that is not the case :crossed_fingers: )

**Comment by mrin9** [comment]
can you provide me with a minimal spec where you see this happening. When I see it in some of the provided [examples](https://mrin9.github.io/RapiDoc/list.html) the schema and the examples are not sorted

![image](https://user-images.githubusercontent.com/5056899/82613460-2e1a1c80-9b7a-11ea-92b8-92fa70b6060c.png)

**Comment by ralpha** [comment]
Sorry this was an issue with the openapi spec generator I'm using. So not an issue with this application.
I'll close the issue.
