### ISSUE TITLE
schemaDescriptionExpanded button in schema table cause misunderstanding

### ISSUE THREAD

**Issue by winonecheng** [mrin9/RapiDoc#219]
Regardless of value of `schema-description-expanded`, there is `toolbar-item` button (named 
Expand/Collapse Details) in schema table. See the below examples.

![image](https://user-images.githubusercontent.com/11289632/82630627-d0430e80-9c25-11ea-9f1b-d70a39dae9cf.png)

![image](https://user-images.githubusercontent.com/11289632/82630637-d933e000-9c25-11ea-993a-df3b27722337.png)

After clicking the button, it has no effect to the schema table if all description are one line.
I think It make user misunderstand that the button is used to expand/collapse schema level and it is broken now.

Suggestions:
1. Hide the button if `schema-description-expanded` is `true`
2. Modify the button text

**Comment by mrin9** [comment]
> After clicking the button, it has no effect to the schema table if all description are one line.
it is true, its not a very clean implementation, 

> Hide the button if schema-description-expanded is true

That way user wont be able to switch it back to a single line view. 

For a description heavy schema, - When a consumer checks out a schema for first few times, they like to see it along with full description, once they get a better understanding of the API, they like to cut out the `description` noise and just concentrate on the data-types and field name.  

**Expand Details** functionality was added specifically to address this concern

> Modify the button text

This can be done, one option would be `Expand/Collapse Description` however I need to put some alternate text suggestions in our next survey to back the change request with some data. 

Our next survey is about a month from now, please provide if you have some thing in mind

**Comment by winonecheng** [comment]
I see. Thx for your help.

One more option: provide another button to expand/collapse schema level
