### ISSUE TITLE
Query parameters ignored in Authorization URL

### ISSUE THREAD

**Issue by shobanavikram** [mrin9/RapiDoc#220]
I need to use Oauth2 for my API and my Oauth2 provider requires a audience as a query parameter. It works in swagger hub if i pass it in the query. But with rapidoc, the audience is ignored when the request is sent.

"securitySchemes" : {
      "OauthSecurity" : {
        "type" : "oauth2",
        "flows" : {
          "implicit" : {
            "authorizationUrl" : "https://<my-auth-url>/authorize?audience=<my audience>",
            "scopes" : {
              "openid email profile" : " Custom",
              "user" : "user"
            }
          }
        }

**Comment by mrin9** [comment]
Thanks for reporting, will get back to you on this

**Comment by mrin9** [comment]
this is taken care of now, its not yet released but either you can take `rapidoc.min.js` from dist folder or build it yourself
