### ISSUE TITLE
Use JSONEditor in example editor and response viewer (JSON)

### ISSUE THREAD

**Issue by Ivan-Baranov** [mrin9/RapiDoc#223]
I want to suggest use [JSONEditor](https://github.com/josdejong/jsoneditor) in example editor and response viewer.

Must have futures:
 - code folding / tree viewer
 - JSON validating
 - button to edit example / preview response in maximized (fullscreen) view

Optional must have:
 - generate JSON schema from response model and validate real response by it
 - sharing response
 - local storage for examples

**Comment by mrin9** [comment]
I dont think our vision or roadmap for RapiDoc would be adding some feature like that.

RapiDoc does one thing which is documenting OpenAPI spec. 

It wont try to become a perfect client for the API. there are many issues with that,
- JSON isnt only the format that can be sent to APIs
- Adding a full fledged editor will increase our bundle size to multiple folds, we try to keep our dependency to minimum and carefully select and bundle them.

Also there wont be any JSON or other validation. 
Many of our client use rapidoc for quick API testing, which includes negative tests too, so need to allow people to send invalid data to see how their API behaves in those situation.

**Comment by Ivan-Baranov** [comment]
It may be possible to make the editor plug-in from outside. For example, if JSONEditor is found in the window object try to use it, else use default editor.

Is it possible to get access to the editor element from the main html?

**Comment by mrin9** [comment]
it may be possible to plug-in an editor, I haven't explored on that aspect, but the way RapiDoc is structured it shouldn't be much difficult.

However, RapiDoc supports theming, there may be considerable amount of work needed to theme the editor or relay the color codes to the editor if it supports theming.
