### ISSUE TITLE
3 column design

### ISSUE THREAD

**Issue by shobanavikram** [mrin9/RapiDoc#224]
Are there there any plans of supporting the 3 column design with the code and try options on the far right column?

**Comment by mrin9** [comment]
No there isnt any,

Our user survey found that design used by renderers such as ReDoc to be more confusing not a good user experience. It also  necessarily repeats content.

For instance the responses codes and schema is repeated  on middle and right section in redoc. 

if you like to keep request and response side by side we have a `render-style=view`

but if you have some interesting reasons to go for a 3 col layout in terms of improved user experience then list them out here, share some screenshots or wireframes if you have something in mind, and I will take it further to our UX design team.

**Comment by shobanavikram** [comment]
One of the best API documentation that i've personally found effecient is the Auth0's management API documentation, where the the first column is the labels, second one is the descriptions and the third being the place holder for code and try now. It looked clean and the swagger documentation page doesnt look really long. If we have an extensive API like the ones Auth0 has, I have a feeling the 3rd column will come in very handy.

Here is a link to their documentation page
https://auth0.com/docs/api/management/v2

**Comment by mrin9** [comment]
What is a good rendering is a very personal opinion, and we at RapiDoc back it up through user feedback and UX team's inputs who happens to have a better experience in dealing with easier usage. 

well w.r.t  to AuthO's example, I have the same issues that seems like you too have that is, it isnt clear whats the purpose of 2nd col and 3rd col. You mentioned the 3rd col is for try out but I found try button on the 2nd col ? - that would be my first red flag when 

besides their 3rd col is confusing coz
- it is neither an area dedicated for request or response, it has both, but only certain parts (request body and one response schema, again which response or which request body is something thats anyone's guess - operations can have multiple request bodies and responses)
- their hierarchical info is not very intuitive,  they all seem to be on the same level, it may give you  a clean look but not that easy to comprehend
- it doesn't seem like they support multiple request bodies,
 
I can go on with various other issues but thats not the point. Something which is good/clean looking may not translate to an easier usage or a complete and better representation of the facts.

So, I would like to have more than a link to take the 3 column request. 
- It needs to clearly differentiate whats the purpose of 3rd col ? 
- what are you trying to solve that cannot be done in 2 col view (`render-style = view`)
