### ISSUE TITLE
Problems with the Authorization header using the API Server with OAuth

### ISSUE THREAD

**Issue by elipinska** [mrin9/RapiDoc#228]
Hi there,

I'm currently exploring options for the new version of our API docs and have come across your project -- really impressed with the features and customisations you offer! 🙏 We've been trying to set up the API "try" functionality using our sandbox environment, however we've come across an issue which is somewhat of a blocker for us:

If I insert a valid token string in the `HTTP Bearer` section under `Authentication`, everything is working hunky dory and I'm able to make successful requests to our API. Note how `Bearer` in the Authorization header starts with an uppercase letter. 

![Bearer_upcase](https://user-images.githubusercontent.com/25990431/84166796-52786300-aa6d-11ea-8a7e-7f1602b4ecba.png)

**However**, If I obtain an access token through the `Authorization Code Flow`,  and then use the `Try` button, Rapidoc seems to be including `bearer` in lowercase in the Authorization header: 

![bearer](https://user-images.githubusercontent.com/25990431/84166414-bfd7c400-aa6c-11ea-9ab2-774ce268320d.png)

Unfortunately this results in a `400 Bad Request` response from our API; we follow the [the OAuth 2.0 Authorization Framework](https://tools.ietf.org/html/rfc6750#section-2.1) rather strictly and expect `Bearer` to be capitalized at all times. 

Is this an inconsistency in the Rapidoc code? Or do you think we might be setting things up wrong and there is in fact a way to capitalize `Bearer` in the second scenario?

**Comment by mrin9** [comment]
during the OAuth2 flows the [`token_type`](https://tools.ietf.org/html/rfc6749#appendix-A.13) is received from the oAuth2 provider, which we use **as-is** in making the API calls.

OAuth2 providers sending `token_type` as 'bearer' (all in small case) is a standard 
but I guess while making API calls, 
- I need to manually covert it to `Bearer` 
- same goes for `token_type=mac` which needs to be converted to `MAC` 

can you confirm me if your oAuth2 Provider is sending `token_type = bearer` that way I would know if my hypothesis is correct ?

> PS: The curl syntax is just an auto generated code. It is not what we use to make the actual API calls. To checkout the actual API calls you should check out the browser's  developer tool

**Comment by elipinska** [comment]
Hi @mrin9,

Thanks for your super swift response -- checking my browser's dev tools I can confirm that the `Authorization` header of the actual request includes lowercase `bearer`:

<img width="448" alt="header" src="https://user-images.githubusercontent.com/25990431/84191458-6d100380-aa90-11ea-9109-0ef318157c03.png">

And indeed, it looks like you've found the smoking gun -- our token endpoint does return `token_type: bearer` as part of the response. 
<img width="674" alt="token_type" src="https://user-images.githubusercontent.com/25990431/84191467-6f725d80-aa90-11ea-8fb1-e5723eb62e09.png">

**Comment by mrin9** [comment]
thanks for confirming - AFAIK OAuth2 providers sending `token_type='bearer'` is per the standard (will cross check this later)
If thats the case, I will push a fix to convert `bearer` to `Bearer` - to comply with the API request standard

**Comment by elipinska** [comment]
To help out with your cross-checking, I've just looked up t[he OAuth 2.0 RFC](https://tools.ietf.org/html/rfc6749#section-5.1) which says: 

```
   token_type
         REQUIRED.  The type of the token issued as described in
         Section 7.1.  Value is case insensitive.
```
So as far as I can tell both `Bearer` and `bearer` are acceptable return values. If you're able to convert it to uppercase in the `Authorization` header when sending requests, that would be great, and would certainly help me make a case for using Rapidoc for our documentation revamp. 🙂

**Comment by mrin9** [comment]
this is now addressed, not yet released.
to test it out you may pick the build from `dist` folder or build it yourself

> do not use `rapidoc.min.js` from `dist` in production - this contains only canary and not tested builds

**Comment by elipinska** [comment]
Thanks a million @mrin9, the speedy fix is much appreciated -- we'll test it out today 👍

**Comment by elipinska** [comment]
Just to confirm, your fix has absolutely done the trick -- thanks again for your help! 🎉
