### ISSUE TITLE
Unexpected nesting of an array example

### ISSUE THREAD

**Issue by elipinska** [mrin9/RapiDoc#229]
Given the following definition:

```
    BankAccount:
      title: BankAccount
      allOf:
        - $ref: '#/components/schemas/EditableBankAccountParams'
        - $ref: '#/components/schemas/ReadOnlyBankAccountParams'
      # example:
      #   url: 'https://api.freeagent.com/v2/bank_accounts/4093'
      #   opening_balance: 0
      #   type: StandardBankAccount
      #   name: Default bank account
      #   is_personal: false
      #   status: active
      #   is_primary: true
      #   currency: GBP
      #   current_balance: 28742
      #   marked_for_review_count: 0
      #   total_count: 40
      #   unexplained_transaction_count: 0
      #   manually_added_transaction_count: 10
      #   bank_code: generic
      #   latest_activity_date: '2020-02-27'
      #   updated_at: 2020-07-28T11:25:20.000Z
      #   created_at: 2020-07-28T11:25:11.000Z
    ListBankAccountsResponse:
      title: ListBankAccountsResponse
      type: object
      properties:
        bank_accounts:
          type: array
          items:
            $ref: '#/components/schemas/BankAccount'
```

I'm getting a JSON example in the exact format I'd expect:

<img width="522" alt="Screenshot 2020-06-11 at 22 57 34" src="https://user-images.githubusercontent.com/25990431/84443428-7daeae00-ac37-11ea-8889-b907c0257ea9.png">

However, if I uncomment the lines with the `example`, the result is as follows:

<img width="717" alt="Screenshot 2020-06-11 at 22 57 01" src="https://user-images.githubusercontent.com/25990431/84443485-98812280-ac37-11ea-9ad3-26fef1d14746.png">

Any idea where the additional object nesting (with `name` as the key) might be coming from?

Edit: The same happens if I don't use references under `allOf` and instead define properties directly in the schema, just to rule that out as the cause of the issue.

**Comment by mrin9** [comment]
I dont think `allOf` can contain `example` under it.
if can have references to schema or direct properties
if you wish to provide example, then provide them in the schema reference (here you are providing outside of all the references)

Test your spec against other established renderer's  such as swagger-ui / redoc / stoplight. If it is working as you are expecting it, then provide me with a minimal and complete spec file where I can re-create the issue.

**Comment by elipinska** [comment]
Sure, here's the way the same spec is rendered by Redoc:

<img width="327" alt="Screenshot 2020-06-12 at 00 21 30" src="https://user-images.githubusercontent.com/25990431/84448846-accb1c80-ac43-11ea-9a1c-888d1cfb44bf.png">

And here's a minimal spec file you should be able to test against: 
[openapi_example.yaml.zip](https://github.com/mrin9/RapiDoc/files/4767782/openapi_example.yaml.zip)
(see line 167 for the problematic example)

In this case I was actually able to resolve the issue by including examples next to each property, but it feels like it should be possible to define the example "in one go" within a schema object (correct rendering in Redoc would support that)

**Comment by mrin9** [comment]
thanks for the minimal spec. I was further able to reduce it and recreate the issue you mentioned. I will work on this one to see why our parsers are acting that way 
```yml
openapi: 3.0.0
info:
  title: Nested Example
  version: '1.0'
paths:
  /bank_accounts:
    get:
      summary: List Bank Accounts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListBankAccountsResponse'
components:
  schemas:
    EditableBankAccountParams:
      properties:
        name:
          type: string
        type:
          type: string
    ReadOnlyBankAccountParams:
      properties:
        url:
          type: string
          readOnly: true
        current_balance:
          type: number
          readOnly: true
    BankAccount:
      title: BankAccount
      type: object
      allOf:
        - $ref: '#/components/schemas/EditableBankAccountParams'
        - $ref: '#/components/schemas/ReadOnlyBankAccountParams'
      example:
        name: Default bank account
        type: StandardBankAccount
        url: 'https://api.freeagent.com/v2/bank_accounts/4093'
        current_balance: 28742
    ListBankAccountsResponse:
      title: ListBankAccountsResponse
      type: object
      properties:
        bank_accounts:
          type: array
          items:
            $ref: '#/components/schemas/BankAccount'
tags:
  - name: Bank Accounts
```

**Comment by mrin9** [comment]
Thanks for bringing up this issue, I have landed a fix, which should take care of this it.
you can find the test case below

Spec
https://github.com/mrin9/RapiDoc/blob/master/docs/specs/example-with-nested-refs.yaml

and here is how its rendered 
https://mrin9.github.io/RapiDoc/examples/example-with-nested-refs.html#get-/nested-refs-with-example

you can pick up the build from `dist` folder to test it out.
Let me know if it fixes your issue ?

**Comment by elipinska** [comment]
That's excellent, you're an absolute superhero @mrin9 for delivering fixes so promptly ⭐ It truly makes Rapidoc a joy to work with!
