### ISSUE TITLE
model does not represent required fields

### ISSUE THREAD

**Issue by jwgcooke** [mrin9/RapiDoc#23]
In both the request and the response renderings there is no indication that a specific property is in the list of required properties.  Take the (simple) case of login/password:

`      
requestBody:
  description: |
    The request should contain the login and password of the user to be authenticated.  
      content:
        application/json:
          schema:
            type: object
            properties: 
              login: 
                type: string
                example: johndoe
              password:
                type: string
                example: myFav0ritePassW0rd
            required:
              - login
              - password`

there is no indication that these fields are required in the rendered model section.

**Comment by mrin9** [comment]
can you share a minimal spec along with the spec-version

**Comment by mrin9** [comment]
this should be now fixed with release `4.2.11`.
