### ISSUE TITLE
Suggestions on making the UI look closer to Redoc like?

### ISSUE THREAD

**Issue by kamaydeo** [mrin9/RapiDoc#232]
I love ReDoc for it's presentation and RapiDoc for presentation + API Console (Try me). It lookslike RapiDoc is very flexible when it's comes to customizations and was wondering if you have any suggestions on what changes (style, font) could to be made to make it look like how ReDoc presents it.

**Comment by mrin9** [comment]
You may refer to https://mrin9.github.io/RapiDoc/api.html for the various UI elements that you can change in RapiDoc

Here is [demo](https://mrin9.github.io/RapiDoc/examples/themes.html) of changing various style elements  and you can find its source code [here](https://github.com/mrin9/RapiDoc/blob/master/docs/examples/themes.html)

I am not sure what you mean by referring " _make it look like ReDoc_ " both renderers have their own distinct ways of displaying information, for instance redoc has 3-col design and RapiDoc supports 3 different render styles `read`, `view`, `focused` these cannot be changed

**Comment by elipinska** [comment]
What I'd add to this is that you can refer to Redoc's [default theme](https://github.com/Redocly/redoc/blob/master/src/theme.ts) to check what fonts and styles are used there; a lot of these elements are customisable in Rapidoc. That said, I'd consider if copying Redoc's style is really necessary, I've recently conducted a pretty exhaustive comparison between the two and found that Rapidoc's styles are often more readable than Redoc's (although of course that's largely a matter of preference).

**Comment by mrin9** [comment]
@elipinska  thanks for your interest in RapiDoc, since you did some research on comparing RapiDoc with others, will it be possible for you to contribute some of your findings towards this issue #141 

We do conduct a lot of surveys/feedback from a very large set of users with our sponsoring organizations,  
but I am not allowed to share my sponsors name or their customer surveys in the open-source section

**Comment by elipinska** [comment]
Of course, I'll go ahead and post some of my notes on issue [#141](https://github.com/mrin9/RapiDoc/issues/141) 🙂
