### ISSUE TITLE
Multiple Security Schemes Issue

### ISSUE THREAD

**Issue by kamaydeo** [mrin9/RapiDoc#236]
I'm using 2 security schemes - apiKey and oauth2
When I use oauth2 scheme to receive a token, it still shows apiKey scheme as active at the operation level.
![image](https://user-images.githubusercontent.com/2191760/84850411-b1b61480-b025-11ea-9a60-3a1a02270834.png)

![image](https://user-images.githubusercontent.com/2191760/84850579-12455180-b026-11ea-9780-66485699525b.png)

**Comment by mrin9** [comment]
operations can have multiple security keys so when you use oauth2 scheme, it wont remove the previous key. To remove the previous key use **SET** button to update the value with blank

when you click on **TRY**  use the browser's dev tools to find how many keys and which keys it is sending in the API request

let me know if thats not what you are expecting.

**Comment by kamaydeo** [comment]
The issue is that it's showing wrong scheme as active in Authentication section which is to the left side of TRY button (2nd screenshot). The 1st screenshot clearly shows that I selected oauth2 scheme (Access Token Received) so my expectation is to see "OAuth Key in Authorization header". Does that make sense?

**Comment by mrin9** [comment]
yes the UI is not in sync, but can you tell me if it  is using the correct token while making the API calls ?

**Comment by kamaydeo** [comment]
yes. it uses the correct token.

**Comment by mrin9** [comment]
okay, will work on fixing the UI label
