### ISSUE TITLE
Properties with no type or format

### ISSUE THREAD

**Issue by ralpha** [mrin9/RapiDoc#238]
Currently when a property inside `components -> schemas -> {name} -> properties` have not `type` or `format` it will display:
![Screenshot from 2020-06-17 21-28-27](https://user-images.githubusercontent.com/2608639/84941331-83960a80-b0e1-11ea-9ff3-acb1416f9a3b.png)
But it will also display this when for example a description is given.
I would like to see my description instead of `No schema details found in the spec` Example:
![Screenshot from 2020-06-17 21-30-50](https://user-images.githubusercontent.com/2608639/84941592-e8516500-b0e1-11ea-9ebc-24ff00ec5f11.png)
If that is my `description`.

( I can not set the `type` because the type changes depending on the users input. )

**Comment by mrin9** [comment]
can you provide me with a minimal spec and complete spec for me to recreate this issue. I will see how best i can address this

**Comment by ralpha** [comment]
Here is the minimal spec:
```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "",
    "description": "",
    "version": "0.1.0"
  },
  "servers": [
    {
      "url": "/api"
    }
  ],
  "paths": {
    "/count": {
      "get": {
        "description": "",
        "operationId": "get_count",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiItemCount"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "ApiItemCount": {
        "description": "",
        "type": "object",
        "required": [
          "value"
        ],
        "properties": {
          "value": {
            "description": "This is my real description"
          }
        }
      }
    }
  }
}
```
