### ISSUE TITLE
Suggestion: Propertie minimum value in view

### ISSUE THREAD

**Issue by ralpha** [mrin9/RapiDoc#239]
When I have field that have the following schema:
![Screenshot from 2020-06-17 22-03-58](https://user-images.githubusercontent.com/2608639/84944703-792a3f80-b0e6-11ea-963a-e38fde9ed0dc.png)
I have a minimum set. But when displaying the page it will display:
![Screenshot from 2020-06-17 22-05-24](https://user-images.githubusercontent.com/2608639/84944824-a971de00-b0e6-11ea-8cfd-c74654672b37.png)
The description field is not visible although there is plenty of space to put this.
Only when I click on "Multiline description" it will show the description at all.
![Screenshot from 2020-06-17 22-06-55](https://user-images.githubusercontent.com/2608639/84945020-ff468600-b0e6-11ea-96b7-8a2e741efb15.png)

Could the description not start on just after the `>=0`? This would give the users more useful information.

The same is true for `enum`s that have only a few values:
![Screenshot from 2020-06-17 22-10-25](https://user-images.githubusercontent.com/2608639/84945256-5c423c00-b0e7-11ea-98f6-7032930e0c9c.png)

**Comment by mrin9** [comment]
> Could the description not start on just after the >=0? This would give the users more useful information.

it is a very personal preference, but at RapiDoc we decided that constraints are more important than descriptions in a schema, therefore they are given more preference than description. Also in many of the specs the description can take up 15-20 lines, In that case constraints will get mixed up if its is just the last line after description 

> The description field is not visible although there is plenty of space to put this.

It is designed that way. We don not want to mixup the constraints and the description and therefore a clear `new-line` marker is used to separate them out

**however, if you like to have the description expanded by default then set `schema-description-expanded = "true"`**

hope it takes care of your issue
