### ISSUE TITLE
On firefox (v66.0.4) response headers are displayed on a single line

### ISSUE THREAD

**Issue by croudet** [mrin9/RapiDoc#24]
rapidoc version 5.0.0

![Screen Shot 2019-05-07 at 08 47 07-fullpage](https://user-images.githubusercontent.com/2042338/57300465-e165bf80-70a4-11e9-8e90-213c3566bca4.png)

**Comment by mrin9** [comment]
Thanks for reporting.
This is fixed in 5.0.2 release
