### ISSUE TITLE
Suggestion: Multi-paragraph Path Description (margin)

### ISSUE THREAD

**Issue by ralpha** [mrin9/RapiDoc#240]
When you have a path description (in markdown) with multiple paragraphs it will render it as:
```html
<p>first paragraph</p>
<p>second paragraph</p>
```
(which is perfect!)
But this will add the second paragraph with a top margin of 24px. As by:
```css
.m-markdown-small p:not(:first-child), .m-markdown p:not(:first-child) {
    margin-block-start: 24px;
}
```
I think this is a bit much as this makes the box its it in much bigger. And most often does not look that great (as it is also cut of after some amount of characters)
![Screenshot from 2020-06-17 22-22-20](https://user-images.githubusercontent.com/2608639/84946498-1e461780-b0e9-11ea-91c2-25ed7b0ae7ac.png)

Just removing the margin there or making it much smaller looks nice in my opinion.
No margin:
![Screenshot from 2020-06-17 22-23-45](https://user-images.githubusercontent.com/2608639/84946641-4e8db600-b0e9-11ea-97e5-964fd2212392.png)
Margin 5px:
![Screenshot from 2020-06-17 22-25-05](https://user-images.githubusercontent.com/2608639/84946709-68c79400-b0e9-11ea-991a-c4706133a3cf.png)

**Comment by mrin9** [comment]
well it takes care of very specific issue where you have just two paragraphs, but wont work with 3 paragraphs, 
It will also create issue with the markdown else where, such as in field-description, request/response descriptions where people expect to have difference between newline and new-paragraph .

IMO, if you want to put contents in two line then use two lines in the markdown not two paragraphs
```
first line  <-- use 2 spaces after last word for new line
second line
```

I dont think our UX team would agree to change paragraph`(<p>)` styles to new line(`<br>`) style, they both will carry their distinct look

**Comment by ralpha** [comment]
I'm not suggesting to change this in all cases there just in this location.
I agree that there should be a difference between `<br>` and `<p>` but in this case I thing 24px is a bit excessive.

I would like to change this in my own view. But the shadow dom does not allow me change things from outside the shadom dom. And forking and compiling my own instance is a bit much for such a small change.

**Comment by mrin9** [comment]
okay

**Comment by ralpha** [comment]
Still wanted to thank you for reconsidering this. Looks good! :heart:
