### ISSUE TITLE
yarn build fails - 'NODE_ENV' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by 2adnan** [mrin9/RapiDoc#241]
Its probably something simple but getting this error in windows:

yarn build
yarn run v1.22.4
$ NODE_ENV=production webpack --mode=production
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by mrin9** [comment]
on windows use `yarn build_windows` instead
