### ISSUE TITLE
export generated html for offline use

### ISSUE THREAD

**Issue by 2adnan** [mrin9/RapiDoc#242]
Is there a way to convert json into html and then store it as .html file for offline viewing without rapiDoc?

**Comment by mrin9** [comment]
Server Side rendering and Pre-rendering is on our roadmap, which is essentially generating the html on a server. 
However RapiDoc is WebComponent and there is no easy/clean way of doing ssr with web-components as of today, having said that, do keep an eye on https://github.com/PolymerLabs/lit-ssr once it takes up some shape we will be adding ssr for RapiDOc

**Comment by sinaa** [comment]
@mrin9 Has there been any updates on this since last year?

SSR would be amazing to have for RapiDoc.
