### ISSUE TITLE
Support syntax highlighting in code samples

### ISSUE THREAD

**Issue by winonecheng** [mrin9/RapiDoc#244]
There are some languages not supported syntax highlighting in code samples, like PHP, Ruby, cURL, etc.

![image](https://user-images.githubusercontent.com/11289632/85246171-7760d300-b47c-11ea-80d5-d3eda56ad270.png)
![image](https://user-images.githubusercontent.com/11289632/85246179-7e87e100-b47c-11ea-8af8-ef8f14465355.png)

**Comment by mrin9** [comment]
for `curl` you can use `lang=bash`
 
we wont be able to support all the languages for syntax highlighting as this will increase our bundle size. And the fact that RapiDoc is a custom-element we pack everything into a single bundle (so no code-splitting)

Therefore, based on the size and language popularity/usage we picked some that we are supporting at present

For more info which languages are supported checkout the below links

https://mrin9.github.io/RapiDoc/examples/code-highlight.html
https://mrin9.github.io/RapiDoc/examples/code-samples.html
