### ISSUE TITLE
Reference error - Window is not defined

### ISSUE THREAD

**Issue by arizvi11** [mrin9/RapiDoc#246]
We are using this library in one of our module. In our application, we have a node server and it uses server side rendering, now when my module is going to serve in the application, it gives me below error-

Reference error: window is not defined
at module.exports../node_modules/rapidoc/dist/rapidoc-min.js
at Object../node_modules/rapidoc/dist/rapidoc-min.js
at _webpack_require_(my module name)

How can we resolve this error?

**Comment by Uzlopak** [comment]
This library is meant to be used by a browser and not as node module. You have to serve the file as static file and not require it as such.

**Comment by mrin9** [comment]
Thats correct what @Uzlopak mentioned. 
However server side rendering and pre-rendering is high on our request list. 
We are waiting on some of the [tooling dependencies](https://github.com/PolymerLabs/lit-ssr) to get updated and we would be adding that feature as soon as these dependencies  take up some shape
