### ISSUE TITLE
RapiDoc adds the parameter `charset=utf-8` to request `Content-Type` header

### ISSUE THREAD

**Issue by ckeboss** [mrin9/RapiDoc#248]
When using the "Try" feature, RapiDoc correctly uses the documented `requestBodyType` for the request, but adds the parameter `charset=utf-8`.

Relevant code: https://github.com/mrin9/RapiDoc/blob/ab23b75a1218562ff7661551f27d06b507da98b2/src/components/api-request.js#L971

Any reason for this? Seems like it should simply pass what the API has documented for the `requestBodyType`. Notably, it does not add the same to the CURL headers

Just wanted to make sure I wasn't missing something before I make a PR.

Thank you.

**Comment by mrin9** [comment]
I think back then when we developed it, there was a confusion, as to what constitue a a valid `media-type` w.r.t. OpenAPI spec
https://swagger.io/docs/specification/media-types/

The spec stated that it should be as per [RFC 6838](https://tools.ietf.org/html/rfc6838#section-4.2.1)
but it's not immediately clear if `charset`  can be part of valid `media-type` w.r.t. OpenAPI spec. Also the fact that `charset` has its own specification standard [RFC2978](https://tools.ietf.org/html/rfc6838#section-4.2.1) adds to this confusion.

However, this confusion was answered in the updated `3.0.3` version of the spec by providing some examples of valid media-types. (which can include the charset) https://swagger.io/specification/

I think we can remove the extra charset param that we append 

Thanks for bringing it up !!!

**Comment by ckeboss** [comment]
No problem. Would you like me to made a PR, or would you like to have the author of https://github.com/mrin9/RapiDoc/pull/247 PR updated to simply remove the parameter instead of having a conditional?

**Comment by mrin9** [comment]
I have made a request for a change to the original PR, will wait for couple of days. 
Then take a new PR.

**Comment by Uzlopak** [comment]
I agree with your arguments. Would be cool if this is fixed asap :).

**Comment by Uzlopak** [comment]
Added new PR
