### ISSUE TITLE
Support for rendering individual JSON schema

### ISSUE THREAD

**Issue by proppy** [mrin9/RapiDoc#253]
It would be nice to support rendering vanilla JSON schema in addition to OpenAPI specs.

Looking at the implementation of `<schema-tree>` and `<schema-table>`, it seems that they currently get an intermediate representation of the schema thru their `.data` attributes.

Do you think it would be desirable to extend those components to allow passing a JSON schema thru the element body, or would you rather see another component by introduced, ex:
```
<rapi-schema>
   <pre>
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/product.schema.json",
  "title": "Product",
  "description": "A product from Acme's catalog",
  "type": "object",
  "properties": {
    "productId": {
      "description": "The unique identifier for a product",
      "type": "integer"
    }
  },
  "required": [ "productId" ]
}
   </pre>
</rapi-schema>
```
(using a `<pre>` would allow to fallback to just displaying the raw schema.

**Comment by mrin9** [comment]
I would like to know about the use case here,
open api schema is a subset of JSON schema so how will it get used up, assuming we create a component from json-schema ?

**Comment by proppy** [comment]
My understanding is that w/ OpenAPI 3.1 both will now be aligned (see https://github.com/OAI/OpenAPI-Specification/pull/1977) and OpenAPI will now be a superset (or vocabulary) of `JSON Schema draft 2019-09`.

The use case would be to render individual JSON schema using `Table` or `Tree` schema display style (like in https://mrin9.github.io/RapiDoc/examples/schema-table.html#get-/schema/person) without the need to create a full OpenAPI spec.

**Comment by mrin9** [comment]
Well, we arn't there yet. 
Our dynamic converter if you throw an OpenAPI/Swagger 2.0 will convert to OpenAPI 3.0.x

But, I am glad you brought it up. I have added this to our task list and will back it up with feature-request
I wont be able to commit to any timeline yet, but will be something that will be supporting within the boundary of OpenAPI 3.1 

If that means its same as JSON-Schema draft 2019 then even better

**Comment by proppy** [comment]
@mrin9 gaave it a try with https://github.com/mrin9/RapiDoc/pull/258 let me know if that's going in the right direction.

**Comment by mrin9** [comment]
please refer to my comments on the PR.

**Comment by shishkin** [comment]
Would really be nice to render just a json schema alone using a subcomponent of this library.

**Comment by shishkin** [comment]
I actually saw in https://github.com/rapi-doc/RapiDoc/issues/781 that this is already somewhat available in https://github.com/rapi-doc/RapiDoc/blob/master/src/json-schema-viewer.js.
