### ISSUE TITLE
Support for [][]type

### ISSUE THREAD

**Issue by CharMixer** [mrin9/RapiDoc#257]
Thanks for your hard work on this OpenAPI render. I like the output a lot better than the default swagger style, and would like to implement it in upcoming projects. However, I have discovered that array's in array's doesnt seem to work (just outputs empty next to the key)

When I'm trying it out with https://editor.swagger.io/ it seems to work as expected.

Take this as an example:
```
openapi: 3.0.3
info:
  title: Test
  description: Testing
  version: 0.0.0
paths:
  /test:
    get:
      summary: Test
      description: Testing
      responses:
        200:
          description: Testing OK Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  test:
                    type: array
                    items:
                      type: array
                      items:
                        type: array
                        items:
                          type: object
                          properties:
                            test1:
                              type: boolean
                            test2:
                              type: string
                            test3:
                              type: integer
                            test4:
                              type: number
```

Am I missing something or is this a bug/limitation in RapiDoc?

**Comment by mrin9** [comment]
Thanks for bringing it up. 
It is a bug, 
Have added it to our internal issue tracker

**Comment by mrin9** [comment]
check out the test case https://mrin9.github.io/RapiDoc/examples/array-and-object-nesting.html#get-/array-of-array-3-levels
