### ISSUE TITLE
Q: Set table columns width

### ISSUE THREAD

**Issue by bkarvas** [mrin9/RapiDoc#260]
If the render-style="table" and the spec level is too big, parameter names word wrapping occurs.
Is there a way how to set different table columns width?

Picture 7th level:
![Sample3](https://user-images.githubusercontent.com/66029993/87299599-a367f500-c50c-11ea-99fd-7854f5b4a263.png)

Thanks ;-)

**Comment by mrin9** [comment]
well, there is no way to change this. A fixed size was chosen based on various device sizes and layout that we support. if not at 7th level we have to stop at may be 12th level to start wrapping of the field names

on the other hand there are specs that has really long descriptions (spanning 10-15 lines) and demand more space. so we have to balance it out some where between the two.

can you put a screenshot of how it looks in `schema-style=tree` ?

I will pass it both the screen shot to our ux team, lets see what they have to say.

**Comment by mrin9** [comment]
I will have to close this, as we have hit a limit on the distribution of space between field-names and description. This spacing set based some of our early experiments and feedback. Our design team is reluctant to change it as the current distribution of spacing is backed by data
