### ISSUE TITLE
Homepage rendering issue in Safari

### ISSUE THREAD

**Issue by waldyrious** [mrin9/RapiDoc#261]
The main image in the homepage is stretched vertically when rendered in Safari. The other images load with the correct proportions. See screenshot below:

![Screenshot 2020-07-13 at 18 55 02](https://user-images.githubusercontent.com/478237/87337052-b98caa00-c53a-11ea-94bc-db26dcb609de.png)

**Comment by mrin9** [comment]
thanks for notifying, will fix it soon
