### ISSUE TITLE
tool tips

### ISSUE THREAD

**Issue by jonvictory** [mrin9/RapiDoc#263]
Hello,

I was wondering if there was a way to toggle the "tool tips" section on/off in the UI. It sometimes overlaps with descriptions:
![image](https://user-images.githubusercontent.com/19315203/87719868-4c168e80-c771-11ea-9e86-e594afcee4e2.png)
![image](https://user-images.githubusercontent.com/19315203/87719883-5173d900-c771-11ea-99dc-b0a0fc1815b0.png)

**Comment by mrin9** [comment]
there is none at the moment , but I will pass this to our UX team, lets see if some style changes can solve this issue
