### ISSUE TITLE
Multiple Authentication Types does not shows normally.

### ISSUE THREAD

**Issue by LI-NA** [mrin9/RapiDoc#267]
Hello.

RapiDoc doesn't seem to describe the multiple security object normally.

Here is security object, and it required apikeyA **_and_** apikeyB at the same time.
`"security": [ { "ApikeyA": [], "ApikeyB": [] } ]`

Full yaml:
```yaml
openapi: 3.0.0
info:
  description: Test the securitySchemes and security for two required api keys.
  version: 1.0.0
  title: Test
paths:
  "/test":
    get:
      summary: test api
      security:
        - ApikeyA: []
          ApikeyB: []
      description: ""
      operationId: test
      responses:
        "204":
          description: Success
servers:
  - url: http://test.com/api/
components:
  securitySchemes:
    ApikeyA:
      type: apiKey
      in: header
      name: X-API-A
    ApikeyB:
      type: apiKey
      in: header
      name: X-API-B
```

But Rapidoc shows it like this: API Key {X-API-A) **_or_** API Key (X-API-B)
![api](https://user-images.githubusercontent.com/3607479/88503325-599f0480-d00c-11ea-990c-c61e0dd10a83.jpg)

It must be API Key {X-API-A) **_and_** API Key (X-API-B), and Requires **_all_** of the following

Here is fiddle: https://jsfiddle.net/cwke4uv6/

I refered swagger document.
https://swagger.io/docs/specification/authentication/#multiple

Thank you.

**Comment by mrin9** [comment]
Yep, you are correct, it is a bug.
thanks for reporting !!! 
will take care of it soon

**Comment by ShaneBoyer** [comment]
A related issue (I can break this out into its own issue if desired) is that if you have non-default security schemes in the global definitions, those are sent and override the local operation security schemes in "try it" requests for operations they do not apply to.  For example, we have these three security schemes:

1. Basic (Authorization header)
2. Bearer (Authorization header)
3. Api Key (x-api-key header)

The Basic security scheme only applies to one particular operation.  Bearer and Api Key are set to default for all operations with a global entry:

`"security":[{"bearer":[],"api_key":[]}]`

In operations that do not specify a security scheme (and should receive the defaults), the Try It functionality sends an Authorization header following the Basic scheme (along with the x-api-key header).  The schema validates and works correctly in Swagger UI.

**Comment by mrin9** [comment]
@ShaneBoyer Will be good if you create a separate issue, and provide a minimal spec to recreate it at our end
