### ISSUE TITLE
Feature request: Sort by endpoint "summary" in render-style="read"

### ISSUE THREAD

**Issue by JavierPAYTEF** [mrin9/RapiDoc#268]
It would be nice to have an option sort-endpoints-by="summary".

This would be useful when render-style="read" because the sidebar shows the endpoint summaries by default, but they are all out of order if the summary doesn't match the path ordering.

I saw there is a pull request that adds an option "label" that does this (https://github.com/mrin9/RapiDoc/pull/243). From the code it involves a minor change to spec-parser.js which I already did in my local copy, but it would be nice if it was supported officially.
I could maybe do a pull request but don't want to overstep if the person that did the pull request is working on it.

**Comment by mrin9** [comment]
arranging left nav links are generally done by combination of `tags` and `sort-endpoints-by` attribute in RapiDoc
check out https://mrin9.github.io/RapiDoc/examples/arrange-by-tags.html#overview if is of any help for your use-case

`summary` and `description` both are optional but `path` and `method` are not thats why we support sort-endpoints-by` path and method only.

However, I am open to consider this feature, but would be interested in knowing how some other renderers (redoc, stoplight etc) handles this situation. If you can provide me some feedback on that I can take it forward to our design team

**Comment by JavierPAYTEF** [comment]
I didn't know summary was optional, the only thing I can say to counter that, is that if someone explicitly assigns "summary" to sort-endpoints-by then most likely they will assign values to summary. Otherwise it wouldn't make sense.

I tried looking at the libraries you mentioned but found nothing at a glance, and I'm not very familiar with them to give an informed opinion. With regards to this feature though, I think it makes sense from a usability perspective, because right now the endpoints look out of order in the sidebar, unless you are lucky and the summary matches the path.

Alternatively I would be fine without the sorting feature entirely, meaning respect the ordering from the specification. In my case the endpoints are in the order they should be displayed, so the sorting could be disabled if I had that option.

To give you an example, if you have 3 endpoints:
- /start _"1. Start request"_
- /poll _"2. Poll request for a result"_
- /result _"3. Get last available result"_

They will be displayed as:
- 2. Poll request for result
- 3. Get last available result
- 1. Start request

**Comment by JavierPAYTEF** [comment]
By the way, I don't mind sending a pull request if you feel it would help. Just wanted to confirm first what the team thought about this before sending anything

**Comment by mrin9** [comment]
>the only thing I can say to counter that, is that if someone explicitly assigns "summary" to sort-endpoints-by then most likely they will assign values to summary. Otherwise it wouldn't make sense.

We do support some use cases and frameworks where the doc rendering is generated programmatically at that point things wont be clear before hand if `summaries` are there or not

>By the way, I don't mind sending a pull request if you feel it would help.

I will take a PR, with the suggestion you made, that is to remove ordering and make it behave to show things in the order how the paths are defined in the spec.
To achieve this I would imagine  `sort-endpoints-by` will now take 3 values `none | path | method`
`none` being the default value.

You must consider that 
- The ordering of the `Tags` should still be respected
- Let me know how the paths will be ordered when they fall under multiple tags

**Comment by JavierPAYTEF** [comment]
> We do support some use cases and frameworks where the doc rendering is generated programmatically at that point things wont be clear before hand if `summaries` are there or not

This could easily be solved by using a default value if the summary is null or undefined. The library is already using a "-" symbol in the sidebar and when rendering the titles if the summary and description are not present, so it would be in line with what's currently implemented.

![image](https://user-images.githubusercontent.com/40425968/88685322-35a2f800-d0cc-11ea-9ad9-07caf6a00875.png)

At the end of the day this is a user option, so if the user chooses to sort by summary and at the same time doesn't specify values for the summaries then it would be a user error, not something wrong with the library.

Another option would be to use the "path" if the summary is empty. We would try to use the summary first, and if it's empty we take the path and sort that element using that instead. We could also change the sidebar to show the path instead of "-" if the summary is empty, so that the sorting and the sidebar are aligned.

**Comment by mrin9** [comment]
>Another option would be to use the "path" if the summary is empty. We would try to use the summary first, and if it's empty we take the path and sort that element using that instead. We could also change the sidebar to show the path instead of "-" if the summary is empty, so that the sorting and the sidebar are aligned.

agree on that. will accept a PR if you wanna give it a try
