### ISSUE TITLE
No support for examples in query/path parameters

### ISSUE THREAD

**Issue by ks-borys** [mrin9/RapiDoc#269]
Hi! 

Could you take a look at the issue when there is no ability to provide examples in the documentation for query/path parameters? Screencaps attached below:

**1. screen from RapiDoc that describes actual behavior:** 
![image](https://user-images.githubusercontent.com/65663395/88647347-9af7e880-d0ce-11ea-8ef6-39e42b814b93.png)
**2. screen from swagger that describes expected behavior:** ![image](https://user-images.githubusercontent.com/65663395/88647198-7b60c000-d0ce-11ea-90b2-51596bcb0257.png)

**Spec used in the example:** 
```
#Related spec 
# https://swagger.io/specification/#example-object
# https://swagger.io/docs/specification/adding-examples/
openapi: 3.0.3
info:
  title: Sample API
  description: Retrieves user by country and city
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
components:
  examples:
    example1:
      value: "ua"
      summary: "example $ref ua"
    example2:
      value: "pl"
      summary: "example $ref pl"
    example3:
      value: "ch"
      summary: "example $ref ch"
paths:
  /users/{country}/{city}:
    get:
      summary: Returns a list of users.
      parameters:
      - name: 'country'
        required: true
        in: 'path'
        schema:
          type: 'string'
        examples:
          example1:
            $ref: '#/components/examples/example1'
          example2: 
            $ref: '#/components/examples/example2'
          example3: 
            $ref: '#/components/examples/example3'
      - name: 'city'
        required: true
        in: 'path'
        schema:
          type: 'string'
        examples:
          example1: 
           value: "uk"
           summary: "example inline uk"
          example2: 
           value: "us"
           summary: "example inline us"
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
```

PS. Let me know if you need more info. Thanks!

@pavlovmike @molochiyivan

**Comment by ks-borys** [comment]
Hi @mrin9! 

Can you take a loot at this issue please?

**Comment by mrin9** [comment]
will take a look at it next week

**Comment by mrin9** [comment]
checkout https://mrin9.github.io/RapiDoc/examples/examples-multiple.html#get-/multiple-examples-in-query-param for reference

You can pick the non-released version from `dist` folder or build it on your own

**Comment by Kitsuneez** [comment]
hi the link is no longer available, is it possible to provide another link?
