### ISSUE TITLE
Usage outside of webcomponent.

### ISSUE THREAD

**Issue by jurijzahn8019** [mrin9/RapiDoc#271]
Hello,

Thanks for a great product first!

Would it be possible to export the library's components/classes/functions as
an es6/cjs module? So i could use them in my own code in order to hook into the rendering process?

For example this would be usable to 
- add more prism modules
- customize the render result

I have tried by modifying the webpack config, but was not successfull.
I also tried to import "rapidoc/src/index.js" but failed due to "@" import aliases.

Thanks in advance

**Comment by mrin9** [comment]
I am not sure of the process to achieve the goal that you mentioned above.

but if you want to export any or all the functions/component/classes then just add those import and export statements here 
https://github.com/mrin9/RapiDoc/blob/master/src/index.js

>PS: just be aware that this library is designed to work with browsers only.
