### ISSUE TITLE
Add support for x-tagGroups

### ISSUE THREAD

**Issue by julienrf** [mrin9/RapiDoc#272]
ReDoc has a convenient extension that groups tags into sections: https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md#x-tagGroups

Would you be interested in supporting a similar option?

**Comment by mrin9** [comment]
I am sorry, this feature wont be supported at the moment. 

We have two levels for grouping operations (tags, and the operations) 
they are  rendered accordingly in various modes `read-mode`, `focused-mode` and `view-mode`
we wont be adding a third level in navigation bar by grouping-tags as this should also be done in `view-mode` and our UX thinks adding third level in `view-mode` will be a poor user-experience

**Comment by NilofarMulla** [comment]
Hi,
We are looking at moving our documentation to RapiDoc and wanted to know

- Is there any other option to group tags under different categories? 
- How to group based on operations in focused mode?
