### ISSUE TITLE
Fix request: Refresh request body examples in "focused" render-style

### ISSUE THREAD

**Issue by poadoc** [mrin9/RapiDoc#276]
Dear developers,

It would be nice if during switching between methods in "focused" mode a request body example would refresh with appropriate data. At the moment, if the user will change the value of some param in example, this example doesn't refresh when he will click on some another method in the navigation.

Details of example:
* Request body type: multipart/form-data || application/x-www-form-urlencoded
* Content type of example: json

**Comment by mrin9** [comment]
can you provide a minimal spec for this

**Comment by poadoc** [comment]
```
<rapi-doc 
    id = "thedoc" 
    spec-url="./sm_openapi.json"
    allow-server-selection = "false"
    show-header = "false"
    theme = "light"
    allow-try = "false"
    allow-api-list-style-selection = "false"
    regular-font = 'Open Sans'
    schema-style = 'tree'
    render-style = 'focused'
    default-schema-tab = "model"
  > </rapi-doc>
```

[sm_openapi.zip](https://github.com/mrin9/RapiDoc/files/5026628/sm_openapi.zip)

**Comment by mrin9** [comment]
thanks for the spec, will investigate it further
