### ISSUE TITLE
Feature request: Versioning

### ISSUE THREAD

**Issue by poadoc** [mrin9/RapiDoc#278]
Dear developers,

It would be nice if a user could configure different versions of API with a possibility to switch between them. In my opinion, it can be resolved by adding some selector on the right side of the header (in case of "view" mode) or at the top of the navigation view (in case of "read" or "focused" mode). 
It can be added some tools to show the diff between different versions of API.

**Comment by mrin9** [comment]
Do you like to have the possibility of opening different specs (or versions) ?

**Comment by mrin9** [comment]
This functionality can be achieved by putting your own buttons/drop-downs  at a desired location and load your choice of API spec or version of API

for reference checkout  https://mrin9.github.io/RapiDoc/examples/example100.html and see how `Change Spec URL` button on the top can dynamically load different specs

the code for the above example can be found here https://github.com/mrin9/RapiDoc/blob/master/docs/examples/example100.html
