### ISSUE TITLE
Example responses are not rendered correctly

### ISSUE THREAD

**Issue by mtamme** [mrin9/RapiDoc#282]
The displayed response models are correct but the rendered examples are only displayed partially and contain an additional comma at the end, which is correct.

Affected RapiDoc version: 8.1.2

BTW: In RapidDoc version 8.0.0 the examples are rendered correctly (ecxept the additional comma at the end).

This is the model as show in RapiDoc 8.1.2:

```
links: array
  rel: string
  href: uri
pageCount: int64
pageIndex: int64
pageSize: int32
totalCount: int64
items: array
  links: array
    rel: string
    href: uri
  value: string
```

And this is the rendered example as show in RapiDoc 8.1.2

```
{
  links: [
    {
      rel: "string",
      href: "http://example.com"
    }
  ]
},
```

An here is my configuration:

```
<rapi-doc
  spec-url="openapi.yaml"
  regular-font="Roboto"
  mono-font="Roboto Mono"
  schema-style="table"
  schema-expand-level="1"
  schema-description-expanded="true"
  show-header="false"
  allow-server-selection="false">
  <div style="height: 16px"></div>
  <div slot="footer" style="height: 16px"></div>
</rapi-doc>
```

**Comment by mrin9** [comment]
provide a minimal spec to recreate the issue on our end

**Comment by mtamme** [comment]
Attached you can find an openapi.yaml and an index.html. Neither the success nor the error response example is rendered correctly.
[test.zip](https://github.com/mrin9/RapiDoc/files/5098012/test.zip)

**Comment by mrin9** [comment]
thanks for the spec. will investigate it further

**Comment by mrin9** [comment]
you can test with the non-released build from `dist` folder

**Comment by mtamme** [comment]
Thanks, the example is now rendered correctly except the leading comma at the end:
```
{
  links: [
    {
      rel: "string",
      href: "http://example.com"
    }
  ]
}**,**
```

**Comment by elipinska** [comment]
I've been wondering about the trailing commas at the end too, personally I find them somewhat confusing and would prefer to remove them if this was the consensus across the community.
