### ISSUE TITLE
RapiDoc does not obscure password strings as expected

### ISSUE THREAD

**Issue by BinaryWizard904** [mrin9/RapiDoc#283]
It was recently brought to my attention that outside of Authentication methods, RapiDoc does not obscure string parameters with `"format":"password"` as expected per https://swagger.io/specification/#data-types.

#### Relevant Excerpt
type | format | Comments
------ | --------- | -------------
string | password | A hint to UIs to obscure input.

In my case, this affects an operation to request a Bearer token used as the authentication method for all other operations.
The attached example schema ([test.zip](https://github.com/mrin9/RapiDoc/files/5097625/test.zip)) should help illustrate the issue.

### Parameter Affected:
```json
"parameters": [
    {
        "name": "password",
        "description": "Enter your login password.",
        "schema": {
            "type": "string",
            "format": "password",
            "example": "password1"
        },
        "in": "query",
        "required": true
    }
]
```
### Current Rendering Behavior for a User-Entered Value
![Password Rendering (current)](https://user-images.githubusercontent.com/62070150/90653962-78f11200-e205-11ea-8614-232003805108.jpg)
### Expected Rendering Behavior for a User-Entered Value
![Password Rendering (expected)](https://user-images.githubusercontent.com/62070150/90653997-827a7a00-e205-11ea-8f62-ec4db335b369.jpg)

**Comment by mrin9** [comment]
thanks for pointing it out, will address it soon
