### ISSUE TITLE
Unable to load local spec file

### ISSUE THREAD

**Issue by tjperry07** [mrin9/RapiDoc#284]
I created a codesandbox
https://codesandbox.io/s/magical-pond-oojwy?file=/src/App.js

I have tried several variations to load the local file, but it can't find the spec. Using a web link works fine though. 
I also used the same setup locally and again using a web link works, but it won't read a local project file. 

`spec-url="./specs/petstore.yaml"`
`spec-url="specs/petstore.yaml"`
`spec-url="/specs/petstore.yaml"`
`spec-url="../specs/petstore.yaml"`

<img width="868" alt="Screen Shot 2020-08-19 at 11 34 24 AM" src="https://user-images.githubusercontent.com/5667652/90663954-f588ee00-e20f-11ea-834a-637e42004eda.png">

**Comment by mrin9** [comment]
I dont think code-sandbox will be able to access any file from `localhost`.
You should upload the file on to a public domain with no security such as a public github repo and try to access the spec from there.

This is not an issue w.r.t rapidoc, therefore closing it

**Comment by kshanta1** [comment]
@mrin9 How do you pass the authentication with spec URL? Our spec Urls are not public we need to pass atuhentication in the headers. Could you please point to me any examples?
