### ISSUE TITLE
Feature request: Allow show/hide API-Servers attribute

### ISSUE THREAD

**Issue by bkarvas** [mrin9/RapiDoc#289]
Currently `allow-try` attribute enables/disables 'TRY' feature together with API-Servers informations if specified in the spec.
It would be nice if tehere is a separate attribute (independent on the `allow-try`) for showing/hiding API-Servers infos?Could you implement a separate attribute (independent on the `allow-try`) for showing/hiding API-Servers if specified in the spec?

**Comment by waldyrious** [comment]
I would like this too :)

**Comment by mrin9** [comment]
`allow-server-selection = true/false` is the attribute you are looking for https://mrin9.github.io/RapiDoc/api.html#att-sections

**Comment by waldyrious** [comment]
@mrin9 right, but that only works if `allow-try` is true. I would like to show the server information (url, description) even if the TRY feature is disabled.

In other words, I'd like to do: `allow-try = "false"` + `allow-server-selection = "true"`, but currently that's not possible. That may be what @bkarvas was seeking, too.

**Comment by mrin9** [comment]
Well `allow-try` overrides `allow-server-selection`.  
It works this way due to historical reason.  We initially only had `allow-try` and later added `allow-server-selection`

Changing this behavior would create a breaking change as people would have used `allow-try` to hide server section.

If you have a suggestion on how it can be tackled, let us know 

> I am reopening it, to keep it under our radar

**Comment by bkarvas** [comment]
@waldyrious you are absolutely right. Behavior, as you described is exactly what I'm looking for.
May be a new parameter `show-servers`, similar like `show-info` parameters could only show API servers and its descriptions without selection possibility. 
I see that `allow-try` and `allow-server-selection` are "true" by default, so `show-servers` could be "false" by default, BUT if set to "true", it will show servers info's independently on `allow-try` setting.

**Comment by mrin9** [comment]
`allow-try` should no more be responsible for hide/show of API-Servers

use build from `dist` folder to give it a try

**Comment by bkarvas** [comment]
This is exactly what I wanted. Thanks a lot 👍

**Comment by waldyrious** [comment]
Thanks for the fix @mrin9. I've submitted #315 to update the documentation to match the new behavior.

If I may add a suggestion, I think when `allow-try` is off, the Servers section should show a simple list rather than a radio button input, and there should be no "SELECTED:" text underneath.
