### ISSUE TITLE
Wrong server URL

### ISSUE THREAD

**Issue by dagnelies** [mrin9/RapiDoc#29]
Hi,

In my swagger definition, I have `"host":"localhost:8080"`.

However, RapiDoc strangely declares that the API server is `//api-docs//localhost:8080/`

...which causes all "try" requests to fail of course.

AFAIK `api-docs` is solely the name of the swagger definition file.

**Comment by mrin9** [comment]
> However, RapiDoc strangely declares that the API server is `//api-docs//localhost:8080/`

is the server declared as `//api-docs//localhost:8080/` or `/localhost:8080/api-docs` ?
What is the location of your swagger spec? 

General assumption is, If there is no server provided in the spec, then rapidoc considers the location of the spec as the base-url for making the API calls

the other way to workaround it, if you have not defined a server in your spec then provide it as an attribute in the element 

`<rapi-doc spec-url="swagger.json" server-url="localhost:8080"> </rapi-doc>`

or if you want to dynamically set it

```
document.addEventListener('DOMContentLoaded', function () {
   document.getElementsByTagName("rapi-doc")[0].setAttribute("server-url", location.origin+"/api")
});
```

**Comment by dagnelies** [comment]
Thanks for the prompt response. The use case is pretty common:

- The Swagger 2.0 definition is here: `http://localhost:8080/v2/api-docs`, containing `"host":"localhost:8080"`
- RAPI doc runs at : `http://localhost:8080/rapidoc.html`, with the component defined as `<rapi-doc spec-url="/v2/api-docs"></rapi-doc>`

Somehow the API server in Rapi becomes `//api-docs//localhost:8080/` ...very confusing.

---

If I add `server-url="localhost:8080"` to the component, both servers are suggested, which is still undiserable.

**Comment by dagnelies** [comment]
My guess is that my Swagger Definition does not contain "schemes", and because of that, the converter swagger2openApi somehow fails to provide correct "servers" ...or something of that sort.

See https://github.com/mrin9/RapiDoc/blob/7aaf6f652a383372cde2d99e47e8beb73128bc3c/src/utils/parse-utils.js#L179

...I only have `host` and `basePath`

**Comment by dagnelies** [comment]
I can confirm that when adding `schemes` in the swagger definition. It would be great if RapiDoc could infer the scheme from the current URL if it is missing ...I think it's an optional thingy anyway.

**Comment by mrin9** [comment]
Thanks for the detailed analysis,
However, if its behaving the way you mentioned is definitely buggy, 
can you share your swagger spec, and I will see how best can we answer this issue

**Comment by dagnelies** [comment]
The swagger spec is 2000 lines, so it's a bit verbose ;)
Here is the "top-level":

```
{  
   "swagger":"2.0",
   "info":{...},
   "host":"localhost:8080",
   "basePath":"/",
   "tags":[...],
   "schemes":["http","https"], <- adding/remove make the API server resolution work/break
   "paths":{...},
   "securityDefinitions":{...},
   "definitions":{...}
}
```

**Comment by mrin9** [comment]
Thanks for sharing,
Can you test release 5.0.4, if it takes care of your use case

**Comment by dagnelies** [comment]
Works, thanks for the prompt fix! 👍 🎉
