### ISSUE TITLE
doesnt work with TypeScript

### ISSUE THREAD

**Issue by rubenzup** [mrin9/RapiDoc#293]
even if i declare in my global declaration files:

```
declare global {
    namespace JSX {
      interface IntrinsicElements {
        rapi-doc: React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>;
      }
    }
  }
```

TypeScript will point that the custom-element is invalid. Any fix to this?

**Comment by rubenzup** [comment]
please change the custom element to RapiDoc if possible

**Comment by mrin9** [comment]
Try the below declaration if it works

```
declare global {
  namespace JSX {
    interface IntrinsicElements {
      'rapi-doc': any;
    }
  }
}
```

> Having hyphen(-) in. a custom element name is a part of custome element naming standard https://html.spec.whatwg.org/#valid-custom-element-name

**Comment by rubenzup** [comment]
thanks its working!!!

**Comment by nuth** [comment]
Could this be mentioned in the Readme.md file?
