### ISSUE TITLE
Feature request: Search by params

### ISSUE THREAD

**Issue by poadoc** [mrin9/RapiDoc#297]
Dear developers,

It would be nice if a user can perform a search by parameters of methods (name + description). A search result can show a full description of the parameter and a list of methods where it does use.

**Comment by mrin9** [comment]
to few details to properly analyze the request ... can you be little more descriptive probably with an example

**Comment by poadoc** [comment]
This functionality gives the user a possibility to perform a search by method parameters name or description and show them methods where these parameters are used.
Related PR: https://github.com/mrin9/RapiDoc/pull/303

**Comment by poadoc** [comment]
The PR has been updated.
