### ISSUE TITLE
How to remove the padding?

### ISSUE THREAD

**Issue by leonheess** [mrin9/RapiDoc#298]
Even though the rapi-doc-element has no padding, the main-content-inner-element and all its children have a padding-left. How can I get rid of this?

**Comment by mrin9** [comment]
`css` inside of RapiDoc component is encapsulated so you wont be able to change that.
Let me know your usecase and send in some UI if thats needed to show what are you trying achieve, will be able to comment better

**Comment by leonheess** [comment]
I use RapiDoc embedded inside a MicroFrontend and to align it properly I would like to remove all those paddings/margins on the left

**Comment by mrin9** [comment]
I dont think we can do much on this one
