### ISSUE TITLE
Response content doesn't render in "column" mode

### ISSUE THREAD

**Issue by jakul** [mrin9/RapiDoc#3]
The response examples don't render at all in column mode.
![captura de tela 2019-02-15 as 09 31 05](https://user-images.githubusercontent.com/862794/52847590-84d9b080-3104-11e9-8931-f6027db8f966.png)

Here's the same example in row mode:
![captura de tela 2019-02-15 as 09 31 16](https://user-images.githubusercontent.com/862794/52847601-8c00be80-3104-11e9-986d-aad2d4ef084f.png)

**Comment by mrin9** [comment]
I am unable to recreate this issue on my end, (tested on chrome, firefox and safari)
Can you share the following info 
- RapiDoc Version you are using
- Browser and its Version
- OS and Screen Resolution
- Are you using JavaScript to change the attribute ? or directly passing it in the element

**Comment by jakul** [comment]
https://mrin9.github.io/RapiDoc/example4.html renders correctly for me - I can see the example and model responses.

I've investigated a bit more, and the problem shows when the first tag in the page is `<html>`. Your exmaple4 starts with `<!doctype html>`.

I see the problem with this HTML:
```
<html>
  <head>
    <meta charset="utf-8"> <!-- Important: The Custom element uses utf8 charecters -->
    <script src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>
  </head>
  <body>
    <rapi-doc
      spec-url="https://api.apis.guru/v2/specs/bitbucket.org/2.0/swagger.json"
      layout="column"
    ></rapi-doc>
  </body>
</html>
```

And not with this HTML:
```
<!doctype html>
  <head>
    <meta charset="utf-8"> <!-- Important: The Custom element uses utf8 charecters -->
    <script src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>
  </head>
  <body>
    <rapi-doc
      spec-url="https://api.apis.guru/v2/specs/bitbucket.org/2.0/swagger.json"
      layout="column"
    ></rapi-doc>
  </body>
</html>
```


I can replicate the problem with example4.html too, by changing the opening tag to be `<html>` instead of `<!doctype html>`

**Comment by mrin9** [comment]
oh I c, thank-you for investigating and finding the cause
