### ISSUE TITLE
Function that creates the URLs?

### ISSUE THREAD

**Issue by tjperry07** [mrin9/RapiDoc#302]
Can someone point me to the function that creates the URLs? `#get-/folders`

**Comment by mrin9** [comment]
it is generated using a RegEx by removing some invalid chars 
 
https://github.com/mrin9/RapiDoc/blob/2409aade4ec856556e5d3181b134488fac8dd400/src/templates/navbar-template.js#L79

the RegEx is defined here
https://github.com/mrin9/RapiDoc/blob/2409aade4ec856556e5d3181b134488fac8dd400/src/utils/common-utils.js#L16
