### ISSUE TITLE
Missing functionality for OAuth2 Password Flow

### ISSUE THREAD

**Issue by Uzlopak** [mrin9/RapiDoc#305]
If you use OAuth2 PAssword Flow you dont get a Button for "Get Token"

**Comment by mrin9** [comment]
Yes, `password-flow` exchange-token is not supported 
we need to clear some legal/internal dependency for that which I do not see being resolved soon.
Most likely it will not be supported.

Even though it is a supported type in OpenAPI, RapiDoc will limit it to documentation only and not provide the functionality to get a token.

It is not a recommended way anymore

https://tools.ietf.org/html/draft-ietf-oauth-security-topics-13#section-3.4
https://oauth.net/2/grant-types/password/
