### ISSUE TITLE
Disable navigation in read/focused mode

### ISSUE THREAD

**Issue by nuth** [mrin9/RapiDoc#307]
Hi, I have a use case where I want to include rapidoc in an existing site with an existing sidebar, but I also want to use the read mode which expands everything.

So a disable-nav option would be great.

**Comment by mrin9** [comment]
the sidebar and the main sections are associated with each other. for instance when you scroll main section, the sidebar changes its selection, similarly when you click on sidebar it scroll to the desired location in main section.

I will see what we can do about it, but it will go in our very low priority queue.
I also like to know bit on your use case, where you are trying use your own supplied sidebar, such as how are you planing to provide navigation links ?

At the moment, the best option that you have is to go with view-mode like this one https://www.northbricks.io/apis/#api-reference
