### ISSUE TITLE
POST plaintext response not shown

### ISSUE THREAD

**Issue by dagnelies** [mrin9/RapiDoc#31]
Dunno if it's because the response is plain text or because it is a POST request, but the response text box stays blank despite seeing the response fine in the network monitor.

**Comment by mrin9** [comment]
Thanks for pointing it out,
this bug was introduced in one of the previous releases.
this should now be fixed in 5.0.4 

Can you confirm if it works for you

**Comment by dagnelies** [comment]
Works, thanks for the prompt fix! 👍 🎉
