### ISSUE TITLE
Question: Can the nav bg color be a gradient?

### ISSUE THREAD

**Issue by mattcobb** [mrin9/RapiDoc#310]
Question: Can the nav bg color be a gradient?

**Comment by mrin9** [comment]
You can have a gradient image but not gradient color.
https://mrin9.github.io/RapiDoc/examples/branding-nav1.html#overview

thats coz when a background color is specified, our theming engine automatically calculates the text color based on the bg-color's contrast and brightness.

ofcourse you can override the text-color by specifying it but it is handy when people only specify the bg-color
