### ISSUE TITLE
"Hide Authentication and provide your own pre-generated api-key" feature is not working

### ISSUE THREAD

**Issue by apsnaidu** [mrin9/RapiDoc#311]
Using a pre generated auth key as detailed in the example https://github.com/mrin9/RapiDoc/blob/master/docs/examples/example8.html doesn't seem to work!

After setting the key and hitting the `TRY` button, the `Authentication` still shows as `No API key applied` and there is no api-key passed in the headers as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/13637018/94398095-3fb6a500-01a8-11eb-8934-9583bbdee387.png)

Here is the curl request showing no api-key in header:

```
curl -X PUT "https://petstore.swagger.io/v2/pet" \
 -H "Content-Type: application/json" \
 -d '{"id":0,"category":{"id":0,"name":"string"},"name":"doggie","photoUrls":["string"],"tags":[{"id":0,"name":"string"}],"status":"available"}' \
```
Let me know if there is any setting that I'm missing?

**Comment by mrin9** [comment]
thanks for bringing it up.

Pickup the latest build from `dist` folder to test it. 
Also make sure that you are providing all the 3 attributes 

 - `api-key-location`
 - `api-key-name`
 - `api-key-value` (default it to hyphen(-) if you want to provide it later using JavaScript)

checkout this example for usage 
https://mrin9.github.io/RapiDoc/examples/api-key.html
