### ISSUE TITLE
Bump swagger2openapi version to avoid yargs prototype pollution

### ISSUE THREAD

**Issue by wszydlak** [mrin9/RapiDoc#316]
Hi, due to detected prototype pollution in yargs (https://nodesecurity.io/advisories/1500) please upgrade used version of swagger2openapi to at least swagger2openapi@6.0.2 (where they bumped yargs version).

**Comment by wszydlak** [comment]
Oh there is swagger2openapi issue: https://github.com/Mermade/oas-kit/issues/218

**Comment by mrin9** [comment]
this isn't an issue for us as `yargs` is applicable only in node environment. Also we explicitly remove this from our final bundle
using our webpack config

https://github.com/mrin9/RapiDoc/blob/cb34cdd52fae504dea7249ba53234ea0aae5a843/webpack.config.js#L58


However, I am keeping the issue open as we plan to upgrade this package, it does involve to deal with some breaking changes and take care of certain corner cases

**Comment by mrin9** [comment]
packages are updated in release `8.3.0`
