### ISSUE TITLE
Support for YAML format

### ISSUE THREAD

**Issue by StephenNay** [mrin9/RapiDoc#32]
I just stumbled onto RapiDoc and I'd like to check it out, but my OpenAPI definition is in YAML format, not JSON. All other swagger-related tools that I've come across work with both YAML and JSON, so it would be very nice if YAML could be added to RapiDoc.

**Comment by jwag956** [comment]
yaml works great - you just can't load it from the top bar - here is part of my html:

<rapi-doc
      spec-url="openapi.yaml"
      allow-try="false"
      allow-spec-url-load="false"
      allow-spec-file-load="false">

**Comment by mrin9** [comment]
this is how you load yaml. 
As of now you can open yaml only if you are hosting it on a web-server
```
<rapi-doc spec-url="https://api.apis.guru/v2/specs/bitbucket.org/2.0/swagger.yaml"> 
</rapi-doc>
```

if you want to load a local file from disk using the top bar, thats limited to json. we will eventually be adding that support, but thats not gonna be soon

**Comment by StephenNay** [comment]
I found my problem. The RapiDoc instructions say to add the HTML to an index.html file and then just open the file. Actually, you have to run a server to serve the file; you can't just open it in a browser. 
Now that I'm past that little misunderstanding, I'm enjoying looking at the RapiDoc output. Is there a way to control the order of tag presentation in the RapiDoc display? They seem to be sorted alphabetically, which is decent for a default order, but just because something starts with A doesn't mean it's the most significant thing or that I want to show it first. I admit that I'm a technical writer and not a programmer, so I'm focused on both content and presentation.

**Comment by mrin9** [comment]
> is there a way to control the order of tag presentation in the RapiDoc display

Well there is no way to specify tag order in the spec, so it is up-to the viewer how it shows up the tags. RapiDoc shows them alphabetically. This gives you an ability to present the content in a sequence you desire by following some naming conventions. I have seen people naming tags like
`1. Authentication`, `2. Users`, `3. Employees`, `4. Products` and so on

I am open to ideas, If you have any suggestions

**Comment by StephenNay** [comment]
ReDoc uses x-tagGroups to group tags and control the order of presentation. You'd have to do some redesigning in the RapiDoc display to somehow show grouped tags, but I've found it very useful for large APIs.

**Comment by mrin9** [comment]
x-tags are OpenApi extensions which are specific to viewers. At this point we do not want to introduce any extensions for RapiDoc.
I have floated the idea of tag-organization to our usability team, if something needed to be changed on this area,  my guess is, it wont be soon.

I will be closing this issue for now as the primary issue has been resolved

**Comment by maxarndt** [comment]
I stumbled accross this as well. Your project is really cool and I love the feature to load local OpenAPI V3 files without spinning up a webserver. Other projects as [ReDoc](https://github.com/Redocly/redoc) don't offer this feature and this is why I preffer yours.

But unfortunately, as @StephenNay mentioned earlier, YAML is much more present than JSON for API specs. 

> As of now you can open yaml only if you are hosting it on a web-server (local or public).
> 
> if you want to load a local file from disk using the top bar button `LOAD LOCAL JSON`, thats currently limited to json. we will eventually be adding yaml support too for local files, but thats gonna be little far in the future

@mrin9 is there any schedule for supporting YAML files without spinning up a web-server? I would really love to see this feature.
