### ISSUE TITLE
Disable redirect_uri in client credentials flow

### ISSUE THREAD

**Issue by JoyceBabu** [mrin9/RapiDoc#320]
The client credentials flow is currently sending `redirect_uri` to the server. Client credentials flow does not require `redirect_uri`, but the server still verifies the value if specified.

Is it possible to remove `redirect_uri` in case of OAuth2 Client Credentials authentication type?

None of the following OAuth servers mention `redirect_uri` in `client_credentials` flow.

https://developer.uber.com/docs/riders/references/api/v2/token-post#example-request-access-token-client-credentials
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow
https://www.pingidentity.com/developer/en/resources/oauth-2-0-developers-guide.html
https://alexbilbie.com/guide-to-oauth-2-grants/
https://docs.apigee.com/api-platform/security/oauth/access-tokens#requestinganaccesstokenclientcredentialsgranttype
https://developer.spotify.com/documentation/general/guides/authorization-guide/#client-credentials-flow
https://docs.identityserver.io/en/dev/endpoints/token.html
https://auth0.com/docs/flows/call-your-api-using-the-client-credentials-flow
https://docs.oracle.com/cd/E50612_01/doc.11122/oauth_guide/content/oauth_flows.html
https://aws.amazon.com/blogs/mobile/understanding-amazon-cognito-user-pool-oauth-2-0-grants/

I could find only one api documentation that included redirect_uri in `client_credentials` flow

https://help.k2.com/kb002814

**Comment by mrin9** [comment]
I will look into this. The goal is to cover most use cases.
