### ISSUE TITLE
Feature request: Support for hyperlinks between schema components

### ISSUE THREAD

**Issue by greatvovan** [mrin9/RapiDoc#325]
Is there a rendering mode where you have only top-level fields for each component but with nested components presented as hyperlinks? Something similar to [Kubernetes API spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/) or `html` mode of [openapi-generator](https://github.com/openapitools/openapi-generator)?

When you have a lot of components, such feature would make API learning process a bit quicker. Currently it just shows the corresponding part of the schema, which introduces lot of redundancy: if component B is nested inside component A, you will get two entries: one for component A, including sub-component B, and another entry for B. It will be repeated even more if component B is used in many places.

Having hyperlinks would allow to list all the definitions much more concisely in cases when same components are reused in multiple places. My suggestion is to have the same tree-like UI in method description section but have table-like UI with hyperlinks in the components section (`show-components="true"`).

**Comment by mrin9** [comment]
I forwarded this to our UX team. Do not expect a quick turn around  on this as many UX decisions are driven by our internal user feedback process. also this has been categorized as a low-priority issue.

**Comment by mrin9** [comment]
UX team came back on this, they would like to keep the experience  consistent across the app.
However, if your schema is too complex then you may use `schema-expand-level = 1` to limit it from expanding all the nodes
