### ISSUE TITLE
Debugging not possible

### ISSUE THREAD

**Issue by dagnelies** [mrin9/RapiDoc#326]
Hi,

I got an error from RapiDoc and wanted to investigate, but I quickly faced the issue that only the minimized version is available on the CDN: 

    https://unpkg.com/browse/rapidoc@8.2.0/dist/

Only `*min.js` versions are available, and the readable source/map is missing.

...I guess the build pipeline is somehow incomplete.

**Comment by mrin9** [comment]
I will look into it what can be done, as we have a complex internal build system, which branches out the open-source code from the org-owned code.
org-owned code contains plugins and test cases that are not relevant for general usage.
It also contain some org specific data that cannot get get into open-source area.

I have created an internal issue for this and will be closing this one, as it needs to be handled in a different area
