### ISSUE TITLE
Bug introduced in 8.2.0

### ISSUE THREAD

**Issue by dagnelies** [mrin9/RapiDoc#327]
There was quite a nasty big bug introduced in the latest version 8.2.0.

...it is rather strange too.

- You can toggle (set/remove) your authentication back and forth (tried Basic Auth & API Key)
- You can expand/collapse an endpoint panel back and forth
- If you have your authentication set, expanding an endpoint will fail (TypeError: Cannot read property 'some' of undefined)
- if you have an endpoint exapanded, setting your authentication fails (TypeError: Cannot read property 'some' of undefined)

It does not happen in 8.1.2

**Comment by mrin9** [comment]
I think these issues do not exist in the latest code 
can you test it with `dist\rapidoc-min.js` the latest code from

**Comment by dagnelies** [comment]
fixed in latest 👍
