### ISSUE TITLE
Failed to correctly parse api key

### ISSUE THREAD

**Issue by dagnelies** [mrin9/RapiDoc#328]
In your example: https://mrin9.github.io/RapiDoc/examples/example1.html

Try: https://petstore3.swagger.io/api/v3/openapi.json

...the API Key is missing, as shown in https://petstore3.swagger.io/

**Comment by mrin9** [comment]
Thanks for reporting, was a regression.
Please test it with the latest code from `dist\rapidoc-min.js`
