### ISSUE TITLE
Appending query string with & fail if API Key in query

### ISSUE THREAD

**Issue by meabed** [mrin9/RapiDoc#33]
https://github.com/mrin9/RapiDoc/blob/7f22f69d201cb964aab6fa8a56b564272f1e45cc/src/components/api-request.js#L514

The above line fails to build correct URL 

Example: https://httpbin.org/get&api_key=test-key
Should be: https://httpbin.org/get?api_key=test-key

Suggested fixe(s)
- check if url contains "?", if true append with "&" else append with "?"
- Parse url and reconstruct it, something like https://developers.google.com/web/updates/2016/01/urlsearchparams

**Comment by mrin9** [comment]
thanks for pointing it out, will take care of this soon

**Comment by mrin9** [comment]
fixed in release 5.0.5.
