### ISSUE TITLE
[suggestion] improve rendering of oneOf items

### ISSUE THREAD

**Issue by tsoestini** [mrin9/RapiDoc#331]
here is a rendering of a oneOf item as it currently is (on the left) and as suggested (on the right):
![image](https://user-images.githubusercontent.com/70355397/97370191-b01a1a00-186b-11eb-9233-d4e8afe3e575.png)

- the horizontal lines on the left cause confusion for large objects, because they split up the large object (which contains a/b/c/d/e) highlighting which might be a relatively insignificant object (c), which might not even be an object at all.

- the extra indentation on the right communicates the same thing, without breaking up the more important parent object.

- the choices that the oneOf is choosing between is made more clear by consistently using numbers [1] and [2], irrespective of whether the choices are objects or simple types.

here is the openapi document, if it helps for testing:
```
{
  "openapi": "3.0.0",
  "info": {
    "title": "sample-render-one",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost"
    }
  ],
  "paths": {
    "/sample-render-one": {
      "get": {
        "summary": "sample-render-one",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "a": {
                      "type": "string"
                    },
                    "b": {
                      "type": "string"
                    },
                    "c": {
                      "oneOf": [
                        {
                          "type": "string"
                        },
                        {
                          "type": "object",
                          "properties": {
                            "x": {
                              "type": "string"
                            },
                            "y": {
                              "type": "string"
                            }
                          }
                        }
                      ]
                    },
                    "d": {
                      "type": "string"
                    },
                    "e": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-sample-render-one"
      }
    }
  },
  "components": {
    "schemas": {}
  }
}
```

**Comment by mrin9** [comment]
> the horizontal lines on the left cause confusion for large objects, because they split up the large object (which contains a/b/c/d/e) highlighting which might be a relatively insignificant object (c), which might not even be an object at all.

> the extra indentation on the right communicates the same thing, without breaking up the more important parent object.

The above two points are unlikely to addressed completely, coz those styles came in after some user feedbacks and style iterations. 

In a large schema, `one-of` options can blend in with the actual object, and therefore those demarkations were proposed and were added

The indentation under `ONE-OF` (you proposed) was the original design, but our user feedback indicated that it creates a perception of another object in a schema, therefore it was removed.

We can change the color code of `key` to match with all other keys. This was done to highlight ONE-OF type but we can remove it now since the horizontal demarkation is added


> the choices that the oneOf is choosing between is made more clear by consistently using numbers [1] and [2], irrespective of whether the choices are objects or simple types.

Agreed, and thanks for pointing it out, this is an issue with primitive types only and will be fixed

**Comment by tsoestini** [comment]
looks great! thanks for the detailed answers!

**Comment by tsoestini** [comment]
Would you consider adding an option to disable the horizontal lines?

in my actual schema, I have
  a:
  b:
  c:one of
  d:
  e:one of
  f:one of

The bottom horizontal line of C and the top of E make D look exactly the same as C/E/F.

When I set `border-style: none` manually (but keep all the padding) it looks great and very legible what is going on.

Unfortunately, setting `border-style: none` in code is not very easy with all the shadowRoots.

(or, more broadly, maybe have the option to specify a slot="stylesheet" that gets put into every shadowRoot so the user can add their own styling very simply?)

**Comment by waldyrious** [comment]
> (or, more broadly, maybe have the option to specify a slot="stylesheet" that gets put into every shadowRoot so the user can add their own styling very simply?)

I would LOVE this!
