### ISSUE TITLE
cURL contains too many values in "Accept" parameter and yields multiple "Content-type" parameters

### ISSUE THREAD

**Issue by ks-borys** [mrin9/RapiDoc#333]
Hi! 

I have encountered strange cURL that returns after I make a call from documentation. 
cURL contains too many "application/json" values in "Accept" and there are 2 "Content-Type" parameters as well. 
I am almost sure that it has to do something with the quantity of examples in both path parameters and body. 

Can you take a look, please?

![rapidoc_application_json_issue](https://user-images.githubusercontent.com/65663395/97565271-9a812d80-19ee-11eb-8122-ac0d9de3bb5b.png)
 

@pavlovmike @molochiyivan

**Comment by mrin9** [comment]
thanks, can you provide a minimal example to reproduce it.
I tested 
https://mrin9.github.io/RapiDoc/examples/examples-multiple.html#post-/multiple-example-in-request-body
and 
https://mrin9.github.io/RapiDoc/examples/examples-multiple.html#get-/multiple-examples-in-query-param

was not able to reproduce it.

**Comment by pavlovmike** [comment]
Hi!
I guess you could take a look [here](https://api-gateway-kot-sandbox.k8s.digital-ks.net/#post-/subscriber/{phoneNumber}/verify-sim)

**Comment by mrin9** [comment]
can you provide a minimal spec that highlights this issue. you can update the example that I shared above if needed

**Comment by molochiyivan** [comment]
> can you provide a minimal spec that highlights this issue. you can update the example that I shared above if needed
Here we go. Please note that content type duplicates as number of items in 'responses' section increases

```
openapi: 3.0.3
tags:
  - name: users
    description: basic description
info:
  title: Sample API
  description: Retrieves user by country and city
  version: 0.0.1
  contact:
    name: me
servers:
  - url: http://api.example.com/v1
components:
  examples:
    example1:
      value: "ua"
      summary: "example $ref ua"
    example2:
      value: "pl"
      summary: "example $ref pl"
    example3:
      value: "ch"
      summary: "example $ref ch"
paths:
  /users/{country}/{city}:
    get:
      operationId: "get_users"
      tags:
        - users
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      parameters:
      - name: 'country'
        required: true
        in: 'path'
        schema:
          type: 'string'
        examples:
          example1:
            $ref: '#/components/examples/example1'
          example2: 
            $ref: '#/components/examples/example2'
      - name: 'city'
        required: true
        in: 'path'
        schema:
          type: 'string'
        examples:
          example1: 
           value: "lviv"
           summary: "example inline lviv"
          example2: 
           value: "kyiv"
           summary: "example inline kyiv"
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
        '404':    # status code
          description: not found
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
```
