### ISSUE TITLE
For primitive data types show description before Default, Allowed, and Pattern

### ISSUE THREAD

**Issue by SteveNay-vz** [mrin9/RapiDoc#336]
I'm a technical writer so I tend to think about the order in which a person should encounter information so that they can make sense of it. Currently, if a primitive data type is an `enum` or has a `default` value or a `pattern`, the `description` of the property is hidden by default in the model view unless `schema-description-expanded=true` (the default is false). That is, when set to single-line description, the description isn't visible if a property has default, allowed, or enum parameters. Even when schema-description-expanded=true or when multi-line description is clicked, the description is still displayed after those other parameters.

I think that the reader needs to see the property description first to give context to any of the other information. My request is to change the order of these parts so that description comes before default, allowed, and enum.

I looked at the code and i can see where the HTML is created in schema-table.js, but I was afraid that the solution might be a bit more involved than just moving the lines for itemParts[6] above the lines for itemParts 3 4, and 5, otherwise I would have created a PR. Like I said, I'm a technical writer, not a real programmer. ;-)

**Comment by mrin9** [comment]
The design was driven by our UX team. and they may have collected some user feedback on this.
I will forward your suggestion but I do not expect it will be accepted as it was brought up previously in this issue #239

We try to balance various kind of situation... specs with no-descriptions or specs with markdown heavy multiline descriptions etc. So having descriptions in first line is no guarantee to be shown in its entirety.
