### ISSUE TITLE
Are paths sorting correctly?

### ISSUE THREAD

**Issue by SteveNay-vz** [mrin9/RapiDoc#337]
I have three paths in my OpenAPI file that all have only a GET method. They all have the same tag. In the source file they are in order 

1
2
3

But they appear in the output in order

1
3
2

Alphabetically the paths should be 1, then 2, and then 3. I didn't specify `sort-endpoints-by` so it should be sorting by path.

I wouldn't be permitted to attach the full OpenAPI file, but here are the three paths in the order that they appear in the OpenAPI file:

1. GET /discover
2. GET /discover/edges/profile/{profileId}
3. GET /discover/subscriber/edges

**Comment by mrin9** [comment]
use this https://mrin9.github.io/RapiDoc/examples/arrange-by-tags.html#get-/common-path-in-first-and-3rd-tag 
to recreate your issue and we will take a look

**Comment by SteveNay-vz** [comment]
I've attached a zip file that contains my test RapiDoc HTML file and my test YAML file based on the one you pointed me to. When I view the RapiDoc version I see this:

![image](https://user-images.githubusercontent.com/71782729/97904362-382d7300-1cf5-11eb-820e-bd56971aaf86.png)

Notice the summaries on the right are in order 1, 3, 2.

When I load the file into Swagger editor, I see this:

![image](https://user-images.githubusercontent.com/71782729/97904458-5d21e600-1cf5-11eb-8755-76a049db9dc0.png)

And the summaries show the sorting is 1, 2, 3.

[issue337.zip](https://github.com/mrin9/RapiDoc/files/5477139/issue337.zip)

**Comment by mrin9** [comment]
I do not see any issues with the sorting. It is sorting based on paths as expected

> you may want to check spellings for the path. it `discover` is spelled as `disover` in Path 2

**Comment by SteveNay-vz** [comment]
I suspected a misspelling, but I stared and stared at it and could not see that! Thank you.
