### ISSUE TITLE
"Try" snippets don't set cookie with API key

### ISSUE THREAD

**Issue by justfortherec** [mrin9/RapiDoc#338]
Security schemes of type `apiKey` allow the API key to be set in a cookie. Snippets generated by RapiDoc do not include these cookies.

An example config could look like:

```yaml
openapi: 3.0.3
info:
  title: Example API
  description: Example API
  version: 1.0.0
servers:
  - url: 'https://example.org'
paths:
  /:
    get:
      summary: Get an example
      description: Get an example
      responses:
        '200':
          description: An empty response
security:
  - cookieAuth: []
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: SESSION
```

RapiDoc correctly recognizes the scheme and allows the user to set the token in the _Authentication_ section.

However, unlike with API key schemes that are set with `in: header`, the snippets to try a request do not include the cookie.

For example, I would expect a curl snippet to look like this:
```
curl -X GET "https://example.org/"  \
  -H  "Cookie: SESSION=123"
```

Instead, RapiDoc displays a snippet without the cookie header:
```
curl -X GET "https://example.org/" \
 -H "Cache-Control: no-cache" 
```

The cookie is also not sent in the request initiated by the _Try_ button.

**Comment by justfortherec** [comment]
The issue simply seems to be that this has only been implemented for API keys in query parameters (see [`api-requests.js` at line 916](https://github.com/mrin9/RapiDoc/blob/master/src/components/api-request.js#L916)) and in headers ([the same file at line 938](https://github.com/mrin9/RapiDoc/blob/master/src/components/api-request.js#L938)).

The [OpenAPI specification](https://swagger.io/specification/#security-scheme-object) lists three allowed values:
- query
- header
- cookie

I don't know how to set cookies with the `fetch` API, so I cannot implement this. At least for the curl snippet, it would probably need to look something like the following:

```javascript
    // Add Authentication Cookie if provided
    this.api_keys
      .filter((v) => (v.in === 'cookie'))
      .forEach((v) => {
        fetchOptions.headers['Cookie'] = "${v.name}=${v.finalKeyValue}"; // No clue if this works for setting cookies with `fetch`
        curlHeaders += ` -H "Cookie: ${v.name}=${v.finalKeyValue}" \\\n`;
      });
```

**Comment by mrin9** [comment]
thanks for reporting,

> I don't know how to set cookies with the fetch API (at most it will work with with a single cookie but not more than one), so I cannot implement this. At least for the curl snippet, it would probably need to look something like the following:

I agree. We will fix the `curl` syntax or can accept a PR if you like to contribute, however this wont change Fetch API behavior

**Comment by justfortherec** [comment]
Great to hear that you want to fix it. Please don't wait for a PR from my side (I am too lazy to set up the entire build environment for this small change :shrug:).

**Comment by mrin9** [comment]
no worries, I think we happy with the way things are. However we will ensure that cookies in security scheme wont provide an option to set it, to imply that it cannot be sent using the `TRY` functionality

**Comment by justfortherec** [comment]
Yes, not allowing to _try_ in cases that are known to not work sounds like a good idea.

However, IMHO it would still be valuable to have the option to show the curl snippet for trying from the commandline.

Do you think there is a way to allow this? It would probably mean to separate the curl command from the try option so that it is shown despite the _try_ option being disabled with api keys in a cookie.

**Comment by mrin9** [comment]
Well `TRY` option wont be disabled,  but setting the cookie value in the Authentication Section will not be allowed. _(since you cant set it, it indicates cookies are not sent  when you click `TRY`)_

`curl` syntax will be available and contain setting cookies

**Comment by Mojken** [comment]
Not being able to manually set cookies does not imply that they cannot be sent by calling authentication endpoints that attempt to set them. It also doesn't imply that sending cookies via `TRY` is not supported. Please clarify this, I've just wasted hours trying to figure out why my cookies aren't being set.
