### ISSUE TITLE
Query Parameter Enum Values Are Rendered Strangely in v8.3.0

### ISSUE THREAD

**Issue by BinaryWizard904** [mrin9/RapiDoc#339]
RapiDoc v8.3.0 renders enum values strangely. Instead of showing them as a list of values prefixed by "**Allowed:**", enum values are now rendered as an unlabeled list of pipe ("|") separated links.  From what I can tell these links emulate the functionality of multiple example links, sans any summary text.

Without the Allowed prefix it is very unclear what these values represent.  They could just as well be more examples instead of a list of all permitted values.

### RapiDoc v8.2.0
![v820](https://user-images.githubusercontent.com/62070150/98417446-866caa00-2046-11eb-950a-2a345515b14e.png)
### RapiDoc v8.3.0
![v830](https://user-images.githubusercontent.com/62070150/98417481-95ebf300-2046-11eb-9107-8c45fdf4ac84.png)

The schema contained in the [EnumProblems.zip](https://github.com/mrin9/RapiDoc/files/5503674/EnumProblems.zip) ZIP can be used to reproduce the issue.

**Comment by mrin9** [comment]
Thanks for reporting... will fix it soon
