### ISSUE TITLE
Request body in GET requests

### ISSUE THREAD

**Issue by dagnelies** [mrin9/RapiDoc#34]
Currently, `GET` and `DELETE` requests with rrequest bodies are forbidden:

   Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.

This is probably because the spec is "translated" in openAPI (where it is forbidden) instead of swagger v2 (where it is allowed).

Luckily, they noticed their "mistake" and will be allowing soon: https://github.com/OAI/OpenAPI-Specification/pull/1937

I hope this tool will update accordingly. This ticket should serve as a reminder. 😃

**Comment by mrin9** [comment]
Thanks for sharing this info, and opening up this ticket !!!

Like you said, the  [swagger2openapi](https://github.com/Mermade/oas-kit/blob/master/packages/swagger2openapi/README.md) library that we use for translating from Swagger-V2 to  OpenAPI-V3 needs to take care of this, once thats fixed I will update RapiDocs dependency.
