### ISSUE TITLE
'TRY' button enabled when user have empty path param

### ISSUE THREAD

**Issue by AndrasescOvidiu** [mrin9/RapiDoc#341]

**Comment by AndrasescOvidiu** [comment]
Could the 'TRY' button be disabled when the user has an empty path parameter? The field is required and therefore the user can still click 'TRY'.

Having the following request:
* myapp/books   - it calls internally a service for retrieving all books
* myapp/books/{book-uid}   - passing now an empty book-uid, it calls internally myapp/books, instead of myapp/books/

So I would like to disable 'TRY' button, and therefore the user can not make a request with an empty parameter.
Where it will be the line code to make this update?

Thank you!

**Comment by mrin9** [comment]
Well, RapiDoc do not validate any of the inputs on purpose, 

this allows people to test their APIs when they provide incorrect values. for instance you can check what response your API returns by sending a string where the field is defined as number. Same goes to check the API response when a parameter is not provided.

We wont be supporting this functionality as it will stop users from testing their APIs with negative cases
