### ISSUE TITLE
Q: Different styling for tag headings?

### ISSUE THREAD

**Issue by StanleyP** [mrin9/RapiDoc#344]
Hello,

My question is: Is it possible to set different background/style for API tag headings?
For example I would like tag headings to have primary-color as background.

If not possible directly through RapiDoc API, what modifications to the RapiDoc source code are necessary for this? If you could at least point me in the right direction it will be very appreciated.

Thank you for this wonderful project!

**Comment by mrin9** [comment]
there are multiple places the tags are shown ... which one you are referring to ?
- in read mode - body
- in read mode - navbar
- in view mode

**Comment by StanleyP** [comment]
I meant in view mode. Sorry I forgot to mention.

**Comment by mrin9** [comment]
you can find it here https://github.com/mrin9/RapiDoc/blob/d6903652878bec93cb7a16d7735e44ac883d1a08/src/templates/endpoint-template.js#L113

For now I have  changed the color to primary color, to collect our user-feedback... it may get reverted based on the feedback we receive on this.

**Comment by StanleyP** [comment]
Thanks for quick fix. My goal was to change background of tag heading to primary color. You changed the foreground color, but it is OK. From your patch I can see how to do it now.
RapiDoc is really great, no competition!

**Comment by BinaryWizard904** [comment]
> For now I have changed the color to primary color, to collect our user-feedback... it may get reverted based on the feedback we receive on this.

While we use read mode in our deployment, the change to the color of .nav-bar-tag is welcomed by my team.  We see it as a great visual aid for distinguishing headers from paths.

**Comment by mrin9** [comment]
thanks for your feedback ... have passed it to our UX team

**Comment by mrin9** [comment]
UX have finalized the styling and decided not to make any more changes
