### ISSUE TITLE
Feature request for controlling paragraph margins in markdown rendered content 

### ISSUE THREAD

**Issue by loraderon** [mrin9/RapiDoc#345]
It would be great if we could control the margins for the paragraphs in the markdown rendered content by setting a css variable that defaults to the original `24px` value.
https://github.com/mrin9/RapiDoc/blob/503997eb145d3b12b4f764b9f70f4b288fc740cc/src/styles/font-styles.js#L97

I think that the current look is a bit to "airy" at the moment.
![image](https://user-images.githubusercontent.com/76928/98843292-10ec4980-244b-11eb-9897-777e7308f3f7.png)

**Comment by loraderon** [comment]
Would you be interested in a PR that (only) adds the "custom css" support from https://github.com/mrin9/RapiDoc/pull/243?

**Comment by mrin9** [comment]
can you expand a bit on the approach you are planing to take ?

**Comment by loraderon** [comment]
Instead of solving this issue with a css-var, I could extract the custom css support from that other PR and if this new PR gets accepted I could use that technique to solve my original issue with paragraph margins.

**Comment by mrin9** [comment]
Sure, please do add documentation on how to use the feature with an example at  [api.html](https://github.com/mrin9/RapiDoc/blob/master/docs/api.html)

You may create a separate section **For Developers** or something similar
