### ISSUE TITLE
Feature Request: API Option to Disable Filling Parameter Fields with Example Values by Default

### ISSUE THREAD

**Issue by BinaryWizard904** [mrin9/RapiDoc#347]
Right now, query parameter fields are automatically populated with the first example available.  I understand the logic behind this, but some of the schemas I manage have nearly a hundred parameters—nearly all of which are optional—and manually removing the example values from each one significantly increases time needed to try a non-example query.

In this situation, an API option to force RapiDoc to list example(s) below the input field without using them as default values would be a fantastic help.  A list-only option if you will.  It would provide my users with examples just a click away without forcing them to meticulously remove example values from the far larger number of fields their query likely isn't using.

The mock-up below is an example of the desired behavior.
![Screenshot - 11_12_2020 , 5_34_32 PM](https://user-images.githubusercontent.com/62070150/99009497-b962e200-250d-11eb-85d0-237f16fa9a92.png)

**Comment by mrin9** [comment]
closed-source version of rapidoc has a helper button `CLEAR` beside the `TRY` button, whose job is to clear the parameter field values. I will see if that can be extracted to the open-sourced version. I think that should be helpful for your use case.

**Comment by BinaryWizard904** [comment]
Thank you @mrin9, that addresses our use case very well.
