### ISSUE TITLE
Allowed values for array properties not shown

### ISSUE THREAD

**Issue by sneakyvv** [mrin9/RapiDoc#348]
For example, the enum values are not shown at https://mrin9.github.io/RapiDoc/examples/example1.html#get-/pet/findByStatus
![image](https://user-images.githubusercontent.com/1423157/99148768-ed631200-2689-11eb-9efe-ca18814fb6e3.png)
Parameter object (https://petstore.swagger.io/v2/swagger.json#/paths/~1pet~1findByStatus/get/parameters)
```
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "description": "Status values that need to be considered for filter",
            "required": true,
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "available",
                "pending",
                "sold"
              ],
              "default": "available"
            },
            "collectionFormat": "multi"
          }
        ],
```

### Expected behavior
Similar to other enums for non-array types, something like 
![image](https://user-images.githubusercontent.com/1423157/99149041-dd4c3200-268b-11eb-8cdc-43d0f7ffda6c.png)

**Comment by mrin9** [comment]
test case can be found here https://mrin9.github.io/RapiDoc/examples/parameters.html
