### ISSUE TITLE
how to support GBK encoding annotation?

### ISSUE THREAD

**Issue by ansiz** [mrin9/RapiDoc#35]
For some historical reasons, I have to use GBK encoding in my project. This makes the swagger document appear strange characters, how can I use RapiDoc in GBK encoding project? Thanks

**Comment by mrin9** [comment]
RapiDoc do not use any specific encoding inside its source but uses whats provided. It however uses some HTML entities for certain icons.

to provide an encoding of your choice, supply it in the HTML using the `<meta>` tag as shown below.

```
<!doctype html>
<head>
  <meta charset="utf-8">
</head>

<body>
  <rapi-doc spec-url="petstore.json"> </rapi-doc>
</body>

</html>
```
 I have not tested with GBK encoding, but if you face issues, please provide me with a sample spec file and will see what best I can do
