### ISSUE TITLE
Improve support for array of default values

### ISSUE THREAD

**Issue by BradHolmes** [mrin9/RapiDoc#353]
### The problems

Multiple default values for an array input field are not well supported.  There are three manifestations of this problem:

1. The 'default' text to the right of the input box is not delimited
2. The pre-populated text in the input box is not delimited
3. If a user over-rides the default with their own set of terms, and clicks try
   A. For a regular field, the user-inputted term is remembered.
   B. The an array field, the user-inputted term is replaced with the default.

### Image example of problems 1 & 2:
![image](https://user-images.githubusercontent.com/8644351/99428197-53db7080-28d4-11eb-80d7-c7085a04a875.png)

### Example specification

```
openapi: 3.0.1
info:
  title: MyTitle
  version: 0.0.0
servers:
  - url: https://www.google.com
paths:
  /foo/bar/{multiple_terms}:
    get:
      summary: Get genome metadata by accession
      responses:
        200:
          description: Successful download
          content:
            application/zip:
              schema:
                type: string
      parameters:
        - name: multiple_terms
          in: path
          required: true
          schema:
            type: array
            items:
              type: string
              default:
                - term1_default
                - term2_default
                - term3_default
                - term4_default
        - name: single_field
          required: false
          in: query
          schema:
            type: string
            default: single_field_default
```

**Comment by mrin9** [comment]
pre-populating fields with `defaults` will be removed. coz `defaults` should be applied by the API-server when they dont receive a value from the request.

In that case this wont be an issue anymore. 

If you like to pre-populate request parameters then use `example`
https://mrin9.github.io/RapiDoc/examples/parameters.html

**Comment by BradHolmes** [comment]
Thank you for the quick reply.  The example fields is really powerful, and we'll switch to using it.  

I did notice two bugs still:
1. When the user overrides the example data, and clicks try, the examples are re-populated.  That can be a frustrating experience.
2. When they are re-populated (if you choose to keep that behavior), in some cases, only *one* of the examples is re-populated, and on the next go-aroudn, *zero* examples are re-populated.  

I was able to re-produce this in the example page, for 'country-code-6'.  Here is a screenshot after typing "foo" "bar" (deleting the example and adding two new entries) and clicking "try"

![image](https://user-images.githubusercontent.com/8644351/99986408-23d11900-2d7d-11eb-8c5d-1ccb6635645c.png)

Again, I'm happy to create a new issue if you feel this is different enough.

**Comment by mrin9** [comment]
> 1. When the user overrides the example data, and clicks try, the examples are re-populated. That can be a frustrating experience.
> 2. When they are re-populated (if you choose to keep that behavior), in some cases, only one of the examples is re-populated, and on the next go-aroudn, zero examples are re-populated.

Thanks for reporting, will fix the issue where fields will not get repopulated after clicking `TRY`. Once thats taken care of . point 2 is not applicable anymore

**Comment by schmurfy** [comment]
@mrin9 I still get this behaviour, I have example for my query parameters, if I change them and click try, the example will replace my input. If the user set a specific value the value should never be reset unless he reloads/change page.
