### ISSUE TITLE
Support to have cache-control header optional in try out option

### ISSUE THREAD

**Issue by Dharmendra205111014** [mrin9/RapiDoc#354]
Currently 'Cache-Control' header is by default added and with default value. We should have a flag based approach for that to include or not to include with user-defined values to override it.

https://github.com/mrin9/RapiDoc/blob/master/src/components/api-request.js#L1173

Let me know your opinion on that,  can raise the PR.

**Comment by mrin9** [comment]
we will be removing  `Cache-Control` all together while me make API calls.
but may I know whats the problem are you facing with this header ?

**Comment by Dharmendra205111014** [comment]
@mrin9 The problem i had was very specific. For the consuming apis `Cache-Control ` was not the supported header in preflight request and hence it was throwing the cors issue.
