### ISSUE TITLE
Events to capture/modify the request and the response of try

### ISSUE THREAD

**Issue by aj-anuragjain** [mrin9/RapiDoc#355]
Do we have any open event to capture or modify the request and the response data coming from the api request when user hit the try button?

`el.addEventListener('request', res => console.log(req.payload));`

`
el.addEventListener('response', res => console.log(res.data));
`

**Comment by mrin9** [comment]
there isnt any, 
RapiDoc isnt a tool that would replace an API client that. 
It just sends and receive un-adulterated requests and responses, it wont even validate anything (even if it the validations are defined in open-api spec)

I would like to know more on whats the use case that you are after ?

**Comment by aj-anuragjain** [comment]
I'm looking to track user try event with Google Analytics or similar tools. So that I can the analysis the user journey and appropriate the default value experience for the end user.


We are just looking for read only values for the tryout so that we can analysis the data based on type of end user and provide the best tryout combination to the user.

**Comment by aj-anuragjain** [comment]
@mrin9 Did you gone through our usecase. Is there any possibility to capture such events?

**Comment by mrin9** [comment]
we are yet to discuss on this

**Comment by arizvi11** [comment]
@mrin9,  Is there any update on this thread?

**Comment by mrin9** [comment]
`after-try` event is provided in the latest build which you can pick from `dist\rapidoc-min.js`

refer to [API documentation](https://mrin9.github.io/RapiDoc/api.html#events) for more details
here is an example of its usage 

https://github.com/mrin9/RapiDoc/blob/36df2728950126aae5d2627aadbbfb06e72ae6d3/docs/examples/mock.html#L29-L36
