### ISSUE TITLE
javascript throws if there is no description for a header

### ISSUE THREAD

**Issue by arabidopsis** [mrin9/RapiDoc#36]
As far I can tell a description for a header is not required (at least for 3.0.2). But with RapiDoc
the javascript will throw without it.

The offending line is here:

https://github.com/mrin9/RapiDoc/blob/master/src/components/api-response.js#L182

Needs a `marked(v.description || "")`  or something.

**Comment by mrin9** [comment]
thanks for taking time to point this out, will fix it soon

**Comment by mrin9** [comment]
fixed in release 5.0.5
