### ISSUE TITLE
[suggestion] add support for slot="stylesheet" (or similar)

### ISSUE THREAD

**Issue by tsoestini** [mrin9/RapiDoc#362]
I was suggested to add this to a new issue for visibility, since closed issues aren't notified:

> What about adding the option to specify a slot="stylesheet" that gets put into every shadowRoot so the user can add their own styling very simply?

For motivating example and additional user support, see thread here: https://github.com/mrin9/RapiDoc/issues/331#issuecomment-717721378

**Comment by mrin9** [comment]
`solt` is not intended for injecting stylesheets, this will also allow users to break things easily as they can inject scripts, htmls and can disturb the overall layout.

We are also working on a major revision that will provide advanced styling capabilities using [CSS Shadow Parts](https://developer.mozilla.org/en-US/docs/Web/CSS/::part). Do not depend on this, we do not have any timeline or have finalized any specific approach but we are working with various clients to define scope of our work. At this point we would like to keep things as is w.r.t styling

However you can introduce your own styling by building rapidoc from source https://mrin9.github.io/RapiDoc/api.html#developers
