### ISSUE TITLE
[bug] Focused View side-nav doesn't work for routes with {} in them

### ISSUE THREAD

**Issue by tsoestini** [mrin9/RapiDoc#363]
Example: https://mrin9.github.io/RapiDoc/examples/focused-mode.html

For example, the left side-nav doesn't work when clicking on "Find Pet by Id" which should show "GET /pet/{petId}" and instead always shows the first route in the document (which in this case is "GET /pet" without {petId}").

**Comment by tsoestini** [comment]
(used to work in 8.2)

**Comment by mrin9** [comment]
thanks ... wil fix this asap
