### ISSUE TITLE
build error on windows

### ISSUE THREAD

**Issue by tsoestini** [mrin9/RapiDoc#364]
Trying to build on windows with `yarn build_windows`.

Any idea what might be causing this error and/or how to fix it?

```
ERROR in src/rapidoc.js 830:85
Module parse failed: Unexpected token (830:85)
File was processed with these loaders:
 * node_modules/babel-loader/lib/index.js
 * node_modules/eslint-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
|     }
|
>     if (this.showInfo === 'true' && !window.location.hash && (this.resolvedSpec.info?.description || this.resolvedSpec.info?.title)) {
|       this.selectedContentId = 'overview';
|     } else if (window.location.hash) {
 @ src/index.js 2:0-32 5:2-9
```

**Comment by tsoestini** [comment]
here was my yarn install output, if it helps:
```yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-jsx-a11y@^6.4.1".
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react@^7.21.5".
warning " > eslint-config-airbnb@18.2.1" has unmet peer dependency "eslint-plugin-react-hooks@^4 || ^3 || ^2.3.0 || ^1.7.0".
[5/5] Building fresh packages...
Done in 35.15s.```

**Comment by mrin9** [comment]
i am unable to recreate this issue for windows build

the environment i test is 

```
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19042 N/A Build 19042
```

```
node -v
//  v15.3.0

yarn -v
// 1.22.5
```

I use powershell to build on windows

**Comment by tsoestini** [comment]
I tracked down the issue. A few things need to be installed manually/globally for it to work.

Here's steps from fresh:

1. Download node.js from https://nodejs.org/en/ (last tested with 14.15.1)
2. Install that (you can skip the extra node-gyp installation)
3. Run the following global installs:
 a. `npm i -g yarn`
 b. `npm i -g webpack`
 c. `npm i -g webpack-cli`
 d. `npm i -g eslint-plugin-react-hooks`
 e. `npm i -g eslint`
 f. `npm i -g eslint-plugin-react`
 g. `npm i -g eslint-plugin-jsx-a11y`
(in steps c/d/f/g you can ignore the warning that you need the peer dependency -- you are installing it)
4. Download RapiDoc
5. In that folder, do `yarn install`
(you can ignore the `fsevents` infos -- you don't need them)
(you can also ignore the three warnings for `eslint-config-airbnb` peer dependencies -- you installed them above)
6. In that folder, do `yarn build_windows`

@mrin9 perhaps it is worth adding these to a windows build instructions somewhere?
