### ISSUE TITLE
Disable fragment routing

### ISSUE THREAD

**Issue by bendiksolheim** [mrin9/RapiDoc#366]
Hello!

We just started using this fantastic product (hey, it actually made me like Swagger again, so props to you!). We are using it inside a React app, and it mostly works. This React app is an old app though, which uses fragment based routing. You might see where this is going: our React app and RapiDoc are currently fighting over who controls the hash. RapiDoc seems to win, which I guess is good for you, but it gives us some difficulties 😅

We could switch over to using the browser history API in our React app, but that is sadly not straight forward. So, before going down that route, is it possible to stop RapiDoc from manipulating the fragment? Either an official way, or through some nasty hacking?

**Comment by mrin9** [comment]
There are certain things that is inter-connected with location hashes. for instance you can create links to various sections of the spec using markdown which depends on location-hash.

I dont thinks there is any hack that would allow you to override the default behavior. The next best thing that you can do is modify the code and build it on your end.

To stop updating the location-hash try commenting out `history.replaceState` throughout the codebase https://github.com/mrin9/RapiDoc/search?q=history.replaceState

I have add included this feedback to our **Integration pain points** that we maintain internally. but do not depend this getting ant traction anytime soon

**Comment by bendiksolheim** [comment]
Alright, its just a minor issue when refreshing the page as of now so I think we'll just live with it for now :) Thanks though!
