### ISSUE TITLE
rapidoc double encodes query parameters

### ISSUE THREAD

**Issue by arabidopsis** [mrin9/RapiDoc#37]
You're encoding a value and then giving it to URLSearchParams...

see (say) here:
https://github.com/mrin9/RapiDoc/blob/master/src/components/api-request.js#L499

This results in a comma becoming not a `%2C` but the encoded version of that: `%252C`

**Comment by mrin9** [comment]
Thanks for taking time and pointing out the very location of the issue, helps us save time.
this should be fixed in 5.0.5. Feel free to reopen incase it is not working as you expect it to
