### ISSUE TITLE
Represent OperationId for methods

### ISSUE THREAD

**Issue by aleksandr-bit1** [mrin9/RapiDoc#370]
Hello.

Now, when I expand method in RapiDoc, in browser address bar shows link for this method. It consists anchor like this:
`#get-/pet/-petId-`

In Swagger UI anchor consist OperationId. Example:
`#/pet/getPetById`

It would be great if it would be possible to see the OperationId in RapiDoc without manually viewing the spec.
Thank you.

**Comment by mrin9** [comment]
per OpenAPI spec operationId is optional, therefore we use a combination of method and path both of which is unique and mandatory.
Do you have any particular reason to switch to operationId ?

**Comment by aleksandr-bit1** [comment]
> Do you have any particular reason to switch to operationId ?

It is convenient to find the method in the code by operationId and find out how it works.

**Comment by mrin9** [comment]
well, feedback we received from our users is they find `method` and `path` more easier also it is an universal way to refer to an API  by method and path.

I dont think team would like to take this direction
