### ISSUE TITLE
Examples for application/xml copy button is missing 

### ISSUE THREAD

**Issue by rafaelrosabal** [mrin9/RapiDoc#373]
Example for application/xml don't show copy button.  In the case of application / json it shows the option to copy
<img width="1690" alt="json" src="https://user-images.githubusercontent.com/6864592/100774815-830fd880-33d0-11eb-8ace-fae4182473e2.png">
<img width="1668" alt="xml" src="https://user-images.githubusercontent.com/6864592/100774819-83a86f00-33d0-11eb-8413-612eb219767a.png">

**Comment by mrin9** [comment]
JSON responses are shown with a special component which has expand/collapse feature. manually selecting text and copying from such component may be little inconvenient, therefore there is a copy button.

XML responses on the other hand are displayed in a text-area, select (cmd-a) and copy (cmd-c) is straight forward so there is  no copy option provided.

Still, for the consistency and better UX i am tagging this as feature-request and will plan to add this functionality

**Comment by mrin9** [comment]
this feature has been added
