### ISSUE TITLE
Reset response selection state in focused mode

### ISSUE THREAD

**Issue by mrin9** [mrin9/RapiDoc#376]
consider https://mrin9.github.io/RapiDoc/examples/focused-mode.html#get-/pet/-petId-
for API `GET /pet/{petId}` (Find pet by ID) go to `Response > Status > MIME Type` and set it to `application/xml`

Now navigate to 

https://mrin9.github.io/RapiDoc/examples/focused-mode.html#post-/pet/-petId-/uploadImage
API `POST /pet/{petId}/uploadImage` (uploads an image)

checkout Response, It will show schema not found, thats coz the previous selection of MIMEType `application/xml` is not available for this path.

The Fix : must always reset selected MimeType and Response Status in focused mode upon navigationg from one path to another

**Comment by Dharmendra205111014** [comment]
It Fix issue persisted in same doc, but on doc change it still happens. have created different bug #377 to address dynamic url issues
