### ISSUE TITLE
Dynamic spec-url change does not reset the states

### ISSUE THREAD

**Issue by Dharmendra205111014** [mrin9/RapiDoc#377]
**Problem**
If you change spec-url using JS dynamically, few things are noticed

- URL still contain the old hash
- In focused render style, it again cause the issue explained in #376 because of above

**Expected behaviour**
When spec Url change, the rapi-doc should reset all states and the visible tab should be **overview** always initially for spec

To Reproduce, you can go to https://dharmendra205111014.github.io/RapiDocExamples/example1.html#post-/pet/-petId-/uploadImage and then click on change spec url button

@mrin9  please let me know your opinion on this, can open PR respectively. Thanks

**Comment by mrin9** [comment]
thanks for reporting... PR is very much appreciated, 
My guess is the fix should be similar to #376
