### ISSUE TITLE
Left panel nav links failing with path parameters in focused mode only

### ISSUE THREAD

**Issue by ajl199** [mrin9/RapiDoc#381]
I'm fairly new to OpenAPI, very new to Rapidoc, so there is a possiblity it's me doing something stupid.

First, thank you for all the work creating Rapidoc; it is fantastic.

However, I'm finding that in render-style="focused", the left-hand nav panel links for paths containing a path parameter all result in the wrong endpoint being displayed. They all show the page for the top path entry in the nav panel.

All links to endpoints without a path parameter work correctly. With render-style="read", all links work correctly.

**Comment by mrin9** [comment]
I think this is a duplicate of #363
A fix has been provided for this, but not yet released .

To test it on your end, use `rapidoc-min.js` from `dist` folder  https://github.com/mrin9/RapiDoc/blob/master/dist/rapidoc-min.js 

let us know if you are still facing any issue

**Comment by ajl199** [comment]
Awesome, thank you! That fixed it so it was indeed a duplicate.
