### ISSUE TITLE
Anchors in description don't work with cyrylic names

### ISSUE THREAD

**Issue by aleksandr-bit1** [mrin9/RapiDoc#386]
I want create table of contents in description.

Example:

```
info:
 description: |
   - [Тест](#overview--тест)
   
   # Тест
```

Clicking on `Тест` link don't going to `Тест` header

**Comment by mrin9** [comment]
If you want to include the Headings of `info` section as a Links on the left-side-nav then you may use `info-description-headings-in-navbar`

```yml
openapi: 3.0.0
info:
  title: Markdown Headings in Navigation Bar
  description: |
    # Heading 1
    content of heading 1

    ## Heading 1
    level2 heading 2
```
you can checkout this example https://mrin9.github.io/RapiDoc/examples/markdown-headings.html#overview--documentation

**Comment by aleksandr-bit1** [comment]
@mrin9 Thank you for response.

Yes, i khow about `info-description-headings-in-navbar`. But if possible, it would be great to be able to use anchors to headings with cyrillic names.

**Comment by mrin9** [comment]
our markdown parser converts special unicode characters to url-encoded equivalent when generating href
and therefore it wont work.

if you are dealing with such characters in hrefs
```yml
openapi: 3.0.2
info:
  title: Test
  version: "1.0"
  description: |
   - [Тест](#overview--тест)
   - [H1 Тест](#overview--heading).    <-- provide a simple href

   # Тест
   Some text

   <h1 id="overview--heading"> H1 Тест </h1>.   <-- provide simple id instead of markdown parser to generate it
   Some Text
```

hope it takes care of the situation
