### ISSUE TITLE
Support for $ref in info -> description

### ISSUE THREAD

**Issue by codedust** [mrin9/RapiDoc#390]
A nice feature of ReDoc is a reference to a markdown file in the description attribute. This allows for nice separation between high-level documentation and the actual API specification:
```yaml
openapi: '3.0.0'
info:
  version: 1.0.0
  title: My example API
  description:
    $ref: /path/to/file.md
```
see https://redoc.ly/docs/api-reference-docs/embedded-markdown/

I opened this issue as an inspiration for a (imho) useful feature. Feel free to ignore/close it if you don't plan to implement it.

Btw, thanks for this great piece of software. I really like RapiDoc a lot! :)

**Comment by mrin9** [comment]
we are discussing this internally with our UX to how best we can address this. It involves some prototyping, and user-survey from our sponsoring org. We do have some alternate ways to inject html and evaluating various options

**Comment by mrin9** [comment]
after some discussion and feedback we decided that it is better that we stick to the open-api spec to avoid any sort of vendor lock-in. this option offer more flexibility too. If separation of documentation is your main concern, you can achieve it  using the regular `$ref`

```yml
openapi: '3.0.0'
info:
  version: 1.0.0
  title: My example API
  description:
    $ref: /path/to/file.md#/description
```

contents of `file.md`

```yml

description: |
  # Heading 1
  Some text

  # Heading 2
  Some text

```
