### ISSUE TITLE
[Focused Style] Parameters and response not reset when changing operation

### ISSUE THREAD

**Issue by rosewood-boutique** [mrin9/RapiDoc#392]
Hello,
When I change operation after click on the TRY button in focused style, PATH PARAMETERS, QUERY-STRING PARAMETERS and the whole RESPONSE area are not reset to empty.

Is there a way to do that ? or am I missing something ?

thanks

**Comment by mrin9** [comment]
this has been fixed now, you may test it using the latest build from `dist\rapidoc-min.js`
