### ISSUE TITLE
Accept header is set incorrectly

### ISSUE THREAD

**Issue by tnotheis** [mrin9/RapiDoc#395]
My API defines a few routes that can deliver both application/json and image/png. The consumer can choose the desired mime type by setting the Accept header. 

I was hoping to test this with RapiDoc by selecting the mime type in the dropdown list of the Response section.
![22-01-_2021_07-31-58](https://user-images.githubusercontent.com/65653426/105455738-4bad0200-5c84-11eb-9b4f-14f384f54157.png)

But no matter which one I select, RapiDoc always sends the first one. Is this a bug or is this feature not supported yet?

**Comment by mrin9** [comment]
this should be a bug... can you provide with a minimal spec for us to recreate this issue ?

**Comment by tnotheis** [comment]
First of all, I have to correct myself. While assembling a sample nodejs server, I noticed that what I reported isn't actually the case. I am using a wrapper library around "express", which parses the incoming Accept header and transforms it into a "user friendly" form. Unfortunately, it seems to delete everything except the first MIME type. :-)

What's actually happening is that RapiDoc sends **all** MIME types supported by the route, no matter which one I select in the dropdown list.

Consider the following path in OpenAPI:

```yaml
/my-route:
  get:
    operationId: myRoute
    responses:
      200:
        description: Success
        content:
          image/png:
            schema:
              type: string
              format: binary
          application/json:
            schema:
              type: object
              properties:
                prop1:
                  type: number
                prop2:
                  type: string
```

This leads to a RapiDoc UI as shown in the screenshot above. Now, no matter whether I select "image/png" or "application/json", RapiDoc sets the [Accept header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept) to "image/png, application/json".

The expected behavior, though, is that depending on my selection the Accept header sent to the server is either "image/png" or "application/json".

---

> But how would your API decide weather to deliver application/json or image/png ?

My API reads the Accept header sent by the client. Depending on the order of MIME types in it, it sends the first one that it supports.

So if the Accept header is "application/json", the response will be JSON. If the header is "image/png", the response will be an image. And if the header is "image/png, application/json", it also sends an image.

And that's exactly my problem. Since RapiDoc always sends both MIME types, the user cannot decide to request JSON.

---

I created a minimal sample application you can view here: https://github.com/tnotheis/rapidoc-accept-header.

**Comment by mrin9** [comment]
thanks for the spec... it is a bug, will fix it soon

**Comment by mrin9** [comment]
this should be fixed now... to check it out use `dist\rapidoc-min.js`

**Comment by timnot90** [comment]
I can confirm that the issue is fixed. Thank you!

**Comment by tnotheis** [comment]
I can confirm that the issue is fixed. Thank you!
