### ISSUE TITLE
Wrong field type for array: object

### ISSUE THREAD

**Issue by hgrueneis** [mrin9/RapiDoc#396]
Hi team, 
just updated RapiDoc version from 8.3.0 to 8.4.3. 

We use the schema display style: table 

Here I see a difference for the displayed field types. For an 'array' now I see 'object'. 

8.3.0
![image](https://user-images.githubusercontent.com/16539285/105834737-25ac9800-5fcb-11eb-922c-77bc412005df.png)

8.4.3
![image](https://user-images.githubusercontent.com/16539285/105834764-2fce9680-5fcb-11eb-9c1b-26f37220a8e9.png)

Is this a bug?

**Comment by mrin9** [comment]
unless I get a minimal spec i wont be able to comment if the rendering is correct.
If the `schema-style=tree` does it show it as an array ?

**Comment by hgrueneis** [comment]
Hi, thanks for your fast response. 

Yes, `schema-style=tree` shows it as an array.

I added a minimum spec which causes the problem - Do you need further information?

https://gist.github.com/hgrueneis/08ae520ab9f1e0efcdcda22590ac3b19

**Comment by mrin9** [comment]
thanks for the spec... this should be fixed now. to test you can pick up the latest code from `dist/rapidoc-min.js`
