### ISSUE TITLE
Missing default values for query parameter and textfield hint: 'add-multiple'

### ISSUE THREAD

**Issue by hgrueneis** [mrin9/RapiDoc#397]
Hi team,

just updated RapiDoc version from 8.3.0 to 8.4.3.

The default values ​​for query parameters are no longer displayed. The hint 'add-multiple' for arrays is also missing.

8.3.0
![image](https://user-images.githubusercontent.com/16539285/105959236-f2761180-607b-11eb-938d-4f9af8d24f09.png)

8.4.3
![image](https://user-images.githubusercontent.com/16539285/105959306-0588e180-607c-11eb-97f2-e0a983bad53d.png)

Here a minimum spec which causes the problem:
https://gist.github.com/hgrueneis/a422188ca107c322a2962e0f867f1ca6

**Comment by mrin9** [comment]
thanks for reporting the issue, however this change is intended. we consider `defaults` only for documentation. this is the value that an API server will fill in if the value is not provided. 

If you like to provide one or more values for a parameter then use `example` instead 

> PS: for more info checkout #359 #353
