### ISSUE TITLE
Question - Option to dynamically set the server URL

### ISSUE THREAD

**Issue by thim81** [mrin9/RapiDoc#398]
There are some many great options to modify RapiDoc.

I wonder if there is an option to allow the user to specify his own server URL.

```
servers:
    - url: 'http://example.com/api'
```

There is the option to set the authentication using ` allow-authentication="true"`.
But I can don't seem to find an example on how to overwrite or allow the user to set it like he would for the api-key.

<img width="716" alt="CleanShot 2021-01-27 at 14 59 21@2x" src="https://user-images.githubusercontent.com/952446/106001450-41d63500-60b0-11eb-9d77-72ce5d3a8af1.png">

**Comment by thim81** [comment]
I tried by using the same approach as with the font-size

`<button class='btn medium' onclick="document.getElementById('thedoc').setAttribute('server-url', 'http://github.com')" >Set Server URL</button>`

But no luck.

Although I can add an additional server URL using the `server-url` property, I can't seem to update it via javascript.

```
<rapi-doc
        spec-url="../.openapi.json"
        render-style="read"
        id="thedoc"
        primary-color="#00b8fb"
        allow-authentication="true"
        show-info="false"
        show-header="false"
        render-style="focused"
        theme="light"
        schema-style="table"
        server-url="http://example.com/api"
/>
```

**Comment by mrin9** [comment]
while RapiDoc provides `server-url` feature we strongly suggest *not* to use it (unless you like to keep server-info and documentation separate). This will also help you not to get into vendor-lock-in

Now in your case if you like Server to be dynamic, you may either provide multiple servers  or provide a Server template url with variables in it . 
here is an example that uses server templating in RapiDoc https://mrin9.github.io/RapiDoc/examples/server-vars.html#get-/server-variables

for more info checkout this issue #256

> If none of the above works for you then after changing `server-url` using javascript try to reload the spec

**Comment by thim81** [comment]
@mrin9 Thanks for taking the time to respond.

Your answer and referred ticket made it clear for me how I can move forward with the server-url handling.
