### ISSUE TITLE
Not expanding the models in HTML.

### ISSUE THREAD

**Issue by mayurpate** [mrin9/RapiDoc#40]
I am trying to generate the HTML doc from swagger 2.0 spec using RapiDoc. My spec has definitions which refer to other definitions.  In generated HTML doc, I do not see these referred objects being expanded inline. Please find the attached screenshot for this. 

<img width="679" alt="RapiDoc_1" src="https://user-images.githubusercontent.com/13736359/60548666-81bc1700-9cd7-11e9-8621-6b6b66d3df7f.png">

<img width="670" alt="RapiDoc2" src="https://user-images.githubusercontent.com/13736359/60548681-8b457f00-9cd7-11e9-87ef-fccc004d9977.png">

In the example section, the reference definition is marked as "?" while in the "Model" section it is only showing up the type which is "object". I am expecting the fully expanded object definition here.  Is it expected behavior?

**Comment by mrin9** [comment]
is your spec using `anyOf` operator ?

**Comment by mrin9** [comment]
currently `anyOf` operator is not supported. closing this as we have it planned in our roadmap
