### ISSUE TITLE
Oauth: is it possible to pre-fill client-id and client-secret programatically?

### ISSUE THREAD

**Issue by davidovich** [mrin9/RapiDoc#401]
I serve the RapiDoc interface and the `client-id` and `client-secret` is known in advance for the oauth flows. Is it possible to somehow pre-fill the corresponding form fields of the UI ?

**Comment by mrin9** [comment]
no you cant provide `client-id` or `client-secret` programmatically. 
I will see what best we can do to provide this feature.

**Comment by davidovich** [comment]
@mrin9 Thanks for the fast response. A click would be excellent, the need is to pre-fill (because the server knows the client-id and secret.

I am in control of the served OpenApi document, I can add the secret in the spec there, this would be excellent! 

Kudos to for this very nice project!

**Comment by mrin9** [comment]
check out this [example](https://mrin9.github.io/RapiDoc/examples/oauth-vendor-extension.html#overview) for usage and [supported vendor extension](https://mrin9.github.io/RapiDoc/api.html#vendor-extensions) 

To use an unreleased build, find it at `dist/rapidoc-min.js`

**Comment by davidovich** [comment]
Thanks @mrin9, this is perfect, and wow was it fast! I'll give it. spin later today. 

Thank you again!

**Comment by davidovich** [comment]
Works as expected, thank you for the exceptional turnaround. Thanks @mrin9 !
