### ISSUE TITLE
Question - Maximum/Minimum Values in Table View?

### ISSUE THREAD

**Issue by joshrap-eb** [mrin9/RapiDoc#402]
First off, absolutely love this project. It has made our lives so much easier for generating our API's documentation page. 

I noticed that when I switch to `schema-style ="tree"` it shows the maximum/minimum values I have for a specific attribute.

![1](https://user-images.githubusercontent.com/74060233/106800376-5f664a00-662e-11eb-8a16-4298a3652f7f.PNG)

However, when I switch to `schema-style ="table"`, those values do not show.
![3](https://user-images.githubusercontent.com/74060233/106800428-7016c000-662e-11eb-8992-13b0dfaf8eb7.PNG)

Is there a way to enable those maximum/minimum values to show on the table view? Or is this intentional?

**Comment by mrin9** [comment]
this is not intentional, I will investigate it further, thanks for reporting !!!
