### ISSUE TITLE
UX enhancements: Adding Tag Grouping name to selected API & automatic Try response clearing

### ISSUE THREAD

**Issue by reyolivo** [mrin9/RapiDoc#404]
Hello, there are a couple items I wanted to raise here to possibly enhance the user experience.:

1. Could we add the grouping Tag name (or description) to the top of a selected API? This is especially useful for the "focused" render mode, particularly, when we are navigating through large specs. For example, if you click on an API that is towards the bottom of the page, then you might lose track of what Tag group that API belongs to since you are redirected to the top of the page. There could be various APIs with a similar summary that, depending on the Tag group, could have a totally different function.

2. After running a "Try" on an API, and then you select another API, then it would be a better UX (in my opinion) to automatically clear the response from the prior API. Else, you may end up seeing an API response from a different API, which could definitely throw off the user. Hopefully this would be an easy change/win!

Thanks a lot and happy to go over either of these in more detailed examples.

-Rey

**Comment by mrin9** [comment]
for point 1 , if you can, then provide a rough visual and i will run it through our UX team

for point 2, check out #392, if this is what you need, then it is already fixed. To try out latest (non-released) build pick it from `dist/rapidoc-min.js`

**Comment by reyolivo** [comment]
OK perfect, yes that does seem to solve it for point 2.

Attached is what I had in mind for point 1:
![rapidoc-example-with-tag-header-focused-mode](https://user-images.githubusercontent.com/50844231/106921443-048a2c80-66da-11eb-855d-c289c1211b30.png)

I based it off this [example](https://mrin9.github.io/RapiDoc/examples/focused-mode.html#get-/user/logout). By the way, is that scroll bar on the left navigation column a part of this upcoming release? I don't seem to have that on the current UNPKG cut, which is what makes my request more critical, since currently, the entire page automatically scrolls to the top when you select an API, thus you can easily lose track of where you selected the API. Either way I think it'd be nice to include the tag grouping name for a selected API in focused mode. Thanks!
