### ISSUE TITLE
Won't load when running as local HTML file.

### ISSUE THREAD

**Issue by tjperry07** [mrin9/RapiDoc#405]
Here is my spec file https://raw.githubusercontent.com/tjperry07/spec-testing/master/api.yaml. I tested using https://mrin9.github.io/RapiDoc/examples/petstore-extended.html#overview and the file appears. I am now using it locally as an HTML file and the spec just shows me a loading screen.

```html
<!DOCTYPE html>
<html>
  <head>
    <title>API Reference</title>
    <meta charset="UTF-8" />
    <script
      type="module"
      src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"
    ></script>
  </head>
  <body>


    <rapi-doc
      spec-url="https://raw.githubusercontent.com/tjperry07/spec-testing/master/api.yaml"
      render-style = "read"
      layout="column"
      regular-font="Source Sans Pro"
      mono-font="Inconsolata"
      font-size="largest"
      schema-style="table"
      info-description-headings-in-navbar="true"
      heading-text="Nylas"
      bg-color="#fff"
      text-color="#161717"
      header-color="#00E5BF"
      primary-color="#00E5BF"
      nav-bg-color="#161717"
      nav-text-color="#fff"
      nav-hover-bg-color="#6A7285"
      nav-hover-text-color="#fff"
      nav-accent-color="#00E5BF"
      show-header="false"
      allow-spec-url-load="true"
      allow-search="false"
      


    >
    </rapi-doc>

</body>
</html>
```

Chrome Console Error:

<img width="1440" alt="Screen Shot 2021-02-03 at 5 42 01 PM" src="https://user-images.githubusercontent.com/5667652/106823809-2a1a2600-6647-11eb-84bc-23c9c9c22702.png">

No idea what is going wrong.

**Comment by mrin9** [comment]
Seems like in one of the code-sample inside the spec has `lang` attribute missing, which is resulting in error. Nevertheless, this shouldn't be the reason to not load the spec.

I have provided a fix for this, if you want to test it out pick up the non released build from `dist/rapidoc-min.js`

**Comment by tjperry07** [comment]
Is there a linter or debugger you are using? So I can make sure my spec matches what your doc tool needs.  I am just using [openapi-cl](https://github.com/Redocly/openapi-cli).

**Comment by mrin9** [comment]
`x-code-sample` is a vendor-extension and i dont think any linter will help you to fix that, I was able to discover it as RapiDoc was getting a runtime error wile trying to access `lang`
