### ISSUE TITLE
Fix Markdown in the method title

### ISSUE THREAD

**Issue by poadoc** [mrin9/RapiDoc#409]
Hi!
We have Markdown parser for the method description but haven't for the method title.
![fix-markdown](https://user-images.githubusercontent.com/69155835/107482898-fa0fdd00-6b88-11eb-8cf6-e91662519485.png)

**Comment by waldyrious** [comment]
[According to the OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#path-item-object), the path object's `summary` field is a plain text string, not rich text (unlike the `description` field).

**Comment by poadoc** [comment]
But we use the same string variable in the title and description of the method, and it can be a little confusing. Consequently, we should parse Markdown in the title or don't parse Markdown in the description of the method.

**Comment by mrin9** [comment]
I agree with @waldyrious , `summary` should'nt be parsed as markdown syntax.

and @poadoc is correct that in the 1st line `summary` is not parsed as markdown 2nd line `summary` is treated as markdown 
and the reasoning behind this is that after parsing  the spec `summary` will contain `summary` or `description` if `summary` is empty, therefore in the 2nd line it was treated as `markdown` in anticipation that it may contain the description.

The way it needs to be addressed is to clearly separate `summary` and `description` and then parse it accordingly.
this will also have effect on `view-mode` therefore it needs to be tested there too.
