### ISSUE TITLE
Enabling FILL button

### ISSUE THREAD

**Issue by charity1475** [mrin9/RapiDoc#411]
I have a RapiDoc for an API documentation, clear button and try are working fine but i want when somebody needs to try he/she should not in put the vales in fields instead to fill default values by clicking fill button then try. How do i do that?.

**Comment by mrin9** [comment]
In your schema for every field you can provide a `default`  and one or more `example` 
- `default` is what the server will substitute when the client do not provide any value.  RapiDoc being a client wont provide this value, its shows up in RapiDoc only for documentation purpose
- `example` for the field is used to fill the data. 

so if you want the `FILL` button to work, you must provide `example` for the corresponding fields in your schema 

below is an example how you can provide examples in your OpenAPI spec
```yml
openapi: 3.0.0
info:
  version: 1.0.0
  title: Demonstrates schema examples 
paths:
  /person:
    post:
      summary: Demonstrates schema examples
      parameters:
        - name: age
          in: query
          example: 24
          schema:
            type: integer
        - name: full-name
          in: query
          example: John
          schema:
            type: string
        - name: email
          in: query
          example: john@example.com
          schema:
            type: string
      responses:
        '200':
          description: successful operation
```

**Comment by charity1475** [comment]
Thanks alot.

**Comment by charity1475** [comment]
one more thing,  I have my openAPI documentation, after logging in the user
gets the session Id which will be needed for all other requests. I need
this value to be put once by a user and all other requests needing it to
use it from authentication. How do I do that?
