### ISSUE TITLE
Feature Request Make Markdown Headings Clickable

### ISSUE THREAD

**Issue by tjperry07** [mrin9/RapiDoc#414]
Make markdown headings clickable in API overview sections.  Using https://mrin9.github.io/RapiDoc/examples/petstore-extended.html#overview as an example, as a user I would expect API Categories, API Operations, etc to be clickable and linkable. The headings (h1-h6) should appear in the menu using a table of content style while in Read mode.

**Comment by mrin9** [comment]
there are plenty of ways RapiDoc allows you to create links and customize them to your heart's content

- **Markdown** : Put internal and external links at your needed location, create a table, arrange them in an indented list or inline it in your text all using markdown syntax
- **HTML Links** : Create HTML elements (button, icons, links etc) style them in your own way (change color, font etc) and place them in key slots, pre-defined by RapiDoc
- **Headings as Navigation Links** use `info-description-headings-in-navbar='true'` option to add your headings as links in the navigation bar which is available in `read` and `focused` mode

Checkout this [example](https://mrin9.github.io/RapiDoc/examples/links.html) to know more on how to create links in your doc

**Comment by tjperry07** [comment]
@mrin9 This isn't quite what I was meant for. You can't actually click headings when they are on the endpoint.

**Comment by mrin9** [comment]
I still do not know what do you mean by `nested folders link`. can you elaborate a bit with clear instruction
If this issue is closed by mistake, please create a new one as we do not receive notifications on closed issues
