### ISSUE TITLE
Semi-Colon added at end of sections in "focused" render style

### ISSUE THREAD

**Issue by joshrap-eb** [mrin9/RapiDoc#416]
Not sure if others have found this, but I noticed a bug when I was using the new "focused" option for the render-style. At the end of any section there is a lone ";".

![bug_1](https://user-images.githubusercontent.com/74060233/108095051-743ed680-704d-11eb-8c7f-4dc3f3c9effd.PNG)

![bug_2](https://user-images.githubusercontent.com/74060233/108095067-786af400-704d-11eb-83d8-0ac2592571be.PNG)

I switched back to "read" mode and that semi-colon is not there.

I'm just pulling the script this way instead of using npm, so not sure if this is just pulling an older package?

`<script type="module" src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>`

**Comment by mrin9** [comment]
thanks for reporting - please use release `8.4.8`
