### ISSUE TITLE
Question - Ability to auto expand operations by clicking endpoint name in "focused" mode?

### ISSUE THREAD

**Issue by joshrap-eb** [mrin9/RapiDoc#419]
I wanted to see if I could start a discussion regarding the new "focused" render style. We really love this style as it is perfect for our relatively large spec (on "read" the page scrolls for quite a long time). I was curious if there are any plans in the future to ever give the option in "focused" mode to default to the first operation in a route when clicking an endpoint, and expanding all of its operations?

To further explain what I am talking about, here's a screenshot of what currently happens when you click an endpoint name in "read" mode (in this case I clicked "Accounts"). 
![1](https://user-images.githubusercontent.com/74060233/108222246-99435000-7106-11eb-8bb8-0ee9a9376ae3.PNG)

It takes you to the first operation, with the endpoint name at the top and its description below it.

Right now when you click an endpoint name in "focused" mode, it takes you only to the endpoint's description.
![2](https://user-images.githubusercontent.com/74060233/108222372-bb3cd280-7106-11eb-9c77-7c329f2dc4c6.PNG)

In our case we aren't even providing descriptions for the endpoints so it just takes the user to a blank screen. 

I'm aware that most specs do include descriptions, but I'm just curious if you all would ever consider having some type of option to have clicking an endpoint auto expand its operations (instead of having to click only the arrow), and then it would take you to the first operation if it is there similar to the "read" mode.

**Comment by mrin9** [comment]
We do get 2 polarising request on this.

- There are users who would write multipage descriptions for a Tag
- And there are some who just use it to group the operation with no description or a one line description. (you fall in this category)

Those who write long descriptions for Tags, request to convert their markdown headings into links on the navigation bar.

your suggestion of clicking Tags should expand the endpoint wont solve your problem coz, focused mode is not a continuous rendering like a read mode and therefore  expanding endpoints wont show up the very next item below it in focused mode. (you can check by manually expanding it using the expand/collapse arrow)

We have received request such as directly take me to the first operation under the tag from those who are'nt heavy user of Tag description.

At this point we are little undecided on how to approach this situation as there are many users who wont use Tag descriptions. and for them the focused rendering of tags looks little incomplete.

we will refine this in future but at present we dont have anything on our design board

I will keep this issue open for others (or you) to comment on the approach they would like to see considering all the aspects

**Comment by joshrap-eb** [comment]
That all makes sense. I figured what I was asking for wasn't possible since it is a bit of a hybrid of both focused mode and read mode.

I do really like this idea. 

> We have received request such as directly take me to the first operation under the tag from those who are'nt heavy user of Tag description.

I assume this would mean then you could never see the tag description for that operation? I think that would be useful for teams like us that do not utilize the tag descriptions.

**Comment by mrin9** [comment]
> I assume this would mean then you could never see the tag description for that operation? I think that would be useful for teams like us that do not utilize the tag descriptions.

yes thats true, however there are other options  we have used to address those who like to avoid tag descriptions. In one of our RapiDoc fork we have introduced an attribute `on-nav-tag-click` which can take values `expand-collapse` or `show-description`

after discussion with the extended team  it was decided to extend this option to the open-source version of RapiDoc. I have updated the code and [API documentation ](http://localhost:8080/api.html#att-layout)

for an example implementation checkout https://mrin9.github.io/RapiDoc/examples/tag-focused-mode.html

we do have plans to revisit this later to bring in more functionality around it, possibly without introducing any breaking change. I think this should address your particular concern. 

I will close this issue  as we are tracking this feature internally as a separate one. feel free to reopen or create a new one in case you find something odd

**Comment by joshrap-eb** [comment]
@mrin9 that feature is exactly what we are looking for. Thanks so much you guys are awesome!
