### ISSUE TITLE
Try button feedback

### ISSUE THREAD

**Issue by darkonejr** [mrin9/RapiDoc#42]
It would be nice for the "Try" button to provide some sort of feedback to prevent a user from clicking it more than once against an slow endpoint.  (for instance, you could grey the button out on click until the request completes, and/or show some sort of progress graphic while the request is being executed)

**Comment by mrin9** [comment]
sure, will consider this

**Comment by roderik** [comment]
I'll second this request, the lack of feedback is making myself click multiple times. Often because click one focusses the browser, click two presses the button, and then you are clicking anyway :)

**Comment by mrin9** [comment]
Will make this happen, I am currently traveling, so allow us a little time on this.

**Comment by mrin9** [comment]
fixed in f646901bf99a219dcade05bfd2f63524e7f9a813

> not yet released, you must build it from master branch
