### ISSUE TITLE
Rendering Mermaid Diagrams inside the description markdown

### ISSUE THREAD

**Issue by stevenj** [mrin9/RapiDoc#420]
I tried installing mermaid diagrams and inserting them into the markdown description like so:
See: https://mermaid-js.github.io/mermaid/#/usage
I inserted at the top of the \<body\>
```
<script src="https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js"></script>
<script>mermaid.initialize({startOnLoad:true});</script>
```
In one of the description fields i inserted the literal text:
```
<div class="mermaid">
     graph LR
      A --- B
      B-->C[fa:fa-ban forbidden]
      B-->D(fa:fa-spinner);
</div>
```
Which i can see when i run the inspector on the generated page.

But, it just gets displayed verbatim, the mermaid js is not picking up the div class like it should and is not rendering the mermaid diagram.  Any ideas why or how I can get this to work?  We want to embed mermaid diagrams directly into our endpoint descriptions and we would prefer NOT to pre-render them.

**Comment by mrin9** [comment]
that wont work, as our `markdown parser` wont understand `mermaid markup` nor it is something thats supported by OpenAPI Spec

the way you would do this for now, is to inject your custom HTML/CSS/JS using `<slots>` in RapiDoc

as of now the latest release of RapiDoc ( `8.4.8`) there are only few  predefined `slots` available

however in the upcoming releases, we are adding more slots for each `tags` and `paths`. 
You can pickup the non-release version from `dist/rapidoc-min.js`

checkout this [example implementation](https://mrin9.github.io/RapiDoc/examples/slots.html) which i updated with `mermaid markup`  or to see how to use `<slots>` in RapiDoc

example-source - https://github.com/mrin9/RapiDoc/blob/master/docs/examples/slots.html

let me know.... if that take care of your situation

**Comment by stevenj** [comment]
That looks really nice.  I am generating my openapi json dynamically using FastAPI,  so i can parse the data similarly and produce the necessary slot definitions for each tag/path, etc, dynamically into the HTML page to display the API as well.  It certainly does take care of my situation.  Thank you.
