### ISSUE TITLE
Query URL Generation Does Not Handle Arrays Properly

### ISSUE THREAD

**Issue by BinaryWizard904** [mrin9/RapiDoc#423]
In RapiDoc v8.4.8, array parameters are no longer handled properly when generating query URLs.

All problems are readily observable in your [Built in API console](https://mrin9.github.io/RapiDoc/examples/try.html#post-/person) example

### Problems

1. An empty copy of all array-type query parameters is included in the generated "Try" URLs, including those for which no value was specified.
2. After clicking "Try" all array-type parameters are reset to their example values.  If there is no example value, the parameter is cleared.

The screenshot below is an example of both the generated URL and query parameter values after clicking the "Try" button.  All problems listed above are visible.
![Screenshot - 2_23_2021 , 11_51_14 AM](https://user-images.githubusercontent.com/62070150/108885490-8086de80-75cd-11eb-8dbd-9ba919bdb02b.png)

**Comment by mrin9** [comment]
this has been partially addressed to not send empty array. (this is there in the the non-released build available at `dist/rapidoc-min.js` )

The 2nd part where the values inside the input gets reset after clicking `TRY` may needs more involvement as it is a custom web-component and being used in our other projects. I am keeping this issue open for tracking. 

However, no one is working on this, I will love to get a PR if anyone is interested in making an attempt

**Comment by BinaryWizard904** [comment]
I can say with certainty that this problem was introduced with commit 4fa451dc58aa0cc7071a088b56b95801f64c0ba7.

For those who don't need the ability to paste comma-separated values into array parameter fields, I've created a variant of RapiDoc based on v8.4.6 that resolves these issues in the short-term by removing support for pasting comma-delimited text into array parameters.  I'm calling it [v8.4.7](https://github.com/BinaryWizard904/RapiDoc/tree/v8.4.7) as that name doesn't appear to have been taken by an official release.

**Comment by mrin9** [comment]
the commit  4fa451d may have also fixed some other issues, apart from enabling comma separated value pasting. for instance it may buggy when initialize the field with multiple values, which is needed to pre-fill multiple example values if provided in the spec.

> I'm calling it v8.4.7 as that name doesn't appear to have been taken by an official release.

JSYK - we scrap some releases if they are buggy or route them to a closed source fork if it contains any company specific implementation, so it is always better to name or tag them in an incremental order if you have to for any reason

**Comment by BinaryWizard904** [comment]
@mrin9 was this issue fixed somewhere or just dropped?

**Comment by BinaryWizard904** [comment]
While @mrin9 has been silent on this—and it wasn't mentioned in the release notes for v9.0.0—this issue appears to have been fully resolved in the release version of v9.0.0.  In my testing, values added to array parameters are no longer reset to their example values when the TRY button is clicked.
