### ISSUE TITLE
Make markdown headings in Tag descriptions links.

### ISSUE THREAD

**Issue by tjperry07** [mrin9/RapiDoc#424]
Make links in Tag descriptions clickable. Markdown included in tag descriptions should generate links. 

For example, in this [OpenAPI 3.0 reference](https://tql31.csb.app/#tag--Folders), I would expect Nested Folders and Folders Object to be clickable.

```yaml
tags:
  - name: Folders
    description: >-
      Folders behave like normal IMAP or filesystem folders. A Message can only
      exist within one folder at a time, but a Thread with many messages may
      span several folders.


      Folders are only supported on accounts for which `organization_unit` is
      folder. You can check if an account supports labels by looking at the
      organization_unit property on the Account object.


      ## Nested Folders


      IMAP has very limited support for nested folders. It encodes a folder's
      path in its name. For example, the folder Accounting/Taxes will actually
      be named Accounting.Taxes or even INBOX.Accounting.Taxes depending on your
      IMAP server. To complicate things, different IMAP servers use different
      path separators. For example, Taxes.Accounting on server A may be
      Taxes\Accounting on server B.


      The Nylas API handles nested IMAP folders transparently. Creating a
      Taxes/Invoices folder using the API will create a folder with the right
      path separators. e.g: Depending on your server: INBOX.Taxes.Invoices or
      Taxes/Invoices.


      ## The Folders Object


      | Attribute  | Type | Description  |

      |----:|---|:----|

      | `id` | string | Globally unique object identifier. |

      | `object` | string | A string describing the type of object (value is
      "folder").

      | `account_id` | string | Reference to parent account object. |

      | `name` | string | Standard categories type, based on
      [RFC-6154](http://tools.ietf.org/html/rfc6154). <br>Can be one of the
      following:
      <ul><li>inbox</li><li>all</li><li>trash</li><li>archive</li><li>drafts</li><li>sent</li><li>spam</li><li>important</li><li>null
      (regular user-created folder)</li></ul>

      | `display_name`| string | Localized name of folder, matching what is
      presented in their other mail apps. If you are displaying folders, use
      this instead of `name`. |
``` 

<img width="847" alt="Screen Shot 2021-02-23 at 2 08 56 PM" src="https://user-images.githubusercontent.com/5667652/108901839-fc3e5680-75e0-11eb-9acb-fc4b8e2a9b4e.png">

<img width="872" alt="Screen Shot 2021-02-23 at 2 14 47 PM" src="https://user-images.githubusercontent.com/5667652/108902263-82f33380-75e1-11eb-8413-5771b9225af7.png">

- For a full demo see https://codesandbox.io/s/rapiddoc-html-latest-tql31?file=/index.html
- To see the markdown tag header behavior in another tool, [see redoc demo](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/tjperry07/spec-testing/master/redoc-spec-test.yaml#tag/Hosted-Authentication).

**Comment by tjperry07** [comment]
https://github.com/mrin9/RapiDoc/issues/414

**Comment by mrin9** [comment]
thanks for the detailed explanation and code-samples. 
Here is what we think about it ,

- Clicking on heading wont take you to any new location (_it just takes you to itself_). our UX team thinks its an unnecessary distraction. Let me know if you feel otherwise and provide some reasoning  and I will take it further
- It is a good idea to list some of the headings on the left nav for users to quickly navigate to important sections. We do it currently, but thats limited to only overview section. [Here is an example](https://mrin9.github.io/RapiDoc/examples/markdown-headings.html#overview--what-is-rapidoc) (_checkout the navigation bar where you find links to the headings_) 

Its not yet extended to Tag Descriptions, will bring this up in our team discussion

**Comment by tjperry07** [comment]
@mrin9 It's for sharing with end-users. Being able to share direct links to headings is an easy way for support teams to send documentation to end users. Instead of them saying go here then scroll down (which they never do), they can link directly to that heading so the end-user doesn't have to think.

**Comment by mrin9** [comment]
Tag description can now appear as links on the navbar. Below is a sample implementation
https://mrin9.github.io/RapiDoc/examples/markdown-headings.html

Headings are not clickable, however they can be anchored. for instance the above document can be linked to any of the H1 or H2 as 
https://mrin9.github.io/RapiDoc/examples/markdown-headings.html#tag--Employees--modifying-an-employee

> to check out at your end, you may pick the non-released build from `dist/rapidoc-min.js`
