### ISSUE TITLE
Having trouble running the test server locally with yarn: lit-html

### ISSUE THREAD

**Issue by amcgaw07** [mrin9/RapiDoc#426]
When I run yarn serve the server runs but displays this error throughout the screen when loaded with temp.yaml:

(part) => { if (!(part instanceof _lit_html_js__WEBPACK_IMPORTED_MODULE_1__["NodePart"])) { throw new Error('unsafeHTML can only be used in text bindings'); } const previousValue = previousValues.get(part); if (previousValue !== undefined && Object(_lib_parts_js__WEBPACK_IMPORTED_MODULE_0__["isPrimitive"])(value) && value === previousValue.value && part.value === previousValue.fragment) { return; } const template = document.createElement('template'); template.innerHTML = value; // innerHTML casts to string internally const fragment = document.importNode(template.content, true); part.setValue(fragment); previousValues.set(part, { value, fragment }); }

Seems like its caused by a duplicate of lit-html since it is included on its own, but also is included with lit-element.

**Comment by mrin9** [comment]
> Seems like its caused by a duplicate of lit-html since it is included on its own, but also is included with lit-element.

a separate lit-html package is needed as we use `unsafeHTML` directive which is not included with `lit-element` package
```
import { unsafeHTML } from 'lit-html/directives/unsafe-html';
```

however we are care full to use `litHtml` from `lit-element` package
