### ISSUE TITLE
Is there a Mobile Menu

### ISSUE THREAD

**Issue by tjperry07** [mrin9/RapiDoc#431]
Is there a mobile menu? I noticed it's responsive, but there isn't a way to navigate when the screen is smaller. Unless I missed some settings I need to enable. Using read view.

<img width="492" alt="Screen Shot 2021-03-04 at 3 23 09 PM" src="https://user-images.githubusercontent.com/5667652/110032278-91d29800-7cfd-11eb-9aed-5714fa40d625.png">

**Comment by mrin9** [comment]
It should provide you a compact view with menu on tablets. 
For phone's the experience is just like a webpage, which you can just scroll through.

Alternatively you can detect screen-size on your end and present a rendering style that suites best for your documentation, if it too much to scroll through, then go with a  `view` style for smaller screens and `read` style for desktops/tablets
