### ISSUE TITLE
Character decenders are cut off in model description field

### ISSUE THREAD

**Issue by dknoern** [mrin9/RapiDoc#433]
See image below.  The bottom of the `p` in `Description` is cut off.  This has to do with `overflow` the css:

```
.key-descr {
    font-family: var(--font-regular);
    color: var(--light-fg);
    flex-shrink: 1;
    text-overflow: ellipsis;
    overflow: hidden;
    display: none;
}
```

<img width="743" alt="Screen Shot 2021-03-09 at 7 51 24 PM" src="https://user-images.githubusercontent.com/161657/110574041-35aeb000-8111-11eb-93c6-3b4e2dc61669.png">

We are using Rapidoc for displaying a public API in our platform.  Our UX folks filed this as a bug for us.  We are not quite sure how best to fix it.  Since it shows in the RapiDoc examples is there a way to address it in source?  Perhaps the overflow parameter can be removed or changed to `visible`?

**Comment by mrin9** [comment]
Thanks for spotting the issue and recommending a solution, 
However, the solution you proposed will disturb other styles. 
We fixed it in an alternate way.

Let me know if it is taken care of.
to test it on your end pick up `dist/rapidoc-min.js` from this repo which is a latest but non-released build
