### ISSUE TITLE
newest update causes publicPath not supported in Chrome with documented example

### ISSUE THREAD

**Issue by tsoestini** [mrin9/RapiDoc#439]
According to the example at the bottom of https://mrin9.github.io/RapiDoc/examples.html , rapidoc is supposed to be invoked like this:
`<script type="module" src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>`

However, when actually clicking on the demo ( https://mrin9.github.io/RapiDoc/examples/example8.html ), it takes you to a page where rapidoc is invoked like this:
`<script type='text/javascript' src='../rapidoc-min.js'></script>`

With the old version of rapidoc-min.js (currently hosted on unpkg.com), you could invoke it with type="module" or type='text/javascript'.

With the latest update of rapidoc, it can only be invoked with type='text/javascript'. Invoking with type="module" causes this issue in Chrome:
![image](https://user-images.githubusercontent.com/70355397/110857837-2bee8f00-826e-11eb-8437-339e4207be4a.png)

Suggestions:
(a) revert change to new version, so it can be invoked either way or
(b) update docs to direct users to not use module.

**Comment by mrin9** [comment]
interesting, I was unable to create this issue on my end, even after changing it import as module.

However, I generated a new build, and changed `example1.html through example9.html` to use import as module.
Can you give  https://mrin9.github.io/RapiDoc/examples/example8.html another try from your end let me know whats happening ?

**Comment by tsoestini** [comment]
interesting... example8 now works for me again.

also, 2 hours ago, I had two files on my computer: index.html and index3.html, the latter with "module", but otherwise identical to the first. and only the first opened okay.

I didn't change anything, but now they both open okay, too.

Maybe rapidoc-min.js changed?

**Comment by mrin9** [comment]
may be, after some digging my search took me to this place https://stackoverflow.com/questions/64294706/webpack5-automatic-publicpath-is-not-supported-in-this-browser

and I updated our webpack config accordingly. But I cant say for sure if that fixed it, as I tested it before that fix and it worked with my setup.

But thanks for your time on this, Looks like its not an issue anymore on your end so closing it
