### ISSUE TITLE
Feature Request: Ability to load API Spec from local string

### ISSUE THREAD

**Issue by stephantabor** [mrin9/RapiDoc#44]
Right now, as far as I can tell, you have to load the API Spec from a remote URL. I have a use case where I need to create a UI that someone can load / edit / create their API Spec in my app. 

Is this a contribution you would accept? Or is there some other way to achieve this with the current implementation?

**Comment by mrin9** [comment]
apart from remote URL, you can also load local JSON files.
core focus of this package is to explore and try the APIs. 
A full fledged API editor will increase its overall bundle size

In my opinion you may create an API editor as a separate Web-Component and can use RapiDoc with in that to explore it. That way it will be more modular

**Comment by stephantabor** [comment]
Just to be clear, i'm not suggesting to bundle the editor into your component. The editor will live in my component/app, I just need to be able to load an api spec into it. Looking at the list of public attributes, and after trying a few things, I don't see how it would work currently. 

Can you give me an example of how this could work starting from this: 

```html
<rapi-doc id="rd"></rapi-doc>

<script>
    const rapiDoc = document.getElementById('rd');
    const apiSpec = {
        // ... api spec here
    };
    
    // now what?
</script>
```

**Comment by bohea** [comment]
@stephantabor  great idea, looking forward to this feature

**Comment by stephantabor** [comment]
So i tried to turn my local JSON into variations of file, blob, and url objects and load them into rapidoc that way, and couldn't get it to work. I have added a first pass of the functionality i need to rapi-doc. If you are interested in contribution I can clean it up and open a PR, otherwise we'll just maintain a fork.

**Comment by mrin9** [comment]
okay, I now get what you are looking for.
as of now there is no way to do this, but wont be difficult to provide it. 

The functionality is interesting, and I would be more than happy to take an PR. 
the way I envision it is to add couple of methods  (one for `json` and one for `yaml`)  to the component. 
the method should validate the `json/yaml` and then further validate the spec and finally render it.

**Comment by mrin9** [comment]
provided a method `loadSpec()` in release 5.1.0 which takes either a string (containing spec-url) or a spec defined in json object. 
checkout this [Example](https://github.com/mrin9/RapiDoc/blob/master/docs/example9.html) for the usage

Let me know if that takes care of your situation

**Comment by stephantabor** [comment]
@mrin9 thanks for adding it

**Comment by garretteklof** [comment]
Any plans to support the `yaml` format in loadSpec()?
