### ISSUE TITLE
allOf does not work, whereas anyOf works fine

### ISSUE THREAD

**Issue by ahmadnassri** [mrin9/RapiDoc#440]
### anyOf

![image](https://user-images.githubusercontent.com/183195/110870378-4cccd980-829a-11eb-8f61-7083263528e0.png)
![image](https://user-images.githubusercontent.com/183195/110870388-548c7e00-829a-11eb-95d6-71aeacb8239a.png)

### allOf

![image](https://user-images.githubusercontent.com/183195/110870408-6110d680-829a-11eb-9225-843878cb48ea.png)
![image](https://user-images.githubusercontent.com/183195/110870425-6b32d500-829a-11eb-8276-695f0fbcf13c.png)

**Comment by mrin9** [comment]
`ALL-OF` dictates that all the listed fields(properties) must be included in the schema which is what the rendering is trying to communicate 

Now from the schema def, here are the few assumptions I am making

- If the intention is Password should have either all lowercase letters or all uppercase letters then `ONE-OF` should be used
- If the intention is Password can have mix of uppercase or lowercase letters the use single field with  better pattern `[A-Za-z]`

If you are using `ALL-OF` or `ANY-OF` with more than one field, it indicates that the password is complex type and is made p of more than one field, which I am guessing is not the case.

Let me know, Incase there is anything else that you are expecting

**Comment by ahmadnassri** [comment]
> If the intention is Password can have mix of uppercase or lowercase letters the use single field with better pattern [A-Za-z]

yes this is the intention, but the provided screenshots are just an example, I know I can merge the regex, but the point here is mixing multiple type definitions under `allOf` is breaking the UI (and the example area)

**Comment by mrin9** [comment]
> since allOf is a json schema level directive, this should be working the same way, the UI should translate the requirements and present them as they are.

true, and thats how it is working, It is listing *ALL-OF* the fields thats needed , in this case 2 fields with different patterns
if you are expecting something else let me know
