### ISSUE TITLE
Provide style override capabilities

### ISSUE THREAD

**Issue by wparad** [mrin9/RapiDoc#449]
Perhaps I should start with: Do we really need to be using shadow roots to in this component? It makes a lot of things unnecessarily complicated, is there some massive value that I'm missing that it has to be a part of this?

----
And more to the explicit issue:
While I agree I don't care of the `stylesheet` injection (#362). The shadow roots are mess for overriding styles. I highly recommend to reject the notion that devs will build rapidoc just override the styles. Like me they'll complain and likely not use it. I'm at the moment really want to switch from swagger-ui, but can't because of the missing necessary styles.

For instance I need to fix this coloring because both backgrounds can't be the same:
![image](https://user-images.githubusercontent.com/5056218/112536951-639d2100-8dae-11eb-8521-7730d08e89b1.png)

And this isn't good:
![image](https://user-images.githubusercontent.com/5056218/112536968-68fa6b80-8dae-11eb-8e48-a525d088d5cb.png)

If there is even a bad way, having that suggestion would be really helpful.

**Comment by mrin9** [comment]
you dont have to build rapidoc just for styling. 

There are plenty of options  control styles, play around with various attributes to get to your desired 
 - attributes `theme, bg-color, text-color` and many more . read about it [here](https://mrin9.github.io/RapiDoc/api.html) 
 - css ::parts (is coming up in the next version, but you can play around with it by picking it from `dist/rapidoc-min.cs`). Read about it [here](https://mrin9.github.io/RapiDoc/css-parts.html)
 - css vars (is not officially supported or documented, but you can change them from your HTML

here is an example that will give you some ideas https://mrin9.github.io/RapiDoc/examples/themes.html#overview

let me know if it takes care of your situation

> Perhaps I should start with: Do we really need to be using shadow roots to in this component? It makes a lot of things unnecessarily complicated, is there some massive value that I'm missing that it has to be a part of this?

there are few thats unique with RapiDoc, for instance,  we support `<slots>`  that allows you to plugin HTML, CSS and even JS without any framework, checkout this issue #420 on how people may be using it to customize

**Comment by wparad** [comment]
> attributes theme, bg-color, text-color and many more . read about it here

Right, but that's not nearly enough.

> HTML elements under <api-request>, <api-response> <schema-tree> and <schema-table> cannot be targeted for styling

So here's really the problem. 

Also the css variables also don't work, while they allow styling of inside those elements they don't provide sufficient scoping to not also also change css of other components.

Perhaps it would be easier if I just said what I can't do. I want to change the background of the `model` element for a request body. How would you suggest I make that happen?

**Comment by mrin9** [comment]
> HTML elements under , and cannot be targeted for styling

the goal is to provide `css ::parts` access to child web components  too, you can checkout the generated html, we do export parts to top level element, however html specs and browser support around this isn't final/good at the moment.

until then, you need to build RapiDoc on your end and provide the styling, You wont be at a high risk of forking away from main and can keep it up-to date if you follow this way https://mrin9.github.io/RapiDoc/api.html#developers

**Comment by mrin9** [comment]
closing it ... I hope it answers your concerns

**Comment by yougotashovel** [comment]
Everything mentioned in this issue is still a problem (now in 2024).  I like what rapidoc offers, but the styling of shadow-root elements is significantly more complex than it needs to be.  Some things are completely inaccessible.

Even if the shadow dom allowed passing in a stylesheet so we can have full control of the styles like we do outside the shadow dom would be far more effective.

I'm at the point where i'll likely migrate away from Rapidoc if I can't find a solution for this.
