### ISSUE TITLE
multiple input type=file

### ISSUE THREAD

**Issue by cryzer12** [mrin9/RapiDoc#45]
Hi, I have a question, is it possible to use multiple input type = file? like in swagger?
![image](https://user-images.githubusercontent.com/29971756/62534693-61412880-b852-11e9-85a8-bdf48627da63.png)

**Comment by mrin9** [comment]
ok will give it a try. allow us a little time

**Comment by mrin9** [comment]
can you share a minimal spec to generate the above UI in swagger ?

**Comment by croudet** [comment]
Looks like Multiple File Upload using the same property name is  not working:
```
  /upload/receive-streaming-iterable:
    post:
      tags:
      - Upload
      operationId: streamingIterable
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  nullable: false
                  items:
                    type: string
                    format: binary
        required: true
      responses:
        default:
          description: streamingIterable default response
          content:
            text/plain:
              schema:
                type: string
```
Reference: 
- https://swagger.io/docs/specification/describing-request-body/file-upload/
- https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#considerations-for-file-uploads

```
requestBody:
  content:
    multipart/form-data:
      schema:
        properties:
          # The property name 'file' will be used for all files.
          file:
            type: array
            items:
              type: string
              format: binary
```

![Screen Shot 2019-11-27 at 15 30 37](https://user-images.githubusercontent.com/2042338/69757656-86241900-112b-11ea-9ced-62699983136c.png)

**Comment by mrin9** [comment]
this has been taken care in release `7.1.0`
example to demonstrate various ways to upload single/multiple files can be found here 
https://mrin9.github.io/RapiDoc/examples/file-upload.html
