### ISSUE TITLE
Default values for parameters are not populated

### ISSUE THREAD

**Issue by wparad** [mrin9/RapiDoc#451]
When there is a default value in the openapi spec, it isn't being auto populated in the resource paths:
![image](https://user-images.githubusercontent.com/5056218/112537320-d4dcd400-8dae-11eb-88db-56da6891ab2d.png)

It would be great to have that default value be the one populated into the input box.

Technically this is doable by having the spec updated on load using lodash

```js
import { cloneDeepWith } from 'lodash';

onSpecLoaded(data) {
      function updateTag(tag) {
        const picker = (value, key) => {
          if (!value || typeof value !== 'object') {
            return value;
          }

          if (Object.prototype.hasOwnProperty.call(value, 'default') && !value.example) {
            return Object.assign(value, { example: value.default });
          }

          return undefined;
        };
        return cloneDeepWith(tag, picker);
      }

      data.detail.tags = data.detail.tags.map(tag => updateTag(tag));
    }
```

**Comment by mrin9** [comment]
The behavior is intended and not a bug.
`Default` is the value that the API-Server will fill in, when it is empty, not what a client will provide. 

If you need to fill the inputs with some data use `example or examples` check out #397 for some context
