### ISSUE TITLE
Not responsive on mobile

### ISSUE THREAD

**Issue by wparad** [mrin9/RapiDoc#453]
While `md` screen sizes "work" `xs` and `sm` do not:

![image](https://user-images.githubusercontent.com/5056218/112540084-0e630e80-8db2-11eb-94b3-48c31a5a72a4.png)![image](https://user-images.githubusercontent.com/5056218/112540105-13c05900-8db2-11eb-9f00-0a5025c3d12f.png)

**Comment by mrin9** [comment]
Minimum form factor that we support in Table `768px` wide

> we do not have a critical mass for mobile usage, when that happens will revisit it

**Comment by mrin9** [comment]
Have updated our styles to support Mobile form factors. 
However, we are yet to certify it as it will need lot of testing with various spec models and form factors. 

We have initiated testing, its manual and will take time. Once done, will certify it.
But the code is already in at `dist/rapidoc.min.js`,  give it a spin to check if it works fine for your use case

34a74fdc92ae432fe96ac11310c0ec352335fca2
