### ISSUE TITLE
Input parameter fields are not correctly sized

### ISSUE THREAD

**Issue by wparad** [mrin9/RapiDoc#454]
On larger screens, the real estate here is not optimal. It would be better to move some of the elements around, potentially playing with flex-growth, so that these three rows are better aligned. Too much space for column three, not enough for column two.
![image](https://user-images.githubusercontent.com/5056218/112540866-fa6bdc80-8db2-11eb-9938-c4522dbb6fee.png)

**Comment by mrin9** [comment]
It is a table, and needs to be supported on various layout that RapiDoc provides, for instance in a `render-style=view` where request and response ore side by side.
But I agree there is a scope for improvement, I will be happy to take a PR and get them tested with various form-factors.

> Minimum form-fact that we support is Tablet (`768px` width)

**Comment by mrin9** [comment]
improved size distribution by making input-field column and constraint-column dynamic , instead of fixed width
fixed in 45b953a48b3c1ad84017e01a201476a1fd9acfe7
