### ISSUE TITLE
Accept */* spec-url

### ISSUE THREAD

**Issue by v1r** [mrin9/RapiDoc#457]
Hi there,

I there any reason why the content negotiation for the `spec-url` is set to JSON or YAML inclusively... Would it be possible to add `*/*`?

**Comment by mrin9** [comment]
To load and parse the spec we depend on https://github.com/swagger-api/swagger-js
which is the one responsible for making the http call to load the spec.

If thats something thats not working out for your case, you can load the spec yourself and provide the JSON object

```
 const objSpec = <load your own spec >
 const docEl = document.getElementById("thedoc");
 docEl.loadSpec(objSpec);
```

the other option would be to raise a issue with `swagger-client` package

**Comment by v1r** [comment]
@mrin9 Great! Thanks for the prompt response.
