### ISSUE TITLE
Invalid Spec URL causes blank screen

### ISSUE THREAD

**Issue by tsoestini** [mrin9/RapiDoc#459]
It used to be that if the Spec URL wasn't valid, RapiDoc would still load, and then you could type a spec URL or load a spec from a file for testing purposes (if you don't have a server around on your test machine).

Now, when the spec URL isn't valid, RapiDoc gives a blank screen with no URL input or load spec button.

To reproduce, visit https://mrin9.github.io/RapiDoc/examples/example100.html

Type an "x" for the spec URL and hit enter.

(Alternatively, set spec-url in the .html file to a URL that doesn't exist.)

**Comment by mrin9** [comment]
thanks for reporting.... will fix this soon
