### ISSUE TITLE
Question: Embeddable Endpoints

### ISSUE THREAD

**Issue by arunabh-wizeline** [mrin9/RapiDoc#463]
Hi,
We are considering RapiDoc as the default swagger spec solution for our Documentation Platform.
However, we are wondering if I can extract/reuse specific endpoints so that we can seamlessly integrate the **Try** feature within our static HTML reference site (non-swagger and source-markdown based).

**Comment by mrin9** [comment]
I am not sure if I am getting the ask correctly. RapiDoc is a function of OpenAPI spec. 

So if you need only specific end-points  then extract out those end-points into a separate spec and show them up in your html using `<rapi-doc>` element. You can have as many `<rapi-doc>` elements as you need and show them at places you need in your html, just like you show an `<img>` tag.

This is how micro-services with few endpoints uses RapiDoc.
For instance you can check out  https://www.northbricks.io/apis/  
check the html source, it uses many rapi-doc elements and each displaying few end-points
