### ISSUE TITLE
Callbacks not shown in render-style `view`

### ISSUE THREAD

**Issue by veeg** [mrin9/RapiDoc#464]
My preferred rendering style is side-by-side comparison of the request-response structure. Unfortunately, the information about callbacks are not reachable in the `view` render style. See screenshot.

Do you have any thoughts on the matter? My preferred solution would be a tabulated switch between request/callback in the left hand column.

![image](https://user-images.githubusercontent.com/3930971/114989646-e9852700-9e97-11eb-8d7f-9c74e82ccb2a.png)

**Comment by mrin9** [comment]
it should be working with the fix, 
test case is updated to have both the rendering styles https://mrin9.github.io/RapiDoc/examples/callback.html

**Comment by veeg** [comment]
Cheers for that swift resolution 🥳
