### ISSUE TITLE
Bookmarking link to a specific section

### ISSUE THREAD

**Issue by wsmelton** [mrin9/RapiDoc#465]
I have this Open API doc deployed that I'm testing RapiDoc with https://thycotic-ps/secretserver-apidoc

I'm not able to build out reference links to this site though from another document site I am using. If I link to a specific endpoint path for this spec such as https://thycotic-ps.github.io/secretserver-apidoc/#get-/secrets when the site loads it is only loading at the top of the spec file. 

When you go to that page the URL the page loads to this: https://thycotic-ps.github.io/secretserver-apidoc/#post-/activations and will never go to the source link that was provided. **Is there an adjustment I can make to the HTML attributes that will let direct links load properly?**

```html
<!doctype html> <!-- Important: must specify -->
<html>
  <title>Secret Server Open API Spec: 10.9.64</title>
  <link rel="shortcut icon" type="image/jpg" href="favicon.ico"/>
  <head>
    <meta charset="utf-8"> <!-- Important: rapi-doc uses utf8 charecters -->
    <script type="module" src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>
  </head>
  <body>
    <rapi-doc spec-url = "openapi.json" id="ssapidoc" allow-authentication="false" show-info="false" show-header="false" allow-search="false" allow-advanced-search="true"
              allow-try="false" allow-server-selection="false" render-style="read" schema-style="table" use-path-in-nav-bar="true"
              primary-color="#80BB01" bg-color="#FFFFFF" nav-bg-color="#081F2C" nav-hover-bg-color="#636F79" nav-hover-text-color="#3CC4E5" default-schema-tab="example">
    </rapi-doc>
  </body>
</html>
```

**Comment by wsmelton** [comment]
Figured out this is due to GitHub Pages that is hosting the site. It requires having the header added because of the way GitHub is rendering the site.

**Comment by mrin9** [comment]
I will look into this issues, 
I am guessing it is due to the fact that we are trying to goto a location while the spec is not yet rendered. 
It will work once it is fully rendered, to test it after the spec is loaded just change the location-hash on the address bar and see if it takes you to the desired location.

I will look into this in few days to see how best can we address this.

> On a side note, I think you are not specifying the `theme` attribute for the RapiDoc element, in that case it will use the default based on the OS settings. In my case, my OS is set to dark theme and this is how it appears  

![image](https://user-images.githubusercontent.com/5056899/115157904-8256a680-a040-11eb-9a3f-d785a1ea2883.png)

so suggest to not depend on default theme, and specify one that suites ur need

**Comment by wsmelton** [comment]
Yes, once the page loads I did find the link directly to a tag out endpoint would load.

**Comment by mrin9** [comment]
You will be better with `render-style = 'focused'` if you want to land  directly on a operation
`render-style=read` is not that well supported for this, It is coz the left-nav and the main-content watch each other to be in sync. If you add a third variable using location-hash to control your scroll-position it will be ignored

**Comment by mrin9** [comment]
For now you may use `render-style = 'focused'` to land  directly on a operation

will provide a fix for `render-style='read'` soon

**Comment by wsmelton** [comment]
I did try with a test site for using `focused` and all that did was load the page without changing the URL but it stays at the top of the page. I'm using Edge chromium build as my primary browser but I get this same result using Chrome as well.

https://wsmelton.github.io/test-rapidoc/#get-/nodes/-nodeId-/configuration

Once the page loads and I go to the URL field again and hit enter then it will jump to that section.

https://github.com/wsmelton/test-rapidoc/blob/main/index.html

```html
    <rapi-doc spec-url = "swagger.json" id="ssapidoc" allow-authentication="false" show-info="false" show-header="false" allow-search="false" allow-advanced-search="true"
              allow-try="false" allow-server-selection="false" render-style="focused" theme="light" schema-style="table" use-path-in-nav-bar="true"
              primary-color="#80BB01" bg-color="#FFFFFF" nav-bg-color="#081F2C" nav-hover-bg-color="#636F79" nav-hover-text-color="#3CC4E5" default-schema-tab="example">
    </rapi-doc>
```

**Comment by richardanaya** [comment]
Thank you, I encountered. this tonight as well!

**Comment by mrin9** [comment]
tested with a large spec to land directly to a operation works 

you can try the below url
https://mrin9.github.io/RapiDoc/tests/perf-v3-read.html#post-/v1/creditmemos/-creditMemoId-/pdfs
