### ISSUE TITLE
New custom event on section displayed change

### ISSUE THREAD

**Issue by acharlop** [mrin9/RapiDoc#469]
First off thanks for an awesome lib.

I'm looking to record some analytics about what api's are being looked at the most. Since most places in the lib uses `window.history.replaceState` subscribing to `hashchange` event doesn't seem to work as expected. Using a mutation observer has to observe a little to high up the tree since the child of `.operations-root` gets replaced completely.

I was wondering if you had any other ideas or if you would you be open to a new custom event? I'm happy to put in a PR 🙏

**Comment by mrin9** [comment]
with `render-style` as  `view` and `focused` it makes sense as user must click to navigate to an operation.
but I am not so sure with  `render-style=read` coz, if I want to jump from operation 1 to operation 9, I may just scroll through and it will register every operation as visited ?

How about this, providing an option to select a  desired routing style `replaceState` or  `pushState`.  and from there you may watch for changes ?
