### ISSUE TITLE
Not showing schemas (regression introduced in 8.4.5)

### ISSUE THREAD

**Issue by JonasGroeger** [mrin9/RapiDoc#472]
Hey!

Using the [PetStore OpenAPI v3 Spec](https://petstore3.swagger.io/api/v3/openapi.json) in Version v8.4.4 we can click on
![image](https://user-images.githubusercontent.com/1790638/117844378-ebb48880-b27f-11eb-90b9-ddb941924f71.png)

and be taken to the Order 
![image](https://user-images.githubusercontent.com/1790638/117844429-f707b400-b27f-11eb-969b-204c6f1b7e23.png)

In all subsequent versions of RapiDoc when clicking on the `Order` in the first screenshot, we are not taken to the `Order` in the right view. This is because its not rendered on the right:

![image](https://user-images.githubusercontent.com/1790638/117844992-7301fc00-b280-11eb-98fb-a8740a63b221.png)

Since 8.4.4 does not have this issue but 8.4.5 has, I guess it was introduced somewhere inbetween.

**Comment by mrin9** [comment]
After a little bit of digging.
This was an intended change but was not suppose to get into `8.4.5` it was suppose to be a part of `9.0.0` which we reserved for introducing all the breaking changes. This may also be the reason I missed to mention it in the release notes

However, `show-components = 'true'` is available only in `render-style = 'focused'`. 
This was done to improve rendering performance in `read` mode. 
This isnt an issue for medium or small size spec but effects large spec, 

Some users will open it up in read mode without much of a thought on rendering speed which resulted in many support calls so like to discourage this practice.

sorry if that caused an inconvenience. but our recommendation is to move to `focused` mode  if that works for your use case.

**Comment by JonasGroeger** [comment]
> However, `show-components = 'true'` is available only in `render-style = 'focused'`.
> This was done to improve rendering performance in `read` mode.
> This isnt an issue for medium or small size spec but effects large spec,
Reasonable.

> sorry if that caused an inconvenience. but our recommendation is to move to `focused` mode if that works for your use case.
No worries. We had a working workaround. Switching to `render-style = 'focused'` did the trick with `9.0.0`.

Thanks!
