### ISSUE TITLE
focus mode do not scroll to top

### ISSUE THREAD

**Issue by MortenHofft** [mrin9/RapiDoc#473]
What a nice project - thank you.

I suppose this is a matter of preference, but think it would be preferable if the the view scrolled to the top when changing path in focused render style.

The behaviour can be seen in [this example](https://mrin9.github.io/RapiDoc/examples/focused-mode.html#post-/pet) when changing between e.g. "Update an existing pet" and "Add a new pet to the store" (make sure to scroll down before changing)

I can get it working locally by changing this line https://github.com/mrin9/RapiDoc/blob/master/src/rapidoc.js#L855
```
// from 
if (this.renderStyle === 'read' || elementId.startsWith('overview') || elementId.startsWith('tag--')) {
// to 
if (this.renderStyle === 'focused' || this.renderStyle === 'read' || elementId.startsWith('overview') || elementId.startsWith('tag--')) {
```

**Comment by mrin9** [comment]
Thanks for the dig, If you like to submit a PR, I can get it reviewed and to the codebase, else will do it myself  soon
