### ISSUE TITLE
Disable Custom Webkit Scrollbar Styling

### ISSUE THREAD

**Issue by Larkenx** [mrin9/RapiDoc#474]
The default webkit scrollbar styling really clashes with the default system scrollbars of our website and I've tried a number of methods to override the scrollbar styling. We're using React and pulling this in as a web component into our own react component. I tried doing the following:

```css
// index.css

::-webkit-scrollbar {
  width: 0px !important;
}

.nav-scroll::-webkit-scrollbar {
  width: 0px !important;
}
```

```jsx
<rapi-doc
    theme="light"
    use-path-in-nav-bar="false"
    render-style="read"
    allow-spec-url-load="false"
    allow-spec-file-load="false"
    allow-search="false"
    allow-advanced-search="false"
    show-header="false"
    schema-style="table"
    id="rapidoc"
    bg-color={theme.palette.background.paper}
    text-color={theme.palette.text.primary}
    primary-color={theme.palette.primary.light}
    regular-font={theme.typography.fontFamily}
    header-color={theme.palette.background.default}
    nav-accent-color={theme.palette.primary.dark}
    nav-item-spacing={'relaxed'}
    nav-text-color={theme.palette.text.primary}
    nav-bg-color={theme.palette.background.paper}
    style={{
        width: '100%',
        height: 'calc(100vh - 64px)',
        overflowY: 'scroll',
        '::-webkit-scrollbar': { width: 0 }
    }}
/>
```

If possible, I'd really like to override these styles in-line or with my own CSS rather than building rapidoc from scratch

**Comment by mrin9** [comment]
we style the scrollbars based on the theme colors. and there are multiple location where scrollbars are applied.
- scroll for navigation bar
- scroll for text-area

from the code you posted it seems like you are trying to apply scroll style to the web-component itself. If thats the case then
- we do not apply any scrollbar or other styling to the web-component, thats for the user to style it
- you cannon apply a `pseudo` css classes with in-line styles. Try to give it a css class and then use the class to apply scroll styles

**Comment by mrin9** [comment]
we style the scrollbars based on the theme colors. and there are multiple location where scrollbars are applied.
- scroll for navigation bar
- scroll for text-area

from the code you posted it is not clear to what element you are trying to apply the scroll style ?
to the web-component itself or `.nav-scroll`

Here are the few things to note
- we do not apply any scrollbar or other styling to the web-component, thats for the user to style it
- you cannot apply a `pseudo` css classes with in-line styles. Try to give the web-component  a css class and then use the class to apply scroll styles 
- if the intent is to style one of the sub element inside  `<rapi-doc>`, then there are restrictions as they are internal to `rapidoc`
w.r.t `nav-scroll` css ,  the scrollbar colors are  styled  according to the selected theme/color options chosen by the user. If the requirement is just to change the width of the scroll bar, I can expose it as a `css var` that can be modified outside of the web-component, but rest of the style elements will still be restricted.

let me know

**Comment by Larkenx** [comment]
the intent is just to completely remove the custom scrollbar styling altogether for us

**Comment by mrin9** [comment]
use css var `scroll-bar-width` to set the width of the scroll bar
