### ISSUE TITLE
Rendering schema examples with `value` key (not stripping it)

### ISSUE THREAD

**Issue by JonasGroeger** [mrin9/RapiDoc#475]
According to the [samples section of the OpenAPI spec](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#fixed-fields-16), schema examples must be defined with the root key being `value`, i.e.:

```
{
  "value": {
    "name": "Toby",
    "kind": "human"
  }
}
```

The Examples section renders this example without stripping the value. It should:

```

{ 
  "name": "Toby",
  "kind": "human"
}
```

Otherwise its confusing for readers of a spec.

**Comment by mrin9** [comment]
thanks for reporting, will check on it soon

**Comment by mrin9** [comment]
I am unable to recreate this issue. 
Here is the example that I am using https://mrin9.github.io/RapiDoc/examples/examples-multiple.html
and the spec for it is https://github.com/mrin9/RapiDoc/blob/master/docs/specs/examples.yaml

it wont show the `value` field .
can you provide with a small spec that shows this behavior

**Comment by JonasGroeger** [comment]
The example you provided does not have any examples under

    components:
      examples:
        MyExample:
          value:
            ...

**Comment by mrin9** [comment]
it shouldn't matter if the examples are inlined or defined under `components` section for reusability
the spec I shared uses inlined examples and works as expected 
https://github.com/mrin9/RapiDoc/blob/master/docs/specs/examples.yaml#L17-L21

If it is not working for examples defined under components, then I would like to check how you are referring them. So if possible provide a spec which I can work with to create this issue on my end

**Comment by JonasGroeger** [comment]
Here is a spec that does not work (IMO) as expected:

* [Spec](https://gist.githubusercontent.com/JonasGroeger/cc98c2d4f532ed7dc307d26a897f85e4/raw/9de09e70a7d19c936009be39e661df4b07f97aeb/f.yml)
* Embed Code
```
    <rapi-doc
        spec-url = "https://gist.githubusercontent.com/JonasGroeger/cc98c2d4f532ed7dc307d26a897f85e4/raw/9de09e70a7d19c936009be39e661df4b07f97aeb/f.yml"
        render-style = "focused"
        show-components = "true"
    ></rapi-doc>```
* Actual: 
![image](https://user-images.githubusercontent.com/1790638/119337497-30ccb780-bc8f-11eb-9222-fb6868b3b983.png)
* Expected: 
![image](https://user-images.githubusercontent.com/1790638/119337668-670a3700-bc8f-11eb-9090-d9e68cbd569d.png)

**Comment by mrin9** [comment]
I see what you mean now.
You were referring to **Examples** section under  **Components** and I was looking in the **EXAMPLE** tab besides the **SCHEMA**  tab

Well, the intention of Component section in RapiDoc is to show the component definition as is , be it example, schema or any other component. The section is more focused for troubleshooting, analysis etc as in many cases the documentation is auto generated using a tool and there are people who who are interested in looking at these definition as is

When these components defs are rendered in the documentation(Operations) section, we apply the rendering rules. 

So if you check out the example tab in you documentation you will have it rendered as you are expecting it to be

let me know if it make things clear

**Comment by JonasGroeger** [comment]
Looking at the source code of rapidoc I also thought to myself: this is expected behaviour :) Thanks for clearing that up.
