### ISSUE TITLE
Default example for UUID type

### ISSUE THREAD

**Issue by abrari** [mrin9/RapiDoc#476]
RapiDoc version 9.0.0 renders default example for UUID format as `"uuid"`. It should render a better representation, for example all-zeros UUID or a random UUID (like swagger-ui does). UUID format is described as an example [in the specs](https://swagger.io/docs/specification/data-models/data-types/), so I think it is necessary for RapiDoc to support it.

**Comment by mrin9** [comment]
yep, I think we have room for improvement here, will check on this soon
