### ISSUE TITLE
show / hide depending on server selected

### ISSUE THREAD

**Issue by douglasduartetb** [mrin9/RapiDoc#479]
Hi, thanks for the great lib!!

My probem: I want to hide some apis from **cliente** server, and show just when local is selected (server.url === "http://localhost").

```
{
    "openapi": "3.0.0",
    "servers": [ {
        "description": "cliente",
        "url": "https://{url}/api/v3",
        "variables": {
            "url": {
                "default": "",
                "description": "A url base do cliente deve vir aqui"
            }
        }
    }, {
        "description": "local",
        "url": "http://localhost/api/v3"
    }]
}
```

Is it possible?

**Comment by mrin9** [comment]
I dont think thats possible for now. 
However we are going to introduce few options/events  shortly which may help your use case

Following are the new things to come
- `api-server-change` event 
- `match-paths` attribute to programmatically filter (hide) paths *( this feature is available in the latest beta but not yet officially introduced )*

Once the above options are introduced you can use  `api-server-change` event  and change the `match-paths` attribute accordingly to filter out things.

**Comment by douglasduartetb** [comment]
Awesome, possibly can solve!
