### ISSUE TITLE
api server not changing when loading new spec 

### ISSUE THREAD

**Issue by jwigankow** [mrin9/RapiDoc#481]
When loading a new spec file the API server stays the same as the first selected. I would expect the API server to be newly selected. In case API Server selection is disabled there is no way to change it to something that works.

Steps for reproduction:

1. go to https://mrin9.github.io/RapiDoc/examples/example2.html
2. enter ```https://rackerlabs.github.io/wadl2swagger/openstack/swagger/identity-admin.yaml``` and load it
3. the selected API Server still is ```https://petstore.swagger.io/v2``` instead of ```https://mrin9.github.io``` (the only one in that file)

The same happends when using the `loadSpec()` javascript API.

**Comment by mrin9** [comment]
thanks for reporting - it should be fixed now
