### ISSUE TITLE
Display scope for security schemes other than OAuth

### ISSUE THREAD

**Issue by lafrech** [mrin9/RapiDoc#482]
Hi.

_First of all, thanks for RapiDoc. It looks pretty neat and very promising. I discovered it yesterday and already added it to the REST API framework I maintain: https://github.com/marshmallow-code/flask-smorest and adopted it for our application._

AFAIU, OpenAPI 3.1.0 allows scopes to be defined for security schemes other than OAuth:
- https://github.com/OAI/OpenAPI-Specification/issues/1366
- https://github.com/OAI/OpenAPI-Specification/pull/1829

When I set `{"BasicAuthentication": ["admin"]}` in an endpoint, I expect "admin" to be displayed somewhere close to the "HTTP Basic" label, as in #422 but not for OAuth.

It doesn't seem to be the case so either I screwed up somewhere, either this is a feature request.

**Comment by mrin9** [comment]
Is a feature thats missing, will add it to our queue. 
We have comeback from a summer break and consolidating our work, so expect some delay gere

**Comment by lafrech** [comment]
Good. I hope you had a great time. No rush. Thanks for RapiDoc.

**Comment by lafrech** [comment]
Hi, just tested it and it works like a charm.

I kinda wish it would appear without hovering but it's nice to have it already.

Thanks again for RapiDoc. Have a nice day.
