### ISSUE TITLE
"format: date-time" with examples displays wrong format and time

### ISSUE THREAD

**Issue by jwigankow** [mrin9/RapiDoc#489]
Displaying `date-time` format is broken for examples. When setting the example value to `2021-01-02T14:00:03.753Z` the value displayed will be `Fri Jun 04 2021 11:07:32 GMT+0200 (Mitteleuropäische Sommerzeit)` (or whatever is the time you are loading the spec).

There are 2 problems here:

1. "format: date-time" is part of the openapi specification and should always be in the rfc3339 format
2. The time from the example is ignored. The time displayed is always the time of loading the spec.

steps for reproduction:

1. go to https://mrin9.github.io/RapiDoc/examples/example2.html
2. load spec from https://gist.githubusercontent.com/jwigankow/3ae7c9cabf3674de76c472dd94495a80/raw/6cb099c8e29b67cfc098d1d8b59675348483254a/openapi.yaml
3. open examples in GET /example

**Comment by mrin9** [comment]
> "format: date-time" is part of the openapi specification and should always be in the rfc3339 format

It works as expected, Only in the case when an example is not provided by the spec author, if an example is provided it attempts to uses the one thats provided 

> The time from the example is ignored. The time displayed is always the time of loading the spec.

When an example is provided by a spec-author then it must adhere to the `data-type` and `format` defined by the schema, if not it will behave in different  ways depending on various data-types, format and inputs. 
In your case the data-type is `string` and the examples contains a non-string value. Try enclosing the date values in quotes and it should work
