### ISSUE TITLE
Feature Request: Add support for Open Api 3.0 schema-combining keywords - oneOf, allOf, etc

### ISSUE THREAD

**Issue by leorush** [mrin9/RapiDoc#49]
This is feature that ReDoc famous for (plus dicriminator support)
If it will be added - that'll be a bye-bye for ReDoc
Here is link to swagger official site:
https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

**Comment by mrin9** [comment]
support for `allOf` exist. `

however, 'anyOf` and `oneOf` will need us to redesign a bit of UI. This would take a little time to arrive

**Comment by mrin9** [comment]
Support for `all-of, one-of and any-of` is provided in release `5.2.0`
check it out in action 
[all-of](https://mrin9.github.io/RapiDoc/examples/allof.html) 
[one-of](https://mrin9.github.io/RapiDoc/examples/oneof.html) 
[any-of](https://mrin9.github.io/RapiDoc/examples/anyof.html)

**Comment by leorush** [comment]
Thank you! 
But it wont work for me. Maybe because they are nested?
Here an example 
[openapi-client-generated.zip](https://github.com/mrin9/RapiDoc/files/3626147/openapi-client-generated.zip)

Also on swaggerhub https://app.swaggerhub.com/apis/leorush/testtw/1

**Comment by mrin9** [comment]
Thanks for sharing  the spec. will work on it further to check what went wrong

**Comment by mrin9** [comment]
can you confirm if the release `5.2.2` takes care of you issue ?
you can checkout running with the above spec that you attached above [here](https://mrin9.github.io/RapiDoc/tests/nested-allof-and-oneof.html)

**Comment by leorush** [comment]
Yes! Now everything works fine!
Thank you vary much!!!
