### ISSUE TITLE
Feature Request - If there is no security scheme defined, do not allow users to make a request.

### ISSUE THREAD

**Issue by tjperry07** [mrin9/RapiDoc#490]
If there is no security scheme defined, do not allow users to make a request.

Currently, if there is no security scheme defined on an endpoint, it still shows the Try button, which lets users return an error. 

Can the Try button either be totally hidden
OR
When they hit Try we just return the curl example. 

Either way, we do not attempt to make a request without a security scheme defined.

**Comment by mrin9** [comment]
`security scheme` is optional in an openapi spec, also it is a very much the case during development of an API where security is not yet defined.

the other reason for not doing so,  coz rapi-doc is also used for testing negative cases, like how would the API behave if a security is not provided.  Therefore providing a TRY functionality becomes important to test out those situations

For your case, there is a `spec-loaded` event which provides you with the spec as a json object thats loaded. You can inspect this object and change the `allow-try`  attribute accordingly

**Comment by tjperry07** [comment]
Oh! That is a great suggestion! Thanks!
