### ISSUE TITLE
Add more general binary formats and allow supplying custom ones

### ISSUE THREAD

**Issue by xSAVIKx** [mrin9/RapiDoc#491]
It looks like the known binary content types are pretty limited and are not covered by the used Regex.

E.g. none of the new MS Office formats (based on open XML formats) will work. It may be not critical for most, but we have to provide a clear separation of downloadable responses via the content type.

It'd be great if RapiDoc provides an API to register custom known binary content types. This will in fact cover all possible combinations/usages for a lot of different cases.

**Comment by wparad** [comment]
What does registering a known content type mean?

**Comment by xSAVIKx** [comment]
E.g. I have an MS Excel 2010 which has content-type `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`. I'd like to be able to configure RapiDoc, so that it triggers such content type as `binary`.

**Comment by mrin9** [comment]
>  I'd say that the ideal way would be to just treat binary OpenAPI format as binary in RapiDoc

what do you mean by `binary OpenAPI format` ?

**Comment by xSAVIKx** [comment]
> > I'd say that the ideal way would be to just treat binary OpenAPI format as binary in RapiDoc
> 
> what do you mean by `binary OpenAPI format` ?

OpenAPI 3 specifies `binary` string format: https://swagger.io/docs/specification/data-models/data-types/#file

**Comment by mrin9** [comment]
What I understand from the discussion is that you like to have a download button for the entire response. 

and the binary format that you are referring is a field level detail. 
that is to say in a response schema you can have two fields one is integer and another is binary now how this can result into a single download button for the entire schema ? are you suggesting we download two files one containing integer value and another the binary file ?

It is best that we decide it based on `content-type`

The situation you are explaining is good for uploading files using `form-data` 
for reference you can check out this example where we use `format=binary`  for file upload
https://mrin9.github.io/RapiDoc/examples/file-upload.html#post-/upload-multiple-file

**Comment by xSAVIKx** [comment]
I guess you're right about the schema, but here is a perfectly valid response:

```
responses:
  200:
    content:
      application/vnd.ms-excel:
        schema:
          type: string
          format: binary
```

I agree that if we have 2 fields there's no way to determine what to do with the response. And, as in my original issue, I guess it would be perfectly fine if we'll just be able to supply a custom `content-type`.
