### ISSUE TITLE
How to programmatically change the default checked status of api scopes and pkce

### ISSUE THREAD

**Issue by davidovich** [mrin9/RapiDoc#493]
Is it possible to activate oauth scopes programmatically ? I would like to have the scopes enabled by default when I load rapidoc.

Also, in the same manner, I would like disabling the pkce checkbox. 

x-client-id and x-client-secret were added to programmatically set the security scheme, I am wondering if scopes could be managed in a similar manner, so that the radios are active - inactive.

Thanks for this wonderful project!

NOTE: I have limited HTML knowledge, but I found out that a simple getElementById('oauth2-pkce') would not work as it is part of the shadowDom. Is there  a way to interact with the shadowDOM and achieve what I want ?

**Comment by mrin9** [comment]
so you need a programatic way to toggle the scopes and `PKCE` ?

**Comment by davidovich** [comment]
@mrin9 yes, as the clients will need to toggle that anyway, and the backend needs three scopes, but does not support `pkce`. So that means five clicks (3 scopes, 1 pkce, and 1 auth button). The `x-client-id` and `x-client-secret` are already injected programatically thanks to you!

**Comment by mrin9** [comment]
I think you should get a token urself using client-id/secret and desired scope and once you get it you can apply this token using a method.

On how to apply a token, you may checkout this example https://mrin9.github.io/RapiDoc/examples/auth.html#operations-top
