### ISSUE TITLE
Links in navbar overwrite url

### ISSUE THREAD

**Issue by Avocher** [mrin9/RapiDoc#496]
Hi,

If the rapidoc component isn't visualized at the url base it will overwrite the url due to: 
https://github.com/mrin9/RapiDoc/blob/50518f69ff8eaac0686032aa3894f3402abe3ab2/src/rapidoc.js#L873

As an example: I put the rapidoc component under the path `/help/api-docs`. Clicking a link will replace the url with `/#some-anchor`.

It would be nice if the component would only replace the hash.

**Comment by mrin9** [comment]
isnt it replacing the hash only ?

for example take the below example, clicking on the links will only change the hash 
https://mrin9.github.io/RapiDoc/examples/focused-mode.html

what do you mean by 
*If the rapidoc component isn't visualized at the url base* ?

**Comment by Avocher** [comment]
I was refering to having the component on a url that didn't match the url defined here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base. As I had `<base href="/">` in my app it wasn't working as I expected. But now that I've looked more closely at the spec, this is how it should work. Sorry for the inconvenience.
