### ISSUE TITLE
API Key not set in header when authorization set in OpenAPI

### ISSUE THREAD

**Issue by kkieffer** [mrin9/RapiDoc#497]
Hi, first off, this is a great library. I am having trouble however setting the API Key when the authorization settings comes from the OpenAPI spec.  In Spring Boot I have:

```
     SecurityScheme secScheme = new SecurityScheme().type(SecurityScheme.Type.APIKEY)
                                                       .in(SecurityScheme.In.HEADER)
                                                       .name("x-api-key")
                                                       .scheme("x-api-key");

        return new OpenAPI()
              .info(new Info().title("My API")
                              .description("My sample application")
                              .version(1.0.0))
             .components(new Components().addSecuritySchemes("x-api-key", secScheme));
```

This produces the RapiDoc auth section, entering the key then appears as if the key has been applied:

<img width="681" alt="image" src="https://user-images.githubusercontent.com/33581862/121783126-f57d2480-cb7a-11eb-94a3-f63dbe87fb72.png">

However the Rapidoc section for each method shows no authentication applied (and the try always fails for lack of auth):

<img width="250" alt="image" src="https://user-images.githubusercontent.com/33581862/121783148-1a719780-cb7b-11eb-99b6-5d7bce7e4ea9.png">

**Note: I have been able to get this to work** only when providing the 3 api-key properties in the react element as follows:

        api-key-name="x-api-key"
        api-key-location="header"
        api-key-value="-" 

_However_ this still is a bit buggy because the first time you enter the key, it appears like the key is set, but again the method section shows no authentication applied.  The only way I could get it to work was to the press CLEAR ALL API KEYS then re-enter the key a second time.  Then it works.

**Comment by mrin9** [comment]
can you provide me with a small spec where you can recreate this issue ?

**Comment by kkieffer** [comment]
Here is how I define a particular REST method:

    static final String APIKEY = "x-api-key";
        
    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.PARAMETER)
    @Parameter(hidden = true) 
    public @interface ApiKey {}
 
    ....


    @GetMapping("/api/any/given/rest/path") 
    public String getSomething(@ApiKey @RequestHeader(APIKEY) String apiKey) {
          ......
    }

If I use this template for the Rest Methods, along with these params in the React element

    api-key-name="x-api-key"
    api-key-location="header"
    api-key-value="-" 

I see this in the Rapidoc auth section

<img width="780" alt="image" src="https://user-images.githubusercontent.com/33581862/129503113-0ef12d8c-7ad0-4aa0-8467-1c50cf9370e8.png">

Yet in the documentation each method shows:

<img width="241" alt="image" src="https://user-images.githubusercontent.com/33581862/129503151-830101e9-1035-45b6-af67-0a90f04649ef.png">

**Comment by mrin9** [comment]
I wont be able to comment by looking at the code you shared. There are many languages and many frameworks which generates openAPI spec from annotations or by other means. You need to share the generated spec from those annotations for me to comment anything.

still if i have to comment, I can say that below is not how you apply security to an end-point. You are just stating that the it has a HEADER PARAM. So I would advice you to research on how to apply security to end-points using the framework that ypu are using.
 
```
@GetMapping("/api/any/given/rest/path") 
public String getSomething(@ApiKey @RequestHeader(APIKEY) String apiKey) {
      ......
}
```

This issue is not RapiDoc's issue, therefore closing it

**Comment by kkieffer** [comment]
Sorry, it was generated by spring doc. So here's the generated open-api doc:

`
{"openapi":"3.0.1","info":{ ......... "securitySchemes":{"x-api-key":{"type":"apiKey","name":"x-api-key","in":"header","scheme":"x-api-key"}}}}`

And in React:

```
<rapi-doc
        spec-url = "/v3/api-docs"
        render-style = "focused"
        show-header="false"
         allow-server-selection="false"
         schema-style = "table"
          theme="light"
          nav-bg-color="#F2F2F2"
          api-key-name="x-api-key"
          api-key-location="header"
          api-key-value="-"
          schema-description-expanded="true"/>          
```
