### ISSUE TITLE
Add a demo page

### ISSUE THREAD

**Issue by Qwertie-** [mrin9/RapiDoc#5]
Would be great to see a demo of how it looks/works before setting it up.

**Comment by mrin9** [comment]
@Qwertie-  there are 8 demos at present all of them are specified [here](https://mrin9.github.io/RapiDoc/)

below i am providing few links for quick access
 - [Basic Demo](https://mrin9.github.io/RapiDoc/example1.html)
 - [Dark Theme demo](https://mrin9.github.io/RapiDoc/example2.html)
 - [Integrate with other html doc demo](https://mrin9.github.io/RapiDoc/example4.html)
 - [Use JavaScript change attribute demo ](https://mrin9.github.io/RapiDoc/example100.html)

Can you provide me a feedback about why you missed to see the demo links? this may be the case with others too and I would like to address that

**Comment by Qwertie-** [comment]
Ah I did see the demo section on the website but I did not notice the headers were links. I know its not particularly trendy in modern web design but if they were underlined I would have seen the links for sure.

**Comment by jakul** [comment]
+1

I didn't realise these headers were links either!

![image](https://user-images.githubusercontent.com/862794/52941163-12650c80-3360-11e9-9916-81af2847077f.png)

**Comment by mrin9** [comment]
Thanks for the feedback, even to me it doesn't look like links. 
I am using a default template that GitHub provides for documentation. But let me do something so that they look like links. 
Just wanted to make sure, was it due to not scrolling enough to reach the demos or coz they dont appear like an link

**Comment by Qwertie-** [comment]
@mrin9 I saw the demo section but I assumed it was just help for setting it up. Did not notice the text was a link.

**Comment by mrin9** [comment]
updated the documentation, to make it little more clear about the demos
Closing this issue.
