### ISSUE TITLE
Unable to set blank password for basic authentication.

### ISSUE THREAD

**Issue by tjperry07** [mrin9/RapiDoc#500]
Our Basic auth takes an `access_token` in the username and then a blank password. Currently, it requires a password. Which means multiple endpoints can't be used from the documentation page.

<img width="923" alt="Screen Shot 2021-06-03 at 3 09 33 PM" src="https://user-images.githubusercontent.com/5667652/120705668-bca7c600-c47d-11eb-8219-0274c9634de1.png">

_Originally posted by @tjperry07 in https://github.com/mrin9/RapiDoc/discussions/488_

**Comment by mrin9** [comment]
I will look into this one. Expect a little delay as we are catching up on our issues after the summer break

**Comment by tjperry07** [comment]
No worries. Everyone needs break time. 🌴
