### ISSUE TITLE
Doesn't behave well when using React HashRouter

### ISSUE THREAD

**Issue by vinchess** [mrin9/RapiDoc#503]
So i was creating a react app which is built and deployed together with Spring Boot.

I was using HashRouter to get around the White Label error when trying to navigate to different route, refresh or manually typing in the url. but with the HashRouter i notice RapiDoc replaces everything after the 1st instance of the hash. This will break the url and hitting refresh will break the routing and it will not be able to find where it was last at.

For example if i had `localhost:3000/#/documentation/PetStore/` ideally i was hoping to get `localhost:3000/#/documentation/PetStore/put-pet` or something similar, instead it changed the definition to `localhost:3000/#put-pet`.

Wondering if this could be a 'flag' type feature or option to provide a prefix or maybe a workaround?
Hoping someone who came across this behaviour could give some insights.

**Comment by mrin9** [comment]
We can add an option to provide a `route-prefix`
or can also  provide an option to not make any changes to the route 
I have included this on internal feature-request list, however we are on a break till the end of july, and work on it soon after that

**Comment by ChrisBarriere** [comment]
I think this option is really mandatory.
I try to integrate RapiDoc in a VueJs SPA app with vue-router.
All routes are broken because there's no route-prefix.

and really, thanks for your wonderful work

**Comment by mrin9** [comment]
you can now 
- disable routing `update-route = true | false`
- provide custom prefixes to routes `route-prefix`

read more about it here https://mrin9.github.io/RapiDoc/api.html#general
