### ISSUE TITLE
Disable main section scrolling when scroll on left navigation

### ISSUE THREAD

**Issue by NehaSachan** [mrin9/RapiDoc#505]
is there any option to enable / disable the scrolling thing separately -

1. Disable main section scrolling when  scroll on left navigation
2. but keep scrolling to left navigation when scroll on main section.

**Comment by mrin9** [comment]
That is exactly how it behaves like you described,  unless you are doing something special with your html. For instance checkout this example https://mrin9.github.io/RapiDoc/examples/read-mode.html

> Make sure that you are properly defining the height/width of the `div` under which you are inserting `<rapi-doc>` element

**Comment by NehaSachan** [comment]
Ya ....its happening when we add Header and Footer of our website.

**Comment by mrin9** [comment]
I cannot comment how the parent HTML could be effecting Rapidoc scrolling. but another option would be to insert HTML inside RapiDoc instead of embedding RapiDoc inside an HTML

check this out for more info 
https://mrin9.github.io/RapiDoc/list-html-content.html
