### ISSUE TITLE
[Question] Changelog

### ISSUE THREAD

**Issue by bentcoder** [mrin9/RapiDoc#507]
Hi,

Just wondering if there is way to, somehow, add "Changelog" section somwhere? Or is there a suggestion/example? I guess [this would work](https://mrin9.github.io/RapiDoc/examples/mix-html.html#overview) at the bottom of the page but the question is, would there be any way for adding a link on the left hand side where the menu is?

Thanks

**Comment by mrin9** [comment]
Use markdown within the spec. This provides you the option of adding section headings on the left menu using the `info-description-headings-in-navbar` attribute
  - here is an example  https://mrin9.github.io/RapiDoc/examples/markdown-headings.html
  - and the spec for that is https://mrin9.github.io/RapiDoc/specs/markdown-headings.yaml

**Comment by BentCoder** [comment]
Thanks for this @mb1511. There are two problems with that. First of all it is a bit jumpy. If you school up or down slowly, it jumps between the items. Second thing is, I am unable to add `<ul>` elements for footer. If I do, they appear on top of the page.

```
        <p slot="footer" style="margin:0; padding:16px 36px; background-color:orangered; color:#fff; text-align:center;" >
            This is an external html content    <--- this appears in the footer which is fine
            <ul><li>line 1</li><li>line 2</li></ul>    <--- this appears on top of the page
        </p>
```

**Comment by BentCoder** [comment]
Never mind the footer issue as I managed to solve with duplicating the slot but the jumping issue persists.

**Comment by mrin9** [comment]
Thanks for the update
- I would prefer markdown over slots as they are native to open-api specs and get the first-class support from rapidoc
- slots should be used if you like to add some extended styles thats not possible with just markdown
