### ISSUE TITLE
v-slots in Vue 3

### ISSUE THREAD

**Issue by j-monteiro** [mrin9/RapiDoc#508]
Hi!

I'm having trouble using this in Vue 3 has the linter complains about the slot attribute being deprecated and by trying to use the new v-slot attribute the HTML does not get attached to the slot. I've tried the following:

```
<rapi-doc
  :spec-url="specUrl"
  render-style="focused"
  style="height: 100vh; width: 100%"
  use-path-in-nav-bar="false"
  primary-color="#42a1ff"
  show-header="false"
  allow-server-selection="false"
  sort-tags="true"
  info-description-headings-in-navbar='true'
>
  <template v-slot:nav-logo>
    <img src="https://placeholder.com/wp-content/uploads/2018/10/placeholder.com-logo1.png" />
  </div>
</rapi-doc>
```

PS: with the `slot="nav-logo"` attribute it works, it's just the linter that annoys me

Thanks in advance

**Comment by mrin9** [comment]
`slot` has never been deprecated in HTML spec https://developer.mozilla.org/en-US/docs/Web/HTML/Element/slot

and `v-slot` has no relation with `solt`.  `v-solt` is somthing unique to `vue` whereas `slot` is a part of HTML spec
the linter complaining about `solt` is actually referring to `vue slot` not `HTML slot`

if you are using `vuter` for your linter then
go to `.vscode/settings.json` and add the following: 
```
"vetur.validation.template": false,
```
what it will do is make `vuter` depend on `eslint` for template validation

next fix your `eslint.js` to ignore deprecated `solt of vue`
```
rules: {
    'vue/no-deprecated-slot-attribute': 'off',
  }
```

This bug do not belong here,  This should be filed with the `linter` which is complaining `slot` is deprecated

**Comment by gablaxian** [comment]
Hello! I'd like to re-open this ticket as the Author of the original post, I believe is correct.

The `"slot="example"` style of applying elements to named slots was deprecated in Vue 2.6+
See: https://vuejs.org/v2/guide/components-slots.html#Deprecated-Syntax

As you are using Vue 3, afaik, then the linting error is accurate. We should be using the newer syntax.
