### ISSUE TITLE
Error on urls while navigating

### ISSUE THREAD

**Issue by davide-marino** [mrin9/RapiDoc#509]
Hi,
using rapidoc in an angular application the base href defined in the angular application has effect on the rapidoc element.
During the navigation the url is related to the base href of the angular application instead relative to the current page.
So if I include the <rapidoc> tag in the page at the url /myapi navigating I see the urls of the navigation bar of the browser changing to /#post-/pet instead of **/myapi**#post-/pet.

A similar issue was opened here https://github.com/mrin9/RapiDoc/issues/496. The problem is that in an angular application I can't remove the `<base href="/">` tag and I can't change to `<base href="/myapi">` otherwyse the full angular application doesn't work.

**Comment by mrin9** [comment]
I can consider adding an option not to change the route at all. do you think that will work for your case ?

**Comment by mrin9** [comment]
you should be now able to achieve the desired routing behavior 

following new options are added 
- disable routing `update-route = true | false`
- provide custom prefixes to routes `route-prefix`

read more about it here https://mrin9.github.io/RapiDoc/api.html#general
