### ISSUE TITLE
Local JSON file does not work

### ISSUE THREAD

**Issue by tomdegoede** [mrin9/RapiDoc#51]
I am currently trying to implement the component by calling .loadSpec using an object similarly to [loading a local JSON file](https://mrin9.github.io/RapiDoc/example1.html). Unfortunately this behavior seems to be broken due to [parse-utilts:21](https://github.com/mrin9/RapiDoc/blob/a675ebda1d13468b3008475ffd27622a2a6852e1/src/utils/parse-utils.js#L21) where source is undefined.

**Comment by mrin9** [comment]
`loadSpec()` is not a public method.

if you are dynamically trying to load a spec then you should try to change `spec-url` attribute  instead (refer [API Documentation](https://mrin9.github.io/RapiDoc/#api))

You can also see it in action in this [example](https://mrin9.github.io/RapiDoc/example100.html)
Click `Change Spec URL` button on the top to  dynamically load various specs

**Comment by mrin9** [comment]
in case it matters,
I have now made the `loadSpec()` method public in release `5.1.0` and updated the API documentation

It takes either a string (containing spec-url) or a spec defined in json object. 
checkout this [Example](https://github.com/mrin9/RapiDoc/blob/master/docs/example9.html) for the usage

Hope this may be of some help.

**Comment by tomdegoede** [comment]
Thanks!
