### ISSUE TITLE
Response schema definition missing a colon for a required array of objects

### ISSUE THREAD

**Issue by NasaGeek** [mrin9/RapiDoc#511]
I think a picture makes this clear:
<img src="https://user-images.githubusercontent.com/474937/125912803-d9a9b537-f0f1-4a1c-8f7a-808e7f96d7c9.png" height="400px"/>

There should be a colon after `entities*`.

**Comment by mrin9** [comment]
Fixed by #512
Thanks for fixing it @NasaGeek
