### ISSUE TITLE
Allow leaving the endpoint order unmodified

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [mrin9/RapiDoc#516]
Currently, the order of endpoints within a tag is always modified. I propose adding the option `none` to `sort-endpoints-by` to leave the order as is.

**Comment by mrin9** [comment]
An endpoint can have multiple tags associated with it. In that case it will appear under more than one tag. 
Have a look at this example https://mrin9.github.io/RapiDoc/examples/arrange-by-tags.html 

In that case what should be the order ?
depending on how we deal with arranging end-points it can make things little complicated. If there is a reasonable approach i am willing to take a PR else I will be moving it to our backlog bucket

**Comment by mrin9** [comment]
An endpoint can have multiple tags associated with it. In that case it will appear under more than one tag. 
Have a look at this example https://mrin9.github.io/RapiDoc/examples/arrange-by-tags.html 

In that case what should be the order ?
I will look into the PR you have submitted . Thanks for attempting  the fix

**Comment by mrin9** [comment]
the PR looks good to me. Thankyou for taking care of this.
