### ISSUE TITLE
Loading specs errors are not handled correctly

### ISSUE THREAD

**Issue by mohannad-musleh** [mrin9/RapiDoc#519]
When the Spec URL is invalid or if an error occurred when loading the spec (e.g: `401 Unauthorized` error), the RapiDoc gives a blank screen with no URL input or load spec button.  

Note: the issue was fixed in `9.0.1-beta` version (related issue: https://github.com/mrin9/RapiDoc/issues/459)

Setup Details:
- node version: `v16.3.0`
- npm version: `7.19.1`
- RapiDoc version: `9.0.0` (note: tested from `CDN` and from NPM)
- Bundler: `vite@2.4.3`

**Comment by mrin9** [comment]
closing this one the fix is already there. There is delay in releasing `9.0.1-beta` due to our summer break.
Will start the testing and release process soon for `9.0.1`
