### ISSUE TITLE
Proposal: use apicurio-data-models library to parse/analyze OpenAPI content

### ISSUE THREAD

**Issue by EricWittmann** [mrin9/RapiDoc#52]
For reference, I work on the [Apicurio Studio](https://www.apicur.io/) project, which is an open source API Designer. One of the outputs of that work is a standalone library called **apicurio-data-models**. It's a library that implements a data model for OpenAPI and AsyncAPI and includes the following useful features:

* Reading/writing OpenAPI/AsyncAPI documents
* Full visitor pattern for analyzing the data model
* Transform OpenAPI 2 documents into OpenAPI 3
* Validation of the data model
* Command layer (with basic operational transformation capabilities) to apply changes to the data model (probably not useful to RapiDoc)

The source can be found here:
https://github.com/Apicurio/apicurio-data-models

The library is here in NPM:
https://www.npmjs.com/package/apicurio-data-models

It's is written in Java but transpiled into TypeScript/JavaScript - this is useful for us because Apicurio Studio's back-end is written in Java while the front-end is Angular ... and the same code powers both.

It has no dependencies and it replaces/deprecates the older **oai-ts-core** library.

We support RapiDoc as one of the renderers available in the "Preview Documentation" feature we have in Apicurio Studio.  And that got us thinking that the work we did in the data model library might be useful to projects like this.  So just wanted to make you aware of it in case it would be useful. :)

Either way, keep up the good work!

**Comment by mrin9** [comment]
thanks for letting us know abt this, I am always on a lookout to reduce our dependency tree and overall package size. 
your work looks promising, will surely give it a try with our test cases.

I had a quick look at the documentation, did not find the support for `.yaml` specs, do you know if thats supported ?

**Comment by EricWittmann** [comment]
The library itself doesn't support YAML - it assumes parsing of the YAML would happen first, and then the resulting javascript object would be passed to the library for "parsing" into a data model.  That's done specifically to avoid a dependency on a YAML parser.

**Comment by mrin9** [comment]
At present state adding Apicurio is increasing RapiDocs overall size, so we wont be pursuing to use it now.
