### ISSUE TITLE
Get Token button missing for oauth2 password grant flow

### ISSUE THREAD

**Issue by patrickbowie** [mrin9/RapiDoc#520]
Currently password grant flow generates the correct input boxes but does not generate a get token button making it non functional.
![image](https://user-images.githubusercontent.com/87037134/127187814-8577f672-ec77-47ff-afa1-cc5259d1d6b1.png)

**Comment by mrin9** [comment]
please refer #305

**Comment by mrin9** [comment]
Fixed by #524
