### ISSUE TITLE
Swagger-UI-style theme ?

### ISSUE THREAD

**Issue by eLvErDe** [mrin9/RapiDoc#521]
Hello,

Is there any theme or CSS that could make Rapidoc looks more swagger-ui-ish ?
I'm considering switching but most of my users (including myself) are really used to the swagger-ui layout and I don't want to disturb them much...

Best regards, Adam.

**Comment by mrin9** [comment]
Not quite sure about what you mean by swagger-ui-ish. the nearest style you can get out of RapiDoc thats close to swagger is the `render-style=view` with `theme=light`  https://mrin9.github.io/RapiDoc/examples/example1.html

If you mean can we change the styles of our UI components like how swagger-ui displays its model/example or the text-boxes, buttons etc. to look like swagger then there is none. 

Have a look at this example which showcases changes to some theming attributes 
https://mrin9.github.io/RapiDoc/examples/themes.html

the source can be found here https://github.com/mrin9/RapiDoc/blob/master/docs/examples/themes.html
