### ISSUE TITLE
Internationalization support?

### ISSUE THREAD

**Issue by lperea00** [mrin9/RapiDoc#526]
Hi, I've been working with rapidoc in the documentation of an api, but this api is for spanish speakers, so is there a way to change the default labels that are shown in rapidoc? 
For example "Introducción" instead of "Overview" in the main menu, "Buscar" instead of "Search", etc.
Thanks.

**Comment by mrin9** [comment]
There is none at the moment. 
But Localization is there in our cards. If this is a feature thats really urgent for you then would you like to sponsor it ?

**Comment by lperea00** [comment]
Thanks for your answer, by the moment it's no urgent for us, we could wait for it.
 Sponsor it? that's sound interesting, how does it work?

**Comment by mrin9** [comment]
There are couple of ways 
- One you sponsor us on a long term basis generally for a year at fixed monthly amount. And will develop the product in consultation with you and according to your needs. There will be 2 forks, one for your organization (private) and one on the open-source. If you are willing any specific functionality that we developed for you can be merged to open-sourced branch. that way you will always be in sync with the open-sourced branch and keep getting the latest updates and fixes. We also develop plugins thats specific to your org which you can add on top of the open-sourced product

- The other way is, If you have a specific functionality in mind you can just fund for that functionality. For instance localization. We can explain you the plan and and work with you that caters to your need.

- The third way to help us, is to develop the functionality yourself, we will review it and see if fits within our vision and plan and include in our product.

Our charges are very nominal and not looking to make profit but just to keep the project afloat. We dont put ads on our website and our team is split on putting a sponsor badge on website or in this repo as it puts some indirect pressure on our users. We like to keep the experience as free as possible.

In any case let me know what do you think abt it, that will help me decide to close this issue

**Comment by mrin9** [comment]
closing this as we have it in our plan, but cannot provide a date.
