### ISSUE TITLE
Looking for contacts of RapiDoc customization experts

### ISSUE THREAD

**Issue by NilofarMulla** [mrin9/RapiDoc#527]
Sorry for creating an issue here as we could not find other contact information.

I am glad to share that our organization has recognized RapiDoc as the most suitable platform for its API documentation portal.

With this regard, we wanted to know if you could help us with any contacts of third-parties or freelancers who are RapiDoc styling experts and can help us customize our API documentation portal.
 
We are hoping for some lead from you. Any help is much appreciated!

**Comment by mrin9** [comment]
We dont have any third party contacts. All our team member works in their personal time. Having said that we are looking for sponsors  or any consultation/implementation work that will help us keep the project free without any subscription model.

Can we help you ? most likely yes but first provide us with your detailed requirements  at mrin9@yahoo.com 
for our assessment and will get back to you
