### ISSUE TITLE
tag-- slots do not work when using focused rendering

### ISSUE THREAD

**Issue by klickyfan** [mrin9/RapiDoc#529]
Hi there,

Great product that I am enjoying using! Thanks so much for making it available.

But I think I have found a bug? When you use "focused" rendering, the tag slots do not work.  I was trying to use them because I'd really like to add a description for each tag (using a slot) in the index.html. 

Thanks,
Kim Jones

**Comment by mrin9** [comment]
Tags behave little differently with focused mode. as this mode focuses on one operation at a time

can you check by setting the following attribute 
`on-nav-tag-click="show-description"`
helps you ?

**Comment by mrin9** [comment]
hope it solved your case. closing it now
