### ISSUE TITLE
automatically "lock in" list parameters

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [mrin9/RapiDoc#530]
If you enter a value into a list parameter field, but don't press enter, it looks exactly like the values in a non-list field. This can lead to confusion, since the entered parameter will not be sent when the request gets executed.

It would make sense to automatically "lock in" values if the field is no longer selected, or once the try button is pressed.

![image](https://user-images.githubusercontent.com/15961647/129872777-a1864442-725c-45af-98eb-5a0c093db9d7.png)

**Comment by mrin9** [comment]
agreed, It can make our UX bit better
