### ISSUE TITLE
Missing dropdown for examples for form

### ISSUE THREAD

**Issue by majoshi1** [mrin9/RapiDoc#532]
In below demo, the POST has `application/json`. But, the dropdown is not shown if that is replaced by `application/x-www-form-urlencoded` or `multipart/form-data`. Any idea?

[Multiple examples in request body](https://mrin9.github.io/RapiDoc/examples/examples-multiple.html#post-/multiple-example-in-request-body)

Basically, question is how to show multiple examples for such cases?
[Fixed form parameters](https://mrin9.github.io/RapiDoc/examples/dynamic-form-params.html#post-/fixed-form-parameters)

Workaround: Replace formData by path. This shows examples as a list.
i.e. From `in: formData` to `in: path`.

**Comment by mrin9** [comment]
I have updated the example to show how to provide multiple values for form parameters
https://mrin9.github.io/RapiDoc/examples/dynamic-form-params.html#post-/fixed-form-parameters

and the spec used for this is at 
https://github.com/mrin9/RapiDoc/blob/b937bdd6eb67b17b3a7feaa056a437950304a056/docs/specs/dynamic-form-params.yaml#L74-L80
