### ISSUE TITLE
Schemas in Navigation Bar

### ISSUE THREAD

**Issue by sk-** [mrin9/RapiDoc#535]
First of all, thanks for this great tool.

I was wondering if it was possible to show the schemas in the Navigation bar.

**Comment by mrin9** [comment]
use `show-components` attribute

Example : https://mrin9.github.io/RapiDoc/examples/components.html

> as of now it shows in JSON format. But there is a PR #531  pending review that will show it as schema-view

**Comment by sk-** [comment]
Thanks @mrin9 for the quick response. Note that `show-components` only works together with the `render-style="focused"`. With the default render style the components are shown but nothing happens when I click them.

Also, there are some issues around that option.

1. The section `Components` y slightly different than the `Operations` one, as it is missing the collapse buttons.
2. It'd be great to omit some of the Components types, for example the `Security Schemes` as those were already rendered in a dedicated section at the top of the page.

**Comment by mrin9** [comment]
Can you create two separate issue for the points you sated above

Thanks
