### ISSUE TITLE
Add link to Spec

### ISSUE THREAD

**Issue by sk-** [mrin9/RapiDoc#537]
Is there an option to show a link to the Open API spec. That would be really useful for external users reading the docs, as in that way they can download it and use it to generate libraries or try it in another tool like Postman.

**Comment by mrin9** [comment]
sure. will look into this request

**Comment by mrin9** [comment]
added buttons to download or view OpenAPI spec
this is available in the Overview(info) section therefore you must ensure that `show-info = 'true'` for it to appear

example: http://localhost:8080/examples/example1.html
