### ISSUE TITLE
Get added to official list of OpenAPI implementations

### ISSUE THREAD

**Issue by afranke** [mrin9/RapiDoc#538]
RapiDoc should be listed [alongside other OpenAPI specification user interfaces](https://github.com/OAI/OpenAPI-Specification/blob/main/IMPLEMENTATIONS.md#user-interfaces).The world needs to know about it! :smile:

**Comment by waldyrious** [comment]
I've created https://github.com/OAI/OpenAPI-Specification/pull/2683 to add RapiDoc to that list :)

**Comment by mrin9** [comment]
@afranke - thanks for the suggestion 

@waldyrious - Thanks much for going ahead and adding it to the list !!!

**Comment by waldyrious** [comment]
Update: the PR was merged earlier today, so this issue is now resolved! :tada:
