### ISSUE TITLE
Oauth2 authentication

### ISSUE THREAD

**Issue by FlaxHaxx** [mrin9/RapiDoc#54]
[MrinDoc](https://mrin9.github.io/OpenAPI-Viewer/#/load/https%3A%2F%2Fapi.apis.guru%2Fv2%2Fspecs%2Fbitbucket.org%2F2.0%2Fswagger.json) has Oauth2 authentication. Will it be available for RapiDoc also soon?

**Comment by mrin9** [comment]
[MrinDoc](https://mrin9.github.io/OpenAPI-Viewer/#/load/https%3A%2F%2Fapi.apis.guru%2Fv2%2Fspecs%2Fbitbucket.org%2F2.0%2Fswagger.json) is an app that is served from a server, therefore you can register that domain with an oAuth provider
But `<rapi-doc>` is a custom-element that runs on browser, you dont need any server, you can just use the tag in any html and open it in a browser.

So we don have any domain that can be registered with the oAuth provider.

we are open to suggestions, to create an workflow that can help getting token from oAuth Provider easier

**Comment by mrin9** [comment]
closing this as it is the responsibility of the Web-App creator to provide an oAuth flow. RapiDoc is just a  WebComponent.
