### ISSUE TITLE
[Request] Refresh OAuth token automatically

### ISSUE THREAD

**Issue by fehbari** [mrin9/RapiDoc#545]
When working with an API with short token expiration time, one has to constantly re-authorize (click the _"Get Token"_ button under Authentication).

Is there a way to have RapiDoc's _"Try"_ button automatically refresh the expired token (i.e. call the `refreshUrl` set in the OpenAPI schema)? Or can this feature be added in the future?

<img width="429" alt="auth" src="https://user-images.githubusercontent.com/3378355/131932023-ab4ab36c-ab19-47cd-8ce1-a28c4cc4b296.png">

As a suggestion for how this could work, in the [Paw](https://paw.cloud/docs/auth/oauth2) REST client, if the user checks an _"automatically refresh token"_ box, when an unauthorized response is returned, it calls the `tokenUrl` (or `refreshUrl`) again to get a new token. 

Another alternative would be to do this at a set interval configured by the user; or upon clicking _"Try"_ if it's been X seconds/minutes since the last click/request (also to be set by the user).

Thanks for the work in this, love the theming support and overall UI!

**Comment by mrin9** [comment]
In RapiDoc, to achieve it you can get the new token in `befor-try` event and apply it to the request. 
For an example, check out this snippet https://mrin9.github.io/RapiDoc/api.html#events

Let me know if you were able to get it

**Comment by mrin9** [comment]
hope you were able to address it 
you can also check this example https://mrin9.github.io/RapiDoc/examples/auth.html#operations-top to find how to apply security key programmatically
