### ISSUE TITLE
JSON Schema 2020-12 Support: Arbitrary fields next to $ref

### ISSUE THREAD

**Issue by seeruk** [mrin9/RapiDoc#547]
I believe RapiDoc does support some OpenAPI 3.1 features, it'd be really fantastic if it could support this. [As outlined here](https://lornajane.net/posts/2020/whats-new-in-openapi-3-1#:~:text=content%3A%0A%20%20%27application/json%27%3A%0A%20%20%20%20schema%3A%0A%20%20%20%20%20%20%24ref%3A%20%27%23/components/schemas/style%27%0A%20%20%20%20%20%20required%3A%0A%20%20%20%20%20%20%20%20-%20hue), you're now allowed in OpenAPI 3.1 to place arbitrary fields next to $ref. This means you can do things like describe a specific usage of a referenced type in the place that it's used, leading to much more accurate and sensible descriptions. 

This also extends to other fields though too, such as `required` which is in the example linked.

**Comment by mrin9** [comment]
providing with a simple use-case (a minimal `yaml`) containing various combinations would be nice for us to work with

**Comment by seeruk** [comment]
Sure thing, here's the specific kind of example I'm talking about:

```yaml
openapi: 3.1.0
info:
  title: GitHub Issue 547
  version: 1.0.0
  contact:
    name: SeerUK
paths:
  /v1/example:
    get:
      summary: /v1/example
      responses:
        '200':
          description: Example response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleResponse'
      operationId: v1Example

components:
  schemas:
    ExampleResponse:
      type: object
      properties:
        someObject:
          description: >
            This is now allowed in OpenAPI 3.1, allowing descriptions for specific usages of 
            referenced types. These kinds of descriptions are far more useful with context!
          $ref: '#/components/schemas/SomeObjectType'
      
    SomeObjectType:
      description: >
        The descriptions should probably fallback to the description of the referenced type if one
        is provided.
      type: object
      properties:
        foo:
          type: string
```

Honestly, I'm quite new to OpenAPI / RapiDoc, etc. I've only started looking at this today. When I realised I couldn't put a description next to a `$ref` I was really confused. Some referenced types are just going to be shared structures for basic data types. Their description alone is meaningless. One example of this kind of thing was a `PhoneNumber` type.

**Comment by mrin9** [comment]
The article you pointed refers to JSON Schema Spec. which is supported by OpenAPI 3.1.0 however there are some overlapping concerns that we will work out with spec authors before implementing a solution in this area.

However, like to address issues in your particular case 

> Some referenced types are just going to be shared structures for basic data types. Their description alone is meaningless. One example of this kind of thing that I've seen elsewhere was a PhoneNumber type.

Using your example of `PhoneNumber` which is defined as a schema this can be used in two ways 
- as a sub-schema of a bigger schema, then you are correct the description may not add much value
- this can be used as a full schema itself within the same spec and then description is rather important

therefore we cannot avoid having description even though they dont add much value in certain uses cases. Now in case you are using this as a sub-schema you can provide a description to the containing schema in which case that description will overshadow the sub-schema level descriptions (In case thats the question you are asking)

Now, to avoid some new schema composition techniques using JSON-Schema and the whole confusion about which description is applied where. can I suggest using a more matured and a stable feature of OpenAPI spec AND JSON Schema; which is the `all-of` operator. This will also provide you with a better compatibility with various open-api tools/echo-system (not just RapiDoc) ?

so I can rewrite the above spec like below

```yml
openapi: 3.1.0
info:
  title: GitHub Issue 547
  version: 1.0.0
  contact:
    name: SeerUK
paths:
  /v1/example:
    get:
      summary: /v1/example
      responses:
        '200':
          description: Example response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExampleResponse'
      operationId: v1Example

components:
  schemas:
    ExampleResponse:
      type: object
      description: Description for Foo and Bar.    # <<< description that applies to all-of the fields
      allOf:
        - properties:                              # <<<  You may add any number of arbitrary fields under it
            bar:                
              type: string
        - $ref: '#/components/schemas/SomeObjectType'
    SomeObjectType:
      type: object
      description: Description for Foo             # <<< description that applies to the sub-schema (is applied if top schema do not have description)
      properties:
        foo:
          type: string
```

if it fixes you issue, please feel free to close the issue

**Comment by mrin9** [comment]
hope it fixed the issue at ur end - closing this
