### ISSUE TITLE
allow-spec-url-load and allow-spec-file-load toggles not working in 9.1.2

### ISSUE THREAD

**Issue by joshrap-eb** [mrin9/RapiDoc#556]
Was testing out the new release and noticed that these toggles are not working properly for me - they have no effect on the resulting html that is generated. I verified that I am using the 9.1.2 dist.

```
allow-spec-url-load="false"
allow-spec-file-load="false"
```

**Comment by mrin9** [comment]
thanks for reporting , I will investigate it further 

> we have the patch window open till first week of sept if we fix it by then will get released

**Comment by mrin9** [comment]
just had a quick check , it works as expected for me 

`allow-spec-url-load` show/hide the url bar on the header
`allow-spec-file-load` show/hide the button on the header to load a JSON

to see the effect of these attributes you should have `show-header = "true"`

```html
<rapi-doc 
  spec-url = "./specs/petstore.yaml" 
  show-header = "true"
  allow-spec-url-load = "false"
  allow-spec-file-load = "false"
></rapi-doc>
```

**Comment by joshrap-eb** [comment]
Hm I tried this and it doesn't work for me. Just to be clear, these are the buttons that I am wanting to hide. Are these buttons not the ones that those two attributes control?
![image](https://user-images.githubusercontent.com/74060233/134068433-6215b6dc-0729-4b32-bba7-e8e4ca52862c.png)

**Comment by mrin9** [comment]
no they aren't, for now we dont have a specific attribute to control those.
To hide it it needs `show-info="false"` which will hide the entire overview section.

We checked with other renderers, who would also provide a way to download the spec. would you like to hide them specifically ?

**Comment by joshrap-eb** [comment]
Yes I would like to specifically hide those if that wouldn't be too hard to implement. None of our clients need to see those buttons so at the moment they are sitting there taking up space.

**Comment by mrin9** [comment]
okay, have similar request from our internal users will add `allow-spec-file-download` attribute which will be defaulted to `true`
should find it soon in next patch release

**Comment by mrin9** [comment]
we set the default value `allow-spec-file-download = false`. 
But I recommend always specify the desired value for attributes and do not depend on defaults. As we have changed defaults in the past in different releases.
