### ISSUE TITLE
Slot documentation uses slot tags instead of divs

### ISSUE THREAD

**Issue by afranke** [mrin9/RapiDoc#560]
[The API documentation](https://mrin9.github.io/RapiDoc/api.html) gives me `<slot>` tags and I tried to use them for `nav-logo` but that didn’t work. I looked at [the logo example](https://mrin9.github.io/RapiDoc/examples/logo.html#overview) and this uses `<div slot="nav-logo">` which worked for me. Something seems to be broken, but I can’t quite tell if it’s the documentation, the API, or something else.

**Comment by mrin9** [comment]
The documentation is wrong .... thanks to bring it to our notice, will fix it soon
