### ISSUE TITLE
Feature request: text entry for custom server

### ISSUE THREAD

**Issue by afranke** [mrin9/RapiDoc#561]
RapiDoc already supports switching servers through the server variables, but this assumes there is a finite list of servers that is known in advance. Developers might be implementing the API spec and want to make calls against a random instance, instead of the ones provided by whoever hosts the spec. Having a way to enable a text field where one could type in the address of their server would be useful for such cases.

**Comment by mrin9** [comment]
Use Server Variable 
Here is an example https://mrin9.github.io/RapiDoc/examples/server-vars.html#servers checkout the 3rd and 4th servers option where you can construct your own server url using variables

Hope it takes care of your issue

**Comment by afranke** [comment]
Cheers! I missed that without an enum it will behave as I need it to. That’s great, thanks.
