### ISSUE TITLE
nullable ref field

### ISSUE THREAD

**Issue by schmurfy** [mrin9/RapiDoc#568]
Since `nullable` is now deprecated (and never worked for $ref anyway) I am trying to find how to show a field as nullable.
I found that oneOf with a null type should work but the result shown is not that great, it literally show (with a $ref):
```
ONE OF
1  NULL 
1 {
    name: string
   }
```

I was looking a way to show some kind of icon like readonly, is there a better way to do nullable fields ?

**Comment by mrin9** [comment]
**OpenAPI v3.0**
```yaml
  type: string
  nullable: true
```

in openapi 3.1 types can take multiple values
**OpenAPI v3.1**
```yaml
type:
- "string"
- "null" 
```
check the phone field below which can take null or string
 
![image](https://user-images.githubusercontent.com/5056899/134777414-6b53e159-89a3-426a-8160-e97fb0670f40.png)

here is the example of this https://mrin9.github.io/RapiDoc/examples/data-types.html#post-/nested-object-in-request-body

all the examples and their spec can be found at `docs/examples` and `docs/specs` folder

**Comment by schmurfy** [comment]
Thanks for the reply but that did not fully answer my question for `$ref` fields, 
I tried the following with no luck:
```json
"user": {
  "$ref": "#/components/schemas/User",
  "type": ["object", "null"]
}

```

after digging a bit more I realized that the way openapi seems to handle this, and this makes it really useless for me is to add null as an allowed type in the ref:
```yaml
components:
  schemas:
    User:
      properties:
        ...
      type:
        - object
        - null
```

I thought that the ref was a bit more clever than that but maybe I should just stop using it altogether since my code is generated anyway... My real problem is more general: https://github.com/OAI/OpenAPI-Specification/issues/2026

and btw when using type array as you shown the way it is displayed is still not that great but that's a nitpick ;)

PS: love the project :)
