### ISSUE TITLE
readOnly and writeOnly ignored on $ref properties

### ISSUE THREAD

**Issue by schmurfy** [mrin9/RapiDoc#569]
With this property:

```json
"user": {
  "writeOnly": true,
  "$ref": "#/components/schemas/User"
}
```

neither writeOnly nor readOnly does anything which should be supported as part of OAS 3.1 unless I am mistaken.
is there any other supported way to do this ?

PS: using latest 9.1.2 release

**Comment by mrin9** [comment]
I am not sure thats allowed in OpenApi 3.1.
can you point me in the spec where they say this is a valid

**Comment by schmurfy** [comment]
You are right, while digging more on my other issue I found than only the description field can be overriden and only in some case so the "problem" is in the openapi spec 3.1, not in rapidoc, too bad :/
(I linked the openapi issue on this in my other issue)
