### ISSUE TITLE
Support for array examples

### ISSUE THREAD

**Issue by StephenNay** [mrin9/RapiDoc#57]
I try to include examples for everything in my OAS definitions, including for arrays, but I'm not seeing the example array values in RapiDoc output. For example, this parameter definition:

        segmentIds:
          type: array
          description: IDs of segments that are included in the route.
          items:
            type: integer
          example:
            - 278
            - 279
            - 280
            - 281

Shows up as:

    segmentIds:[
        0
    ]

It would be nice if example array values were displayed as all other example values are.

**Comment by mrin9** [comment]
provided in release `5.3.1`

**Comment by StephenNay** [comment]
The fix looks great. Thank you!
