### ISSUE TITLE
Api key is sent with a leading whitespace

### ISSUE THREAD

**Issue by sk-** [mrin9/RapiDoc#570]
For some reason when testing out an API, the request made has an extra leading space in the api key set in the authentication section at the beginning of the page.

This happens both for api keys set in the header as well as for api key set in the query string.

You can try it out on the example: https://mrin9.github.io/RapiDoc/examples/example100.html#get-/pet/-petId-
And then making a request.

Even the generated curl code has the extra leading space:

```
curl -X GET "https://petstore.swagger.io/v2/pet/1234" \
 -H "Accept: application/json" \
 -H "api_key:  foo" 
              ^
```

**Comment by mrin9** [comment]
thanks for the report ... was able to create it on my end, will provide a fix with patch release soon as it has potential to effect many customers

**Comment by yassenb** [comment]
Please release a new version, this is a critical fix
