### ISSUE TITLE
Need indication an integer is int64 v. int32

### ISSUE THREAD

**Issue by suntereo** [mrin9/RapiDoc#574]
Int64s are appearing as "integer" in some cases. And I'm concerned our API readers will not know when we're using int64 (and not int32).

For example, consider this definition:

```
"VehicleGetBasicRequest": {
        "required": [
          "vehicleId"
        ],
        "type": "object",
        "properties": {
          "vehicleId": {
            "type": "integer",
            "description": "The VehicleId to get.",
            "format": "int64"
          }
        },
        "additionalProperties": false,
        "description": "VehicleGetBasicRequest object"
      },
```
The int64 in the above example appears as "integer" in RapiDoc:

![Example](https://user-images.githubusercontent.com/171720/135500636-b36fddc1-71aa-40b0-83cc-1b1a8657fb95.png)

As far as I can tell, RapiDoc does show "int64" for path parameters. But it does not do so for requests whose body is an object (or responses). Another example from the Pet Store demo will show this:

https://mrin9.github.io/RapiDoc/examples/example1.html#get-/pet/-petId-

![Example2](https://user-images.githubusercontent.com/171720/135501519-d2585398-e2ea-47d6-b0dd-f798ae8a4a0c.png)

The arrow on the left has the "int64" while the arrow on the right just has "integer".

**Comment by mrin9** [comment]
Thanks for reporting this issue.

The reason for this is that from  OpenAPI v3.1.0 it has shifted to use strictly the [JSON Schema spec](https://json-schema.org/understanding-json-schema/index.html), however in until v3.0.3 it is using ([JSON Schema +  own extensions](https://swagger.io/specification/))

From `3.1.0` there is no format for numeric types as it is not supported in JSON Schema. and thats where RapiDoc will head towards as well. 
You will see in future release that the  format details for numeric fields are removed from  path, query and header params as well.

Let me know what do you think

**Comment by suntereo** [comment]
Thanks for getting back to me so quickly! I guess I can manually add a note to the description for each property saying that it is "long". I was hoping to avoid this for obvious reasons. Thanks by the way for such a great tool!

**Comment by mrin9** [comment]
if the need is to differentiate between a integer value and a decimal value (long) then there are two different types
- integer
- number (accepts decimals)

`int32` and `int64` both are integers just that their range differs which you should control using [range](https://json-schema.org/understanding-json-schema/reference/numeric.html#range)
