### ISSUE TITLE
Is there a way to show both path and title in nav bar (read/focus mode)?

### ISSUE THREAD

**Issue by sammy-tam** [mrin9/RapiDoc#585]
Currently we are using "view" mode because that is the only view that contains the list of endpoints / description at a glance. However, the read/focus mode is awesome, with features like filtering, and easier navigation in general.

Is there a way that we can display the endpoint on the nav list?

**Comment by mrin9** [comment]
> The read/focus mode is awesome, with features like filtering,

Filter and searching both are available in view mode too 

> Is there a way that we can display the endpoint on the nav list?

`use-path-in-nav-bar = true | false` Example https://mrin9.github.io/RapiDoc/examples/nav-item-as-path.html

feel free to close the issue, if it takes care of ur use case
