### ISSUE TITLE
Option to switch location of summary and method/path

### ISSUE THREAD

**Issue by StephenNay** [mrin9/RapiDoc#59]
One key principle in information design is that you want to tell someone _what_ something does before telling them _how_ to do it. For example, "To add a customer, send this request." People approach documentation with their current task in mind, such as "I want to add a customer." Only someone who is already very familiar with an API can go to the documentation already knowing what method and path they are looking for.

Swagger UI just lists methods and paths, grouped by tags, but there isn't a single word of explanation anywhere until you click on something. Not good information design.

RapiDoc does better. The "path" view includes tag descriptions and method summaries. However, the summaries are off on the right, so the layout is "how before what," not "what before how." 

Would it be possible to have an attribute that would cause the method summaries to appear on the left and the method/path on the right? Or maybe not show the method and path at all until the user clicks the summary. I know that must sound like heresy to a programmer, but it's actually common and respected in the world of API documentation. For example, Stripe documentation, PayPal API reference, Microsoft Azure API Reference. 

Sorry this was so long -- just trying to describe and justify what I'm asking for.

**Comment by mrin9** [comment]
path summaries and descriptions are optional in a spec, plus they can be written down in a markdown syntax, therefore we dont use it as the primary text.

Having said that, most of the spec-renderers focus on one  type of rendering, either geared towards programmers (SwaggerUI) or towards read friendly doc (Redoc)

When you make a renderer specifically for reading, then you expect certain fields to exist even though it is not mandatory in the spec, else it appears broken, this is also the case with ReDoc. Try providing a spec with empty summaries or extra long summaries with markdown syntax, it becomes difficult to read/navigate around

In the current state RapiDoc is more a programmers tools _(our goal was to accommodate most API specs not just the ones written specifically with documentation in mind)_.
but I am working on a feature where RapiDoc can also be used more like a reader, which is what you are after I guess. this will be provided by an option allowing multiple rendering styles.
This is not just about shifting the path and summaries from right to left but many other aspects are being considered to make it read friendly.

we are working towards a 2 column, fully expanded docs without the need of collapse/expand sections. more or less like in these lines https://npr.api-docs.io.
I am happy to take visual design feedback if you have some or want to contribute in some of ur ideas.

Unfortunately, I do not have any timeline on it for now, but i am actively working on it

**Comment by mrin9** [comment]
I am very close to finish up designing/developing -  **RapiDoc - Read Mode** . wanted to share few screenshots of whats coming up

**Read - Mode**
<kbd>
![image](https://user-images.githubusercontent.com/5056899/67026796-5958fc80-f0bd-11e9-948d-34a6405a5144.png)
</kbd>

**Read - Mode** with markdown content
<kbd>
![image](https://user-images.githubusercontent.com/5056899/67027150-e734e780-f0bd-11e9-82d6-6f7e7e2f76b6.png)
</kbd>

**Comment by mrin9** [comment]
in version `6.0.0` there is a `render-style = 'read'` option, which is more appropriate to what you are looking for. 
The priority here is given to `summary` and `descriptions` rather than the paths. The view style is also more tuned for reading 
Here is a [demo](https://mrin9.github.io/RapiDoc/examples/read-mode.html)

Feedbacks are welcome

**Comment by StephenNay** [comment]
I'm sorry that my attention had to go to other projects for a while and I just now found your comments on this. I just tried render-style="read" and I'm loving it! I appreciate how you've built two different render styles for two different uses. Nice.

I'm thrilled to see the navigation in the left column. I know that you aren't a big fan of accordion sections, but you might want to consider making it an option to expand/collapse each heading there. The API that I'm working on right now only has four tags, and each of those has 4-6 requests, so only about 20 requests grouped under 4 headings and I already have to scroll a little. Your swagger pet store demo is about the limit in size for being able to see the navigation without scrolling. For any API with a large number of endpoints/requests, it would be nice to be able to collapse the headers.

If clicking the headers in the navigation column doesn't expand/collapse, perhaps it could link to that heading in the main column. Right now I can click a method summary to navigate right to that method but I can't navigate right to the start of the section.

I'll spend more time with this over the next few days and send more comments if I have any. I really like it, though!

Steve

**Comment by StephenNay** [comment]
I've used the Chrome inspector to look at elements in the page source, but I can't tell from that what format I need to use in my OAS file to create a link within the page. I know how to create a link in markdown, but what anchor name do I use to link to a  section (tag) heading, and what anchor name to link to a specific request? It looks like RapiDoc doesn't use the operationIds defined in the file, but creates its own IDs for requests.

Thanks again,
Steve

**Comment by StephenNay** [comment]
I just noticed that longer descriptions in response models don't wrap when the column is too narrow to display the full text. Also true for request models. 

![image](https://user-images.githubusercontent.com/15385013/67727560-1ba28080-f9a7-11e9-9342-b0bbfcfb7c8b.png)

**Comment by mrin9** [comment]
is it possible for you to share a minimal spec where you see the description cut off ?
I am reopening this issue to address cut off description

> we dont get much notification on closed issues, so please open up a new issues for us to address it quicker.

**Comment by mrin9** [comment]
>If clicking the headers in the navigation column doesn't expand/collapse, perhaps it could link to that heading in the main column. Right now I can click a method summary to navigate right to that method but I can't navigate right to the start of the section.

so are you looking to have those tags too act as links to the start of section ?  

we do have plans to make them links, but isn't the first operation/method under the tag takes you closer to the start of the section. unless you have lot of markdown written at the tag level. I am trying understand the useless here

**Comment by StephenNay** [comment]
Clicking the first operation under a tag scrolls the page so that operation is right at the top, which is nice, but it means that any Markdown description of the tag is off the top of the page and can't be seen. I use the tags to group operations by resource type, such as customers, orders, etc. I use the tag description to provide information about each resource type. If that scrolls off the page, you're looking at a request such as "Get all customers" but you don't know everything you need to know about customers. (That example is too simple because most people understand customers, but I have other resource types that aren't as obvious.)

**Comment by StephenNay** [comment]
I don't see an **Expand Details** link in the top right corner, so I couldn't try clicking on that. I added schema-description-expanded = true and that caused long descriptions to wrap (which is what I want). I then set it to false, and the descriptions are cut off. I'll just leave it set to true.

**Comment by mrin9** [comment]
>I don't see an Expand Details link in the top right corner, so I couldn't try clicking on that. 

I can see it on the screen-shot you attached. The **orange colored text** top-right

![image](https://user-images.githubusercontent.com/15385013/67727560-1ba28080-f9a7-11e9-9342-b0bbfcfb7c8b.png)

**Comment by StephenNay** [comment]
Oh, I was looking in the top right corner of the page, not the top right corner of the model box. I see that link now. :-)
