### ISSUE TITLE
Relative URLs in the `servers` section

### ISSUE THREAD

**Issue by gozdal** [mrin9/RapiDoc#598]
Not sure if this is a bug, maybe there is a way to do what I need but I couldn't find it.

I have OpenAPI spec which I'm shipping with the product. The product could be setup to be served from `/` but could also be setup to be served from `/foo`. The API is exposed at `api` but relative from the root URL, so in the first case it'd be `/api` but in the second case it'd be available at `/foo/api`. 
Documentation is served from `{root}/doc/api` so ideally I'd like to have a way to put something like `../api` in the servers list. However, putting `../api` as a server results in `http://host..api` (note there is no `/` after `host`).

Is it possible to specify a relative server URL in the servers list? I know I could put absolute URL there but I was looking for a way for the API spec to be working without changes even if the customer redeploys the app to a different root URL.

**Comment by mrin9** [comment]
How about using a server template (or some say server variables) ?
That way you host the spec in single location and yet can connect to APIs hosted at different locations or environments such as Test, Dev, Prod, Staging etc

Below is an example you can follow 
https://mrin9.github.io/RapiDoc/examples/server-vars.html

**Comment by gozdal** [comment]
Thanks. I know about the server variables. The thing is that I (as the spec author) do not control the URL prefix or the environment the app is deployed in. The customer may deploy it under `/foo` or under `/`. However, the URL relative to the API docs is always the same so a relative URL would work.

**Comment by mrin9** [comment]
> The thing is that I (as the spec author) do not control the URL prefix or the environment the app is deployed in

precisely i was trying to address that situation.
- if you control the base API path then provide one in your spec
- if you do not, then provide a template URL where your end-user can provide either `/` or `/foo` or any other value that suites her/him

there is another option, where you can provide a `server-url` attribute for the `<rapi-doc>` element to point to an API server.
You can set this value using javascript when the HTML is loaded. you can figure out the relative url in javascript using `window.location.href`

**Comment by gozdal** [comment]
> if you do not, then provide a template URL where your end-user can provide either / or /foo or any other value that suites her/him

Right, although with relative URL this could happen automatically, i.e. if the app is run from `/prefix`, then if the API is available at `/prefix/api` and the docs at `/prefix/doc/api` then using `../api` as the SERVER should work regardless if the prefix is empty or `/` or `/prefix`. Right now it seems to break.

**Comment by gozdal** [comment]
I tried the Javascript approach by adding the following snippet to HTML:
```html
  <script>
    function set_server_url() {
      var pathname=new URL(window.location.href).pathname;
      if (pathname.indexOf("/doc") != 0) {
        document.querySelector("rapi-doc").setAttribute("server-url", window.location.href.replace(/(\/doc\/api.*)/, "/api"));
      }
    }
    document.addEventListener("DOMContentLoaded", set_server_url);
  </script>
```
The intention is to do nothing if the documentation is loaded from `/doc` URL. If is starts from a different prefix then replace `/doc/api` with `/api` and set `server-url`.

This generates 2 entries if the app is server from `/prefix`:
![obraz](https://user-images.githubusercontent.com/619444/140314014-90fa30bd-ca12-401e-ae9a-19d92eb9ebdb.png)

Is there a way to avoid 2 entries and have only the `/prefix/api` one?

**Comment by mrin9** [comment]
I am afraid there is none at the moment
