### ISSUE TITLE
curl url invalid due to duplicate question mark for paths with question marks.

### ISSUE THREAD

**Issue by ekkelenkamp** [mrin9/RapiDoc#603]
When specifying an api with a question symbol in the url, for example:

```
  "/ssd?request=GetDisplay" : {
```

And using a request parameter, for example: "language", the generated curl command is invalid and will contain an extra question symbol.
For example

```
curl -X GET "http://localhost:8181/FewsWebServices/ssd?request=GetDisplay?language=nl" \
 -H "Accept: image/svg+xml" 
```

If a ? is specified in the path, it shouldn't be added to the URL.

**Comment by mrin9** [comment]
Question marks (?) is not allowed in OpenAPI spec Path Object, as 

- Anything after question mark is treated as parameter. If thats the intention then it should be defined under the parameter section.
-In case Question mark (?) is intended to be the part of the path and not a delimiter between path and query-string it should be URL encoded `3F`
- Same is the case if any query-strings parameter's value contains a `?` then it should be URL encoded

> PS: The issue you described not only generates an incorrect `curl` syntax, it will also not work as expected when you click `TRY` which uses JavaScript not curl. The issue is due to an incorrect spec therefore wont be making any changes to effect this
