### ISSUE TITLE
Markdown info openAPI specification extension Footer section?

### ISSUE THREAD

**Issue by supsup** [mrin9/RapiDoc#604]
**Feature Request.**

today you can provide a little markdown using the info block like:
```

info:
  title: Markdown Content
  description: Test case to show markdown support. For more info check specification (http://spec.openapis.org/oas/v3.0.3)
  version: 1.0.0
```

This gets displayed before the specs paths are looped over. The description allows for you to inject a lot of HTML if you want before the spec is looped over, this is nice!

Idea would be to support a new Specification Extensions https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#specificationExtensions  to allow the same idea after the spec is looped over.

```

info:
  title: Markdown Content
  description: Test case to show markdown support. For more info check specification (http://spec.openapis.org/oas/v3.0.3)
  version: 1.0.0 
  x-footer:   <markdown here>

```

The footer would be displayed after the path specs.

x-names could be whatever you guys want like _x-content-after-spec_ for example, or whatever you guys think is good.

General idea for this would be to inject a change log or some other html rich content after the spec.

**Comment by mrin9** [comment]
there are couple of ways you can do this.
- you may use `<slots>`. It allows you to embed external contents into various locations of rapidoc. If you like to have separation of concerns. like the `changelist` may not be a part of the spec but maintained with a version control system. you may inject the contents at various slots (footer is also available). Example for slots https://mrin9.github.io/RapiDoc/examples/slots.html

- in case you want to put it inside the spec and use markdown syntax, and like rapidoc to treat it as a separate section  you can do that as well. Just use a h1 or h2 to create different sections and use the property `info-description-headings-in-navbar = true`


Example
https://mrin9.github.io/RapiDoc/examples/markdown-headings.html  (checkout the section on the left nav)
