### ISSUE TITLE
default anchor tag to "#overview"

### ISSUE THREAD

**Issue by alvin30595** [mrin9/RapiDoc#608]
Hi, may i know is there a default anchor tag when first open the page as currently it will point to the first operation? 
I had tried jquery href & scroll but still not working. Currently set to update-route="false" to temporary solve the issue but the nav bar still clicked at first operation

**Comment by mrin9** [comment]
use `operations-top`

example
https://mrin9.github.io/RapiDoc/examples/read-mode.html#operations-top

**Comment by alvin30595** [comment]
alright, will try it and thanks
