### ISSUE TITLE
Downloaded file named incorrectly for responses with "attachment"

### ISSUE THREAD

**Issue by fehbari** [mrin9/RapiDoc#609]
**Bug report:**

When a response contains a `Content-Disposition` header with `attachment` and a `filename`, the "Download" button in RapiDoc UI saves the file with leading and trailing `_`

For example, a response containing:

```
Content-Disposition: attachment; filename="sample.jpg"
```

will appropriately display the "Download" button to download the binary file. However, the downloaded file is named `_sample.jpg_` instead of `sample.jpg`.

I can reproduce this consistently, and the issue doesn't happen with Swagger UI when testing the same API.

**Comment by mrin9** [comment]
thanks for reporting... will get to it soon

**Comment by mrin9** [comment]
fixed by PR: https://github.com/mrin9/RapiDoc/commit/efdcf9840ebd70781b7d5168de030f59664f1c76

**Comment by fehbari** [comment]
> fixed by PR: https://github.com/mrin9/RapiDoc/commit/efdcf9840ebd70781b7d5168de030f59664f1c76
> 
> 

Awesome. Thanks for taking care of that.
