### ISSUE TITLE
How to add dynamic querystring parameters

### ISSUE THREAD

**Issue by vasnav** [mrin9/RapiDoc#61]
Hi,
   Does RapiDoc support sending dynamic query string parameters in the url?
   As per the link https://stackoverflow.com/questions/49582559/how-to-document-dynamic-query-parameter-names-in-openapi-swagger, OpenAPI 3.x supports free-form query.
   Does RapiDoc support it?

   When I provide the following in my .yaml file:
             

> openapi: 3.0.1
servers:
    - url: https//sample
paths:
  /users:
    get:
      parameters:
        - in: query
          name: params
          schema:
            type: object
            # If the parameter values are of specific type, e.g. string:
            additionalProperties:
              type: string
            # If the parameter values can be of different types
            # (e.g. string, number, boolean, ...)
            # additionalProperties: true
          # style: form and explode: true is the default serialization method
          # for query parameters, so these keywords can be omitted
          style: form
          explode: true

and provide the following as input for 'params' field:

> additionalProperties=id

I get the output as "https://sample/users?params=additionalProperties=id".
Instead output should be as "https://sample/users?additionalProperties=id"

**Comment by mrin9** [comment]
no dynamic props are not supported at this time or rather this aspect has been overlooked. will fix it soon.
thanks for reporting

**Comment by vasnav** [comment]
Thanks.
Waiting for the fix.

**Comment by mrin9** [comment]
Fixed in version `6.0.0`
You can try out this [Test Case](https://mrin9.github.io/RapiDoc/examples/dynamic-query-params.html)

Please reopen in case its not working as you expect it to
