### ISSUE TITLE
Document PATCH operations with application/merge-patch+json

### ISSUE THREAD

**Issue by shahamit** [mrin9/RapiDoc#611]
This is a query that's not purely linked with the rapidoc codebase but I am adding it here to get suggestions/inputs based on the experience the team has gained by looking at various api documentation portals.

We have a lot of PATCH operations on various api resources that accept the content type as `application/merge-patch+json`. With this content-type one can pass only a subset of properties from the actual entity object. 

For e.g. For a create user api POST /users, we could pass 30 attributes including its firstname, lastname, address, phone, email, dob etc. Address, phone, email could itself be nested objects. I would like to update only the mobile number and email attribute through the PATCH /users/{id} api, hence we accept the content type as `application/merge-patch+json`. 

How do I specify the schema for such a PATCH operation? Without specifying any I see the documentation as shown in the screenshot which isn't quite desirable. The schema tab shows "Schema not found" while the examples tab does not have json highlighting. This is not incorrect from rapidoc's perspective but I am trying to see how can we improve the developer experience instead of showing what it does right now.

Any suggestions/inputs on how should this be configured so that the api documentation looks developer friendly?

Thanks

![image](https://user-images.githubusercontent.com/1281926/142633573-cfb7ad3a-0529-4974-a0ac-1748b622101d.png)
![image](https://user-images.githubusercontent.com/1281926/142633596-939c60e5-13a2-4667-aa99-2a92f9cf1831.png)

**Comment by mrin9** [comment]
This should be a question to OpenAPI spec project

What I can suggest is to Use `ANY-OF` Schema Composition Operator. This can accept a subset of schema
You may checkout an example of this in RapiDoc https://mrin9.github.io/RapiDoc/examples/anyof.html#get-/api/employee

Hope that helps
