### ISSUE TITLE
Downloaded file name incorrect when UTF-8 filename is also present in response header. 

### ISSUE THREAD

**Issue by fredericwatteyne** [mrin9/RapiDoc#619]
My response header is the following: 

`content-disposition: attachment; filename=MyFile.zip; filename*=UTF-8''MyFile.zip
content-length: 1005
content-type: application/zip
date: Mon, 06 Dec 2021 06:58:47 GMT
server: Microsoft-IIS/10.0
www-authenticate: Bearer
x-powered-by: ASP.NET`

When clicking the download button:
**Expected**: The downloaded filename is "MyFile.zip" 
**Actual**: The downloaded filename is "MyFile.zip; filename_=UTF-8''MyFile.zip"

PS: Thank you for the nice tool, it's works very well!

**Comment by alexreznikoff** [comment]
it seems that an error occurs while processing **content-disposition** header with filename*=utf-8:
`content-disposition: attachment; filename*=utf-8''test.pdf`
![Снимок экрана 2021-12-28 в 14 51 44](https://user-images.githubusercontent.com/72597181/147563574-9cda280e-a647-4850-8b46-877cce9679b6.png)

PR: https://github.com/mrin9/RapiDoc/commit/efdcf9840ebd70781b7d5168de030f59664f1c76

**Comment by mrin9** [comment]
closed by PR: https://github.com/mrin9/RapiDoc/commit/efdcf9840ebd70781b7d5168de030f59664f1c76
