### ISSUE TITLE
Authorization is not work after change spec-url use loadSpec

### ISSUE THREAD

**Issue by GloriaCHL** [mrin9/RapiDoc#62]
Hi, I change `spec-url`  value and use `loadSpec`  to reload the new swagger file. But after change, the authorization is not work.

HTML:
```html
<rapi-doc
  spec-url="/v2/api-docs"
  theme="dark"
  id="rapidoc"
  show-header="false"
  show-info="false"
>
  <header>
    <select name="" id="apis">
      <option value="/v2/api-docs">/v2/api-docs</option>
    </select>
  </header>
  <div style="height: 60px" slot="footer"></div>
</rapi-doc>
```

JS:
```js
function setApiKey(){
    const docEl = document.getElementById('rapidoc');
    const authToken = JSON.parse(localStorage.getItem("authenticationToken") || sessionStorage.getItem("authenticationToken"));
    docEl.setAttribute('api-key-name','Authorization');
    docEl.setAttribute('api-key-location','header');
    docEl.setAttribute('api-key-value', `Bearer ${authToken}`);
  }

  document.addEventListener('DOMContentLoaded', e => {
    setApiKey();
    createSelector();

    const selector = document.getElementById('apis');
    selector.onchange = function(e) {
      const value = e.target.value;
      const docEl = document.getElementById('rapidoc');
      docEl.loadSpec(value);
    }
  })
```

Before change I can find `Authorization` in request header but cannot find it after change, and the request return 401.

**Comment by mrin9** [comment]
the default behavior  is to reset  `'api-key-name', 'api-key-location' and 'api-key-value'` whenever you load a new spec ( _make a call to `loadSpec()`_)
but I think you are correct, I shouldn't be reseting those attributes on `loadSpec()`. 
 
for now, in your above code please call `setApiKey()` after you call `loadSpec()` and i will get this working as expected soon

**Comment by GloriaCHL** [comment]
Thank you for your support. And now, I will use reload page to resolve my problem.

**Comment by mrin9** [comment]
This should now be working as you expect in release `6.0.0`. Let me know if it takes care of your issue
