### ISSUE TITLE
New event.detail.request is ignored in before-try

### ISSUE THREAD

**Issue by jstirnaman** [mrin9/RapiDoc#621]
I'm trying to use a `before-try` listener to replace the server URL with a proxy URL. Am I assigning it wrong or missing something?

Thanks!

Problem: The docs (https://mrin9.github.io/RapiDoc/api.html#methods) state that the Request object can be modified during `before-try` and used to make the request. However, the Request object is immutable. If I replace event.detail.request with a new Request object (that contains my new URL), the old/default URL is still used instead.

Steps:
1. Code example below.
2. The handler runs before the request is made.
3. The handler successfully creates the new object.

Expectation: The request URL should be my new, modified proxy URL.

Example:
```
function handleBeforeTry(event) {
  console.log('before try...')
  if(!event?.detail?.request) {
     return;
  }
  const proxyBaseUrl = 'http://localhost:3000/doc-proxy';  //rapidoc URL
  try {
    /** Create proxy URL. **/
    const apiUrl = new URL(event.detail.request.url);
    const proxyUrl = new URL(`${proxyBaseUrl}${apiUrl.pathname}${apiUrl.search}`);
    /** Clone the request, but use the new URL. **/
    const request = new Request(proxyUrl.toString(), event.detail.request);
    event.detail.request = request;
    console.log(event);
  } catch {
    console.log(event);
    console.error('Failed to create the proxy URL from the request.');
  }
}

current.addEventListener('before-try', (e) => {
  handleBeforeTry(e);
});
```

**Comment by mrin9** [comment]
you may not replace Request object which you are trying to do by creating a new request object. Instead you may modify the existing request object (i,e) change its attributes etc.
