### ISSUE TITLE
Specify accept in file inputs

### ISSUE THREAD

**Issue by ObserverOfTime** [mrin9/RapiDoc#624]
RapiDoc should check if a [`contentType`](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#encoding-object) is available for any given binary field in a multipart request body and use it to set the `accept` attribute of the input element so that the selection dialog can properly filter the files.

**Comment by mrin9** [comment]
RapiDoc do not put any constraints on the UI, even when it is specified in the spec. 

The reason for doing so is, coz, many of our users/developers use it for testing their APIs. Therefore it allows user to provide incorrect values and test out how the API responses are received.

It is not the goal of RapiDoc to become a perfect client for the APIs. Instead it helps in quick and dirty testing of APIs

**Comment by ObserverOfTime** [comment]
> The `accept` attribute doesn't validate the types of the selected files; it provides hints for browsers to guide users towards selecting the correct file types. It is still possible (in most cases) for users to toggle an option in the file chooser that makes it possible to override this and select any file they wish, and then choose incorrect file types.
