### ISSUE TITLE
Rendering of schema titles

### ISSUE THREAD

**Issue by mol-pensiondk** [mrin9/RapiDoc#626]
Titles from schemas are not rendered. I would expect them to be renderes as a title above the description (if any). According to the OpenAPI spec, the title property of schema elements are "as is" from JSON schema, i.e. it is supposed to be a one-line description of the schema. The description property is for longer descriptions (and may use MarkDown in OpenAPI - which the title may not!).

Screenshots are using the rapidoc js file from the playground (actual rendering) and from using a locally modified one from the PensionDanmark doc site (expected rendering).

The OpenAPI spec is "titles.json" (attached as [titles.txt](https://github.com/mrin9/RapiDoc/files/7704728/titles.txt)).

Expected rendering, inline schemas:
![expected1](https://user-images.githubusercontent.com/96067271/145836499-b3011c68-b984-4965-b366-5fb75220960e.PNG)
Actual rendering, inline schemas:
![actual1](https://user-images.githubusercontent.com/96067271/145836662-351da626-b22c-45ab-82b9-a47bb4e15ff8.PNG)

Expected rendering, schemas in components:
![expected2](https://user-images.githubusercontent.com/96067271/145836753-f88837a4-ab66-4a2a-9326-2507dcbf8241.PNG)
Actual rendering, schemas in components:
![actual2](https://user-images.githubusercontent.com/96067271/145836842-bf8b6bfd-6e9a-44cf-a2b9-f94d8ffec7fe.PNG)

Expected rendering, schemas section:
![expected3](https://user-images.githubusercontent.com/96067271/145838439-c5a7de62-0f51-41d1-be4e-0556fb7c4d0b.PNG)
Actual rendering, schemas section:
![actual3](https://user-images.githubusercontent.com/96067271/145837047-4e2f530e-9fe7-491a-a848-4a95e12c1c15.PNG)

**Comment by mrin9** [comment]
Thanks for the suggestions and screenshots !!!. 

I have made a note of it and will be addressing them over several commits

**Comment by mrin9** [comment]
Thanks for the detailed test case and spec...made it easy for us to test it

https://mrin9.github.io/RapiDoc/examples/schema-title-and-descriptions.html

**Comment by mol-pensiondk** [comment]
Great!

I see that you incorporated the title into the text as a markdown title. I guess that to ensure correct rendering, you would have to “markdown-escape” the title? I guess a title could contain characters that the markdown formatter would interpret as markdown, even though they are not intended as such, and that would potentially interfere with the rendering of the entire description?

Med venlig hilsen / Kind regards

Morten Larsen

________________________________

Bemærk
Denne e-mail og vedhæftede filer er alene forbeholdt den person eller enhed, som e-mailen er stilet til. E-mail og vedhæftede filer kan indeholde personlige og fortrolige oplysninger. Er du ikke den rette modtager, bedes du bemærke, at enhver udbredelse, distribution eller kopiering er forbudt. Har du modtaget denne e-mail ved en fejl, bedes du underrette afsender om det straks og derefter slette e-mail og vedhæftede filer fra dit system.

Disclaimer
This transmission is intended solely for the person or entity to whom it is addressed. It may contain privileged and confidential information. If you are not the intended recipient, please be notified that any dissemination, distribution or copying is strictly prohibited. If you have received this transmission by mistake, please let us know and then delete it from your system.
Fra: Mrinmoy ***@***.***>
Sendt: 24. februar 2022 07:13
Til: mrin9/RapiDoc ***@***.***>
Cc: Morten Larsen ***@***.***>; Author ***@***.***>
Emne: Re: [mrin9/RapiDoc] Rendering of schema titles (Issue #626)


Thanks for the detailed test case and spec...made it easy for us to test it

https://mrin9.github.io/RapiDoc/examples/schema-title-and-descriptions.html<https://url12.mailanyone.net/v1/?m=1nN7Ny-0004On-5d&i=57e1b682&c=0ahr-MvaUOQUebQ1utx8WtSUQtYZi696_lE5xUFoPnZUGLnzLC-pp6lBwOPXYquhT60tpUZ9ZbvHSZklH9QEUZtY3K8SlTKxgdqdIDwavzjMrfFJ2o_jN20aU4ZvusqKYJIKA_ZB2T4w9aL5H03Timb3pK2ajeq-C-P88AsT82R4iGgke1U7QN9jJds35ad_Ra_KRJxd6kWDDRzdm4ZTAmEjPnn-CmnHwkaFdPTV60yAdKu9_p0ZGL0y5HOMFqkymJjE4FiIfL3wYsL9BxbdYg>

—
Reply to this email directly, view it on GitHub<https://url12.mailanyone.net/v1/?m=1nN7Ny-0004On-5d&i=57e1b682&c=OCKnSJYEaiC8klxrS6QpNwIUpFXp-aHd7R_SpSbwJ6FVRzo38y5Hxzhib7rFP_AzBfrDuVuA1yGSj30L3FPU_Urq20BcIZV4UTBzTvwddqPpk0sv9qkGW6ZCzuofopmNXHgXQ6Bq9T3OLlh1ejhHNfoS4A04XvlJF1U5emYdc8wyF2twT9c6TQclRPnVmHhOPTvqBK0Q5TSAIU0MDaERcUX4sIq3i6m4rq3jlUFRgVnIAjtLwFxssi3GGozANxKdrFvn-t2wBaAYsf3Tk7rdAg>, or unsubscribe<https://url12.mailanyone.net/v1/?m=1nN7Ny-0004On-5d&i=57e1b682&c=YEpjJ1-5Rc7X1kWBwZjzbxE00UU5wnpEtDKTx5177mOnoOogAMqjPjvhBIxnjxoqSBUuR4Za2tSOX_kECWuYVpQvaFXxE0_iNZGovlcE0h-jgJso5gHZaRWH6oXXwEQj37T782CAGdKcT1bqCVP2PJITTtEqIAZ2ICv8hE3SloLhhoq8fSUPsZyMX-B7ggDureYb0KjRInOoPqeEHyC_daqpyRhRWId_S1h4A33LaYTWToK1XcMrqU3qaHrRF9ZEGVjYIe7sGBcYVSbYcUDHy94Lq9ECmai-snDXFPaTmx4>.
Triage notifications on the go with GitHub Mobile for iOS<https://url12.mailanyone.net/v1/?m=1nN7Ny-0004On-5d&i=57e1b682&c=jU_aaVVvU7xYVuPN0svw-AwoHWzCSG-A6G4ELY-foN7nJqmnXy04dzgxbx7Jw67313OtjptTJOX2ejyriBlRvPItbwL6Ra9sx68BGvBl-hPTPt536i3ProOB3GOqWty3cEFGAQTbzwq7qiIlj013i70_qDuCh1EwTEUahoR4WATekDoXaiEwvch_EVZxkVhzTaV7OPoPlggs2YoxEh3yzJUaudh5qh7qtI6jFWN-7LjD14AGw4Av3wBpltUBAyibMDTxsL74niUDq7t8rtth1L9Rgw97xS9tG-Rti_t1oeU> or Android<https://url12.mailanyone.net/v1/?m=1nN7Ny-0004On-5d&i=57e1b682&c=boXUyKBtXpUC8jrdV3_uVYb29wpsoyEF_518ZNRI5_03uLVi5xUYKlGlWsuRvJ5ou2XggYs-DGyvf3nrrsj3vvF3ko2UoJuifob0JXe0yFalM3huH0XRfGiUxwZoUv5QlJ7lR4DvFkNEjX6Sfw99AGaDWpmHAYihxMCmiCsbjWfQiahHa3eo-y_JbD1JWTuvi4d1ryskikEd6tITg5teHzHxFVhf4gOtIHu-V1pwqw4Ozz2v70dv9ho8wgnL0HmGzckk1ratNo2Z4pCNYac8nsXAf4mRW_inSVlD4Rb7QIB5QQX-otQrO0zUmi0lWFo9Lg9PoqH7OYeV4OuuFYrE5xFfd8hJwAlPxh2AqgbTFHEVgXzLXt-V7Lk5Grmh4b-a>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

________________________________

Bemærk
Denne e-mail og vedhæftede filer er alene forbeholdt den person eller enhed, som e-mailen er stilet til. E-mail og vedhæftede filer kan indeholde personlige og fortrolige oplysninger. Er du ikke den rette modtager, bedes du bemærke, at enhver udbredelse, distribution eller kopiering er forbudt. Har du modtaget denne e-mail ved en fejl, bedes du underrette afsender om det straks og derefter slette e-mail og vedhæftede filer fra dit system.

Disclaimer
This transmission is intended solely for the person or entity to whom it is addressed. It may contain privileged and confidential information. If you are not the intended recipient, please be notified that any dissemination, distribution or copying is strictly prohibited. If you have received this transmission by mistake, please let us know and then delete it from your system.
