### ISSUE TITLE
ApiKey is prefixed with %20 in query

### ISSUE THREAD

**Issue by umeckel** [mrin9/RapiDoc#630]
If i enter a api key as query parameter its always got prefixed with an %20.

Occurs in 
- 9.1.3,
- 9.1.2, 
- 9.1.1 and 
- 9.1.0 

but not in 9.0.0

**Comment by afranke** [comment]
Already fixed in master, by 06137450de5014435e90cbe76d7f7f7a262668a6. Duplicate of #570
