### ISSUE TITLE
Is there a good way to connect some static pages to the API references?

### ISSUE THREAD

**Issue by anador** [mrin9/RapiDoc#633]
I`m wondering if there is already a good solution how we can extend the API reference documentation generated with RapiDoc and add some pages with custom content (e.g. markdown) to cover some other topics about the API?
These pages are sometimes called API conceptual topics, e.g. overview, rate limits, quick start, FAQ, glossary etc.
The thing is how to made them look not different from API reference to not confuse users and to not overengineer the idea. Just thinking if someone already thouth about this and maybe there is handy solution

**Comment by mrin9** [comment]
Did you looked at 
- HTML Slot injection https://mrin9.github.io/RapiDoc/examples/slots.html
- Mini RapiDoc https://mrin9.github.io/RapiDoc/rapidoc-mini.html
- Use Markdown to list your sections on the navbar https://mrin9.github.io/RapiDoc/examples/markdown-headings.html#overview--documentation

**Comment by anador** [comment]
Hi!
Thanks for the reply.
Yeah, I did look through that variants and figured out that the one with Markdown sections is the most useful in our case.
By using this one we can add any information we need and do it in a long-page-way which is ok
Just had a thought myabe there any other handy options, because this idea (of adding conceptual topics) is kinda common and i don`t think i`m the first one who faced this question.
Anyway thanks for your help.
