### ISSUE TITLE
How to Convert API data in openAPi specification Formate

### ISSUE THREAD

**Issue by sundershyam** [mrin9/RapiDoc#636]
I need help in converting my API data which is coming from backend in react JS because Rapidoc accepts only open API specifications json format

Please Feel Free to contact if anyone have answer it's urgent :- 
shamsundertejpal@gmail.com 
9816464912

**Comment by mrin9** [comment]
If you like to generate OpenAPI spec of your backend APIs then depending upon your backend language there are other framework which can do the job.
RapiDoc is not a server-side tool nor it can convert/generate your backends APIs to OpenAPI
