### ISSUE TITLE
Aborting try-it-now API call

### ISSUE THREAD

**Issue by ryanolsonx** [mrin9/RapiDoc#637]
Hello!

I have a case where I'm using the "before-try" event to add some headers that are gathered in a form I'm embedding in the "auth" slot. Is there any way to abort/cancel the API call that is about to send? I'd really like to abort the API call if they don't have their auth all set up as they need it.

Thanks,
Ryan

**Comment by mrin9** [comment]
check out the our [API - Events](https://mrin9.github.io/RapiDoc/api.html#events) section to see how to abort

**Comment by ryanolsonx** [comment]
Thank you so much
