### ISSUE TITLE
Adding a custom section

### ISSUE THREAD

**Issue by ryanolsonx** [mrin9/RapiDoc#638]
Using render-style "read", there's the left navigation area. Is there a way to add a custom navigation area within there?

For example, after Overview, I might like to add a section called "Standard Error Responses." This navigation item would navigate to a space on the right side where there's some documentation that talks about how errors from the API can be handled properly. 

I have a few use cases where something like this would be valuable. It would nice if there were slots over there (besides nav-logo)

**Comment by ryanolsonx** [comment]
I understand from the https://mrin9.github.io/RapiDoc/examples/markdown-headings.html#overview--our-story example that we're able to add this sort of thing from the spec, but I'm curious about a different way (if there is one).

**Comment by mrin9** [comment]
you may use markdown headings to create navigation items
checkout this example https://mrin9.github.io/RapiDoc/examples/markdown-headings.html#overview--how-to-use-apis

refer to `info-description-headings-in-navbar` attribute in our [API section](https://mrin9.github.io/RapiDoc/api.html)

**Comment by ryanolsonx** [comment]
Thank you. That seems to accomplish what I'm looking for.
