### ISSUE TITLE
unminified js

### ISSUE THREAD

**Issue by Aloren** [mrin9/RapiDoc#639]
Hi!
First of all thank you for such a great tool and especially documentation and demos :) They are very useful!

I'm quite novice to JS and my question may be quiet dumb for the experts :)
I'm currently debugging my custom page that aggregates multiple rapidocs and have issues with understanding how focus works. Debugging rapidoc-min.js is completely impossibble (even beautified by chrome). So my question is where I can find/how to build nonminified version of rapidoc? 

Thanks!

**Comment by mrin9** [comment]
you may build the non-minified version at your end. to do that clone the repo and 

update `webpack.config.js` to remove minification. 
for that you need to replace [this](https://github.com/mrin9/RapiDoc/blob/master/webpack.config.js#L83-L92) part with below snippet
```
optimization: {
  minimize: false,
}
```
after this you may build by using 

```
npm install
npm run build
```

this will produce the non-minified js under the `dist` folder. use this in your html

**Comment by Aloren** [comment]
Thanks @mrin9, I will try this.

I've found the following feature: https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/
and I wonder why rapidoc-min.js.map was removed in 9.1.3 version? https://packagegalaxy.com/javascript/rapidoc

**Comment by mrin9** [comment]
>  I wonder why rapidoc-min.js.map was removed in 9.1.3 version?

It is un-intentional and It could be due to some glitch with out build pipeline.

on checking the [config](https://github.com/mrin9/RapiDoc/blob/master/webpack.config.js#L77) still contains the option to build source-maps and it is building too.

Will keep an eye on this next time we release
