### ISSUE TITLE
selectedServer undefined after 6.0.0 release

### ISSUE THREAD

**Issue by peterbroadhurst** [mrin9/RapiDoc#64]
After the release of v6.0.0 we have problems with our hosted RapiDoc based documentation, and it seems to be related to the change in:
https://github.com/mrin9/RapiDoc/commit/5da2c44b51bd357079b615e02b52b63693c9c164

From:
https://github.com/mrin9/RapiDoc/blob/8057012c7b1a45ddfe7b0e50ad46f25be33b8be4/src/rapidoc.js#L642-L648
To:
https://github.com/mrin9/RapiDoc/blob/5da2c44b51bd357079b615e02b52b63693c9c164/src/rapidoc.js#L720-L724

Combined with the fact that the initial `setTimeout()` call to `onApiServerChange()` is not passing the value of the first server in:
https://github.com/mrin9/RapiDoc/blob/8057012c7b1a45ddfe7b0e50ad46f25be33b8be4/src/rapidoc.js#L705-L707

So this means the initial value of the `selectedServer` is `undefined`

**Comment by peterbroadhurst** [comment]
Clicking the radio button next to the single server defined in the OpenAPI doc, resolves the issue.
So a related issue, is that  that `checked` is no longer set on the first URL:

See:
https://github.com/mrin9/RapiDoc/blob/5da2c44b51bd357079b615e02b52b63693c9c164/src/rapidoc.js#L510

`this.selectedServer === server.url` does not evaluate true, as `this.selectedServer` is not set.

The code that would set an initial value for `selectedServer` is not evaluated, as `allowServerSelection` is at the default value (true).
https://github.com/mrin9/RapiDoc/blob/5da2c44b51bd357079b615e02b52b63693c9c164/src/rapidoc.js#L776-L782

**Comment by mrin9** [comment]
thanks for investigating this,
can you try if it works by supplying an `default-api-server` attribute to the `<rapi-doc>` element 

```
<rapi-doc sec-url='...' default-api-server = 'http://example.com/api'> </rapi-doc>
```
Will be releasing our first patch in about 10 days. will address it in that

**Comment by sebastianvoss** [comment]
I can confirm the issue. When setting `default-api-server` it works as expected. But this requires hardcoding the desired server in HTML, rather taking it from the OpenAPI spec. So, a fix would be highly appreciated.

**Comment by peterbroadhurst** [comment]
Thanks @mrin9 for the quick response on this, I really appreciate it.
I have updated the PR code to honour `default-api-server`, and tested that.

I agree with @sebastianvoss that rolling out a more urgent fix for this issue would be extremely helpful, as this breaks code that is running for us in production. Changing the wrapping HTML package that imports RapiDoc (to generate + set a `default-api-server`, or roll back to 5.3.1) is not an immediate fix for us - as that would require us to roll out a fix to all affected environments that generate the simple HTML wrapper.

There is a workaround for our users of clicking the 🔘 manually next to the server to make the interface work, but that's unlikely to be noticed directly by our users.

I note rolling the main `https://unpkg.com/rapidoc/dist/rapidoc-min.js` redirect back to 5.3.1 would address this change in behavior too, if that is an easier solution than rolling out a `6.0.1` patch.

**Comment by sebastianvoss** [comment]
@mrin9 Thanks for pushing a release. It fixed the issue.
