### ISSUE TITLE
CURL for try-it-now doesn't include custom headers from "before-try" event

### ISSUE THREAD

**Issue by ryanolsonx** [mrin9/RapiDoc#640]
After using try-it-now, the CURL tab creates a curl to run to recreate the request. For my use case, I add a custom header for x-api-version. I add this using the "before-try" event. Is there any way that the curl tab could include those custom headers added?

**Comment by mrin9** [comment]
I dont think we would be able to support that. `before-try` event can contain arbitrary peace of code including usage of frameworks such as React, Vue, JQuery etc and it wont be possible for us to parse that code and make sense of it.

**Comment by ryanolsonx** [comment]
Can we possibly add a way to provide custom headers for each "Try" request? (I'd even be willing to do the dev work)

**Comment by mrin9** [comment]
this should be done using OpenAPI spec
- either you add HeaderParams (like you add query params)
- or you can define multiple security tokens for specific end points

here is an example that contain each endpoint having different security needs. 
https://mrin9.github.io/RapiDoc/examples/auth.html#get-/users 
![image](https://user-images.githubusercontent.com/5056899/150674121-bcada723-ad4e-4a1d-8bd2-e6967ff70a22.png)

**Comment by ryanolsonx** [comment]
To give a little more context, we are using slots to provide some forms. Based on those forms (which call an API), we'd like to be able to set the auth token (for bearer token authentication), version of the api, and another id. These values are passed to every API endpoint and so that's why we've been using the "before-try" event handler. So it would be nice to be able to handle this for our API users behind the scenes.

**Comment by peebles** [comment]
Back to the original question; couldn't you just execute the before-try function to get the request.headers before showing the curl command?  I can't even see the "curl" snippet until after I "try".  I sure would be useful to include the headers for the curl snippet.
