### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by majoshi1** [mrin9/RapiDoc#644]
Two suggestions:
-Create new Search button, that works same as enter key.
-Change title of current search button to "Adv. Search", with tooltip of "Advanced Search".

e.g.
[______________________]    [Search]  [Adv. Search]

**Comment by mrin9** [comment]
not sure whats the intent here, we cannot create a new search button that works same as enter key, thats for filtering.

`search` and `filter` are two different functionality

- Clicking search opens the search dialog
- Typing on filter text-box and pressing enter filter out the links on the navigation bar 

feel free to recreate another issue if there is something missing in my explanation
- please provide the actual intent of the UI change
- explain the problem it solves
- provide the pain point of the existing UI
