### ISSUE TITLE
Lock icon

### ISSUE THREAD

**Issue by majoshi1** [mrin9/RapiDoc#645]
The right panel shows lock icon. Two comments:
-Can it show un-lock icon, when one more api key is added?
-If that is not possible, then can it be hidden altogether?

**Comment by mrin9** [comment]
the purpose of Lock icon is to indicate if the end point is secured or not. If not present it indicates the endpoint do not need any api-key or any other security therefore we wont show/hide based on what keys are applied.  

in case you are trying to figure out what keys are applied to an end-point you can check it by looking under the API server shown at the bottom of the Request section

![image](https://user-images.githubusercontent.com/5056899/151353119-e35f4e34-f9c1-4f92-9445-35cc205429fa.png)
