### ISSUE TITLE
Filter & Search features

### ISSUE THREAD

**Issue by majoshi1** [mrin9/RapiDoc#646]
Currently, filter text box and search button are next to each other. This creates confusion to users. So here are few suggestions:
-Replace Search button by a text box, with lens icon on left and enter icon on right. When clicked or focused, show search popup. Then user can type and search as usual.
-Add filter icon to left of filter text box, to differentiate both features.
e.g.
[F____E]  [L_____E]

F - Filter icon.
E - Enter icon.
L - Lense icon.

**Comment by mrin9** [comment]
so let me know if I get the suggestion correct 

below is how the filter/search panel look like

![image](https://user-images.githubusercontent.com/5056899/151351258-2576eed0-d5cb-4478-923b-a5bcb6594271.png)

- Suggestion 1: Get rid of the search button and put a text-box. And even though its a text box it will work like a button. That is on clicking it you wont be able to type anything in it, instead it will open up the search dialog (just how a button would work)

- Suggestion 2: get rid of the place-holder text which says `Filter` instead put an Filter Icon 
 
I am going to pass this feedback to our UX team, along with the fact that some may find it hard/confusing to differentiate between filter and search. 

I will close this one here and let see what our UX say on that
