### ISSUE TITLE
Path parameters are not rendered correctly

### ISSUE THREAD

**Issue by schnes4** [mrin9/RapiDoc#648]
Hi,

we faced an issue where the path parameters of our specifications are not rendered correctly sometimes.
After a while of researching we find out, that rapidoc won't interpret the references in the parameter sections after the first usage.

<details>
  <summary>Example api specification json</summary>

```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "test",
    "description": "This is an example",
    "version": "1.0.0"
  },
  "paths": {
    "/twoPathParams/{param1}/{param2}": {
      "get": {
        "description": "a sample description",
        "parameters": [
          {
            "$ref": "#/components/parameters/param1"
          },
          {
            "$ref": "#/components/parameters/param2"
          }
        ],
        "responses": {
          "200": {
            "description": "get exampleResponse"
          }
        }
      },
      "delete": {
        "parameters": [
          {
            "$ref": "#/components/parameters/param1"
          },
          {
            "$ref": "#/components/parameters/param2"
          }
        ],
        "responses": {
          "200": {
            "description": "delete exampleResponse"
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "param1": {
        "description": "param1 sample description",
        "name": "param1",
        "in": "path",
        "required": true,
        "schema": {
          "$ref": "#/components/schemas/param"
        }
      },
      "param2": {
        "description": "param2 sample description",
        "name": "param2",
        "in": "path",
        "required": true,
        "schema": {
          "$ref": "#/components/schemas/param"
        }
      }
    },
    "schemas": {
      "param": {
        "allOf": [
          {
            "pattern": "^[a-z0-9.~_-]+$"
          },
          {
            "maxLength": 256
          },
          {
            "type": "string",
            "example": "example-example",
            "description": "example description"
          }
        ]
      }
    }
  }
}
```
</details>

This specification contains two endpoints (`GET` and `DELETE`) of `/twoPathParams/{param1}/{param2}` with the two params `param1` and `param2`.
Both endpoints references the same params.

If I open this specification json in the rapidoc Docker container with

```bash
docker run --rm -ti -p 8080:80 mrin9/rapidoc:v9.1.4
```

rapidoc renders the first usage of the params correctly

![Screenshot 2022-02-01 at 12 03 28](https://user-images.githubusercontent.com/23531340/151957439-77d6c2e3-23dd-449a-a2d0-bd22499737ed.png)

but not the second usage of the params

![Screenshot 2022-02-01 at 12 03 36](https://user-images.githubusercontent.com/23531340/151957471-beaa15bc-4e18-46da-88d2-b0492a3d4c0a.png)

Could you please check this?

**Comment by mrin9** [comment]
thanks for pointing ... i think this is stemming from one of our dependency on https://github.com/swagger-api/swagger-js
which is unable to parse the spec.

But let me confirm back in a week, if thats really the case, and we can raise an issue with them

**Comment by mrin9** [comment]
use the lates build from `dist` folder to test it

**Comment by schnes4** [comment]
I could verify it with the current master.
Thanks for the fast support!

Is there already a timeline for the next release?
