### ISSUE TITLE
Try Feature not working when Schema tab is selected for POST request

### ISSUE THREAD

**Issue by bluesage13** [mrin9/RapiDoc#651]
Hi,
We are facing an issue when using RapiDoc's Try feature, specifically for POST request. We are using RapiDoc with:
1. render-style as "VIEW"
2. fill-request-fields-with-example as "true"
3. default-schema-tab as "example"

Whenever we try to use the TRY feature with the EXAMPLE tab open in request section, we get response as expected. But if we open the Schema tab in Request section and use click on the Try button, we get invalid_json error response.

Our request body is of type : application/json
 I can see that in cURL command, the -d is not added when Schema tab is open, but is present whenever Example tab is open.

Is there a way to maybe disable the try feature when schema tab is open or any other solution?

**Comment by mrin9** [comment]
There is none at the moment but I will soon fix it

**Comment by mrin9** [comment]
We did a little user survey on this after we created a fix, the feedback we received is that 
- Most users were not able to figure out why `TRY` button is disabled in certain cases
- Some users would like to retain the ability to call API without any request-body and test out how it behaves

So at the moment we decided to make the `EXAMPLE` Tab the first and default one. That way if some one is directly clicks on TRY button will have expected result, however if they deliberately change to `SCHEMA` tab it is rather simple to reason out why the Request Body is not getting  submitted.

I will be closing this now. However if you have some better idea, please do share by opening a new Issue
