### ISSUE TITLE
How does Rapidoc behave under huge load ~>10,000 concurrent users?

### ISSUE THREAD

**Issue by gaoyan198** [mrin9/RapiDoc#652]
Hi rapidoc team, thanks for open sourcing such a great product for api documentation with minimal setup process. I am having question with how does the custom tag perform under scale? Sorry if it is a basic question am not very familiar with custom tags.
Thanks in advance

**Comment by mrin9** [comment]
RapiDoc (Custom Element) runs on the browser, therefore it doesn't matter if there are 10.000 or 1 million users, each user wud be running RapiDoc on their own respective browser and therefore will not have any scalability issues
