### ISSUE TITLE
Click to expand and show description

### ISSUE THREAD

**Issue by majoshi1** [mrin9/RapiDoc#653]
As part of request in issue #419, a new feature was added and a sample was provided:
https://mrin9.github.io/RapiDoc/examples/tag-focused-mode.html#overview

Is it possible to combine both features? So, a click will both expand and show summary page.

**Comment by mrin9** [comment]
if you follow the discussion at #419 what was decided is not to show tag description in `focused` 

We may try to change few things around it but nothing is concrete enough to share anything
We do have an internal issue open over this so closing this one
