### ISSUE TITLE
Filter & Search

### ISSUE THREAD

**Issue by majoshi1** [mrin9/RapiDoc#656]
Filter and search are confusing new users.
Two suggestions:
- Add a button next to filter text box, with label "Filter".
- Change current search button to a hyper-link.
![image](https://user-images.githubusercontent.com/292394/153011200-49a2ebc9-1d69-4d19-a48a-b80c470f8661.png)

**Comment by mrin9** [comment]
UI changes that alters workflows are driven by our UX team based on our client survey. Filter and search  has created some confusion and we have made few changes in the past based on our users feedback which is what you see today.  It wont be easy to discard all that and change it 

However, you can always remove the confusion by hiding one of them as shown here
https://mrin9.github.io/RapiDoc/examples/search-by-params.html#overview

I have forwarded your feedback to our UX team, they will make a call on what can be done with it
