### ISSUE TITLE
Redirect url

### ISSUE THREAD

**Issue by majoshi1** [mrin9/RapiDoc#657]
Currently, the redirect url can only be appended. Is it possible to set complete url?

Current:
```<rapi-doc oauth-receiver="/oauth-page" . . . ```

Proposed:
``` <rapi-doc oauth-receiver-url="https://example.com/oauth-page" . . . ```

**Comment by mrin9** [comment]
Its designed in a way that it mandates it to be in the same folder as your main API Doc HTML as they both need to communicate.
May I know, what problem are you facing to have API-Doc html and  `oauth-receiver.html` in the same folder ?

**Comment by majoshi1** [comment]
Current oauth flow:
-When user clicks "Get Token", a new page is opened.
-The new page obtains auth code and redirect to oauth-receiver.
-Oauth-receiver extracts auth code and call parent rapidoc and close itself.
-Rapidoc obtains token using auth code.

Proposed oauth flow:
-When user clicks "Get Token", a new page is opened.
-The new page obtains auth code using a xhr call.
-The redirection request is submitted as an xhr request, without actual redirection in browser.
- The same page collects auth code, as part of response handling.
-Oauth-receiver extracts auth code and call parent rapidoc and close itself.
-Rapidoc obtains token using auth code.

The reason for change in flow is to avoid extra redirection. But this also needs overriding of redirect-url as same redirect-url is used by both auth code and token requests. Please get back in case of any further questions.

**Comment by mrin9** [comment]
> The reason for change in flow is to avoid extra redirection.

There is no **Extra** call in the original flow. What you are proposing is to replace URL-Redirection with XHR _(which I am not sure why the ask is)_

> The new page obtains auth code using a xhr call.

If you are dealing with an OAuth2 compliant security system, then AFAIK there is no way you can avoid `redirect-url`. All OAuth2 providers sends token only to `redirect-url` unlike XHR where you get the token on any arbitrary system where you are making the call from. https://www.oauth.com/oauth2-servers/redirect-uris

Now, lets say you are able to get a token using XHR call and you would like to apply this token to one of the security-scheme defined in your spec, then you may use [`setApiKey()`](https://mrin9.github.io/RapiDoc/api.html#methods) method of `<rapi-doc>` to do that
