### ISSUE TITLE
Change Logo not working

### ISSUE THREAD

**Issue by gaoyan198** [mrin9/RapiDoc#660]
Hi , I was following the Change Logo demo and it does not work (still the default logo)
<img width="807" alt="image" src="https://user-images.githubusercontent.com/48423809/153109514-1b8746a2-945c-4edf-ac50-b3f8561325d4.png">

When clicked into the demo and inspecting element, the sample provided does not seem to have img tag within the rapid-doc tag.

<img width="591" alt="image" src="https://user-images.githubusercontent.com/48423809/153109616-77e59d03-a373-431d-9764-873e035ec684.png">

**Comment by mrin9** [comment]
thanks for bringing it up. It was not documented properly.  `<rap-doc>` element had a misplaced closing tag
it is fixed now as shown below

<img width="801" alt="image" src="https://user-images.githubusercontent.com/5056899/153126979-a038167f-2e25-48a8-bda0-e71a0d7d03a7.png">
