### ISSUE TITLE
Doc references no Docker tag whereas latest does not exist

### ISSUE THREAD

**Issue by b2p-fred** [mrin9/RapiDoc#664]
As of #158 you choose to not publish a latest tag Docker image ... but the documentation about the Docker use of Rapidoc is not correct because no tag is specified.
One should run : 
```
$ docker pull mrin9/rapidoc:v9.1.4
```
but the documenation says:
```
$ docker pull mrin9/rapidoc
```

IMHO you should publish a Docker image with a release number and then tag it as the latest image :wink:

**Comment by mrin9** [comment]
thanks for bringing it up. 
I have generated one with `latest` tag 
 
> PS: We lost the automatic build and tagging functionality on docker-hub since it stopped providing that functionality for `free` and as well as in `basic` plan. we need to figure out an automated way of doing this using our `basic` plan

**Comment by b2p-fred** [comment]
Perhaps it should be possible to build the Docker image in the Github actions and then push to your Docker hub account ? 

I am not very aware about this because I am using Gitlab and my own Docker registry ...
