### ISSUE TITLE
Wrong destructuring after upgrading to eslint 8

### ISSUE THREAD

**Issue by micheletriaca** [mrin9/RapiDoc#667]
Hi,
In the master branch I've noticed a couple of regressions (wrong object destructuring) after the last few day changes:

https://github.com/mrin9/RapiDoc/blob/2d412e84147793a10d9c511135fd8be70291dd44/src/components/api-request.js#L1114
https://github.com/mrin9/RapiDoc/blob/2d412e84147793a10d9c511135fd8be70291dd44/src/templates/security-scheme-template.js#L256

Again, thank you for the great contribution. RapiDoc has completely substituted swagger UI in my stack

**Comment by 0x78f1935** [comment]
Hi,

I'm using the CDN. "https://unpkg.com/rapidoc/dist/rapidoc-min.js"
Last time I checked if everything was working was last Friday. Now I encounter the following error.

```
rapidoc-min.js:2 Uncaught (in promise) TypeError: Cannot destructure property 'authorizationUrl' of 'a.authorizationUrl' as it is undefined.
    at WR.zP (rapidoc-min.js:2:334547)
    at rapidoc-min.js:2:341670
    at Array.map (<anonymous>)
    at rapidoc-min.js:2:341659
    at Array.map (<anonymous>)
    at WR.UP (rapidoc-min.js:2:339292)
    at WR.VR (rapidoc-min.js:2:475614)
    at WR.render (rapidoc-min.js:2:488782)
    at WR.update (rapidoc-min.js:2:17083)
    at WR.performUpdate (rapidoc-min.js:2:14034)
zP @ rapidoc-min.js:2
(anonymous) @ rapidoc-min.js:2
(anonymous) @ rapidoc-min.js:2
UP @ rapidoc-min.js:2
VR @ rapidoc-min.js:2
render @ rapidoc-min.js:2
update @ rapidoc-min.js:2
performUpdate @ rapidoc-min.js:2
_enqueueUpdate @ rapidoc-min.js:2
await in _enqueueUpdate (async)
loadSpec @ rapidoc-min.js:2
await in loadSpec (async)
(anonymous) @ rapidoc-min.js:2
setTimeout (async)
attributeChangedCallback @ rapidoc-min.js:2
310 @ rapidoc-min.js:2
a @ rapidoc-min.js:2
(anonymous) @ rapidoc-min.js:2
(anonymous) @ rapidoc-min.js:2
```

It might be related.

Amazing lib, keep it up! Can't live without

**Comment by mrin9** [comment]
this has been addressed in https://github.com/mrin9/RapiDoc/commit/bb68082527144434fb9f6fdc6ee7403554e08184

> PS: We are collecting some feedback from our internal users on  `lit` upgrade ... will release it soon if there is nothing breaking
