### ISSUE TITLE
There was an issue while parsing the spec S2OError: (Patchable) parameter.type is mandatory for non-body parameters

### ISSUE THREAD

**Issue by dagnelies** [mrin9/RapiDoc#67]
Hi,

I think my specs are OK, since they are simply generated by a tool, but apparently something is causing trouble for RapiDoc. 

It was not a problem with version 5.3.1

**Comment by mrin9** [comment]
without a sample spec, It wont be possible to for me to address this issue

**Comment by mrin9** [comment]
did an urgent release, let me know if it resolves your issue in `6.0.2` ?

**Comment by dagnelies** [comment]
Works perfectly! thanks 👍
