### ISSUE TITLE
Query and Path parameter examples/description has an offset

### ISSUE THREAD

**Issue by joshrap-eb** [mrin9/RapiDoc#670]
Curious if there would be any way to remove this offset? Just looks a little strange to have that the example/description offset from the column to its left. Not sure if others agree.
![image](https://user-images.githubusercontent.com/74060233/154997988-5aa07743-bc56-4593-a96a-77eaa473e96e.png)

**Comment by joshrap-eb** [comment]
For what it's worth it looks normal/fine when there is a default value
![image](https://user-images.githubusercontent.com/74060233/154998729-c8028769-3e50-4d3f-8a28-0cd28f2bf8c7.png)

**Comment by mrin9** [comment]
provide RapiDoc version info and the attributes that you have applied to `<rapi-doc>` element

**Comment by joshrap-eb** [comment]
Just using whatever is on the CDN here.
```
<html>
<head>
  <title>Documentation</title>
  <link rel="icon" href="favicon.png">
  <meta charset="utf-8">
  <script type="module" src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>
</head>
<body>
  <rapi-doc 
    spec-url="https://our_data_link/docs.json"
    render-style="focused"
    show-header="true"
    sort-endpoints-by="summary"
    allow-try="false"
    primary-color="#eb4034"
    schema-style="table"
    allow-authentication="false"
    allow-server-selection="false"
    info-description-headings-in-navbar="true"
    schema-description-expanded="true"
    allow-spec-url-load = "false"
    allow-spec-file-load = "false"
    regular-font="Segoe UI"
    theme="dark">
  </rapi-doc>
</body> 
</html>
```
