### ISSUE TITLE
Latest rapi-doc not rendering spec with oauth2 security scheme

### ISSUE THREAD

**Issue by christiancorey** [mrin9/RapiDoc#673]
Looks like the latest versions of rapi-doc have broken the rendering of a few of our API docs.  The ones that are no longer rendering have an oauth2 security scheme in common.  

Forcing rapi doc back down to 9.1.4 resolves the issue for the time being.

Here is the error from the browser console:

`
Uncaught (in promise) TypeError: Cannot destructure property 'authorizationUrl' of 'a.authorizationUrl' as it is undefined.
    at WR.zP (rapidoc-min.js:2:334547)
    at rapidoc-min.js:2:341670
    at Array.map (<anonymous>)
    at rapidoc-min.js:2:341659
    at Array.map (<anonymous>)
    at WR.UP (rapidoc-min.js:2:339292)
    at WR.VR (rapidoc-min.js:2:475614)
    at WR.render (rapidoc-min.js:2:488782)
    at WR.update (rapidoc-min.js:2:17083)
    at WR.performUpdate (rapidoc-min.js:2:14034)
zP @ rapidoc-min.js:2
(anonymous) @ rapidoc-min.js:2
(anonymous) @ rapidoc-min.js:2
UP @ rapidoc-min.js:2
VR @ rapidoc-min.js:2
render @ rapidoc-min.js:2
update @ rapidoc-min.js:2
performUpdate @ rapidoc-min.js:2
_enqueueUpdate @ rapidoc-min.js:2
await in _enqueueUpdate (async)
loadSpec @ rapidoc-min.js:2
await in loadSpec (async)
(anonymous) @ rapidoc-min.js:2
setTimeout (async)
attributeChangedCallback @ rapidoc-min.js:2
310 @ rapidoc-min.js:2
a @ rapidoc-min.js:2
(anonymous) @ rapidoc-min.js:2
(anonymous) @ rapidoc-min.js:2
`

**Comment by mrin9** [comment]
duplicate of #667
