### ISSUE TITLE
OAuth2 Security Flow Parse Error

### ISSUE THREAD

**Issue by 0xbayo** [mrin9/RapiDoc#674]
Hello,
I discovered two bugs in the security-scheme section:
1. Regardless of oauth2 flow type, RapiDoc tries to parse the `authorizationUrl`. The `authorizationUrl` is only applicable to 'implicit' and 'authorizationCode' flows. This table in the spec provides the details: [https://swagger.io/specification/#:~:text=with%20Specification%20Extensions.-,oauth%20flow%20object,-Configuration%20details%20for](url) (chrome's page-text link format)

2. When the token URL is absolute, it does not get set. This might apply to authorization URL as well. The example in the spec shows an absolute URL being used.

I have tested the issues above with the quickstart HTML file while loading a JSON file. The spec is the same as the one used in this example, converted to JSON: [https://mrin9.github.io/RapiDoc/examples/oauth-vendor-extension.html#auth](url). Thank you

**Comment by mrin9** [comment]
this error was introduced in recent versions of RapiDoc , check if `v9.1.4` works for you
Duplicate of #667

**Comment by 0xbayo** [comment]
Thank you. `v9.1.4` worked just fine. I will stick with that until a new release.
