### ISSUE TITLE
Using Rapidoc styles inside the slots

### ISSUE THREAD

**Issue by jcolladosp** [mrin9/RapiDoc#678]
Hi,
first of all I want to thank you for maintaining this amazing library! 

I was adding a button inside a slot and my question is if there's a way  to use the same styles that RapiDoc it's using for the buttons, etc:
![2022-03-04_08-54](https://user-images.githubusercontent.com/9121186/156724868-d7cec8e2-dcab-434a-af03-1461726a3560.png)

Thanks!

**Comment by mrin9** [comment]
if the goal is to achieve a single style for all buttons then I suggest to use css-parts

for example the below style will change all the buttons border-radius inside rapidoc
you can also individually style or change various sections and UI elements to your need
read about it here https://mrin9.github.io/RapiDoc/css-parts.html

```html
<html>
  ...
  <style>
    rapi-doc::part(btn){ border-radius: 15px; }
  </style>
  <rapi-doc  spec-url = "https://petstore.swagger.io/v2/swagger.json"> </rapi-doc>
  ...
</html>
```
[here is the result of above styling](https://mrin9.github.io/RapiDoc/examples-theme/cssparts-btn.html#overview)

**Comment by jcolladosp** [comment]
Hi @mrin9,
sorry if my explanation was not good enough, but the goal was to create a custom button inside a slot space that has the same styling as the rapidoc default buttons.
In my example image I want to achieve that "Download PDF" button has the same style as "Download OpenAPI spec"

**Comment by mrin9** [comment]
No that wont be possible, you cannot extract out the styles from a web-component. there is a hard encapsulation there, instead you can override them with yours
