### ISSUE TITLE
Schema Object - "array" elements - mixed-up constraints and description

### ISSUE THREAD

**Issue by ilPittiz** [mrin9/RapiDoc#681]
When defining, within a Schema Object, an "array" element with both constraints (e.g. "minLength") and "description", they get mixed-up in unclear way.

RapiDoc version 9.2.0 (from CDN: https://unpkg.com/rapidoc@9.2.0/dist/rapidoc-min.js)

Example:

<details>
  <summary>Schema</summary>
<pre><code>{
  "info": {
    "title": "Demo",
    "version": "0.0.1"
  },
  "openapi": "3.0.3",
  "paths": {
    "/api/v1/demo": {
      "post": {
        "operationId": "demo",
        "description": "Demo API",
        "parameters": [],
        "responses": {
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "description": "Error key",
                      "type": "string",
                      "pattern": "^[a-z_]+$",
                      "minLength": 1
                    },
                    "invalidIds": {
                      "description": "List of invalid IDs",
                      "type": "array",
                      "items": {
                        "type": "string",
                        "pattern": "^ID[0-9]$"
                      },
                      "minItems": 1,
                      "maxItems": 1000
                    }
                  },
                  "required": [
                    "error",
                    "invalidIds"
                  ],
                  "additionalProperties": false
                },
                "example": {
                  "error": "invalid_id",
                  "invalidIds": [ "IDn" ]
                }
              }
            }
          }
        }
      }
    }
  }
}</code></pre>
</details>

<details>
  <summary>Screenshot (comparison of "string" and "array" elements, both with constraints and description)</summary>
<img width="904" alt="schema_array_description" src="https://user-images.githubusercontent.com/5478561/157060481-fba41518-ea41-470d-b2e3-5d4c02c51c5f.png">
</details>

**Comment by mrin9** [comment]
Can you provide me, how would you expect it to be displayed ?

**Comment by mrin9** [comment]
after some discussion we decided to take the description at the top. This do create a problem of constrains being in the 2nd line and most likely be not shown in single line mode. but added an indicator for that

<img width="685" alt="image" src="https://user-images.githubusercontent.com/5056899/160261179-9ac9bca6-a879-42e9-93f9-21cf22510168.png">

with descriptions expanded
<img width="685" alt="image" src="https://user-images.githubusercontent.com/5056899/160261196-7403820c-1351-457d-ab5e-086cb55135ca.png">
