### ISSUE TITLE
Summary of examples removed

### ISSUE THREAD

**Issue by majoshi1** [mrin9/RapiDoc#685]
The summary of examples was removed in v9.1.4. It has been working fine till [v9.1.3/api-request.js#L248](https://github.com/mrin9/RapiDoc/blob/72ea3b4a1295f9a171071a1523b222a6e572714a/src/components/api-request.js#L248). Is there a way to achieve it in v9.1.4? If not, is it possible to revert the change?
```{
	"parameters": [{
			"name": "someName",
			"schema": {},
			"examples": {
				"example1": {
					"summary": "Item1",
					"value": "10"
				}
			}
		}

	]
}

**Comment by mrin9** [comment]
> The summary of examples was removed in v9.1.4

 where, you mean when listing them it now uses value instead of summary ?

**Comment by majoshi1** [comment]
Yes. Below are the lines from both versions for comparison:

[v9.1.3/api-request.js#L248](https://github.com/mrin9/RapiDoc/blob/72ea3b4a1295f9a171071a1523b222a6e572714a/src/components/api-request.js#L248)

`>${v.description || v.summary || v.value}</a>`

[v9.1.4/api-request.js#L249](https://github.com/mrin9/RapiDoc/blob/6c4aa89abc73a5bbe75a42c8e2797eaf1f2dea2d/src/components/api-request.js#L249)

`>${v.value && Array.isArray(v.value) ? (v.value?.join(', ')) : (v.value || '')}</a>`

**Comment by majoshi1** [comment]
Any update here please? Can't update to latest version, until this defect is fixed.

**Comment by mrin9** [comment]
this was done as we received many user feedback stating its better to show the actual values than summary for examples
I will check if I can provide any options for both possibilities.

**Comment by majoshi1** [comment]
How about vendor extension?
e.g. `x-example-summary-show : no` for each parameter to indicate if summary should be used. Also may be RapiDoc attribute `show-examples-summary = true/false` to indicate for the entire spec.

**Comment by mrin9** [comment]
use `use-summary-to-list-example = true` to list example summary instead of value (default is false)
