### ISSUE TITLE
x-code-sample and x-codeSample does not currently work?

### ISSUE THREAD

**Issue by arlington6988** [mrin9/RapiDoc#691]
I'm trying to engage the vendor extension to show code samples.  When I simply include this in the open api yaml it does not generate the samples as the documentation suggests.  Am I missing something?  Do I need to include another JS to use this functionality?  I have tried both naming conventions.

I am following this instruction here for x-code-samples - https://mrin9.github.io/RapiDoc/examples/code-samples.html#get-/code-samples
paths:
  ## Api ##
  /api/count_devices:
    post:
      operationId: 22222
      x-code-samples:
        - lang: 'ruby'
          label: 'Ruby'
          source: 'console.log()'
      tags:
      - Api
      summary: Counts the number of devices that match input-specified criteria

**Comment by mrin9** [comment]
> Do I need to include another JS to use this functionality? 

No.

The example that you are referring to, is showing the code sample. So it works and most likely the issue is how you are constructing your spec. (check for proper indentation etc)

The OpenAPI spec that the example uses is https://mrin9.github.io/RapiDoc/specs/code-samples.yaml
may be you can start from that and modify to bring in your changes

**Comment by arlington6988** [comment]
I was following example exactly as it is in the doc and still was not working.  Now today I get this error regardless of what spec is loaded (event he example one you rsent) 

RapiDoc:  There was an issue while parsing the spec TypeError: (e.operationId || "").replace is not a function
    at g_ (common-utils.js:13:1)
    at l (common-utils.js:13:1)
    at $_ (common-utils.js:13:1)

**Comment by arlington6988** [comment]
Looks like someone fixed this! Thank you sir, it is now working.
