### ISSUE TITLE
Allow setting default selection of Request Body option to receive auth tokens

### ISSUE THREAD

**Issue by valmoz** [mrin9/RapiDoc#705]
As discussed here: #700 

I would like to be able to automatically select the "Request Body" option in the Authorization Code Flow section. I'm worried that my users could try with the default option "Authorization Header" obtaining an error.

Thanks 
Mauro

**Comment by mrin9** [comment]
closed by e6453370b8ef76f9b1eafa58a5f45b79dd0b2d33

use vendor-extenstion `x-receive-token-in` 
for usage check our API section
