### ISSUE TITLE
Feature Request - $ref to markdown description

### ISSUE THREAD

**Issue by elnipa** [mrin9/RapiDoc#709]
We are currently looking into moving from Redoc to RapiDoc and love the feature of including markdown for API description.
I was able to render md inline style for description.

However, having it linked via $ref is not working currently. Any plans to support this in the near future?

## example

```yaml
openapi: '3.1'
info:
  version: '1.2.3'
  title: my API
  description:
    $ref: ./docs/index.md
```

**Comment by mrin9** [comment]
you can `$ref` to another `yaml` or `json` 
therefore your `index.md` should be defined like 

```yml
description: >
  your entire index.md content

```

**Comment by wparad** [comment]
@elnipa we actually had a similar desire to support dynamic references, so this is something that we also added to our fork. I'm not sure if our implementation would work for you, but you can certainly try it out if you're interested: https://www.npmjs.com/package/openapi-explorer

**Comment by mrin9** [comment]
IMO I think `$ref` to `yaml` or `json` will work with most of the tooling out there including swagger, redoc, rapidoc and others and it will help you out of a vendor lock-in situation.

Though it is not supported by OpenAPI spec but is something thats requested quite often and we have provided feedback to the spec to allow it. 
Also keep an eye on [TypeSchema](https://chriskapp.medium.com/typeschema-an-alternative-to-jsonschema-bdc99f3e3f43) space, which might be a better and simpler alternative to JSONSchema
