### ISSUE TITLE
Incorrect example for date format

### ISSUE THREAD

**Issue by LeoJohannsson-imtf** [mrin9/RapiDoc#712]
properties with `type: string` and `format: date` get an example with the `date-time`  format i.e. `2017-07-21T17:32:28Z` instead of `2017-07-21`

**Comment by mrin9** [comment]
i am unable to recreate it , can you provide a spec then will show up this issue ?

**Comment by mrin9** [comment]
closing due to no response

**Comment by mrin9** [comment]
thanks for putting up a complete spec. this issue is now addressed in  a3fd23dfd4a021dc773c943ea3f674c2476f7f30

> We get too many issues, and one of the criteria for initial triaging is if we can recreate it on our end, for which a spec is needed. no matter how trivial is the issue including a complete spec (not partial) immediately gets our attention.<br>
Another thing that I would like to mention is, please open a new request if an closed request did not fix an issue as we do not get notifications on closed requests

thanks.

**Comment by SingleShot** [comment]
FYI for the fix to work, the example must be surrounded by quotes. For example, this works:
```
example: '2024-01-15'
```

This does not:
```
example: 2024-01-15
```
