### ISSUE TITLE
Read Render style keeps scrolling up to Overview section on scrolling

### ISSUE THREAD

**Issue by valmoz** [mrin9/RapiDoc#713]
I'm currently trying to integrate RapiDoc into our Docusaurus documentation as a React page.

We were able to integrate it correctly using the "View" and "Focused" render styles, while for the **"Read" style** a strange behavior appeared.

It seems that while scrolling the page down to check the various methods the page is immediately scrolled up to the #overview tag, making it impossible to reach the following content.
This seems to happen when the line separating the different methods is visualized.

It also happens when you click one of the methods in the left bar: the method documentation is visualized correctly, but then when scrolling up or down the page returns to #overview.

The other render styles don't have the same issue.

You can see an example [here](https://storage.googleapis.com/fic_api_prova_mauro/rapidoc-read/index.html)

I also tried from Docusaurus StackBlitz playground, and the same thing happens ([here](https://stackblitz.com/edit/github-djde9j?file=docusaurus.config.js)'s the link)
 
This is the code of my React page:

```
import React, {useEffect} from "react";
import Layout from '@theme/Layout';

import useIsBrowser from '@docusaurus/useIsBrowser';
import {
  useColorMode,
} from '@docusaurus/theme-common';

const RapiDoc = () => {
  const isDarkTheme = useColorMode().colorMode === "dark";

  return <div>
    <rapi-doc id="apiref"
      style={{ "minHeight": "100vh", width: "100%" }}
      spec-url="https://raw.githubusercontent.com/fattureincloud/openapi-fattureincloud/test-rapidoc-auth/openapi-enriched.yaml"
      theme={isDarkTheme ? 'dark' : 'light'}
      render-style="read"
      primary-color='#0094d4'
      font-size='large'
      nav-bg-color={isDarkTheme ? '#171819' : '#ffffff'}
      bg-color={isDarkTheme ? '#171819' : '#ffffff'}
      allow-server-selection='false'
      show-header='false' >
    </rapi-doc>
  </div>;

};

const ApiRef = () => {
  const isBrowser = useIsBrowser();

  if (isBrowser) {
    require("rapidoc");

    return (
      <Layout title="API Reference">
        <RapiDoc />
      </Layout>);
  } else {
    return (
      <Layout title="API Reference">
        Loading...
      </Layout>);
  }

}

export default ApiRef;
```

Could you please help me to understand if it is an issue related to RapiDoc? Could it be due to the fact that I integrated it into React or Docusaurus?

Thanks
Mauro

**Comment by mrin9** [comment]
> Could you please help me to understand if it is an issue related to RapiDoc? Could it be due to the fact that I integrated it into React or Docusaurus?

`render-style = 'read'` needs a little special handling if you intend to embed it inside another HTML element. The html element containing `<rapi-doc>` should have a defined height, either by way of inhering from its parent or by defining it on itself, but it cant dynamic like based on its content 

So I think it will work if you give a height to the element containing the `<rapi-doc>` element like below

```html
  return <div style={{ minHeight: '100vh' }}>
    <rapi-doc id="apiref"
      style={{ "minHeight": "100vh", width: "100%" }}
      spec-url="https://raw.githubusercontent.com/fattureincloud/openapi-fattureincloud/test-rapidoc-auth/openapi-enriched.yaml"
      theme={isDarkTheme ? 'dark' : 'light'}
      render-style="read"
      primary-color='#0094d4'
      font-size='large'
      nav-bg-color={isDarkTheme ? '#171819' : '#ffffff'}
      bg-color={isDarkTheme ? '#171819' : '#ffffff'}
      allow-server-selection='false'
      show-header='false' >
    </rapi-doc>
  </div>;
```

> please feel to close the issue, if it takes care of your situation
