### ISSUE TITLE
Improve template for optional Auth 

### ISSUE THREAD

**Issue by elnipa** [mrin9/RapiDoc#714]
According to OpenAPI Spec single endpoints can have optional auth:
https://spec.openapis.org/oas/v3.1.0#optional-oauth2-security

In our case by defining
```
  security:
    - {}
    - bearerAuth: []
```

In this case the endpoint template should have some indication that auth is optional. Currently it's still marked as "required" and the options for Auth show an empty string for No Auth.
![image](https://user-images.githubusercontent.com/34566347/161032650-1fe3a986-e1e6-4162-ad35-324a9bd56e2c.png)
![image](https://user-images.githubusercontent.com/34566347/161032664-199dda68-af5e-4f92-8b97-3be7f85ae743.png)

**Comment by elnipa** [comment]
Example how this is rendered in ReDoc

![image](https://user-images.githubusercontent.com/34566347/161033641-c5a9f0b7-c986-4144-9a09-89f926484abe.png)

**Comment by mrin9** [comment]
thanks for reporting ... will fix it soon
