### ISSUE TITLE
Feature Request - spec-url "Picker"

### ISSUE THREAD

**Issue by enobrev** [mrin9/RapiDoc#715]
Hello,

I just replaced an install of redoc with this for our team, and I'm a huge fan thus far, so I'll start just with saying thanks for making / maintaining this great project.

Ok, on with the request:

I have multiple specs for different teams, (client_1.json, client_2.json, internal_service.json, etc).  Typing them in works perfectly fine as-is, but I'd love to instead have a dropdown where we could pick from the available (pre-defined) spec-urls.   If there were then a way to specify which to load in the url, well that would just be incredibly useful.

**Comment by mrin9** [comment]
check if #82 works for you

**Comment by enobrev** [comment]
It definitely should, I appreciate it. I'm using a docker build, but there's no reason I couldn't also generate an index file and replace the existing one using a volume mount.

Thanks!
