### ISSUE TITLE
Example/Collapse multiple schemas for the same API

### ISSUE THREAD

**Issue by gaoyan198** [mrin9/RapiDoc#716]
Hey, I notice that I was not able to expand and collapse/toggle between multiple schemas of the same endpoint. 

This is critical for my team because our schema are faily huge, being able to expand/collapse helps improve the readability of the content (and is also a feature that redoc provides)

May I check if this is a feature that you are currently working on?

**Comment by mrin9** [comment]
I am not sure what do you mean by multiple schema of same end-point. are these multiple schema of various responses from the same end-point ?

may be explain with a minimal spec and screenshot what you mean and what are you looking for

**Comment by mrin9** [comment]
closing due to no clarification provided
