### ISSUE TITLE
data type format appearing twice for parameters

### ISSUE THREAD

**Issue by StephenNay** [mrin9/RapiDoc#74]
When a parameter definition includes a format value as well as the type, the format is being shown twice in the RapiDoc output, the second time in parentheses. For example, this parameter:

    OrgId:
      name: orgid
      in: path
      description: Customer ID
      required: true
      schema:
        type: string
        format: UUID

Is displayed like this. Note "UUID (UUID)"

![image](https://user-images.githubusercontent.com/15385013/68168714-937c2800-ff1e-11e9-8dbb-7dc79073fb94.png)

**Comment by mrin9** [comment]
thanks for pointing that out, will fix it soon

**Comment by mrin9** [comment]
fixed in release `7.0.1`
