### ISSUE TITLE
Use parameters from another .yaml file

### ISSUE THREAD

**Issue by vasnav** [mrin9/RapiDoc#75]
Hi,
   Is it possible to use the parameters defined in an external file?
   I have 2 files A.yaml and B.yaml. Both the files are in the same directory.

    B.yaml has the parameter defined as below:
              

> openapi: 3.0.2
> 
> servers:
>     - url: https//sample
> 
> parameters:
>     paramA:
>         name: param A
>         in: header
>         description: >
>           Language locale accepted by client (used for locale specific fields in resource representation and in error responses). 
>         required: true
>         schema:
>             type: string
>             enum: [en-US, es-ES, fr-FR]
> 

   When trying to use the parameter defined above in A.yaml, the parameter is not being picked:

> openapi: 3.0.2
> 
> servers:
>     - url: https//sample/system
> 
> paths:
>     /path1:
>         post:
>             summary: Sample summary.
>             operationId: sampleSummary
>             description: | 
>                Sample   
>             parameters:
>                 - $ref: 'B.yaml#/parameters/paramA'

Is the above usage correct?

**Comment by StephenNay** [comment]
You can only use $ref in specific places in OpenAPI definitions, and your example is not one of those places. You can use $ref to reference the schema of individual parameters, but you cannot use it for the entire list of parameters.

If you want to break up your OAS definition into multiple files but $ref doesn't meet your needs, check out yamlinc. It lets you place $include statements anywhere you want to merge in another YAML file, and then you run yamlinc when you are ready to merge the files into a single file. You can also set it to watch for changes in a folder and automatically merge and create the single file when files are saved. You can use yamlinc along with $ref.

**Comment by mrin9** [comment]
the `.yaml` you provided lost its indentation, therefore it is invalid. 

but just so you know, RapiDoc usage of `$ref` in the spec. and as @StephenNay mentioned, it is valid  only in certain valid sections  per the OpenApi spec.

I am closing this issue, in-case you think any of your spec with $ref isnt working, feel free to reopen it and provide a properly formatted spec for me to re-create the issue

**Comment by vasnav** [comment]
I have attached the yaml files (Have appended the files with .log as I was not able to upload .yaml files).
In file Login.yaml the parameter 'accept' that is referred from 'Common.yaml' is not loaded (image AcceptHeaderMissing.png attached):
           - $ref: './Common.yaml#/parameters/accept'
Is this the correct way of using $ref parameter from another file?
![AcceptHeaderMissing](https://user-images.githubusercontent.com/56592616/69781289-a8717180-11d3-11ea-9893-d5520ab7db35.png)
[Common.yaml.log](https://github.com/mrin9/RapiDoc/files/3900134/Common.yaml.log)
[Login.yaml.log](https://github.com/mrin9/RapiDoc/files/3900135/Login.yaml.log)
