### ISSUE TITLE
Response examples have extra commas

### ISSUE THREAD

**Issue by StephenNay** [mrin9/RapiDoc#78]
I'm seeing an extra comma at the end of response examples. If the example is an array of objects, there is a comma after the closing curly brace at the end of the object and a comma after the closing square bracket for the array. Here is a screenshot of that:

![image](https://user-images.githubusercontent.com/15385013/68230600-32039a00-ffae-11e9-9963-65ea59f777db.png)

**Comment by mrin9** [comment]
thanks, 

Strict JSON dont allow trailing commas, but was introduced in ES5 literals. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

I will remove the comma at the end of the array but may do anything to the comma after the curly

**Comment by StephenNay** [comment]
If you scroll down that page that you referenced, you'll find a section on "Trailing commas in JSON," and in bold text there it says, "trailing commas are not allowed in JSON." Causes a syntax error.
