### ISSUE TITLE
Content-Type for POST request without a body?

### ISSUE THREAD

**Issue by StephenNay** [mrin9/RapiDoc#79]
An API that I'm working with has a POST request that includes some parameters in the URL, but does not include a body. When I try sending the request through RapiDoc, I get back an error that says that the request needs to set the Content-type to application/json. I know that's a little odd because the service shouldn't care what the content-type is if there is no body, but that's how the service works for now. 

Is there a way to set a default content-type to be used in all POST/PUT/PATCH requests?

**Comment by mrin9** [comment]
hmm, not sure how other renderers are dealing with this, do you know what swagger-ui would do for this ?

**Comment by StephenNay** [comment]
Swagger UI seems to do the same thing: no content-type if no body. I'll check with the API developers and see what they think, and then I'll update this issue.

**Comment by mrin9** [comment]
can you provide me a minimal spec where I can recreate this issue, I can give it a try

**Comment by StephenNay** [comment]
Hopefully this is enough snippet:

```
paths:
  '/customers/{orgid}/sites/{siteid}/nodes/{nodeid}/schedule_push':
    post:
      x-lighting: true
      tags:
        - Nodes
      summary: Resend schedule to a node
      description: Resend a schedule to a node.
      operationId: resendScheduleToNode
      parameters:
        orgid:
          in: path
          description: Customer account ID
          required: true
          schema:
            type: string
            format: UUID
          example: 47d5ed30-bdd7-11e7-95af-b3b0c15ebf90
        siteid
          in: path
          description: Site ID
          required: true
          schema:
            type: string
            format: UUID
          example: 78520930-bdd7-11e7-95af-b3b0c15ebf90
        nodeid
          in: path
          description: Node ID
          required: true
          schema:
            type: string
            format: UUID
          example: N313098
      responses:
        '204':
          description: Success

```

**Comment by mrin9** [comment]
RapiDoc did not had any issue in submitting that request. Most likely the validation/response is coming from your API

I created a  fake `POST` endpoint using [Mockable](https://www.mockable.io/a/#/try)
and it had no issues in submitting the `POST` request without a body
```
openapi: 3.0.2
info:
  version: '1.0'
  title: POST with no request-body
  description: POST with no request-body
servers:
  - url: 'http://demo1373839.mockable.io'
paths:
  /sample-post:
    post:
      summary: Resend schedule to a node
      description: Resend a schedule to a node.
      operationId: resendScheduleToNode
      parameters:
        - orgid:
          in: query
          schema:
            type: string
      responses:
        '204':
          description: Success
```
