### ISSUE TITLE
How to create links in RapiDoc output?

### ISSUE THREAD

**Issue by StephenNay** [mrin9/RapiDoc#80]
This is really a usage question and not an issue, but I wasn't sure where else to ask it.

I know how to create links in Markdown, but what anchor name do I use to link to a section (tag) heading, and what anchor name to link to a specific request? For example, in the description of one request I might want to say say something like, "This other request returns related information," and have "other request" be a link that goes to that request in the RapiDoc output.

**Comment by mrin9** [comment]
RapiDoc uses custom-elements which generated [shadow-dom](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM).  shadow-doms are isolated and encapsulated dom fragments, so even if you happen to know the ID of an element you cannot href it from a different section

https://stackoverflow.com/questions/43425398/anchor-tag-a-id-jump-with-hash-inside-shadow-dom

But there have been few other requests on similar lines and we are working on a solution, so hang on a bit, I will have more info then

**Comment by mrin9** [comment]
cross-linking feature added in release `7.0.1`
in markdown to create links you should follow the format of `#{method}-{path}`
checkout this [example](https://mrin9.github.io/RapiDoc/examples/data-types.html#get-/simple-object) for reference
