### ISSUE TITLE
Possibility to provide a predefined list of the specification urls

### ISSUE THREAD

**Issue by mikemadisonweb** [mrin9/RapiDoc#82]
Hello, thank you for the awesome package.
I have a question, is there some plans to add a feature to provide a list of the specifications to the input rather then one specification url.
We have a lot of services in our company and I'm building a centralized documentation tool for them. Rapidoc looks like a perfect fit for this.
What do you think, what would be the best way to inject the predefined list of specifications to the input, ideally with the autocomplete feature (like select2 plugin for example)?
I think such a feature could be invaluable for others as well.

**Comment by mrin9** [comment]
You have enough ways to build this functionality the way you want to, with minimal scripting in your html

- Use your favorite UI control to create a predefined list of spec 
- `onSelect` change the `<rapi-doc>` element's  `spec-url` attribute  to the one selected from the UI control
- If you want you may hide the spec-url input of `rapi-doc`

here is an [example](https://mrin9.github.io/RapiDoc/examples/example100.html) show how various attributes can be changed.
the code for it is here https://github.com/mrin9/RapiDoc/blob/master/docs/examples/example100.html

feel free to reopen it, if you still unable to make this work on your side or have any other issues/doubts
