### ISSUE TITLE
Display callback information

### ISSUE THREAD

**Issue by carlo-quinonez** [mrin9/RapiDoc#83]
Currently, no information is displayed about any [callbacks](https://swagger.io/docs/specification/callbacks/). Is this a bug or just not implemented?

Here's an example of how swaggerhub shows callbacks.
![image](https://user-images.githubusercontent.com/53790047/68723529-9f469a80-056d-11ea-96c9-03723d44fd70.png).

Aside from this, I think this library is excellent! Thank you for putting it together.

Regards,
Carlo

**Comment by mrin9** [comment]
Thanks, 
`callbacks` are yet to be implemented not yet implemented,

**Comment by mrin9** [comment]
support for callbacks is now implemented in release 7.0.3.
Thanks for bringing this up

Give it a try here https://mrin9.github.io/RapiDoc/examples/callback.html
