### ISSUE TITLE
Example how to render on backend

### ISSUE THREAD

**Issue by axpira** [mrin9/RapiDoc#84]
Hi,

I want to render RapiDoc on node.js before send html to browser.

It's possible? Can you show an example?

Thanks

**Comment by mrin9** [comment]
`<Rapi-Doc>` is a web-component and there is no good way to render web-component on server-side.
However we have plans for enabling server-side rendering, this is a slow process and involves a lot of churn in the code-base. 
the current plan is to come with the initial version with server-side rendering in the Q1 of 2020 

Can you tell me, why would you need server side rendering ? if it is due to slowness, then try `render-style='view'` this helps in delaying the load of all the sub-components untill the user clicks and opens them.

**Comment by axpira** [comment]
Thanks for reply.

I'm trying to put a examples tab, this is what I'm done for now https://imgur.com/VJ1dzru

But for this work I put a sleep until the RapiDoc finish load to work, and this is terrible.

**Comment by mrin9** [comment]
first, I think the code-sample tab looks pretty cool

![image](https://user-images.githubusercontent.com/5056899/68919557-65b98f00-0727-11ea-81c9-d468fec5f167.png)

I am not sure how you are adding this tab,  are you directly manipulating the dom ?.

most likely you wont need to sleep, if you create it as a separate web-component or a template and plug it in the main render function. I am just shooting in the dark here, 
but if you can share a bit of code as how you are plugging in the panel,  I can comment further

**Comment by axpira** [comment]
I'll check this lit-html-server thanks.

The code is not working for all operations for the moment and sorry if the code is not very smell, I'm not node developer

For the moment I'm trying to get this data from https://github.com/ErikWittern/openapi-snippet

But in a short way this is the code to wait a RapiDoc finish to proper render the snippets
```
            executeAsync(1000, function() {
                for (i=0;i<10;i++) {
                  sleep(1000);
                  if (!getRapiDoc().loading) {
                      break;
                  }
                }
                if (getRapiDoc().loading) {
                    console.log("ERROR RapiDoc is loading");
                    return;
                }
                
                var btnTry = getRapiDoc().shadowRoot.querySelectorAll("api-request")[0].shadowRoot.querySelector("button.try-btn");
                
                fetch('/sample/<%=api_name%>')
                .then(function(response) {
                    return response.json();
                })
                .then(function(snippets) {
                    btnTry.parentNode.parentNode.append(createSnippet(snippets));
                });
            });
```

I'll try to create a working code and I can share in github if you want we can try to include in a future version.

Many thanks for help

**Comment by axpira** [comment]
Do you have any example for how can I import RapiDoc on lit-html-server ?

**Comment by mrin9** [comment]
in the current state you cannot, coz RapiDoc is built on `lit-element and lit-html` but `lit-html-server` can render only render `lit-html` so, first you need remove `lit-element` dependency and then you can try

**Comment by chekwube** [comment]
Hi @mrin9 . Please has server-side rendering been enabled in RapiDoc? Thanks
