### ISSUE TITLE
Feature: Display the Models and Examples

### ISSUE THREAD

**Issue by LevinGuy** [mrin9/RapiDoc#85]
Hi, 
It is possible to add a display of the models (also in the left section) like in the swagger editor?

![image](https://user-images.githubusercontent.com/8510784/68850211-43e6ea80-06dc-11ea-82f7-e5b54ecaeb83.png)

Keep up the great work ! :)

Thanks,
Guy

**Comment by mrin9** [comment]
we never found a compelling reason for showing it separately, for larger specs it will add more time to parse.

at this point there is no option to pre-process or do a server side rendering of RapiDoc therefore it is very important for us to keep the processing time in check especially when `render-style` is set to `read`

but if you can tell me the why you need it ? or provide with a good reason to have it, I will take it further

> PS : Thankyou for mentioning us in your blog https://blog.restcase.com/openapi-documentation-and-beyond !!!

**Comment by LevinGuy** [comment]
Hi @mrin9 

My please about the mention, I think you have done a great work. 

From what we have seen, many want documentation because of testing the API and in many cases, they just want to check the body to send or to receive, so models with examples is very important. 

Perhaps only the components -> models part? (I would also add the examples, since examples are the first thing one looks in an API documentation). Perhaps it can be controlled by a variable / variables?

**Comment by mrin9** [comment]
Models and Examples are there for each path in RapiDoc, write inside the response and request panels.
So why would that be listed again in a separate section .  

Are you suggesting a spec with lots of markdown content can create a distraction for a person who understands the system properly, but just interested in the Request-URI , Models and Examples?

![image](https://user-images.githubusercontent.com/5056899/68921896-01023280-072f-11ea-94a9-9661c66f66f3.png)

**Comment by LevinGuy** [comment]
Hi @mrin9,

From what we saw, the API spec documentation is good for the first glance from user perspective. Then when the user is ready to work / connect with an API, he is more interested in examples, models (to see what options there are). Markdown with explanation is good, on the path level. But in most cases, you want to checkout examples and structure of the models.

Thanks, 
Guy

**Comment by mrin9** [comment]
To update you on this 

My usability guy wasn't convinced enough to bring this change. his reasons were
- Models and API Paths were far apart from each other
- There is no easy way to associate a API's response/request to a model
- when we tested it with some pretty large spec, it added few more seconds to render
Instead his suggestion was to provide a flag that will allow you to hide all the markdown, and present a less distracted view to someone who is much familiar with the API.

Let me know if you have any opinion or say on this

**Comment by LevinGuy** [comment]
Hi @mrin9 , I have managed to do the changes and sent you a pull request (hope it is fine).

It is an optional (showComponents) so it can be turned off.
But it will allow the users who already working with the API to take a look at models, examples and etc.. without the need to go to a specific endpoint. 

Thanks,
Guy

**Comment by SkyaTura** [comment]
I would also like this feature, in fact, this is the only reason that I didn't replaced the original Swagger UI yet.

**Comment by LevinGuy** [comment]
Hi @mrin9,

I think that this issue was done and can be closed. 

Thanks, 
Guy
