### ISSUE TITLE
Windows EDGE browser error: 'customElements' is not defined

### ISSUE THREAD

**Issue by whentotrade** [mrin9/RapiDoc#89]
When opening with windows10 edge browser, empty page shows up and console reads:

`"SCRIPT5009: SCRIPT5009: 'customElements' is not defined"`

Check using demo site and Windows10 Edge browser:
[https://mrin9.github.io/RapiDoc/examples/example2.html](https://mrin9.github.io/RapiDoc/examples/example2.html)

**Comment by mrin9** [comment]
We do not support or test on edge. 
RapiDoc is a web-component (custom-element) Edge do not support web-components out of the box

but I believe it should work if you include this polyfill https://www.jsdelivr.com/package/npm/@webcomponents/webcomponentsjs

however we have tested on newer Edge based of chromium and it works just fine 
https://www.microsoftedgeinsider.com/en-us/
