### ISSUE TITLE
Multi-word tag headings not linked when render-style=read

### ISSUE THREAD

**Issue by StephenNay** [mrin9/RapiDoc#92]
render-style=read

If I use single words to tag operations, such as "Pets" or "Orders," the heading links in the left column work fine to jump to those sections in the main column. However, if I use multi-word tags, such as "Pet store," clicking the heading in the left-column doesn't do anything. 

![image](https://user-images.githubusercontent.com/15385013/69286527-5c597800-0ba8-11ea-9b0c-66c2b1a25e0d.png)

**Comment by mrin9** [comment]
this has been addressed already in commit 17e02f4bd928a81a1f2f462ac8705a8a6eb22982
will be included in our next patch or you may build it out from master to test it
