### ISSUE TITLE
Is there a list of RapiDoc options?

### ISSUE THREAD

**Issue by StephenNay** [mrin9/RapiDoc#93]
I've clicked through the pages on GitHub and looked at the examples, but I haven't found a list of all options for the <rapi-doc> element that describes the possible values and what they do. Is there a page that explains that? I apologize if I've overlooked it.

**Comment by mrin9** [comment]
If you go to the [RapiDoc homepage](https://mrin9.github.io/RapiDoc/) the top right corner has the [API](https://mrin9.github.io/RapiDoc/api.html) link 

here is the direct link 
https://mrin9.github.io/RapiDoc/api.html

**Comment by apsnaidu** [comment]
Hi @mrin9, is there an option to load swagger spec from local disk in reactjs?
I'm looking for an option similar to https://github.com/mrin9/RapiDoc/blob/master/docs/examples/example9.html but for reactjs component?

```
<rapi-doc
        spec-url="/local/file/path"
        render-style="read"
        style={{ height: "100vh", width: "100%" }}
      ></rapi-doc>
```
