### ISSUE TITLE
Use parameters ($ref) from another .yaml file

### ISSUE THREAD

**Issue by vasnav** [mrin9/RapiDoc#96]
I have attached the yaml files (Have appended the files with .log as I was not able to upload .yaml files).
Files 'Login.yaml' and 'Common.yaml' are present in the same folder.
In file 'Login.yaml', the parameter 'accept' that is referred from 'Common.yaml' is not loaded (image AcceptHeaderMissing.png attached):
           - $ref: './Common.yaml#/parameters/accept'
![AcceptHeaderMissing](https://user-images.githubusercontent.com/56592616/69781289-a8717180-11d3-11ea-9893-d5520ab7db35.png)

Is this the correct way of using $ref parameter from another file?

[Common.yaml.log](https://github.com/mrin9/RapiDoc/files/3900134/Common.yaml.log)
[Login.yaml.log](https://github.com/mrin9/RapiDoc/files/3900135/Login.yaml.log)

_Originally posted by @vasnav in https://github.com/mrin9/RapiDoc/issues/75#issuecomment-559356211_

**Comment by mrin9** [comment]
At the moment in RapiDoc  ref-pointers can only point to refs inside `.json` file. However keep an eye on this space, we have plans to extend this feature to `.yaml` files

For now, I think, this is how you can create your files

**login.yaml**
```yaml
openapi: 3.0.2
servers:
  - url: https//example/system
paths:
  /sample/login:
    post:
      summary: Login
      operationId: userLogin
      description: Login.
      parameters:
        - $ref: './partial.json#/components/parameters/accept'
        - $ref: '#/components/parameters/acceptLanguageHeader'   
        - $ref: '#/components/parameters/contentType'
# Components
components:
  parameters:
    acceptLanguageHeader:
      name: Accept-Language
      in: header
      description: Language locale accepted by client (used for locale specific fields in resource representation and in error responses). 
      required: true
      schema:
        type: string
        enum: [en-US, es-ES, fr-FR]
    contentType:
      name: Content-Type
      in: header
      description: Media type sent by the client
      required: true
      schema:
        type: string
        enum: [application/xml, application/json]
```

**partial.json**
```yaml
{
  "components": {
    "parameters": {
      "accept": {
        "name": "Accept",
        "in": "header",
        "description": "Content type accepted by client.",
        "required": true,
        "schema": {
          "type": "string",
          "enum": [
            "application/xml",
            "application/json"
          ]
        }
      }
    }
  }
}

```
