### ISSUE TITLE
IE not supported / missing polyfills

### ISSUE THREAD

**Issue by dagnelies** [mrin9/RapiDoc#98]
Hi,

I know it's probably the kind of annoying things, sorry about that, but I'd like to point out that it does not work on IE/Edge at all.

It tried with polyfills but it was still broken. 😞

**Comment by mrin9** [comment]
works with newer edge https://www.microsoftedgeinsider.com/en-us/

we dont and wont be supporting IE/Edge. The solution is based upon web-components and many ES6 language construct thats not available in older browsers.

duplicate of #89
