### ISSUE TITLE
Question: callback on spec parsing?

### ISSUE THREAD

**Issue by croudet** [mrin9/RapiDoc#99]
Hi,

Is it possible to be notified when the spec file has been parsed?

Thanks,

Christophe

**Comment by mrin9** [comment]
I can provide an event, but can you provide me with your use case that will help me decide whats the best place to provide it

**Comment by croudet** [comment]
I have a spec file that is generated at compile time and at runtime a server context path can be defined.
I need to update the server with this context path.

**Comment by mrin9** [comment]
okay , I am guessing the `context-path` is available to you.
this commit d049b5699724822ea79d2bfe63b5e388f6525824 added `spec-loaded` event.  
More info here: https://mrin9.github.io/RapiDoc/api.html

this is not yet released
to test it either you can build it yourself or use `rapidoc-min.js` from `dist` folder
feel free to reopen, incase you were expecting something else.

> do not use `rapidoc-min.js` from `dist` in production. we dont actively support it and can be removed or updated without any release or notice
